### ISSUE TITLE
It does not seem possible to log explicitly in UTC (if TZ is set differently)

### ISSUE THREAD

**Issue by sjmudd** [openark/orchestrator#1004]
I would prefer my apps to log in UTC to avoid issues around summer/winter time changes but right now some servers are configured with a non-UTC timezone.

I tried starting up orchestrator with `TZ=utc` but this does not seem to modify the logging behaviour.  It would be good to take this into account or allow me to provide a command line option to request orchestrator log in UTC directly.

I also notice that of all the logging most of it uses `"github.com/openark/golib/log"` except one place which uses `"log"` directly: https://github.com/github/orchestrator/blob/master/go/raft/file_snapshot.go#L12.  This seems somewhat odd as it means logging will not be consistent.

Neither of these issues is critical but it might be nice to ensure that logging is consistent and that there is a way that I can force logging to be in UTC even if the system timezone is not UTC. I notice that `log.SetFlags` from package `"log"` has a flag `LUTC` precisely to set logging in UTC.

**Comment by shlomi-noach** [comment]
thank you -- I'll look into it.

**Comment by jfudally** [comment]
@shlomi-noach I can look into this.
