### ISSUE TITLE
MySQL 5.6 turns on parallel replication

### ISSUE THREAD

**Issue by jackiesre721** [openark/orchestrator#1021]
MySQL 5.6 turns on parallel replication and encounters the following error

`set global slave_parallel_workers = 4`

`ERROR Mismatching entries, aborting: table_id: ###
ERROR Unexpected: 0 events processed while iterating logs. Something went wrong; aborting. nextBinlogCoordinatesToMatch: <nil>
`
When I turn off parallel replication, I am doing a graceful switch.

**Comment by shlomi-noach** [comment]
Sorry, can you please explain again exactly what the status is, what you're trying to do, what happens? Please accompany with as much data as possible. I'm afraid I do not understand the question.

**Comment by jackiesre721** [comment]
MySQL 5.6 Database-level replication causes the following error `ERROR Mismatching entries, aborting: `

**Comment by shlomi-noach** [comment]
I really want to help you out, but there's just not enough detail here. Please, be more verbose.

Taking a hunch: are you using Pseudo-GTID? Pseudo-GTID is not supported in MySQL 5.6 paralell (aka per-schema) replication.
