### ISSUE TITLE
question about replica = movedReplica in moveReplicasViaGTID

### ISSUE THREAD

**Issue by MOON-CLJ** [openark/orchestrator#1037]
https://github.com/openark/orchestrator/blob/855e930e89c0cf7934a4bd05281cc010c9cde589/go/inst/instance_topology.go#L692-L695

"if replicaErr != nil && movedReplica != nil {" seems like should be 

"if replicaErr == nil && movedReplica != nil {" ?

what's the original thought here?

cc @yangeagle

**Comment by yangeagle** [comment]
After `moveInstanceBelowViaGTID(replica, other) `, `movedReplica` contains the lastest infomation about the instance `replica`.

1. The condition `if replicaErr != nil && movedReplica != nil { `
means:   update `replica` only if an error occured.

2. `moveInstanceBelowViaGTID()` called by `relocateReplicasInternal()`, 
and then `relocateReplicasInternal()` call itself under some condition:
https://github.com/openark/orchestrator/blob/5126b849ae4f655e1cbe0fbddfa0d7299674f712/go/inst/instance_topology.go#L2738-L2750

Sum up, I guess the purpose is:  using the lastest information to try again.

**Comment by MOON-CLJ** [comment]
@yangeagle thx got it
