### ISSUE TITLE
Manual failover

### ISSUE THREAD

**Issue by vitobotta** [openark/orchestrator#1048]
Hi! I'm using the MySQL operator for Kubernetes which includes the Orchestrator. Is it possible to manually and gracefully promote a slave as the new master fom the UI, and have the old master become a slave, possibly without downtime? I am wondering what to do when I need to do maintenance etc on the node that is currently the master. Thanks in advance!

**Comment by yangeagle** [comment]
It seems like this: https://github.com/openark/orchestrator/issues/1051

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/openark/orchestrator/pull/1165

**Comment by shlomi-noach** [comment]
fixed by #1165
