### ISSUE TITLE
graceful-master-takeover and transactions that commit after readonly is set

### ISSUE THREAD

**Issue by eddawley** [openark/orchestrator#105]
While comparing orchestrator promotions with an internal alternative, I noticed that the order of operations in graceful-master-takeover allows for data loss if any transactions commit after readonly is set.  I thought that maybe I could have PreFailoverProcesses STONITH the old master but that process happens after the final coordinates are determined for the slave so there's no way to prevent this race condition.

edit: oops, my test was faulty.  I was inadvertantly using a SUPER user which was throwing off the results.  This can be closed/deleted.

**Comment by shlomi-noach** [comment]
I'm having thoughts on using a `flush tables with read lock` which is ultimately a locking solution. The thing is it take longer to execute.

With regard `super` being able to write, where possible, I suggest using [super_read_only](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_super_read_only)

**Comment by eddawley** [comment]
Yes, I'd like to switch to super_read_only but that disallows GRANTS/REVOKES which are something we currently don't replicate but instead programmatically sync to all instances.  In this case, my vagrant instance is setup for ease of use rather than real settings and I just plain forgot.
