### ISSUE TITLE
Question : Switchover

### ISSUE THREAD

**Issue by fuyar** [openark/orchestrator#1051]
Hello,

I have a traditional setup of 3 instances : 1 RW (db1) as primary and 2 RO (db2 / db3) as replicas (async replication).

I'd like to provoke a manual (intended) switch over between db1 and db2 : db2 as primary and db1/db3 as replicas.

graceful-master-takeover does that but put old master (db1) as non replication and downtimed.

So I need to do : 
1/ graceful-master-takeover -i db1
2/ start-slave -i db2
3/ end-downtime -i db2

Is there a way to do that in a single command ? I just want to gracefully switch master. 

Thanks

**Comment by shlomi-noach** [comment]
step 3 is redundant. Once replication runs, the `downtime` state is auto-removed, within 1 minute.
I'd suggest running `start-replica` from within `PostGracefulTakeoverProcesses`. Unfortunately there isn't a flow to match everyone's needs...

**Comment by fuyar** [comment]
Thanks for the answer Sholmi. I totally understand and agree that every use cases can't be covered.
Still I think that 
- switchover (switch roles between a master and a standby)
- failover (switch master role to a standby and lose old master)
are 2 basic operations on any cluster.

**Comment by shlomi-noach** [comment]
> are 2 basic operations on any cluster.

And so `switchover` exists, it's just that the replica does not auto-start; am I correct in understanding what you find to be missing?

**Comment by fuyar** [comment]
Exactly that. Here switchover is implemented with a "put maintenance mode automatically" option.

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/openark/orchestrator/pull/1165

**Comment by shlomi-noach** [comment]
fixed by #1165
