### ISSUE TITLE
/api/status unusable in conjunction with AuthenticationMethod

### ISSUE THREAD

**Issue by EagleEyeJohn** [openark/orchestrator#1067]
Our goal is to have a secured UI for Orchestrator and to use Managed Instance Group Health Checks within GCP, with autohealing enabled for the Orchestrator instances spread across 3 zones.

To enter the load balancer, `/api/leader` on an Orchestrator instance *must* return 200 http status when called by load balancer health check.
To be part of the instance group, an Orchestrator instance *must* return 200 http status on `/api/status` to the managed instance group health check.

Orchestrator using raft forms a fully HA cluster using the above setup without issue.

We now need to secure the UI.  If we set `AuthenticationMethod`  to "_basic_" or "_multi_" (etc.) the response from `/api/status` becomes 401 http status, as health checks are unable to authenticate.

This prevents us building instances, as the api end points never return a 200 http status.  The managed instance group then performs a continual cycle of building, testing and destroying instances.

Is there a means of obtaining health without requiring credentials when all other types of access do require credentials?

**Comment by shlomi-noach** [comment]
Two ideas:

1. With `multi`, you can query `https://readonly:whatever@hostname:3000/api/status`
  that is, in `multi`you have the `readonly` user and with any password, see https://github.com/github/orchestrator/blob/master/docs/security.md.
 The above URI should authenticate as such. Can you please try?

2. I think best authentication is to put `orchestrator` behind a reverse proxy, such as nginx etc. They will do the authentication based on LDAP; `orchestrator` will use `proxy`. Your reverse proxy will allow `/api/status` to pass without authentication.

**Comment by EagleEyeJohn** [comment]
Thank you.

1. GCP health checks only allow you to specify a port and path to be checked, so unfortunately this one is not an option.

2. Will work I believe, if we put the reverse proxy on the same instance that is hosting `orchestrator`.
