### ISSUE TITLE
QueryRowsMap unexpected error: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sjmudd** [openark/orchestrator#1073]
I noticed the following in logging in the latest version of orchestrator:

```
2020-02-13 09:02:49 ERROR ReadTopologyInstance(A.B.C.D:P) show variables like 'maxscale%': QueryRowsMap unexpected error: runtime error: invalid memory address or nil pointer dereference
```
It looks to me like the QueryRowsMap produces an error if no rows are returned. Probably related to trying to dereference a nil pointer (as mentioned in the message).

Probably this should be fixed. Reported here in the orchestrator repo but this is really from `openark/golib/sqlutils/sqlutils.go`. So not sure if I should report this there.

There is code in orchestrator which catches this "exception" so it doesn't cause a problem, but clearly the code should not do what it's doing.

**Comment by yakirgb** [comment]
Was same issue on our cluster:
```
[martini] Started GET /api/discover/db.abc.com/3306 for 1.2.3.4:51172
2020-02-19 21:48:48 ERROR dial tcp 5.6.7.8:3306: connect: no route to host
2020-02-19 21:48:48 ERROR ReadTopologyInstance(db.abc.com:3306) show variables like 'maxscale%': QueryRowsMap unexpected error: runtime error: invalid memory address or nil pointer dereference
[martini] Completed 500 Internal Server Error in 3.922317ms
```
The issue was firewall that blocked connections from Orchestrator.
The UI stuck with icon "loading" without any error or timeout.

**Comment by shlomi-noach** [comment]
Until this is fixed, people who don't actually use MaxScale should set `SkipMaxScaleCheck: true` in their config.

**Comment by sjmudd** [comment]
Maybe this should be the default setting? `SkipMaxScaleCheck: true`? I wonder if anyone is actually still using MaxScale as a binlog router.  I would think that anyone that is using it would know and would know to enable this setting.

**Comment by shlomi-noach** [comment]
https://github.com/openark/orchestrator/pull/1114 is expected to fix this issue.
