### ISSUE TITLE
how could I discover mysql instance which does not use default port 3307

### ISSUE THREAD

**Issue by MonkeyFang** [openark/orchestrator#1076]

**Comment by MonkeyFang** [comment]
[root@zb-mongodb-test-203-23 orchestrator]# orchestrator-client -c topology -i zb-search-test-203-31:3307
zb-search-test-203-31:3307   [unknown,invalid,5.7.22-22-log,rw,ROW,>>]
- zb-search-test-203-29:3307 [unknown,invalid,5.7.22-22-log,rw,ROW,>>]
- zb-search-test-203-30:3307 [unknown,invalid,5.7.22-22-log,rw,ROW,>>]
[root@zb-mongodb-test-203-23 orchestrator]# orchestrator-client -c replication-analysis
zb-search-test-203-31:3307 (cluster zb-search-test-203-31:3307): DeadMasterAndSlaves

log info:
2 Detected UnreachableMaster on zb-search-test-203-31:3307. Affected replicas: 1

**Comment by MonkeyFang** [comment]
[root@zb-mongodb-test-203-23 orchestrator]# mysql -u orchestrator  -h 172.21.203.31 -P 3307 -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 453
Server version: 5.7.22-22-log Percona Server (GPL), Release 22, Revision f62d93c

Copyright (c) 2009-2018 Percona LLC and/or its affiliates
Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

percona-5.7.22-22-->orchestrator@(none)>status
--------------
mysql  Ver 14.14 Distrib 5.7.22-22, for Linux (x86_64) using  6.2

Connection id:		453
Current database:	
Current user:		orchestrator@172.21.203.23
SSL:			Cipher in use is ECDHE-RSA-AES128-GCM-SHA256
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		5.7.22-22-log Percona Server (GPL), Release 22, Revision f62d93c
Protocol version:	10
Connection:		172.21.203.31 via TCP/IP
Server characterset:	utf8mb4
Db     characterset:	utf8mb4
Client characterset:	utf8mb4
Conn.  characterset:	utf8mb4
TCP port:		3307
Uptime:			2 hours 18 min 22 sec

Threads: 3  Questions: 1022  Slow queries: 0  Opens: 159  Flush tables: 2  Open tables: 52  Queries per second avg: 0.123
--------------

percona-5.7.22-22-->orchestrator@(none)>system ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:50:56:84:7c:69 brd ff:ff:ff:ff:ff:ff
    inet 172.21.203.23/24 brd 172.21.203.255 scope global eth0
       valid_lft forever preferred_lft forever

**Comment by MonkeyFang** [comment]
Analysis | Failed instance | Affected | Cluster name | Cluster alias | Detect time
-- | -- | -- | -- | -- | --
UnreachableMaster | zb-search-test-203-31:3307 | 1 | zb-search-test-203-31:3307 | zb-search-test-203-31:3307 | 2020-02-14 16:15:55
Detected: 2020-02-14 16:15:551 replicating hosts :zb-search-test-203-29:3307Changelog :2020-02-14 16:15:55 NoProblem,Related recoveryProccessed by zb-mongodb-test-203-23

**Comment by shlomi-noach** [comment]
This is a kind request to format your messages with markdown. Please consider that is is difficult to understand them. 
Also, I’m not sure what the question is.

**Comment by MonkeyFang** [comment]
the question is I have a mysql cluster which used the port 3307,the orchestrator can not afford it

orchestrator-client -c topology -i zb-search-test-203-31:3307
zb-search-test-203-31:3307 [unknown,invalid,5.7.22-22-log,rw,ROW,>>]
zb-search-test-203-29:3307 [unknown,invalid,5.7.22-22-log,rw,ROW,>>]
zb-search-test-203-30:3307 [unknown,invalid,5.7.22-22-log,rw,ROW,>>]

orchestrator-client -c replication-analysis
zb-search-test-203-31:3307 (cluster zb-search-test-203-31:3307): DeadMasterAndSlaves

**Comment by shlomi-noach** [comment]
use `DiscoverByShowSlaveHosts` and make sure to set `@@report_host` and `@@report_port` on your servers.

**Comment by MonkeyFang** [comment]
ok，I'll try it,I had only set report_host not set report_port,by the way,can orchestrator support this situation that if there only one master and one slave?

**Comment by shlomi-noach** [comment]
I’m not sure I understand the follow up question. Orchestrator supports
topologies with one master one replica

**Comment by MonkeyFang** [comment]
thanks
