### ISSUE TITLE
Publish official docker image on Docker Hub?

### ISSUE THREAD

**Issue by ushuz** [openark/orchestrator#1087]
It would be helpful for users who want to run orchestrator in containers or on k8s, as they don't need to build the image themselves. 

Setting up an automated build on Docker Hub, or a GitHub Action to automate the process doesn't require much effort.

**Comment by shlomi-noach** [comment]
Good idea. Experimental repository: https://hub.docker.com/r/openarkcode/orchestrator

**Comment by ushuz** [comment]
Thank you for your quick response. It would be better if the images are tagged with orchestrator version,  but the `latest` would do right now.
