### ISSUE TITLE
Multi Master Topology Host names  in Consul KV

### ISSUE THREAD

**Issue by rushi47** [openark/orchestrator#1103]
Hello Team,

I have below cluster setup.
There are two DCs - **DC & GCP**.

**Orchestrator without Cluser**  <- @shlomi-noach 
 
GCP - orchestrator & consul is running on 3001 & 8501
DC -  orchestrator & consul is running on 3000 & 8500
 
**GCP** :
![Screenshot from 2020-03-26 12-35-41](https://user-images.githubusercontent.com/13472344/77619843-113ce080-6f5f-11ea-9eab-ba8232b3b042.png)

**DC**:
![Screenshot from 2020-03-26 12-35-23](https://user-images.githubusercontent.com/13472344/77620311-1c444080-6f60-11ea-9d86-65b28c856627.png)

Now even though orchestrator has detected different data centres. And i explicitly declared this params :

```
  "PreventCrossDataCenterMasterFailover": true,
  "PreventCrossRegionMasterFailover": true,
```

Still when master fails on GCP side (gcp-db01) it promotes the master as (dc-db01 | please have look in below attached screen shot) instead of promoting master as (gcp-db02) and it also doesnt update the KV in consul. Am i missing anything anywhere ?

![Screenshot from 2020-03-26 12-39-48](https://user-images.githubusercontent.com/13472344/77620617-be642880-6f60-11ea-909f-c7f4d8fd6e5a.png)

--------------------------------------------------------------------------
** orchestrator with cluster ** <- @shlomi-noach 

The other thing which i tried along with above config was to run orchestrator in Cluster Mode.
But the problem with this mode is there are co masters right but it always update the value of only one master in consul kv though they are from different DC. Is it the expected behaviour ? Cause am expecting two masters as there will be seprate proxysqls for their respective DCs. 

![Screenshot from 2020-03-26 19-58-11](https://user-images.githubusercontent.com/13472344/77658326-8c70b780-6f9c-11ea-8053-ad0335a5099e.png)

Seeking your valuable inputs @shlomi-noach on this :).
Thanks a lot.
Attaching the orchestrator.conf  below.

```
{
  "Debug": true,
  "EnableSyslog": false,
  "ListenAddress": ":3000",
  "MySQLTopologyUser": "orchestrator",
  "MySQLTopologyPassword": "orchestrator",
  "MySQLTopologyCredentialsConfigFile": "",
  "MySQLTopologySSLPrivateKeyFile": "",
  "MySQLTopologySSLCertFile": "",
  "MySQLTopologySSLCAFile": "",
  "MySQLTopologySSLSkipVerify": true,
  "MySQLTopologyUseMutualTLS": false,
  "MySQLOrchestratorHost": "172.16.238.16",
  "MySQLOrchestratorPort": 3306,
  "MySQLOrchestratorDatabase": "orchestrator",
  "MySQLOrchestratorUser": "orchestrator",
  "MySQLOrchestratorPassword": "orchestrator",
  "MySQLOrchestratorCredentialsConfigFile": "",
  "MySQLOrchestratorSSLPrivateKeyFile": "",
  "MySQLOrchestratorSSLCertFile": "",
  "MySQLOrchestratorSSLCAFile": "",
  "MySQLOrchestratorSSLSkipVerify": true,
  "MySQLOrchestratorUseMutualTLS": false,
  "MySQLConnectTimeoutSeconds": 1,
  "DefaultInstancePort": 3306,
  "DiscoverByShowSlaveHosts": true,
  "InstancePollSeconds": 5,
  "UnseenInstanceForgetHours": 240,
  "SnapshotTopologiesIntervalHours": 0,
  "InstanceBulkOperationsWaitTimeoutSeconds": 10,
  "HostnameResolveMethod": "default",
  "MySQLHostnameResolveMethod": "@@hostname",
  "SkipBinlogServerUnresolveCheck": true,
  "ExpiryHostnameResolvesMinutes": 60,
  "RejectHostnameResolvePattern": "",
  "ReasonableReplicationLagSeconds": 10,
  "ProblemIgnoreHostnameFilters": [],
  "VerifyReplicationFilters": false,
  "ReasonableMaintenanceReplicationLagSeconds": 20,
  "CandidateInstanceExpireMinutes": 60,
  "AuditLogFile": "",
  "AuditToSyslog": false,
  "RemoveTextFromHostnameDisplay": ".mydomain.com:3306",
  "ReadOnly": false,
  "AuthenticationMethod": "",
  "HTTPAuthUser": "",
  "HTTPAuthPassword": "",
  "AuthUserHeader": "",
  "PowerAuthUsers": [
    "*"
  ],
  "SlaveLagQuery": "",
  "DetectClusterAliasQuery": "SELECT ifnull(max(cluster_name), '''') as cluster_alias from meta.cluster where anchor=1;",
  "DetectClusterDomainQuery": "",
  "DetectInstanceAliasQuery": "",
  "DetectPromotionRuleQuery": "",
  "DataCenterPattern": "(.*)[-]",
  "PhysicalEnvironmentPattern": "(.*)[-]",
  "PromotionIgnoreHostnameFilters": [],
  "DetectSemiSyncEnforcedQuery": "",
  "ServeAgentsHttp": false,
  "AgentsServerPort": ":3001",
  "AgentsUseSSL": false,
  "AgentsUseMutualTLS": false,
  "AgentSSLSkipVerify": false,
  "AgentSSLPrivateKeyFile": "",
  "AgentSSLCertFile": "",
  "AgentSSLCAFile": "",
  "AgentSSLValidOUs": [],
  "UseSSL": false,
  "UseMutualTLS": false,
  "SSLSkipVerify": false,
  "SSLPrivateKeyFile": "",
  "SSLCertFile": "",
  "SSLCAFile": "",
  "SSLValidOUs": [],
  "URLPrefix": "",
  "StatusEndpoint": "/api/status",
  "StatusSimpleHealth": true,
  "StatusOUVerify": false,
  "AgentPollMinutes": 60,
  "UnseenAgentForgetHours": 6,
  "StaleSeedFailMinutes": 60,
  "SeedAcceptableBytesDiff": 8192,
  "PseudoGTIDPattern": "",
  "PseudoGTIDPatternIsFixedSubstring": false,
  "PseudoGTIDMonotonicHint": "asc:",
  "DetectPseudoGTIDQuery": "",
  "BinlogEventsChunkSize": 10000,
  "SkipBinlogEventsContaining": [],
  "ReduceReplicationAnalysisCount": true,
  "FailureDetectionPeriodBlockMinutes": 60,
  "RecoveryPollSeconds": 10,
  "RecoveryPeriodBlockSeconds": 3600,
  "RecoveryIgnoreHostnameFilters": [],
  "RecoverMasterClusterFilters": [
    ".*"
  ],
  "RecoverIntermediateMasterClusterFilters": [
    "_intermediate_master_pattern_"
  ],
  "OnFailureDetectionProcesses": [
    "echo 'Detected {failureType} on {failureCluster}. Affected replicas: {countSlaves}' >> /tmp/recovery.log"
  ],
  "PreFailoverProcesses": [
    "echo 'Will recover from {failureType} on {failureCluster}' >> /tmp/recovery.log"
  ],
  "PostFailoverProcesses": [
    "echo '(for all types) Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Successor: {successorHost}:{successorPort}' >> /tmp/recovery.log"
  ],
  "PostUnsuccessfulFailoverProcesses": [],
  "PostMasterFailoverProcesses": [
    "echo '{replicaHosts} : XXXXXXXXXXXXX TRIGGERED XXXXXXXXXXX : {slaveHosts} : Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Promoted: {successorHost}:{successorPort}' >> /tmp/recovery.log",
    "/etc/posthook.sh {slaveHosts} {failedHost}",
    "/etc/manage_proxysql.py {failureCluster}"
  ],
  "PostIntermediateMasterFailoverProcesses": [
    "echo 'Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Successor: {successorHost}:{successorPort}' >> /tmp/recovery.log"
  ],
  "CoMasterRecoveryMustPromoteOtherCoMaster": true,
  "DetachLostSlavesAfterMasterFailover": true,
  "ApplyMySQLPromotionAfterMasterFailover": true,
  "MasterFailoverDetachSlaveMasterHost": false,
  "MasterFailoverLostInstancesDowntimeMinutes": 0,
  "PostponeSlaveRecoveryOnLagMinutes": 0,
  "PreventCrossDataCenterMasterFailover": true,
  "PreventCrossRegionMasterFailover": true,
  "OSCIgnoreHostnameFilters": [],
  "GraphiteAddr": "",
  "GraphitePath": "",
  "GraphiteConvertHostnameDotsToUnderscores": true,
  "BackendDB": "sqlite",
  "SQLite3DataFile": "/usr/local/orchestrator/orchestrator.db",
  "ConsulAddress": "127.0.0.1:8500",
  "KVClusterMasterPrefix": "mysql/master",
  "ConsulAclToken": ""
}

```

**Comment by rushi47** [comment]
@shlomi-noach  Did you get any chance to look at it ?

**Comment by shlomi-noach** [comment]
@rushi47 I'm on low volume right now (I'm actually on vacation), sorry for delays.

**Comment by rushi47** [comment]
> @rushi47 I'm on low volume right now (I'm actually on vacation), sorry for delays.

Hey @shlomi-noach no problem, please take your time and enjoy the vacations.
If possible can you just let me know, when you will be back on work ? It will help us in our project timeline.

**Comment by shlomi-noach** [comment]
hehe, http://code.openark.org/blog/mysql/the-state-of-orchestrator-2020-spoiler-healthy ; I'm more specifically not working right now. But, give me a few days, I hope to be able to take a look.

**Comment by rushi47** [comment]
@shlomi-noach oops sorry i didnt know about this :) Please have your personal time :).

**Comment by shlomi-noach** [comment]
Thank you for your patience. I started reading the question and something strikes odd. Can you please clarify this before I proceed to analyze the situation?

What I understand is that you have two different, independent, `orchestrator` setups. Is that the case? So, you have one `orchestrator` in `DC` and another `orchestrator` in `GCP` and these two `orchestrator`s do not talk to each other -- they don't share the same backend, and they don't run in `raft` setup.

1. Did I understand it correctly?

If so, then you should not run like this. See https://github.com/openark/orchestrator/blob/master/docs/deployment.md

If I'm wrong please explain what the `orchestrator` setup is. 

2. Same question for Consul. Are your two Consul clusters connected?

**Comment by rushi47** [comment]
@shlomi-noach So you know i tried both setup one where orchestrator dont talk with each, like it works independently and other in which orchestrator talks with each other.

> 
> 1. Did i understand correctly ? ->
> I have updated the issue, Highlighting both cases with Headings. Please let me know if any further info is needed.
> 

> 2. Same question for Consul. Are your two Consul clusters connected?
> In both the cases consul is NOT running in cluster.

**Comment by shlomi-noach** [comment]
OK, so, a few things:

- You should never run such setup. You have two independent `orchestrator`s -- they will both run a failover _independently_ of each other, this is a recipe for catastrophe.
- You didn't answer question number 2 -- are your consul setups likewise idsassociated? If so, and if one `orchestrator` writes to one Consul, you cannot expect the data to be in the other Consul cluster. Unless, they are aware of each other via `"dc"` API.
- You have `"CoMasterRecoveryMustPromoteOtherCoMaster": true`. This means no-matter-what, the co-master has to get promoted.
- I need to verify, but co-master promotion logic, which is way more complex, does not take DC/Region constraints in same way as master promotion.

**Comment by rushi47** [comment]
@shlomi-noach 


> OK, so, a few things:
> 
> * You should never run such setup. You have two independent `orchestrator`s -- they will both run a failover _independently_ of each other, this is a recipe for catastrophe.
So basically the orchestrator should touch the nodes only on their respective sides right ?
Like if orchestrator is on DC side it should just handle the mysql cluster on DC side and vice versa.
 
> * You didn't answer question number 2 -- are your consul setups likewise idsassociated? If so, and if one `orchestrator` writes to one Consul, you cannot expect the data to be in the other Consul cluster. Unless, they are aware of each other via `"dc"` API.

No so the consul setup is independent., there is no inter data connectivity. But if you want we can join the cluster.

> * You have `"CoMasterRecoveryMustPromoteOtherCoMaster": true`. This means no-matter-what, the co-master has to get promoted.

So you know this is our use case,  maybe i will explain the use case again at the end of this answer and you can suggest maybe proper setup for the same.

> * I need to verify, but co-master promotion logic, which is way more complex, does not take DC/Region constraints in same way as master promotion.
oh Ok !.

---------------------------------------------------------------------------------------
Ok so the real problem is, we are having our setup in DC and we are migration on google cloud as well so some apps are deployed in GCLOUD. Now the problem is data should be consistent between both because of what not reasons.

So we have one master & one slave in DC, One master & one Slave in Gcloud. We need to have replication between both. And if something happens and we need to do the failover the Slave in DC side should be promoted as Master for DC. Same for Gcloud,  Slave in Gcloud should be promoted as Master in Gcloud. They should not move between dc in gcloud. Like for the Slave of Gcloud Master cannot be of DC.

Also we are having ProxySQL which will be managed by Consul Template, if the master get updated on any side we update it in ProxySQL (reader,writers group basically). And just to clarify there are two proxysql one for DC and one for GCP.


Can you helping me in implementing the above scenario, how should i implement this.

**Comment by shlomi-noach** [comment]
> So we have one master & one slave in DC, One master & one Slave in Gcloud. We need to have replication between both. And if something happens and we need to do the failover the Slave in DC side should be promoted as Master for DC. Same for Gcloud, Slave in Gcloud should be promoted as Master in Gcloud. They should not move between dc in gcloud. Like for the Slave of Gcloud Master cannot be of DC.

Then it sounds to me like you really want `"CoMasterRecoveryMustPromoteOtherCoMaster": false`. Right now you have `"CoMasterRecoveryMustPromoteOtherCoMaster": true`.

**Comment by rushi47** [comment]
I tried it but you know its getting in weird situation, one of it is below.
So as stated above there are two orchestrators not in cluster & have their own consuls.
In one orchestrator my discovery point is dc-db01 & for other is gcp-db01.
I have failed master on DC-Side, leading to below situation.

![Screenshot from 2020-05-06 19-54-35](https://user-images.githubusercontent.com/13472344/81189352-18cabd00-8fd4-11ea-861c-a7ffd3708636.png)

 But consul kv is not updated with latest master.

![Screenshot from 2020-05-06 19-54-46](https://user-images.githubusercontent.com/13472344/81189431-2d0eba00-8fd4-11ea-8ebc-56b918375aa5.png)


Even after doing this.

![Screenshot from 2020-05-06 19-55-13](https://user-images.githubusercontent.com/13472344/81189470-3730b880-8fd4-11ea-94ac-76ed2006f7c9.png)



Am not sure where am going wrong now & sometimes what happens is after failing of master, slave for the respective master get attached to other master instead of being promoted.

**Comment by shlomi-noach** [comment]
Please understand that I cannot proceed to debug this if you're running two different, independent `orchestrator` services. Weird things will happen. The two independent services will not report o each other, and may both attempt a failover in parallel.
And so the baseline to tackling this issue is to have a single `orchestrator` cluster (there can still be multiple `orchestrator` services, but they must communicate with each other). Then, let's see if/what weird cases we see.

**Comment by rushi47** [comment]
@shlomi-noach Sorry we had to switch priorities at that time, for using the implementation of orchestrator with consul.
We decided not to go with that feature for that time, but as first phase is done, we again want to add up consul with orchestrator.
So to start this time,  we can start this thread as fresh thread , can you just let me know, after enabling this 
```
  "KVClusterMasterPrefix": "mysql/master",
  "ConsulAddress": "127.0.0.1:8500",
```
in Conf, how frequently the code inside orchestrator which is responsible for updating the consul values is run ? Cause i see significant delay with this operation.
Also it will be great help if you can help me with the behaviour for three cases:
- When setup is co-mastered, will it update the consul KV with both masters ?
- Out of this co-masters lets say one master crashes, will orchestrator remove that node from Consul KV
- If co-master toplogy is changed to master slave i.e previously the nodes which were co-masters, now one of them is slave of other so topology is change to master to slave, in that case will it remove the key which is added in Consul KV [assumming the answer is Yes for first case]

**Comment by shlomi-noach** [comment]
> how frequently the code inside orchestrator which is responsible for updating the consul values is run ? Cause i see significant delay with this operation.

Only when there's actually something to write, which is upon failover. And once, first time.

> When setup is co-mastered, will it update the consul KV with both masters ?

No, just one.

> Out of this co-masters lets say one master crashes, will orchestrator remove that node from Consul KV

"remove that node from Consul KV" is no a correct way to describe this. There's an entry in KV that indicates your cluster. We update the entry with identity of new primary.

>  in that case will it remove the key which is added in Consul KV

Same answer as previous one.

I might suggest that all these are things you should be able to easily experiment with, and you can validate behavior on your side.

**Comment by rushi47** [comment]
@shlomi-noach  yep i tried from my end but i was not able to conclude the behaviour because of some issues.

> > When setup is co-mastered, will it update the consul KV with both masters ? 
> No, just one.

This is little problematic .

Thanks for the inputs and sorry for troubling you :sweat_smile: .
