### ISSUE TITLE
Orchestrator cannot connect to MySQL instances: net.Error from Dial() i/o timeout

### ISSUE THREAD

**Issue by MatthewMiller2** [openark/orchestrator#1108]
Hello,

I am running into an issue with Orchestrator and MySQL in a 3 node setup. Orchestrator does not seem to be able to discover the topology correctly. After a call to `orchestrator-client -c discover -i localhost:3307` the cluster topology does not get discovered properly. In the orchestrator logs, I am seeing a continuous stream of messages of this type:
```
[mysql] 2020/04/01 18:20:33 driver.go:81: net.Error from Dial()': dial tcp <ip address>:3307: i/o timeout
[mysql] 2020/04/01 18:20:33 driver.go:81: net.Error from Dial()': dial tcp <ip address>:3307: i/o timeout
...
2020-04-01 18:20:35 ERROR driver: bad connection
```
I am seeing groups of those messages continuously in the logs. What is interesting is that the IP address in the error message `net.Error from Dial()` (that I removed) does not correspond to any IP addresses in my cluster.

I have gotten orchestrator to work in similar configurations before, so I know I am not trying to do anything not possible. I expect the output of `orchestrator-client -c topology -a <alias>` to be something like
```
node-1_host:3307   [0s,ok,5.7.29-log,rw,ROW,>>,GTID]
+ node-2_host:3307 [0s,ok,5.7.29-log,ro,ROW,>>,GTID]
+ node-3_host:3307 [0s,ok,5.7.29-log,ro,ROW,>>,GTID]
```
However, the output of that command has been of the form:
```
node1_host:3307 [unknown,invalid,5.7.29-log,rw,ROW,>>,GTID]
```

Here is my /etc/orchestrator.conf.json:
```json
{
  "Debug": false,
  "ListenAddress": ":3308",
  "MySQLTopologyUser": "orchestrator",
  "MySQLTopologyPassword": redacted_password,
  "MySQLTopologySSLSkipVerify": true,
  "MySQLTopologyUseMixedTLS": false,
  "BackendDB": "sqlite",
  "SQLite3DataFile": "/usr/local/orchestrator/orchestrator.sqlite3",
  "MySQLConnectTimeoutSeconds": 1,
  "DefaultInstancePort": 3307,
  "DiscoverByShowSlaveHosts": true,
  "HostnameResolveMethod": "default",
  "MySQLHostnameResolveMethod": "@@hostname",
  "SlaveLagQuery": "",
  "DetectClusterAliasQuery": "SELECT SUBSTRING_INDEX(@@hostname, '-', 1)",
  "DetectClusterDomainQuery": "",
  "DetectInstanceAliasQuery": "SELECT SUBSTRING_INDEX(@@hostname, '.', 1)",
  "DetectSemiSyncEnforcedQuery": "",
  "StatusEndpoint": "/api/status",
  "StatusSimpleHealth": true,
  "RecoveryPeriodBlockSeconds": 5,
  "RecoverMasterClusterFilters": [
    "*"
  ],
  "RecoverIntermediateMasterClusterFilters": [
    "*"
  ],
  "OnFailureDetectionProcesses": [
    "echo 'Detected {failureType} on {failureCluster}. Affected replicas: {countSlaves}' >> /var/log/orchestrator-recovery.log"
  ],
  "PreFailoverProcesses": [
    "echo 'Will recover from {failureType} on {failureCluster}' >> /var/log/orchestrator-recovery.log"
  ],
  "PostFailoverProcesses": [
    "echo '(for all types) Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Successor: {successorHost}:{successorPort}' >> /var/log/orchestrator-recovery.log",
    "redacted/after-failover-script.sh {failedHost} {failedPort} {successorHost} {successorPort}"
  ],
  "PostUnsuccessfulFailoverProcesses": [
    "echo 'Unsuccessful failover process for {failureType} on {failureCluster}' >> /var/log/orchestrator-recovery.log"
  ],
  "PostMasterFailoverProcesses": [
    "echo 'Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Promoted: {successorHost}:{successorPort}' >> /var/log/orchestrator-recovery.log"
  ],
  "PostIntermediateMasterFailoverProcesses": [
    "echo 'Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Successor: {successorHost}:{successorPort}' >> /var/log/orchestrator-recovery.log"
  ],
  "RaftEnabled": true,
  "RaftDataDir": "/var/lib/orchestrator",
  "RaftBind": REDACTED_INTERNAL_IP,
  "DefaultRaftPort": 3309,
  "RaftNodes": [
    REDACTED_IP_1, REDACTED_IP_2, REDACTED_IP_3
  ]
}
```

Any help understanding that error message I am seeing in the logs, and what might be causing it/how I can solve it would be greatly appreciated! Thank you!

### Update 1:
I increased the value of `MySQLConnectTimeoutSeconds` to 100 (arbitrarily) and I'm no longer seeing the same exact net.Error from Dial error messages in the logs, however I'm still seeing messages like:
```
ERROR ReadTopologyInstance(node3_host:3307) show global status like 'Uptime': dial tcp <ip>:3307: connect: connection refused
WARNING discoverInstance exceeded InstancePollSeconds for node3:3307, took 227.5630s
ERROR ReadTopologyInstance(node2:3307) show global status like 'Uptime': dial tcp <ip>:3307: connect: connection refused
WARNING  DiscoverInstance(node2:3307) instance is nil in 227.576s (Backend: 0.002s, Instance: 227.574s), error=dial tcp <ip>:3307: connect: connection refused
```
Again, the redacted IP addresses don't correspond to any actual IP addresses in my cluster.

Additionally, the cluster was not discovered properly. Shortly after startup, `orchestrator-client -c clusters` was reporting three different clusters, one for each node. However, after enough time, `orchestrator-client -c clusters` was only reporting one cluster again, and that cluster's topology was simply
```
node3:3307 [unknown,invalid,5.7.29-log,rw,ROW,>>,GTID]
```
which is the same incorrect output that it was before, without the increased timeout.

**Comment by jackiesre721** [comment]
You should config hosts

**Comment by MatthewMiller2** [comment]
@liuqian1990 Hello, thanks for the help. Do you mean to configure /etc/hosts on the nodes? If so, I already have that configured.

**Comment by MatthewMiller2** [comment]
I was able to resolve this issue. The resolution was that I had to set `MySQLHostnameResolveMethod` to `@@report_host`. `report-host` is explicitly set in my mysql configuration file to the IP address of each node, due to the way my cluster is configured to deal with hostnames.
