### ISSUE TITLE
the analysis log can not tell which cluster

### ISSUE THREAD

**Issue by yangeagle** [openark/orchestrator#1125]
https://github.com/openark/orchestrator/blob/244aa5eef45df43a52eff9adfb05599ed8dba52e/go/inst/analysis_dao.go#L310-L317

the log here can not tell which cluster.

if two clusters have the same analysis at the same time, 
only one `analysisMessage` printed.

If agreed, I can give PR with pleasure.

cc @MOON-CLJ

**Comment by shlomi-noach** [comment]
Behavior confirmed. Thank you!

**Comment by yangeagle** [comment]
close it.
