### ISSUE TITLE
Graceful takeover failed when set global read_only=1 failed due to timeout.

### ISSUE THREAD

**Issue by junli0411** [openark/orchestrator#1127]
We got several times for this failure.  Here's the details info :
- Master status
```
[Id:13783517]
[User:lt_wms_internal_rw]
[Host:xxxxx:60982]
[db:wms_internal]
[Command:Query]
[Time:32]
[State:Waiting for semi-sync ACK from slave]
[Info:commit]

[Id:13820386]
[User:orchestrator]
[Host:xxxxx:52785]
[db:null]
[Command:Query]
[Time:32]
[State:Waiting for commit lock]
[Info:set global read_only = 1]
```

- New Master(Original Slave, it's replication thread already stopped by Orchestrator)
```
[Slave_IO_State:]
[Master_Host:xxxxx
[Master_User:repl]
[Master_Port:3306]
[Connect_Retry:60]
[Master_Log_File:mysql-bin.000272]
[Read_Master_Log_Pos:972301402]
[Relay_Log_File:mysql-relay.000002]
[Relay_Log_Pos:173336913]
[Relay_Master_Log_File:mysql-bin.000272]
[Slave_IO_Running:No]
[Slave_SQL_Running:No]
[Replicate_Do_DB:]
```

The master is in `Waiting for semi-sync ACK from slave`  , rpl_semi_sync_master_timeout was set to a vary big num, then `set global read_only=1` failed due to timeout , Orchestrator still did some failover operations , the MySQL (1 Master 2 Slaves) now is  1 Master 1 mid-master and 1 slave. 

I suppose it should be stopped when `set global read_only =1` failed.

**Comment by jackiesre721** [comment]
Have a debug log

**Comment by junli0411** [comment]
> Have a debug log

it's a production server , no debug info now. 
but you can repeat it :
 first , enable semi syn replication ， second,  start a transaction without commit , third , do the graceful takeover .

**Comment by jackiesre721** [comment]
https://bugs.mysql.com/bug.php?id=96644

**Comment by junli0411** [comment]
> https://bugs.mysql.com/bug.php?id=96644

so , Orchestrator will sill do failover even though the set read_only failed ?

**Comment by junli0411** [comment]
Hi, 
just double confirm .
I did a test on dev environment , I found that the Orchestrator will point the siblings slaves to the new master frst , then do the set read_only on the old master and then point the old master to the new master  ?
