### ISSUE TITLE
Possible documentation improvements for MariaDB/GTID scenario

### ISSUE THREAD

**Issue by thehunmonkgroup** [openark/orchestrator#1134]
I'd like to create a PR to provide some documentation enhancements for the MariaDB/GTID case, but before I post it I need some clarification:

 * Where in the doc would you like the new ```ReplicationCredentialsQuery``` variable described?
 * Over at https://github.com/openark/orchestrator/issues/918#issuecomment-507175107 you seem to indicate that bringing up and old master as a slave is only possible with MySQL/GTID, but using ```ReplicationCredentialsQuery``` and ```PostGracefulTakeoverProcesses``` in the 'planned manual failover' scenario, I *seem* to be able to do that with MariaDB/GTID as well, with the following two queries: ```CHANGE MASTER TO MASTER_CONNECT_RETRY=1, MASTER_USE_GTID=current_pos; START SLAVE;``` -- am I right about that or am I missing someting?

**Comment by shlomi-noach** [comment]
> Where in the doc would you like the new ReplicationCredentialsQuery variable described?

I suggest https://github.com/openark/orchestrator/blob/master/docs/configuration-discovery-classifying.md

> am I right about that or am I missing someting?

What I think you may be missing is: what if the master applied some transactions, which never made it to any of the replicas?

With MySQL GTID, you can actually check if that happened, and if not, then the master can join as a replica. I'm not aware you can make that check with MariaDB GTID.

**Comment by thehunmonkgroup** [comment]
> I suggest https://github.com/openark/orchestrator/blob/master/docs/configuration-discovery-classifying.md

sounds good.

> What I think you may be missing is: what if the master applied some transactions, which never made it to any of the replicas?

I'm admittedly inexperienced with this kind of replication, so please correct me if I'm wrong or missing something in any of the following points:

1. At https://github.com/openark/orchestrator/blob/master/docs/topology-recovery.md#graceful-master-promotion it says, as one of the steps of the process: ```orchestrator makes sure your designated server is caught up with replication```
2. This seems to indicate that the new master would not be missing any transactions
3. ```MASTER_USE_GTID=current_pos``` means that the old master now becoming a slave will use the last transaction it its logs as its starting point, which should prevent the new master from sending an older, out of order transaction.

If orchestrator does in fact ensure that the designated new master is caught up, I'm not clear how the case you're describing can happen?

**Comment by shlomi-noach** [comment]
Sorry, I think two things got mixed here. I now realize you're talking about graceful takeover. I was confused, because https://github.com/openark/orchestrator/issues/918#issuecomment-507175107 to which you pointed me, discusses restoring the master from _any_ failover.

So, with graceful takeover the promoted replica does indeed have same dataset as master, and you may restore the demoted master back into the replication chain. In fact, orchestrator does that for you, but does not run `start slave`.

**Comment by thehunmonkgroup** [comment]
Very helpful, thank you!

How would you feel about me adding some clarification at https://github.com/openark/orchestrator/blob/master/docs/topology-recovery.md#graceful-master-promotion based on your last comment?

And also, in the graceful failover case, does orchestrator always handle everything but ```start slave```, or are there exceptions to that case?

**Comment by shlomi-noach** [comment]
> How would you feel about me adding some clarification at

please do

> does orchestrator always handle everything but start slave

everything, to the best of my understanding.

**Comment by thehunmonkgroup** [comment]
I think I'll need an answer to #1146 in order to proceed with the PR.

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/openark/orchestrator/commit/fc05b377b4f728012cafc338eaf02326d510cfa9 as part of #1165

**Comment by thehunmonkgroup** [comment]
I reviewed the new doc at #1165 and it looks good.

The one tiny suggestion I would make is clarifying for the web interface case whether it uses ```graceful-master-takeover``` or ```graceful-master-takeover-auto```.

**Comment by shlomi-noach** [comment]
Thank you -- doc updated.

**Comment by shlomi-noach** [comment]
#1165 is merged. Closing this issue.
