### ISSUE TITLE
Starting slave on demoted master from graceful failover broken for MariaDB in GTID strict mode

### ISSUE THREAD

**Issue by thehunmonkgroup** [openark/orchestrator#1146]
I can provide more output if needed, to start here's the simple report:

 * Following graceful takeover instructions at https://github.com/openark/orchestrator/blob/master/docs/topology-recovery.md#graceful-master-promotion
 * MariaDB, using GTID with strict mode set
 * After executing a graceful takeover in orchestrator, I run ```start slave``` on the demoted master
 * ```slave show status``` on the demoted master shows this error message: ```An attempt was made to binlog GTID 1-1-1 which would create an out-of-order sequence number with existing GTID 1-2-830, and gtid strict mode is enabled```

However, if I run the following manually (or in the ```PostGracefulTakeoverProcesses``` hook), the failover works:

```sql
CHANGE MASTER TO MASTER_CONNECT_RETRY=1, MASTER_USE_GTID=current_pos;
START SLAVE;
```

I ran into this working on the documentation enhancements proposal at #1134 

Should this be regarded as a bug in orchestrator, or should we simply provide some extra documentation for the MariaDB GTID strict mode case?

**Comment by shlomi-noach** [comment]
> Should this be regarded as a bug in orchestrator

A parallel discussion with @sjmudd exposed the fact that for MariaDB GTID, `orchestrator` always uses:
```
CHANGE MASTER TO ... master_use_gtid=slave_pos
```
In your `PostGracefulTakeoverProcesses`, what happens if you run 
```
CHANGE MASTER TO MASTER_CONNECT_RETRY=1, MASTER_USE_GTID=slave_pos;
START SLAVE;
```
?

At this time I don't have personal experience with MariaDB GTID and the differences between the various `MASTER_USE_GTID` flavors. I will need to dig in.

Related: https://github.com/openark/orchestrator/issues/1133

**Comment by thehunmonkgroup** [comment]
This is a quite succinct summary of the difference between ```slave_pos``` and ```current_pos```: https://dba.stackexchange.com/a/234323

In my experimentation, what's mentioned in that comment holds true:
 * For new slave or rejoining slave ```slave_pos```
 * For a master turning into a slave ```current_pos```

I'm pretty sure your suggestion won't work in the graceful failover scenario, as the old master will almost assuredly have a ```slave_pos``` that is behind its last transaction before the switchover.

What I mentioned in my first comment is what's worked well for me in the ```PostGracefulTakeoverProcesses``` hook:

```sql
CHANGE MASTER TO MASTER_CONNECT_RETRY=1, MASTER_USE_GTID=current_pos;
START SLAVE;
```

It's not the end of the world if in the MariaDB GTID case, I have to use that extra line instead of just ```START SLAVE;```, but it would be nice if orchestrator could figure that out and do the right thing when it reconnects to the new master. In either case, I'd like to document it accurately!

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/openark/orchestrator/commit/fc05b377b4f728012cafc338eaf02326d510cfa9 as part of #1165

**Comment by shlomi-noach** [comment]
@thehunmonkgroup can you please try this binary: https://github.com/openark/orchestrator/suites/689941869/artifacts/6490910, built by the #1165 CI:

- It should correctly `CHANGE MASTER TO ... MASTER_USE_GTID=current_pos` in the case of a graceful master takeover (in fact, in any case of a MariaDB server that'c turning from being a `master` into a replica)
- use `graceful-master-takeover-auto` to also have replication auto-start at the end of the takeover. So you can remove the code from your `PostGracefulTakeoverProcesses`.

Can you please let me know how this works for you?

**Comment by thehunmonkgroup** [comment]
Works beautifully! I've attached the log of one full cycle of invoking ```graceful-master-takeover-auto``` in case you want to review -- upon my review everything looks good.
[graceful-master-takeover-auto.log](https://github.com/openark/orchestrator/files/4640990/graceful-master-takeover-auto.log)

**Comment by shlomi-noach** [comment]
#1165 is merged; closing this issue.
