### ISSUE TITLE
Collecting Metrics of orchestrator 

### ISSUE THREAD

**Issue by rushi47** [openark/orchestrator#1178]
Hello @shlomi-noach ,
Hope you are doing Good :) 
I was looking at monitoring part of orhcestrator & i found this :- 
https://github.com/openark/orchestrator/blob/master/resources/metrics/orchestrator-grafana.json
, which looks great seems to have sufficient information am expecting .
But am unable to find the way to pull this metrics out of orchestrator. Have gone through previous issues and i found one api end point, you have mentioned couple of times which is `api/debug/metrics`, this doesnt seem to exist anymore.
Can you help me with in pulling all those metrics out, which are defined in orchestrator-grafana.json for Grafana Dashboard.

**Comment by shlomi-noach** [comment]
You can pull data from `/debug/metrics` (without `/api`).

My memory on the grafana JSON isn't so clear. I wrote that 5 years ago, and I hardly remember the occasion -- haven't used Grafana since, so I'm sorry that at this time I don't have much insight.

**Comment by rushi47** [comment]
@shlomi-noach haha ok :D, anyway Thanks a lot for Quick Reply :).
