### ISSUE TITLE
how orchestrator handle full connection or master dry run ?

### ISSUE THREAD

**Issue by pcleon** [openark/orchestrator#1197]
hello, currently i use orchestrator for mysql ha, but i face these two question below:
1. it doesn't recognize full connection, untill i kill orchestrator's sleep thread.
2. when  mysql dry run, but master can't write data such as  os/hardware problem ,or set super_read_only=on, then nobody can write anything,  but orchestrator think it's running good.

Looking forward to any suggestions !

**Comment by shlomi-noach** [comment]
I regret that I don't understand the questions.

1. What does it mean "recognie full connection"? What's the orchestrator kill thread?
Can you please clarify:

- what did you expect
- what happened
- attach logs, output as needed

2. what is "mysql dry tun"? 

> but orchestrator think it's running good.

there's various situations where the above gets analyzed correctly. Again, please:

- what did you do?
- what did you expect?
- what happened?
- attach logs, output etc.

**Comment by shlomi-noach** [comment]
it's best to follow the instruction in the new issue template.
