### ISSUE TITLE
Failure recovery does not give enough detail on what it did and why

### ISSUE THREAD

**Issue by sjmudd** [openark/orchestrator#120]
Orchestrator recovers from master or intermediate master failover pretty well and that is great. However, sometimes if you want to look at the details they are hard to find.

I would like to see the following information being shown in these 3 places:
* notifications by orchestrator of what it's done and why (through the external hooks)
* in logging
* in the output you can see here: https://orchestrator.domain.com/web/audit-failure-detection

1. What the failure type was (I think this is already shown)
1. Which replacement master was chosen and why.  e.g. most up to date master in the same DC.
1. The steps that were taken to achieve the adjustment in the replication topology and any errors that occurred during the process.  This information is available in the logs but the information in the logs may not be kept for long and will also contain the constant discovery processes that are running, so keeping this specific information is useful should things go wrong.

This would make the reporting of problems and later investigation easier as it wouldn't be necessary to scan through a large number of logs. The information is available but is not necessarily logged or kept for later use.  Even when orchestrator works fine it's convenient to see all these details to confirm the correct behaviour, but also should there be an issue it makes it easier to diagnose the cause, whether that's due to orchestrator failing or the systems responding in some unexpected way.

**Comment by shlomi-noach** [comment]
I agree that we can have better well formed auditing for failovers. I'm happy to write to a specialized recovery-audit-table. Does that make sense?

**Comment by sjmudd** [comment]
To be honest I've not checked exactly how much information is currently stored, and a more complete recovery audit table probably makes sense.  I guess we need to look and figure out the details of exactly what it makes sense to add and then figure out how and where to do that.
