### ISSUE TITLE
How to introduce a reasonable delay before Orchestrator executes automated failover

### ISSUE THREAD

**Issue by thehunmonkgroup** [openark/orchestrator#1219]
I have my cluster set up for auto-recovery via the ```RecoverMasterClusterFilters``` configuration.

This works perfectly save for one issue: my 'primary' MariaDB instance is actually a two-node Pacemaker cluster. From Orchestrator's view it looks like one server, but in the background, Pacemaker manages the two nodes in an active/passive topology.

The challenge is that if I (or Pacemaker automatically via some failure detection) moves the active MariaDB service to the other Pacemaker node, the database connection is down for 15-30 seconds, and from Orchestrator's point of view during that transition, it is a failed master, which results in the automated recovery feature of Orchestrator kicking in and moving the master elsewhere.

What I'm looking for is some way to introduce a grace period into Orchestrator's automated failover workflow. If I could delay Orchestrator deciding on failure for about a 60 second grace period, then the movements of the service amongst Pacemaker nodes would not result in spurious master failovers.

I've looked at all of the config options, and don't see anything that does what I'm looking for.

I've also considered adding a ```PreFailoverProcesses``` hook that simply sleeps 60 seconds, then checks the Pacemaker cluster to see if the service is alive again, and if so, returns a non-zero exit code, thus cancelling the rest of the failover process -- but I'm unsure of the side effects of such an approach.

So, questions:
 * Have I missing a config setting that will solve my problem?
 * If not, will the ```PreFailoverProcesses``` hook approach work, and do so without compromising Orchestrator's ability to initiate future automated failovers in the event of an actual outage?
 * If neither of those, would you consider adding some kind of config setting that introduces an optional grace period in automated failover?

**Comment by shlomi-noach** [comment]
First, I'm confused on why you need `orchestrator` if you have `pacemaker` for your failovers. Or, conversely, why you need `pacemaker` if you use `orchestrator` for your failovers. 

The `PreFailoverProcesses` is the correct way to go. Rather, it's the only way to go right now if you want delayed failovers. FYI if a `PreFailoverProcesses` hook returns with non-zero exit code, the failover is aborted. That can also prove useful.

I'm not keen on a graceful period in automated failover. But you're the 2nd to ask. If more people present with use cases, I may reconsider.

**Comment by thehunmonkgroup** [comment]
I use Orchestrator to manage my MariaDB instances between regions, and Pacemaker to manage my data nodes (MariaDB, ProxySQL, NFS) in my 'primary' region.

I suppose I could chose to have Orchestrator manage all the MariaDB nodes, but that actually seems more complex given my redundancy needs in my primary region.

Thx for the clarification on ```PreFailoverProcesses```.

**Comment by sbrattla** [comment]
I'd be interested in a grace period as well. I've got all databases running in OVH infrastructure, and I've seen network issues come and go for very short periods of time. Nothing wrong with the actual servers, but although not often, I have seen that the internal openstack networking for some reason decided on taking a very small break (maybe just for a single, say, database server).

I run databases and latency sensitive applications in the same datacenter (DC). If that DC fails, it's OK if both databases and applications start up in another DC. But it would be a pity if the master database moves to another DC just because the network went on a small break. By introducing a grace period, that would probably save me from having to deal with that scenario.
