### ISSUE TITLE
Simple Python wrapper for Orchestrator API

### ISSUE THREAD

**Issue by thehunmonkgroup** [openark/orchestrator#1226]
Not really sure where else to put this, if there's some kind of announcement list (if it's worthy) I"m happy to do that.

I've written a very simple Python wrapper for the Orchestrator API. It mostly services my personal needs, but could easily be extended for other purposes, so I published it here: https://github.com/apartmentlines/python-mysql-orchestrator

From the README:

This humble library provides the following:

 * A base ```Orchestrator``` class
 * ```orchestrator-run.py```: Wraps the base class for calling from CLI
 * ```auto-master-writer.py```: Detects a healthy cluster with a master that has
   ```read_only = true```, and sets ```read_only = false``` (this allows
   configuring all cluster nodes to start in read-only mode, and still provide
   an automated way to set the master as writeable.

Really appreciate all of the great work put into Orchestrator, and hoping this small contribution can benefit others.

**Comment by shlomi-noach** [comment]
Hey, really cool, thank you for sharing!

If you like, consider making a PR to update [related projects](https://github.com/openark/orchestrator#related-projects).

**Comment by thehunmonkgroup** [comment]
Done: https://github.com/openark/orchestrator/pull/1229
