### ISSUE TITLE
Remove "Long queries" from the documentation

### ISSUE THREAD

**Issue by marostegui** [openark/orchestrator#1227]
Per https://github.com/openark/orchestrator/pull/726, long-running queries aren't supported anymore, however the documentation still mentions it at _docs/using-the-web-interface.md_ and at _docs/gotchas.md_

**Comment by shlomi-noach** [comment]
Thank you -- yes, these docs should be updated. Are you in a capacity to make a PR for the docs?

**Comment by marostegui** [comment]
Yep! Can do :)

**Comment by shlomi-noach** [comment]
Closed by #1228
