### ISSUE TITLE
Would anything speak against running orchestrator on the MySQL database servers?

### ISSUE THREAD

**Issue by sbrattla** [openark/orchestrator#1231]
Assuming a setup of 3 MySQL database servers (1 master, 2 slaves), would anything speak against deploying orchestrator in raft mode on these same servers?

I can't find anything in the documentation which mentions this specifically, but I'd be interested in knowing if there are any obvious arguments against this kind of setup?

**Comment by shlomi-noach** [comment]
@sbrattla there's nothing to speak against it, and I'm familiar with one setup that does exactly that.

**Comment by kien-truong** [comment]
When you use 3 MySQL server, you'd expect to tolerate 2 MySQL server failure, however I think with this setup you can only tolerate at most 1 server failure, since orchestrator/raft won't be able to reach quorum with only 1 server left.

**Comment by sbrattla** [comment]
@kien-truong that's a good point I did not think about. So, in summary, it's absolutely doable, but with the tradeoff that you really only can tolerate a single failure.
