### ISSUE TITLE
Username 'test' after graceful-master-takeover

### ISSUE THREAD

**Issue by AshDevilRed** [openark/orchestrator#1247]
### I get an error when I trigger a master takeover.
I have two percona-server with orchestrator on it. (Master/slave)

**Here is the topology :** 

> root@debianPercona1:~# orchestrator-client -c topology -a debianPercona1
> debianPercona1:3306   [0s,ok,5.7.31-34-log,rw,ROW,>>,GTID]
> + debianPercona2:3306 [0s,ok,5.7.31-34-log,rw,ROW,>>,GTID]

**Here is what I have when I query slave_master_info table:** 
**(On the master)**
mysql> select User_name,User_password from slave_master_info;
x - - - - - - - - - - -+- - - - - - - - - - - - - - -+
|....User_name...|....User_password....|
+- - - - - - - - - - - +- - - - - - - - - - - - - - -+
|........test............|.................................|
+- - - - - - - - - - - +- - - - - - - - - - - - - - -+

**(On the slave)**
mysql> select User_name,User_password from mysql.slave_master_info;
x - - - - - - - - - - -+- - - - - - - - - - - - - - -+
|...User_name....|....User_password....|
+- - - - - - - - - - - +- - - - - - - - - - - - - - -+
|...repl_user........|.............root..............|
+- - - - - - - - - - - +- - - - - - - - - - - - - - -+

The test user on the master is unexpected and when i want to make a graceful-master-takeover (debianPercona1 > debianPercona2)
debianPercona1 can't connect to the new master : 

Last_IO_Error: error connecting to master 'test@debianPercona2:3306' - retry-time: 60  retries: 1

Is it possible to change the credentials in any config file ? So that when the master falls he retrieve the credentials of the slave ?

**Percona config file on the master :**

```
[mysqld]
user   = mysql
pid-file = /var/run/mysqld/mysqld.pid
socket   = /var/run/mysqld/mysqld.sock
port   = 3306
basedir    = /usr
datadir    = /var/lib/mysql
tmpdir   = /tmp
lc-messages-dir  = /usr/share/mysql
explicit_defaults_for_timestamp

server-id = 1
log-bin = mysql-bin
binlog_format = row
gtid-mode=ON
enforce-gtid-consistency
log-slave-updates
session_track_gtids=ALL_GTIDS

log-error    = /var/log/mysql/error.log

binlog-ignore-db = orchestrator
binlog-ignore-db = mysql

sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_ALL_TABLES
master_info_repository=TABLE

symbolic-links=0
```

**Percona config file on the slave :** 

```
[mysqld]
user   = mysql
pid-file = /var/run/mysqld/mysqld.pid
socket   = /var/run/mysqld/mysqld.sock
port   = 3306
basedir    = /usr
datadir    = /var/lib/mysql
tmpdir   = /tmp
lc-messages-dir  = /usr/share/mysql
explicit_defaults_for_timestamp
server-id = 2
log-bin = mysql-bin
relay-log = relay-log-server
read-only = OFF
gtid-mode=ON
enforce-gtid-consistency
log-slave-updates
session_track_gtids=ALL_GTIDS

log-error    = /var/log/mysql/error.log

replicate-ignore-db = orchestrator
replicate-ignore-db = mysql
binlog-ignore-db = orchestrator
binlog-ignore-db = mysql

sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_ALL_TABLES
master_info_repository=TABLE

symbolic-links=0
```

**Thanks in advance for your assistance.**

**Comment by shlomi-noach** [comment]
This seems to be unrelated to `orchestrator`. I'm not sure where the user `test` came from. You seem to have a primary and a replica, and other than the fact `orchestrator` observes your topology, it doesn't create accounts.

**Comment by AshDevilRed** [comment]
Thanks, but i seen a similar issue you posted 2 years ago : 
https://github.com/datacharmer/dbdeployer/issues/9

The master User_name is 'test' too.

If you have any idea to solve that problem i'll take it.

**Comment by shlomi-noach** [comment]
The one I created for dbdeployer - if my memory serves me correctly the problem was with some automation script that generated the user. I'm afraid I have no idea what's happening on your setup. A Debian install? Some puppet script?
Sorry. At any case it is unrelated to orchestrator as best as I can tell. I'll keep this open for a couple days but will then close the issue.

**Comment by AshDevilRed** [comment]
Thanks for your time, i will look toward percona's config.
