### ISSUE TITLE
Question: "alias" mode and "instance_alias" field unused

### ISSUE THREAD

**Issue by azavorotnii** [openark/orchestrator#1252]
In UI under "anonymous" mode there is "alias" mode which I assume should expose human-readable instance aliases. But I didn't find a way to assing "instance_alias" field anyhow. From code it seems always written empty to database.

Could you please clarify if my understanding of "alias" mode is correct and how can I assign human readable aliases for separate instances inside cluster?

**Comment by shlomi-noach** [comment]
There is a config variable called `DetectInstanceAliasQuery`. The value is a query, which `orchestrator` will run on the instance, and is expected to return a single row, single column, text value -- that's the alias. It's a ad-hoc solution, iirc contributed by the community.
