### ISSUE TITLE
How to control timeout for master

### ISSUE THREAD

**Issue by gvasileiou** [openark/orchestrator#1257]
Hi all, 

 What is the variable needs to be increased for timeout in Master ? 
For example in our case the response from Master might take more than 20 seconds due to migration activities. 

So we don't wont the master to be considered as dead, and the UnreachableMasterWithLaggingReplicas to be triggered. (since migration there is lots of lag in replicas).

**Comment by shlomi-noach** [comment]
> and the UnreachableMasterWithLaggingReplicas to be triggered.

`UnreachableMasterWithLaggingReplicas` does not cause a failover, though it does cause replication restart on all replicas. I can see that may be a problem.

You may increase `ReasonableReplicationLagSeconds` in configuration (default is `10` seconds).

**Comment by gvasileiou** [comment]
Thank you @shlomi-noach !! 
Much appreciated. 
:)
