### ISSUE TITLE
ERROR ReadTopologyInstance(***) show global status like 'Uptime': dial tcp ***: connect: connection refused

### ISSUE THREAD

**Issue by biaoyun** [openark/orchestrator#1287]
Hello！
I ran into some problems when using orchestrator V3.2.3
my mysql topology is as follows:
192.168.11.11:3301(主) -> 192.168.11.12:3301(从) -> 192.168.11.13:3801(binlog server)

I use ripple(make by google, https://github.com/google/mysql-ripple) to be binlog server,when binlog server started,then orchestrator will print error like that:
2020-12-30 10:58:21 ERROR ReadTopologyInstance(192.168.11.13:3301) show global status like 'Uptime': dial tcp 192.168.11.13:3301: connect: connection refused

As seen above,real port of binlog server is 3801,but port in error message is 3301(same as mysql port) and I'm sure nothing using 3301 to connect mysql in 192.168.11.13(binlog server address)

Can I think it is a compatibility issue between the orchestrator and binlog server(ripple)?

**Comment by shlomi-noach** [comment]
`orchestrator` does not support ripple. Although the problem you describe is slightly different: it seems to me `orchestrator` discovers your ripple servers by running `show processlist` on `192.168.11.12:3301`, and it then sees `192.168.11.13`. it has no idea what port `192.168.11.13` listens on, so it heuristically assumes `3301`.

Does `ripple` know how to identify itself with `report_host` and `report_port`? In which case, please configure it so, and use `DiscoverByShowSlaveHosts: true` in your `orchestrator`'s config file.

Even so, like I said, there's no support for `ripple`, it will probably still not work. Consider adding `192.168.11.13` to `DiscoveryIgnoreHostnameFilters`.

**Comment by biaoyun** [comment]
Thank you for your answer!
