### ISSUE TITLE
What is a forced failover vs. promotion?

### ISSUE THREAD

**Issue by sbrattla** [openark/orchestrator#1289]
I'm trying to get familiar with orchestrator, and have a setup a master database + 2 slaves. I have disabled automatic failover.

When I stop the master database, orchestrator detects that and presents recovery options :+1: 

- Forced failover
- Slave promotion

![image](https://user-images.githubusercontent.com/1845372/104468109-5ea24100-55b7-11eb-8282-b9e7a1e2139e.png)

What is the difference between failover and promotion in this case? As far as I can see, to recover from this situation I can promote one of the slaves.

What does the forced failover actually do?

**Comment by shlomi-noach** [comment]
"Force fail over" tells `orchestrator` to use same logic as if it initiated the failover automatically, which means it will pick the replica that makes most sense, and try to preserve as much data and servers.

By choosing a specific server to promote you're taking a risk that you've miscalculated; maybe you picked the wrong server, with e.g. higher version or with some other inocompatibility, or maybe you picked a replica which was behind other replicas.

**Comment by sbrattla** [comment]
When I choose the "force fail" option, the old master gets moved into its own cluster - so that's good.

However, the promoted slave is still attempting to replicate, even though `MasterFailoverDetachReplicaMasterHost` is set to `true`. Could I be doing anything else which leads to this situation.

I'd like all failures to be resolved manually.

![image](https://user-images.githubusercontent.com/1845372/104472430-3cf78880-55bc-11eb-8eb0-a0411439d5df.png)

**Comment by shlomi-noach** [comment]
You want to configure `"ApplyMySQLPromotionAfterMasterFailover": true`. See https://github.com/openark/orchestrator/blob/master/docs/configuration-recovery.md#promotion-actions

**Comment by sbrattla** [comment]
Thanks! Looks good now :-) 

Thank you very much for quick answers!

![image](https://user-images.githubusercontent.com/1845372/104476169-3bc85a80-55c0-11eb-885c-c81d5c66f507.png)
