### ISSUE TITLE
Does  binlog file:pos support moving replications from old master to new master automatically  after failover?

### ISSUE THREAD

**Issue by MonkeyFang** [openark/orchestrator#1291]
Does  binlog file:pos support moving replications from old master to new master
automatically  after failover?

**Comment by shlomi-noach** [comment]
Per the documentation [here](https://github.com/openark/orchestrator/blob/master/docs/topology-recovery.md#requirements), no.

consider enabling `AutoPseudoGTID`, per https://github.com/openark/orchestrator/blob/master/docs/configuration-discovery-pseudo-gtid.md#automated-pseudo-gtid-injection

**Comment by MonkeyFang** [comment]
Thanks very much!
