### ISSUE TITLE
Cannot establish replication after graceful takeover if super_read_only is enabled

### ISSUE THREAD

**Issue by akamac** [openark/orchestrator#1304]
Hi Shlomi,

I have one master and one slave, `UseSuperReadOnly: true`.
After running `orchestrator-client -c graceful-master-takeover-auto -alias mysql` orchestrator cannot update replication coordinates on the old master, particularly setting Master_Host to `_` (underscore). If I disable `UseSuperReadOnly`, everything looks good.

Is it possible to use `super_read_only` and set the correct coordinates after takeover?

**Comment by shlomi-noach** [comment]
Was not aware that `super_read_only` blocks `CHANGE MASTER TO`. Which server versoin are you using?

**Comment by akamac** [comment]
Percona Server 5.7.14
It's weird, because `CHANGE MASTER TO` works good if run from mysql client.

**Comment by shlomi-noach** [comment]
Interesting. Do you have the capacity to investigate this? I'm unlikely to look into this right now

**Comment by akamac** [comment]
It turned out it was not related to `super_read_only`, but other issue. Sorry for distracting you.
