### ISSUE TITLE
Nginx configuration about  orchestrator/raft

### ISSUE THREAD

**Issue by MonkeyFang** [openark/orchestrator#1314]
If I enable the orchestrator/raft's  http authentication,the nginx would not work.
Document security.md does not have the sample configuration of nginx in the http authentication's situation,
Could you give me a sample configuration?

**Comment by shlomi-noach** [comment]
I do not have a handy sample configuration for `nginx` reverse-proxy at this time. Used to, but not working with `nginx` these days.

**Comment by MonkeyFang** [comment]
I have catched the meaning of  the configuration '"AuthenticationMethod": "proxy"'.Thanks for your commented.
