### ISSUE TITLE
Discover instance error:TLS requested but server does not support TLS

### ISSUE THREAD

**Issue by MonkeyFang** [openark/orchestrator#1317]
# Scenario where the error occurred
When I first use orchestrator-client to discover my instance,I execute below command:
`/usr/bin/orchestrator-client -c discover -i 172.25.2.241:3306 -e 'X-Forwarded-User:xxxxxxxxxxxxx'`
command executed error.
# error info
- TLS requested but server does not support TLS
- orchestrator leader log: ERROR ReadTopologyInstance(172.25.2.241:3306) show global status like 'Uptime': TLS requested but server does not support TLS

# Orchestrator and orchestrator-client version
3.2.4

# Orchestrator configuration  about tls
```
  "MySQLTopologyUseMutualTLS": false,
  "MySQLOrchestratorUseMutualTLS": false,
  "AgentsUseMutualTLS": false,
  "UseMutualTLS": false,
```

# MySQL version
5.6.26-log MySQL Community Server (GPL)

**Comment by shlomi-noach** [comment]
I'm low on cycles for TLS-related issues. Any contribution is appreciated.

**Comment by MonkeyFang** [comment]
According to my test, PowerAuthUsers contains uppercase letters and the error will appear.Thanks for your comment.

**Comment by MonkeyFang** [comment]
thanks

**Comment by kormat** [comment]
This might be related to #1294 (which has a PR attached)

**Comment by leiless** [comment]
Hi, All. I met this issue also today:
```
$ orchestrator-client -c discover -i 192.168.3.8:13306
TLS requested but server does not support TLS

```

`192.168.3.8:13306` is running with `10.5.11-MariaDB-1:10.5.11+maria~focal-log` (Ubuntu 20.04.2 LTS), I'm assured that the DB doesn't use TLS at all.

---

```
2021-07-08 13:06:29 82 [Warning] Aborted connection 82 to db: 'unconnected' user: 'unauthenticated' host: '192.168.3.172' (This connection closed normally without authentication)
2021-07-08 13:06:29 81 [Warning] Aborted connection 81 to db: 'unconnected' user: 'unauthenticated' host: '192.168.3.172' (This connection closed normally without authentication)
```

It seems that the cause is the topology user access is restricted in `172.31.254.%`, which I(`192.168.3.172`) definitely not in there.

**Comment by zhouyh139** [comment]
Hi, All. I met this issue also today:
$ orchestrator-client -c discover -i xx.xxx.xxx.xxx:13300
TLS requested but server does not support TLS
ip用xx.xxx.xxx.xxx代替
$ ./orchestrator --version
3.2.6

[martini] Started HEAD /api for xx.xxx.xxx.xxx:42082
[martini] Completed 404 Not Found in 322.306µs
[martini] Started HEAD /api for xx.xxx.xxx.xxx:42084
[martini] Completed 404 Not Found in 398.099µs
[martini] Started GET /api/discover/xx.xxx.xxx.xxx/13300 for 10.121.7.70:42086
2022-12-01 00:21:53 ERROR ReadTopologyInstance(pg-meta-1:13300) show global status like 'Uptime': TLS requested but server does not support TLS
[martini] Completed 500 Internal Server Error in 6.527586ms
