### ISSUE TITLE
orchestrator\go\inst\instance_topology.go --> line : 2284:   have  invalid logic

### ISSUE THREAD

**Issue by ywhywl** [openark/orchestrator#1326]
orchestrator\go\inst\instance_topology.go  line : 2284 

> `replicas = sortedReplicasDataCenterHint(replicas, stopReplicationMethod, dataCenterHint)
 if err != nil {
  return candidateReplica, aheadReplicas, equalReplicas, laterReplicas, cannotReplicateReplicas, err
 }`

> `if err != nil`
condition is always 'false' because 'err' is always 'nil', 

maybe we need err message for sortedReplicasDataCenterHint  or  delete the code

**Comment by shlomi-noach** [comment]
Permalink: https://github.com/openark/orchestrator/blob/f30980b87d323d3bfeb7ebbb404a40244bc293c8/go/inst/instance_topology.go#L2277-L2284

**Comment by shlomi-noach** [comment]
The entire `if err ...` block can go away. As you suggest, the condition is always `false`. However, there is also no need for it. `sortedReplicasDataCenterHint` does not and should not return an error.

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/openark/orchestrator/pull/1327
