### ISSUE TITLE
Orchestrator to monitor RW status of the primary node.

### ISSUE THREAD

**Issue by llintes** [openark/orchestrator#1328]
Hi,

Our config file has super_read_only set by default so whenever a mysql instance is started, it will be in super_read_only mode . 
On the initial configuration of a cluster to be monitored by Orchestrator, the primary node is set to RW and subsequent failovers/takeovers are handled by Orchestrator which will set the newly promoted primary to RW. 
There are cases when mysql instance is restarted so fast that Orchestrator will not detect it fast enough and will not do a failover. One such example is when memory manager picks mysql instance as the biggest memory offender and kills it. mysqld_safe will restart it quickly and Orchestrator does not get to do a failover. In this case, former primary which continues to be primary, will be started with RO and we need to have an outside process to monitor it and switch it to RW. We have tested with  MASTER_CONNECT_RETRY lowered to 1 second to make sure that standbys would detect the change of status fast enough but even with this value, Orchestrator did not trigger the failover in our tests.
Since Orchestrator has the topology info, would it be possible to implement a feature that monitors the status of the primary and switches it back to RW if it becomes RO? 

Thank you,
 Liviu

**Comment by shlomi-noach** [comment]
@llintes thank you -- I'm looking into this.

**Comment by shlomi-noach** [comment]
Please see ~~https://github.com/openark/orchestrator/pull/1330~~

**Comment by shlomi-noach** [comment]
Created #1332 and deprecated ~~#1330~~

**Comment by shlomi-noach** [comment]
@llintes would you like to test #1332 ?
