### ISSUE TITLE
Please update github.com/go-sql-driver/mysql as some bugs disappear

### ISSUE THREAD

**Issue by sjmudd** [openark/orchestrator#1339]
While trying to diagnose an issue which came up intermittently with bulk writes, something we use to reduce the write load generated by orchestrator I was unable to find the cause.  I did try modifying a few bits of code to try to find the problem but that did not help.

The error rate was ~ 1:50,000 bulk writes so in theory was not an issue but did mean that if during this time there was a failure orchestrator might act on stale information as several hundred instance updates would be lost.

I tried upgrading `github.com/go-sql-driver/mysql` to the latest version and tried `commit bcc459a906419e2890a50fc2c99ea6dd927a88f2 (HEAD -> master, tag: v1.6.0, origin/master, origin/HEAD)`

Rerunning orchestrator again and the intermittent faults went away.

So I suspect a minor bug which I was triggering under some special situation, but which is now correctly handled by the latest  driver.

So please consider updating the `vendor` version of this driver in orchestrator.

The error seen was:

```
2021-04-15T09:33:11.725035+02:00 <hostname-removed> orchestrator[60080]: 2021-04-15 09:33:11 ERROR Error 1264: Out of range value for column 'uptime' at row 792
```
Interestingly Uptime is a 32-bit unsigned value in both Go and MySQL so assuming the bits are transferred from one place to the other it's impossible for them to be out of range yet orchestrator (and go) were convinced something was wrong. I can only guess a negative > 32-bit value was being compared/checked but again that should be impossible.  It also seemed to be triggered when failing to reach a backend server. I suspect the logic here https://github.com/openark/orchestrator/blob/master/go/inst/instance_dao.go#L394 should split `QueryRow` and `Scan` as if `QueryRow` fails applying `Scan` is not defined. At least the `go-sql-driver` docs do not mention this specific situation.

Thanks,

Simon

**Comment by sjmudd** [comment]
The go driver update did not help as eventually I saw the same error. So please disregard this request.

**Comment by sjmudd** [comment]
Updating the driver and moving orchestrator to use go modules would be good. That would make it easier to keep orchestrator up to date with external libraries.

**Comment by shlomi-noach** [comment]
Update it is!

**Comment by shlomi-noach** [comment]
`go mod` -- yeah, there's no escaping it, it will have to happen, I'll look into it.

**Comment by shlomi-noach** [comment]
Updated in vendor/github.com/go-sql-driver/mysql/.gitignore

**Comment by shlomi-noach** [comment]
Updated in https://github.com/openark/orchestrator/pull/1341
