### ISSUE TITLE
Orchestrator promoting a replica as master even where there is significant lag.

### ISSUE THREAD

**Issue by mohankara** [openark/orchestrator#1342]
Hi,
We have a 3 node Ec2/Centos/MySQL Instance. 1 Primary and 2 Replicas. MySQL Version is 5.6.7 and orchestrator is 3.1.4.
We have semi-sync replication enabled.

Over the weekend OPTIMIZE table was running on 3 big tables sequentially along with bunch of other purges. There was a lag due to this on the replicas. However after few hours the master died and orchestrator promoted Node 2 with 12 hours of replication delay as new master. We lost 12 hours of data !!!

I recreated the same issue in test to the best I could.

3 Node cluster with semi-sync enabled. Node 1 Master, Node 2, 3 replicas

-Stop SQL_THREAD on Node 2 and Node 3
-Initiate some transactions on Node 1. They will go through because IO_THREAD is still up.
-Kill -9 mysql on Node 1.
-Watch Orchestrator promote one of the replicas as new master even with lag.
-Check the transactions started in step 2. They will be TOTALLY MISSING on the new master and the replica.
-Start MySQL Node 1. It will be an “orphan” master with no replicas.
 
I figured this could be because when SQL_THREAD is down, the Seconds_Behind_Master is NULL when you run show slave status\G; I have not configured anything for SlaveLagQuery in orchestrator.conf.json, is that the reason why orchestrator ignores the lag and promotes a replica ? But I read somewhere that if this is not defined it will look in Seconds_Behind_Master but in my case, it will be NULL because SQL_THREAD was down. 
How do I fix this ?  Any help is greatly appreciated !!!

---

Contents of /etc/orchestrator.conf.json :
```json
{
  "Debug": false,
  "ListenAddress": ":3308",
  "MySQLTopologyUser": "orchestrator",
  "MySQLTopologyPassword": "xxxxx",
  "MySQLTopologySSLSkipVerify": true,
  "BackendDB": "sqlite",
  "SQLite3DataFile": "/usr/local/orchestrator/orchestrator.sqlite3",
  "MySQLConnectTimeoutSeconds": 1,
  "DefaultInstancePort": 3307,
  "DiscoverByShowSlaveHosts": true,
  "HostnameResolveMethod": "default",
  "MySQLHostnameResolveMethod": "@@report_host",
  "SlaveLagQuery": "",
  "DetectClusterAliasQuery": "SELECT 'abc-18172'",
  "DetectClusterDomainQuery": "",
  "DetectInstanceAliasQuery": "SELECT SUBSTRING_INDEX(@@hostname, '.', 1)",
  "DetectSemiSyncEnforcedQuery": "",
  "StatusEndpoint": "/api/status",
  "StatusSimpleHealth": true,
  "RecoveryPeriodBlockSeconds": 5,
  "RecoverMasterClusterFilters": [
    "*"
  ],
  "RecoverIntermediateMasterClusterFilters": [
    "*"
  ],
  "OnFailureDetectionProcesses": [
    "echo $(date -u \"+%F %T %Z\") - 'Detected {failureType} on {failureCluster}. Affected replicas: {countSlaves}' >> /usr/local/apps/orchestrator/logs/orchestrator-recovery.log"
  ],
  "PreFailoverProcesses": [
    "echo $(date -u \"+%F %T %Z\") - 'Will recover from {failureType} on {failureCluster}' >> /usr/local/apps/orchestrator/logs/orchestrator-recovery.log"
  ],
  "PostFailoverProcesses": [
    "echo $(date -u \"+%F %T %Z\") - '(for all types) Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Successor: {successorHost}:{successorPort}' >> /usr/local/apps/orchestrator/logs/orchestrator-recovery.log",
    "/usr/local/apps/mysql-failover/after-failover.sh {failedHost} {failedPort} {successorHost} {successorPort}"
  ],
  "PostUnsuccessfulFailoverProcesses": [
    "echo $(date -u \"+%F %T %Z\") - 'Unsuccessful failover process for {failureType} on {failureCluster}' >> /usr/local/apps/orchestrator/logs/orchestrator-recovery.log"
  ],
  "PostMasterFailoverProcesses": [
    "echo $(date -u \"+%F %T %Z\") - 'Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Promoted: {successorHost}:{successorPort}' >> /usr/local/apps/orchestrator/logs/orchestrator-recovery.log"
  ],
  "PostIntermediateMasterFailoverProcesses": [
    "echo $(date -u \"+%F %T %Z\") - 'Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Successor: {successorHost}:{successorPort}' >> /usr/local/apps/orchestrator/logs/orchestrator-recovery.log"

 ],
  "RaftEnabled": true,
  "RaftDataDir": "/var/lib/orchestrator",
  "RaftBind": "xxx.xx.xx.xxx",
  "DefaultRaftPort": 3309,
  "RaftNodes": [
    "xxx.xx.xx.xxx", "yyy.yy.yy.yyy", "zzz.zz.zz.zzz"
  ],
  "GraphitePollSeconds": 60,
  "GraphiteAddr": "localhost:9109",
  "GraphitePath": "orchestrator"
}
```

**Comment by shlomi-noach** [comment]
Hi, a few things:

> I figured this could be because when SQL_THREAD is down, the Seconds_Behind_Master is NULL

1. Use `ReplicationLagQuery`, https://github.com/openark/orchestrator/blob/master/docs/configuration-discovery-classifying.md#replication-lag, along with a heartbeat mechanism. The issue with `Seconds_Behind_Master: NULL` is unfortunately a common source for trouble. By injecting your own heartbeats and by monitoring the heartbeat through `ReplicationLagQuery`, you completely avoid the issue of `NULL`.
2.  Consider setting `FailMasterPromotionOnLagMinutes`, https://github.com/openark/orchestrator/blob/master/docs/configuration-recovery.md#promotion-actions
3. **or** `FailMasterPromotionIfSQLThreadNotUpToDate`
4. **or** `DelayMasterPromotionIfSQLThreadNotUpToDate`
5. General suggestion: be _very_ cautious about using `OPTIMIZE TABLE`. It makes a blockgin, complete rebuild of the table.
  - At the very least run `OPTIMIZE LOCAL TABLE` so that the command is not writen to the binary log (and then apply on each replica individually)
  - My suggestion: use an online schema change tool (`pt-online-schema-change` or `gh-ost`) to `ALTER TABLE your_table ENGINE=InnoDB`. This emulates the `OPTIMIZE` command, but does so online.

**Comment by mohankara** [comment]
Thanks Shlomi for your quick response.
I tried #3 that you suggested - "FailMasterPromotionIfSQLThreadNotUpToDate": true, in /etc/orchestrator.conf.json , restarted orchestrator and ran a test. It still promoted the slave. Am I missing something here ?

As far as your point about OPTIMIZE LOCAL, agreed, will review it.

**Comment by shlomi-noach** [comment]
> I tried #3 that you suggested - "FailMasterPromotionIfSQLThreadNotUpToDate": true,

Did you configure a heartbeat mechanism? What was the lag at time of failover/promotion?

**Comment by mohankara** [comment]
I haven't set up the heartbeat mechanism yet, I was trying to use either FailMasterPromotionIfSQLThreadNotUpToDate and/or DelayMasterPromotionIfSQLThreadNotUpToDate to get this working.
[root@node1 logs]# tail -f orchestrator-recovery.log
2021-04-27 01:56:41 UTC - Detected AllMasterSlavesNotReplicating on node1:3307. Affected replicas: 2 << Even after detecting AllMasterSlavesNot replicating, why did the orchestrator promote a replica with lag as master ?
2021-04-27 02:00:07 UTC - Detected DeadMaster on node1:3307. Affected replicas: 2
2021-04-27 02:00:07 UTC - Will recover from DeadMaster on node1:3307
2021-04-27 02:00:09 UTC - Recovered from DeadMaster on node1:3307. Failed: node1:3307; Promoted: node2:3307
2021-04-27 02:00:09 UTC - (for all types) Recovered from DeadMaster on node1:3307. Failed: node1:3307; Successor: node2:3307

I was trying to add a script to PreFailoverProcess. Logic in that is.. if SECONDS_BEHIND_MASTER is NULL or slave_SQL_thread is NOT running, do NOT promote that node as master. When I tested this logic, it detects the condition, but I don't know how to make it quit the whole promotion process, it recognizes the condition but proceeds to failover anyways.

**Comment by shlomi-noach** [comment]
Per documentation, if you exit a pre failover hook with nonzero exit code, the failover aborts.

**Comment by mohankara** [comment]
Thanks Shlomi-noach. Yes that part worked. Now I notice another issue, not sure if it's related to my change.
When the master and orchestrator leader run on the same node, if master is shutdown then orchestrator does not promote another node as master, it indefinitely waits for the master on node1 to come up. As a workaround, If I restart the orchestrator then another node gets promoted as master.

**Comment by shlomi-noach** [comment]
If the issue is solved, then please close it and open a new one, providing all necessary logs and data.

**Comment by mohankara** [comment]
Intent of this issue was to add a preFailover hook and it worked. Closing this issue now. Thanks
