### ISSUE TITLE
Migrating to Go Modules

### ISSUE THREAD

**Issue by cndoit18** [openark/orchestrator#1355]
Since Go 1.11, go includes Modules which is a dependency management system that makes dependency version information explicit and easier to use.

Please refer to the following two blogposts to understand and read more about using Go modules, and migrating to Go modules.

1. [Using Go Modules](https://blog.golang.org/using-go-modules) > 2. [Migrating to Go Modules](https://blog.golang.org/migrating-to-go-modules) >  > Using Go modules will enable us to easily manage dependencies and also run Go programs outside the GOPATH. We don't need to specify the GOPATH anymore.
2. [Here](https://medium.com/@fonseka.live/getting-started-with-go-modules-b3dac652066d) you can read more about using Go modules.

**Comment by shlomi-noach** [comment]
Thank you! Are you offering to submit a PR to migrate to `go modules`?

**Comment by cndoit18** [comment]
> Thank you! Are you offering to submit a PR to migrate to `go modules`?

let me try
