### ISSUE TITLE
Question about StartReplication at the end of  ResetReplication

### ISSUE THREAD

**Issue by yangeagle** [openark/orchestrator#1382]
At the end of the function `ResetReplicationOperation`, there is an operation `StartReplication`. I don't understand why this operation is there. I think it is redundant.

https://github.com/openark/orchestrator/blob/c7387314d2f35d16b1f6b24c08238e2824049ad4/go/inst/instance_topology.go#L1062

https://github.com/openark/orchestrator/blob/c7387314d2f35d16b1f6b24c08238e2824049ad4/go/inst/instance_topology.go#L1090

I look forward to your reply.

cc @MOON-CLJ

**Comment by shlomi-noach** [comment]
`StartReplication` is called in case `ResetReplication(instanceKey)` fails.

- if `ResetReplication(instanceKey)` succeeds, then `StartReplication` is meaningless and does nothing
- if `ResetReplication(instanceKey)` fails, then `StartReplication` restores the state back to before calling the function `ResetReplicationOperation()`
