### ISSUE TITLE
orchestrator 3.2.6 version "Deadlock" not print to orchestrator.log

### ISSUE THREAD

**Issue by MisKatherine** [openark/orchestrator#1399]
hello:
       We now use two versions of orchestrator(3.2.6 and 3.2.5 version) in our production environment.but the orchestrator.log output to the log is different. So when we monitor the ERROR keyword to see if the orchestrator is abnormal, we get results we don't need.
       Orchestrator 3.2.6 prints MySQLOrchestratorDatabase deadlock to the error log(like: ERROR Error 1213: Deadlock found when trying to get lock; try restarting transaction), orchestrator 3.2.5 database has a deadlock, but can't print to the orchestrator.log. How do I avoid printing deadlock logs?

       - what did you expect to happen?
         When I used the Orchestrator 3.2.6 version, I didn't want to print deadlock information to the orchestrator.log and only receive topology-related errors(like :ERROR ReadTopologyInstance(mmm-prod-bj1:3306) DetectPromotionRuleQuery: sql: no rows in result set)
       -  what did you do?
       Run the "show engine innodb status" command to view deadlock information, 3.2.6 and 3.2.5 both versions are displayed with deadlock information ;
      show engine innodb status\G
      LATEST DETECTED DEADLOCK
------------------------
2021-08-21 07:02:24 0x7efbd01f2700
*** (1) TRANSACTION:
TRANSACTION 2173552854, ACTIVE 0 sec starting index read, thread declared inside InnoDB 5000
mysql tables in use 1, locked 1
LOCK WAIT 3 lock struct(s), heap size 1136, 2 row lock(s)
MySQL thread id 14072791, OS thread handle 139619552904960, query id 2144196440 127.0.0.1 orchest_backend_user updating
delete
				from cluster_alias
			where
			last_registered < NOW() - interval 240 hour
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 98 page no 3 n bits 160 index PRIMARY of table `orchestrator`.`cluster_alias` trx id 2173552854 lock_mode X locks rec but not gap waiting
Record lock, heap no 87 PHYSICAL RECORD: n_fields 5; compact format; info bits 32
 0: len 17; hex 31302e33332e37302e3134313a33333036; asc 10.33.70.141:3306;;
 1: len 6; hex 0000818dc8d4; asc       ;;
 2: len 7; hex 7c0000021e0d4a; asc |     J;;
 3: len 17; hex 31302e33332e37302e3134313a33333036; asc 10.33.70.141:3306;;
 4: len 4; hex 6120347e; asc a 4~;;

*** (2) TRANSACTION:
TRANSACTION 2173552852, ACTIVE 0 sec updating or deleting, thread declared inside InnoDB 4996
mysql tables in use 2, locked 1
3 lock struct(s), heap size 1136, 2 row lock(s), undo log entries 1
MySQL thread id 14072774, OS thread handle 139619993593600, query id 2144196470 127.0.0.1 orchest_backend_user Sending data
replace into
					cluster_alias (alias, cluster_name, last_registered)
				select
						cluster_name as alias, cluster_name, now()
				  from
				    database_instance
				  group by
				    cluster_name
					having
						sum(suggested_cluster_alias = '') = count(*)

            - your orchestrator.conf.json config file/contents,orchestrator 3.2.6 and 3.2.5 config file is same:

  "Debug": false,
  "EnableSyslog": true,
  "ListenAddress": ":3000",
  "MySQLTopologyUser": "",
  "MySQLTopologyPassword": "*****",
  "MySQLTopologyCredentialsConfigFile": "",
  "MySQLTopologySSLPrivateKeyFile": "",
  "MySQLTopologySSLCertFile": "",
  "MySQLTopologySSLCAFile": "",
  "MySQLTopologySSLSkipVerify": true,
  "MySQLTopologyUseMutualTLS": false,
  "MySQLTopologyReadTimeoutSeconds": 2,
  "MySQLDiscoveryReadTimeoutSeconds": 2,
  "MySQLOrchestratorHost": "127.0.0.1",
  "MySQLOrchestratorPort": 3306,
  "MySQLOrchestratorDatabase": "orchestrator",
  "MySQLOrchestratorUser": "******",
  "MySQLOrchestratorPassword": "******",
  "MySQLConnectTimeoutSeconds": 1,
  "DefaultInstancePort": 3306,
  "DiscoverByShowSlaveHosts": true,

 Thank you!

**Comment by MisKatherine** [comment]
The problem has been solved,thanks

**Comment by fanxinlei** [comment]
I encountered the same problem, how did you solve it? 
thank you very much
