### ISSUE TITLE
raft: Failed to AppendEntries to XXX:10008: read tcp XXX:1309->XXX:10008: i/o timeout

### ISSUE THREAD

**Issue by songshiqiang** [openark/orchestrator#1420]
I have 3 machines with orchestrator installed, and recently encountered the following log errors frequently. As long as these errors occur, orchestrator will not be able to complete the MySQL master-slave switch. 

I upgraded from 3.1.0 to 3.2.6, but the same problem still exists.

```
# tail -F orchestrator.log | grep 10008
2021/11/20 01:31:21 [ERR] raft: Failed to AppendEntries to 10.64.70.204:10008: read tcp 10.35.38.10:1309->10.64.70.204:10008: i/o timeout
2021/11/20 01:31:21 [ERR] raft: Failed to AppendEntries to 10.11.222.7:10008: read tcp 10.35.38.10:63065->10.11.222.7:10008: i/o timeout
2021-11-20 01:31:23 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021-11-20 01:31:28 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021-11-20 01:31:33 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021-11-20 01:31:38 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021/11/20 01:31:42 [ERR] raft: Failed to AppendEntries to 10.64.70.204:10008: read tcp 10.35.38.10:10113->10.64.70.204:10008: i/o timeout
2021/11/20 01:31:42 [ERR] raft: Failed to AppendEntries to 10.11.222.7:10008: read tcp 10.35.38.10:7888->10.11.222.7:10008: i/o timeout
2021-11-20 01:31:43 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021-11-20 01:31:48 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021-11-20 01:31:53 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021-11-20 01:31:58 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021/11/20 01:32:02 [ERR] raft: Failed to AppendEntries to 10.64.70.204:10008: read tcp 10.35.38.10:19291->10.64.70.204:10008: i/o timeout
2021/11/20 01:32:02 [ERR] raft: Failed to AppendEntries to 10.11.222.7:10008: read tcp 10.35.38.10:17078->10.11.222.7:10008: i/o timeout
2021-11-20 01:32:03 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021-11-20 01:32:08 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021-11-20 01:32:13 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021-11-20 01:32:18 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021/11/20 01:32:22 [ERR] raft: Failed to AppendEntries to 10.64.70.204:10008: read tcp 10.35.38.10:27257->10.64.70.204:10008: i/o timeout
2021/11/20 01:32:22 [ERR] raft: Failed to AppendEntries to 10.11.222.7:10008: read tcp 10.35.38.10:25036->10.11.222.7:10008: i/o timeout
2021-11-20 01:32:23 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021-11-20 01:32:28 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021-11-20 01:32:33 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021-11-20 01:32:38 DEBUG raft leader is 10.35.38.10:10008 (this host); state: Leader
2021/11/20 01:32:42 [ERR] raft: Failed to AppendEntries to 10.64.70.204:10008: read tcp 10.35.38.10:35683->10.64.70.204:10008: i/o timeout
2021/11/20 01:32:42 [ERR] raft: Failed to AppendEntries to 10.11.222.7:10008: read tcp 10.35.38.10:33464->10.11.222.7:10008: i/o timeout
```

 I don't know what causes these errors. Stop all orchestrator processes, then delete the raftdata directory, and then restart the orchestrator process to delay the occurrence of the above error. Sometimes it reappears not long after, sometimes it doesn’t reappear for a long time.

Does anyone know what the problem is?

**Comment by songshiqiang** [comment]
This is my orchestrator.conf.json

{
  "Debug": true,
  "EnableSyslog": false,
  "ListenAddress": ":3000",
  "MySQLTopologyUser": "",
  "MySQLTopologyPassword": "",
  "MySQLTopologyCredentialsConfigFile": "",
  "MySQLTopologySSLPrivateKeyFile": "",
  "MySQLTopologySSLCertFile": "",
  "MySQLTopologySSLCAFile": "",
  "MySQLTopologySSLSkipVerify": true,
  "MySQLTopologyUseMutualTLS": false,
  "MySQLOrchestratorHost": "10.11.222.7",
  "MySQLOrchestratorPort": 3306,
  "MySQLOrchestratorDatabase": "orchestrator",
  "MySQLOrchestratorUser": "",
  "MySQLOrchestratorPassword": "",
  "MySQLOrchestratorCredentialsConfigFile": "",
  "MySQLOrchestratorSSLPrivateKeyFile": "",
  "MySQLOrchestratorSSLCertFile": "",
  "MySQLOrchestratorSSLCAFile": "",
  "MySQLOrchestratorSSLSkipVerify": true,
  "MySQLOrchestratorUseMutualTLS": false,
  "MySQLConnectTimeoutSeconds": 1,
  "DefaultInstancePort": 3306,
  "DiscoverByShowSlaveHosts": true,
  "InstancePollSeconds": 5,
  "DiscoveryIgnoreReplicaHostnameFilters": [
    ""
  ],
  "UnseenInstanceForgetHours": 240,
  "SnapshotTopologiesIntervalHours": 0,
  "InstanceBulkOperationsWaitTimeoutSeconds": 10,
  "HostnameResolveMethod": "none",
  "MySQLHostnameResolveMethod": "",
  "SkipBinlogServerUnresolveCheck": true,
  "ExpiryHostnameResolvesMinutes": 60,
  "RejectHostnameResolvePattern": "",
  "ReasonableReplicationLagSeconds": 10,
  "ProblemIgnoreHostnameFilters": [],
  "VerifyReplicationFilters": false,
  "ReasonableMaintenanceReplicationLagSeconds": 20,
  "CandidateInstanceExpireMinutes": 60,
  "AuditLogFile": "",
  "AuditToSyslog": false,
  "RemoveTextFromHostnameDisplay": "",
  "ReadOnly": false,
  "AuthenticationMethod": "multi",
  "HTTPAuthUser": "",
  "HTTPAuthPassword": "",
  "AuthUserHeader": "",
  "PowerAuthUsers": [
    "*"
  ],
  "ClusterNameToAlias": {
  },
  "SlaveLagQuery": "",
  "DetectClusterAliasQuery": "",
  "DetectClusterDomainQuery": "",
  "DetectInstanceAliasQuery": "",
  "DetectPromotionRuleQuery": "",
  "DataCenterPattern": "",
  "PhysicalEnvironmentPattern": "",
  "PromotionIgnoreHostnameFilters": [],
  "DetectSemiSyncEnforcedQuery": "",
  "ServeAgentsHttp": false,
  "AgentsServerPort": ":3001",
  "AgentsUseSSL": false,
  "AgentsUseMutualTLS": false,
  "AgentSSLSkipVerify": false,
  "AgentSSLPrivateKeyFile": "",
  "AgentSSLCertFile": "",
  "AgentSSLCAFile": "",
  "AgentSSLValidOUs": [],
  "UseSSL": false,
  "UseMutualTLS": false,
  "SSLSkipVerify": false,
  "SSLPrivateKeyFile": "",
  "SSLCertFile": "",
  "SSLCAFile": "",
  "SSLValidOUs": [],
  "URLPrefix": "",
  "StatusEndpoint": "/api/status",
  "StatusSimpleHealth": true,
  "StatusOUVerify": false,
  "AgentPollMinutes": 60,
  "UnseenAgentForgetHours": 6,
  "StaleSeedFailMinutes": 60,
  "SeedAcceptableBytesDiff": 8192,
  "AutoPseudoGTID": true,
  "PseudoGTIDPattern": "",
  "PseudoGTIDPatternIsFixedSubstring": false,
  "PseudoGTIDMonotonicHint": "asc:",
  "DetectPseudoGTIDQuery": "",
  "BinlogEventsChunkSize": 10000,
  "SkipBinlogEventsContaining": [],
  "ReduceReplicationAnalysisCount": true,
  "FailureDetectionPeriodBlockMinutes": 60,
  "RecoveryPeriodBlockSeconds": 3600,
  "RecoveryIgnoreHostnameFilters": [],
  "RecoverMasterClusterFilters":["*"],
  "RecoverIntermediateMasterClusterFilters": ["*"],
  "OnFailureDetectionProcesses": [
     "/usr/local/orchestrator/failureDetection.sh  {failureCluster} {failureType}  {countSlaves}"
  ],
  "PreFailoverProcesses": [
     "/usr/local/orchestrator/preFailover.sh   {failedHost} {failedPort}"
  ],
  "PostFailoverProcesses": [
     "/usr/local/orchestrator/postFailover.sh {failedHost} {failedPort} {successorHost} {successorPort}"
  ],
  "PostUnsuccessfulFailoverProcesses": [
     "/usr/local/orchestrator/postUnsuccessfulFailover.sh {failedHost} {failedPort} {failureType} {failureCluster}"
  ],
  "PostMasterFailoverProcesses": [
  ],
  "PostIntermediateMasterFailoverProcesses": [
  ],
  "CoMasterRecoveryMustPromoteOtherCoMaster": true,
  "DetachLostSlavesAfterMasterFailover": true,
  "ApplyMySQLPromotionAfterMasterFailover": true,
  "PreventCrossDataCenterMasterFailover": false,
  "PreventCrossRegionMasterFailover": false,
  "MasterFailoverDetachSlaveMasterHost": false,
  "MasterFailoverLostInstancesDowntimeMinutes": 0,
  "DelayMasterPromotionIfSQLThreadNotUpToDate": true,
  "PostponeSlaveRecoveryOnLagMinutes": 0,
  "OSCIgnoreHostnameFilters": [],
  "GraphiteAddr": "",
  "GraphitePath": "",
  "GraphiteConvertHostnameDotsToUnderscores": true,
  
  
  "RaftEnabled": true,
  "RaftBind": "10.11.222.7",
  "RaftDataDir": "/usr/local/orchestrator/raftdata",
  "DefaultRaftPort": 10008,
  "RaftNodes": [
     "10.35.38.10",
     "10.11.222.7",
     "10.64.70.204"
    ]  
}

**Comment by leiless** [comment]
Hi, @songshiqiang, I met the same problem. I deployed three orchestrator nodes in a container environment. (podman)
Have you solved this problem yet?
