### ISSUE TITLE
feature request: timestamps in recovery.log

### ISSUE THREAD

**Issue by eslocombe** [openark/orchestrator#147]
In troubleshooting, it would be helpful if timestamps were included somewhere in recovery.log.

from the orchestrator log:
`2017-04-06 08:50:45 INFO CommandRun(echo 'Will recover from DeadMaster on dev-mysql101:3306' >> /tmp/recovery.log,[])`

but then, I don't have timestamps in the recovery.log. It looks like it is just the most recent recovery - but I am not fully sure. :) Simple solution would be to just prepend the dump to the recovery.log with a commented timestamp.

**Comment by shlomi-noach** [comment]
`2017-04-06 08:50:45 INFO CommandRun(echo 'Will recover from DeadMaster on dev-mysql101:3306' >> /tmp/recovery.log,[]` is just a usage example presented in https://github.com/github/orchestrator/blob/5642f04f7d5c862f93a620c1b65bc120a996a1e8/conf/orchestrator-sample.conf.json#L122-L124. 

You will most certainly want to re-implement it, invoke your more elaborate scripts, etc. We, for example, send a notification to chat just as recovery is about to start.

Noteworthy is a recently merged PR (not yet released): https://github.com/github/orchestrator/pull/131, which writes down recovery steps to a well structured table (`topology_recovery_steps`). This allows for well audited migrations without `grep`ping the error log. There is ongoing work on this.

**Comment by eslocombe** [comment]
ok thanks! we will get right on that :) closing this then.
