### ISSUE TITLE
Suggestions for improvements in auditing of the recovery process

### ISSUE THREAD

**Issue by sjmudd** [openark/orchestrator#148]
Work has been started to audit the recovery process for later analysis. Studying the logs on a busy orchestrator server can be really hard.  It's also good to keep this information to later explain what happened and why.

After looking at v2.1.1 I've triggered a test failure of an intermediate master and notice the following.  Original logging shows:

```
2017-04-10 13:54:30     searching for the best candidate sibling of dead intermediate master dead-intermediate-master:3306
2017-04-10 13:54:30     found replacement-intermediate-master:3306 as a replacement for dead-intermediate-master:3306 [any sibling]
2017-04-10 13:54:30     - RecoverDeadIntermediateMaster: will next attempt regrouping of replicas
2017-04-10 13:54:30     - RecoverDeadIntermediateMaster: will next attempt relocating to another DC server
2017-04-10 13:54:30     - RecoverDeadIntermediateMaster: will attempt a candidate intermediate master: replacement-intermediate-master:3306
```

* It would be good to record the "error message trying to connect to the intermediate master".  Several problems may occur so knowing which one is triggering the problem would be good.
  * In my case the error I saw was: `2017-04-09 13:03:52 WARNING Discovery failed for host: dead-intermediate-master:3306 in 1.269s (Backend: 0.267s, Instance: 1.002s), error: ReadTopologyInstanceBufferable failed: dial tcp 1.2.3.4:3306: i/o timeout`
  * So perhaps something like `dead-intermediate-master had error: dial tcp 1.2.3.4:3306: i/o timeout` would be useful?
* Prior to "searching for the best candidate sibling of dead intermediate master" it would be good to indicate the list of slaves that are affected by the IM failure.
* there is a step: "will next attempt regrouping of replicas". Unless I'm mistaken this arranges the "affected slaves", promoting one of them as a master and putting the others underneath.  If that's the case it would seem helpful to indicate which slave was promoted and at least how many were successfully moved under that "temporary master"
* again in this output if there are errors indicating the error message seems helpful.

The goal in my case here is to have a checklist of the steps taken, to be able to see if everything went ok, to know why certain actions were taken, and to see a high level overview of failures with enough information to understand their cause.

I am very happy to see the work that has been done so far.  This helps a lot.

**Comment by sjmudd** [comment]
Looking at the error message above the extra logging of `ReadTopologyInstanceBufferable failed:` is probably not actually useful and just needs to be removed. Some extra debugging was added by me to identify where failures occured but it looks to me as if this extra "bit" of information is not actually helpful.

**Comment by sjmudd** [comment]
After seeing some updates I did a new test of a failed intermediate master. This leaves the correct result as shown.

![screen shot 2017-04-20 at 12 32 07](https://cloud.githubusercontent.com/assets/116250/25227335/66cc4a6a-25c8-11e7-9c34-8019d79ead79.png)

The auditing of this event shows:

![screen shot 2017-04-20 at 12 33 08](https://cloud.githubusercontent.com/assets/116250/25228099/51d90578-25cb-11e7-8979-74b8dca33bb8.png)

My feeling here is the following information is missing:
* The number and names of the slaves under the failed intermediate master
* The content or output of the different hooks. That is the name of the scripts called etc and any output they generate together with the scripts' exit status. (this confirms if they ran successfully or not)
* the process of relocating the "blue slave" under the "orange slave" is not clear here.  From the view point of a DBA or maybe sysadmin it would be good to make this clearer.

Having said that the work done so far in adding this detail, visible from the GUI is something which DBAs, sysadmins and auditors will love as once complete it should help clarify when things fail exactly what happened.

**Comment by shlomi-noach** [comment]
Thank you for all the above suggestions!
