### ISSUE TITLE
Home.md seems to consist of links to pages that have been renamed or removed. 

### ISSUE THREAD

**Issue by fipar** [openark/orchestrator#170]
Hello, 

It seems that the links found on: 
https://github.com/github/orchestrator/blob/master/docs/Home.md
are to pages that have been renamed or remove, as I get a 404 for all of them. 

It seems that Home.md itself may just be outdated and can possibly be removed, as toc.md seems a likely replacement for entry point?

Thanks, 
Fernando.

**Comment by shlomi-noach** [comment]
Thank you -- indeed `Home.md` should be removed.
