### ISSUE TITLE
No drag&drop changes are allowed in Web GUI

### ISSUE THREAD

**Issue by dandoondrasik** [openark/orchestrator#186]
I have installed PMM which contains also Orchestrator, the setup went quick and easy, my environment was detected without any problem, however I'm not able to do any changes in the setup by doing drag and drop, when I want to change the topology of the replication and make the slaves chained, it says 'Cannot drop here'
![issue](https://cloud.githubusercontent.com/assets/28976734/26487542/3909ca7c-4200-11e7-8616-0073493d18f2.png)

**Comment by jonahberquist** [comment]
You'll need to turn on `log_slave_updates`in your mysql config in order to chain replication. Orchestrator will display an icon like ⏩  if you have it on.

**Comment by dandoondrasik** [comment]
That did the trick, many thanks
