### ISSUE TITLE
ClusterAlias Set by Web Interface Won't Persist

### ISSUE THREAD

**Issue by ushuz** [openark/orchestrator#23]
The cluster alias set using web interface won't stay long. After a while, it will be changed back to cluster name, again.

![image](https://cloud.githubusercontent.com/assets/1430856/21536117/5aa8d792-cdb9-11e6-8617-108cb4d205aa.png)

Above screen shot was captured on a read-only instance, and aliases were set in config file, but I'm talking about a read-write instance.

**Comment by shlomi-noach** [comment]
I suspect this is the result of a recent change I made, though I can't seem to find it right now. Will pursue.

**Comment by ushuz** [comment]
@shlomi-noach 

Guess it's related to https://github.com/github/orchestrator/commit/35a810f3a31efadb4c71924f55c8e9995d087707. 

Before, aliases set by web interface were _also_ stored in `clusterAliasMap`, which lives inside memory. `GetClusterByAlias` only looks up aliases inside the map. 

After, `SetClusterAlias` `GetClusterByAlias` directly write to / read from `cluster_alias` table. But `UpdateClusterAliases`, which is [called periodically](https://github.com/github/orchestrator/blob/adc4366f34c7ec84371f931d76e31c44d690a4c0/go/logic/orchestrator.go#L268), also modifies `cluster_alias` table and set `alias` to `cluster_name`.

**Comment by shlomi-noach** [comment]
Nice drill down! A minor correction:

> Before, aliases set by web interface were also stored in clusterAliasMap, which lives inside memory.

the in-memory map is very old by now, and is unrelated to our case. The real change is https://github.com/github/orchestrator/commit/00007bd0#diff-5e8c6e39592986f38c6f2641e88adc0aR120, where I force-populate the `cluster_alias` table by suggested cluster name. In this change I forgot about the case of aliases via web interface.

While I will proceed to fix this, I'd argue that this setup is undesired, and in retrospect I wouldn't develop it this way today. The `DetectClusterAliasQuery` or similar, should be used to populate aliases.

But, working to fix this.

**Comment by shlomi-noach** [comment]
https://github.com/github/orchestrator/issues/28 is in testing and will likely be merged in a few days

**Comment by shlomi-noach** [comment]
fixed by #28. To be released in a few days.
