### ISSUE TITLE
Thoughts related to triggering recovery processes shortly after orchestrator startup

### ISSUE THREAD

**Issue by sjmudd** [openark/orchestrator#244]
Being paranoid I always worry about what could go wrong. As you manage more servers that paranoia level increases ...

This possible issue is to check about what happens if you startup orchestrator after some [considerable] delay.  This may be handled correctly but I'm not sure.

If the topology has changed sufficiently during the time that orchestrator comes up I think there may be a situation where the information it holds is not fully up to date and consequently it may decide there have been failures which need recovery "too quickly" without having full information.

I was wondering if it might be good to ensure we wait at least 3-4 x InstancePollSeconds since process start prior to enabling/triggering automatic recovery so that in theory orchestrator will have had sufficient time to poll all mysql servers at least once and therefore should have a complete and up to date topology map.

Any thoughts on this?

In any case maybe this is a useful FAQ type entry?

**Comment by shlomi-noach** [comment]
This makes perfect sense! Thank you for bringing this into attention.

**Comment by shlomi-noach** [comment]
@sjmudd is this something you want to work on or shall I?

**Comment by sjmudd** [comment]
The thing is I normally disable global recoveries prior to doing maintenance on orchestrator. Then start it up, and wait "about a minute" (I guess this should be 3-4 x InstancePollSeconds) as this should give orchestrator enough time to start up, poll all of the MySQL instances and thus get an up to date view of the current topology, and then enable global recoveries.

We are automating the deployment procedure of our clusters and have various sleeps in there to do just this but really I don't think that this should be something that the user should have to configure. Having orchestrator handle this "possible short moment of instability on startup" feels better and cleaner. However, I was not sure if my understanding of the orchestrator logic was completely correct which is why I was asking to see if you felt this sort of behaviour was appropriate.

Hence the question. Having some similar timeout (multiple of InstancePollSeconds) which is used to prevent initial automatic recovery feels like a sane solution and should be easy to configure.

What do you think?

**Comment by shlomi-noach** [comment]
As I commented above, this makes perfect sense. I'm happy to do that, unless you want to.

**Comment by sjmudd** [comment]
Please feel free. I'm a bit short of time atm.
