### ISSUE TITLE
orchestrator-client error on curl version below 7.32.0

### ISSUE THREAD

**Issue by tapuhi** [openark/orchestrator#257]
I am using CentOS 7 (7.3.1611) with version 3.0 of the cli  and got the following :
`curl: option -m: expected a proper numerical parameter`

in line 161 in the orchestrator-client script you have:

`    leader_check=$(curl -m 0.5 -s -o /dev/null -w "%{http_code}" "${api}/leader-check")`

in the man page it's mentioned (on the web) : 

>  since 7.32.0, this option accepts decimal values, but the actual time-out will decrease in accuracy as the specified timeout increasesin decimal precision.

So unless it's not a prerequisite to have curl version 7.32.0 (by enforcing this in the script for example) the number should be increased to 1.

**Comment by shlomi-noach** [comment]
I edited title + comment `s/orchestrator-cli/orchestrator-client`
