### ISSUE TITLE
cli installation from rpm 

### ISSUE THREAD

**Issue by tapuhi** [openark/orchestrator#259]
I installed the rpm from 
https://github.com/github/orchestrator/releases/download/v3.0.1.pre-release/orchestrator-cli-3.0.1-1.x86_64.rpm 

And it seems that it's only installing the orchestrator binary `/usr/bin/orchestrator` and not the orchestrator-client script.

On Debian I had the same result. Unless I am missing something.

**Comment by tapuhi** [comment]
I think I understood my mistake (stupid one :-) ) . I stalled cli rpm and not the client script . 
But shouldn't that be a good idea to install the client script somehow via rpm or yum repo?

**Comment by shlomi-noach** [comment]
Yeah, it would be a good idea indeed.
