### ISSUE TITLE
Help requested: Simple failover setup

### ISSUE THREAD

**Issue by mapolone** [openark/orchestrator#289]
Hello, this is not actually an issue but I'm somewhat lost into documentation.
Here's the plan: I've a simple master/2 slaves setup (cluster is built with Percona Server 5.7), with GTID and `log-slave-updates` both enabled.

What I'm trying to accomplish is a simple failover, with a DeadMaster (process simply stopped by systemd unit), promote automatically one of the slaves (let's say `slave-01`), and make `slave-02` the new slave of `slave-01`.

Config file is set as follows:
```
{
  "Debug": false,
  "EnableSyslog": false,
  "ListenAddress": ":3000",
  "MySQLTopologyUser": "orchestrator",
  "MySQLTopologyPassword": "<empty>",
  "MySQLTopologySSLSkipVerify": true,
  "MySQLTopologyUseMutualTLS": false,
  "MySQLOrchestratorHost": "192.168.1.29",
  "MySQLOrchestratorPort": 3306,
  "MySQLOrchestratorDatabase": "orchestrator",
  "MySQLOrchestratorCredentialsConfigFile": "/etc/mysql/orchestrator-backend.cnf",
  "MySQLOrchestratorSSLSkipVerify": true,
  "MySQLOrchestratorUseMutualTLS": false,
  "MySQLConnectTimeoutSeconds": 1,
  "DefaultInstancePort": 3306,
  "DiscoverByShowSlaveHosts": true,
  "InstancePollSeconds": 5,
  "UnseenInstanceForgetHours": 240,
  "SnapshotTopologiesIntervalHours": 0,
  "InstanceBulkOperationsWaitTimeoutSeconds": 10,
  "HostnameResolveMethod": "none",
  "MySQLHostnameResolveMethod": "@@report_host",
  "SkipBinlogServerUnresolveCheck": true,
  "ExpiryHostnameResolvesMinutes": 60,
  "RejectHostnameResolvePattern": "",
  "ReasonableReplicationLagSeconds": 10,
  "ProblemIgnoreHostnameFilters": [],
  "VerifyReplicationFilters": false,
  "ReasonableMaintenanceReplicationLagSeconds": 20,
  "CandidateInstanceExpireMinutes": 60,
  "AuditLogFile": "",
  "AuditToSyslog": false,
  "RemoveTextFromHostnameDisplay": ".mydomain.com:3306",
  "ReadOnly": false,
  "AuthenticationMethod": "",
  "HTTPAuthUser": "",
  "HTTPAuthPassword": "",
  "AuthUserHeader": "",
  "PowerAuthUsers": [
    "*"
  ],
  "ClusterNameToAlias": {
    "127.0.0.1": "test"
  },
  "SlaveLagQuery": "",
  "DetectClusterAliasQuery": "SELECT SUBSTRING_INDEX(@@hostname, '.', 1)",
  "DetectClusterDomainQuery": "",
  "DetectInstanceAliasQuery": "",
  "DetectPromotionRuleQuery": "",
  "DataCenterPattern": "[.]([^.]+)[.][^.]+[.]mydomain[.]com",
  "PhysicalEnvironmentPattern": "[.]([^.]+[.][^.]+)[.]mydomain[.]com",
  "PromotionIgnoreHostnameFilters": [],
  "DetectSemiSyncEnforcedQuery": "",
  "ServeAgentsHttp": false,
  "AgentsServerPort": ":3001",
  "AgentsUseSSL": false,
  "AgentsUseMutualTLS": false,
  "AgentSSLSkipVerify": false,
  "AgentSSLPrivateKeyFile": "",
  "AgentSSLCertFile": "",
  "AgentSSLCAFile": "",
  "AgentSSLValidOUs": [],
  "UseSSL": false,
  "UseMutualTLS": false,
  "SSLSkipVerify": false,
  "SSLPrivateKeyFile": "",
  "SSLCertFile": "",
  "SSLCAFile": "",
  "SSLValidOUs": [],
  "URLPrefix": "",
  "StatusEndpoint": "/api/status",
  "StatusSimpleHealth": true,
  "StatusOUVerify": false,
  "AgentPollMinutes": 60,
  "UnseenAgentForgetHours": 6,
  "StaleSeedFailMinutes": 60,
  "SeedAcceptableBytesDiff": 8192,
  "PseudoGTIDPattern": "",
  "PseudoGTIDPatternIsFixedSubstring": false,
  "PseudoGTIDMonotonicHint": "asc:",
  "DetectPseudoGTIDQuery": "",
  "BinlogEventsChunkSize": 10000,
  "SkipBinlogEventsContaining": [],
  "ReduceReplicationAnalysisCount": true,
  "FailureDetectionPeriodBlockMinutes": 60,
  "RecoveryPollSeconds": 10,
  "RecoveryPeriodBlockSeconds": 60,
  "RecoveryIgnoreHostnameFilters": [],
  "RecoverMasterClusterFilters": [
    "master"
  ],
  "RecoverIntermediateMasterClusterFilters": [
    "_intermediate_master_pattern_"
  ],
  "OnFailureDetectionProcesses": [],
  "PreFailoverProcesses": [],
  "PostFailoverProcesses": [],
  "PostUnsuccessfulFailoverProcesses": [],
  "PostMasterFailoverProcesses": [],
  "PostIntermediateMasterFailoverProcesses": [],
  "CoMasterRecoveryMustPromoteOtherCoMaster": true,
  "DetachLostSlavesAfterMasterFailover": false,
  "ApplyMySQLPromotionAfterMasterFailover": false,
  "MasterFailoverDetachSlaveMasterHost": false,
  "MasterFailoverLostInstancesDowntimeMinutes": 0,
  "PostponeSlaveRecoveryOnLagMinutes": 0,
  "OSCIgnoreHostnameFilters": [],
  "GraphiteAddr": "",
  "GraphitePath": "",
  "GraphiteConvertHostnameDotsToUnderscores": true
}
```

So, if I got it correctly, if `DetachLostSlavesAfterMasterFailover` is disabled a manual intervention is requested for promotion. Even if `DetachLostSlavesAfterMasterFailover` is set to `true`, one of the two slaves is detached from the rest of cluster. I'm missing the point of making it automatic, but cannot find it elsewhere. Can you please help?

**Comment by mapolone** [comment]
After hitting my head on the wall a bit harder, I think I've found the solution.

Apparently, Pseudo-GTID is required (mandatory?) for automatic topology recovery of a `DeadMaster`, correct me if I'm wrong. So, [this piece of documentation](https://github.com/github/orchestrator/blob/master/docs/deployment.md#pseudo-gtid) did the job. One of the two slaves previously set as candidate has been promoted as new master, followed by the surviving slave. The original master is out of the game.

So the question is: if GTID is a valid option for topology recovery as stated [here](https://github.com/github/orchestrator/blob/master/docs/topology-recovery.md), there's a particolar reason why it's not working?

Again, maybe I didn't follow the documentation deep enough, but I'd like to know.

**Comment by shlomi-noach** [comment]
Failovers work with either GTID or Pseudo-GTID. If you have GTID enabled you shouldn't need to setup Pseudo-GTID.

> What I'm trying to accomplish is a simple failover, with a DeadMaster (process simply stopped by systemd unit), promote automatically one of the slaves (let's say slave-01), and make slave-02 the new slave of slave-01.

This sounds like a classic setup.

`"RecoverMasterClusterFilters"` is an opt-in list for all clusters where you want `orchestrator` to automatically fail over a dead master. I don't know what `"master"` stands for in your setup, but you would either list a regex matching you cluster's hostnames, or alias of you cluster, or... if you're just testing for now, setup:

```json
"RecoverMasterClusterFilters": [
    "*"
  ],
  "RecoverIntermediateMasterClusterFilters": [
    "*"
  ],
```

which will instruct `orchestrator` to auto-recover all dead masters (and all dead intermediate masters).

Maybe `orchestrator` didn't kick in because `"master"` doesn't match the names of your hostnames -- you'd know.

You haven't really said what the problem is, essentially. What exactly happened? Nothing? Any error messages? Anything in the logs? Can you paste the logs? Is there a failure discovery? (you can browse the web interface and Audit->Failure Detection)? Was a recovery attempted? (you can browse the web interface and Audit->Recovery).
I'm really missing input here.

`DetachLostSlavesAfterMasterFailover` is unrelated to your question. I know this variable may be confusing.

What you _do_ want to set up is `"ApplyMySQLPromotionAfterMasterFailover": true`

This flag will instruct `orchestrator` to `RESET SLAVE ALL` on promoted master and to make it writable. Why is this not the default, you may ask? Browse the Issues to find multiple explanations and incidents ; many users expect to control this behavior outside `orcehstartor`.

**Comment by shlomi-noach** [comment]
@mapolone if the above answers your problem, please consider closing this issue.

**Comment by mapolone** [comment]
Sorry for the late reply, this issue can be closed.

**Comment by SQLadmin** [comment]
I have a similar issue now.

1 Master 2 slaves with native GTID enabled. 

config:
```
"RecoverMasterClusterFilters": [
    "*"
  ],
 "RecoverIntermediateMasterClusterFilters": [
    "*"
  ],
.......
 "CoMasterRecoveryMustPromoteOtherCoMaster": true,
  "DetachLostSlavesAfterMasterFailover": true,
  "ApplyMySQLPromotionAfterMasterFailover": true,
  "MasterFailoverDetachSlaveMasterHost": false,
  "MasterFailoverLostInstancesDowntimeMinutes": 0,
  "PostponeSlaveRecoveryOnLagMinutes": 0,
```
But automatic failover didn't happen. Still trying to figure out.

**Comment by shlomi-noach** [comment]
@SqlAdmin please open a new issue
