### ISSUE TITLE
Topology is not showing over UI in laster version of orchestrator 2.1.5 

### ISSUE THREAD

**Issue by vinayjaiswal1990** [openark/orchestrator#294]
Hi , 

Upgraded latest version of orchestrator orchestrator-2.1.5-1.x86_64 but topology is not showing over UI .Nothing getting any error in the orchestrator log . 

Could you please suggest me to resolve this issue . 

Web page log : Uncaught ReferenceError: isCompactDisplay is not defined
    at Object.success (cluster.js:1555)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:5)
    at XMLHttpRequest.b (jquery.min.js:5)
(anonymous) @ cluster.js:1555
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
x @ jquery.min.js:5
b @ jquery.min.js:5
XMLHttpRequest.send (async)
send @ jquery.min.js:5
ajax @ jquery.min.js:5
m.(anonymous function) @ jquery.min.js:5
getData @ cluster.js:1679
domReady @ cluster.js:1545
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2
cluster.js:1494 Uncaught ReferenceError: isCompactDisplay is not defined
    at renderCluster (cluster.js:1494)
    at Object.success (cluster.js:1541)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:5)
    at XMLHttpRequest.b (jquery.min.js:5)
![screen shot 2017-09-11 at 10 05 03 pm](https://user-images.githubusercontent.com/30997861/30286134-1f6db608-973e-11e7-9d31-711774c6af8e.png)

Thank you!

**Comment by shlomi-noach** [comment]
The function `isCompactDisplay()` moved from `cluster.js` to `orchestrator.js` as per https://github.com/github/orchestrator/commit/60621513

I'd suggest refreshing your browser cache ; Shift+refresh or Cmd+refresh should do the trick.

**Comment by shlomi-noach** [comment]
Closing as no response given and as I believe this is a non-bug.
