### ISSUE TITLE
Delete API?

### ISSUE THREAD

**Issue by bbeaudreault** [openark/orchestrator#301]
We run in kubernetes and have automation to be able to do rolling restart of our few hundred mysql servers there. We also have to use IP address for routing, so we've disabled name resolving. So, when we do the rolling restart we inevitably end up with a bunch of stale nodes left over.

Would it be possible to create a Delete API for deleting nodes that we know will never come back?

**Comment by shlomi-noach** [comment]
please use:

```
curl http://my.orchestrator.service/api/forget/hostname/port
```

or

```
orchestrator-client -c forget -i hostname:port
```

**Comment by bbeaudreault** [comment]
Thanks! Did not see that API.

**Comment by bbeaudreault** [comment]
@shlomi-noach is there an API to get the current raft leader?  We realized this can only be called against the leader. But not sure how to know which is at a given time, from code.

**Comment by bbeaudreault** [comment]
Nevermind, found the doc: https://github.com/github/orchestrator/blob/master/docs/raft.md. Would be nice if there were a way to hit any node and find out who the leader is, as opposed to check all of them.

**Comment by bbeaudreault** [comment]
Ok, digging through code we found `/api/raft-leader` API.
