### ISSUE TITLE
Flip Dead Master to Slave

### ISSUE THREAD

**Issue by shahbour** [openark/orchestrator#311]
This is more a question than issue . 

I am testing orchestrator , so i created master (mysql01) --> slave (mysql02) and discovered , then i shut down the master (mysql01) through systemd and slave (mysql02) was promoted to Master as expected . 

Next step for me was to put back old master (mysql01) back as slave for mysql02 . I could not figure out how to do that using orchestrator .

The only way i found was clear every thing and start from clean db . I am asking this because my database is around 1 TB and starting over from clean db will take too much time.

Thanks

**Comment by shlomi-noach** [comment]
Discussed in https://github.com/github/orchestrator/issues/190#issuecomment-306023357

> You can't expect it to be come a replica because it potentially (likely, in many environments) have applied more transactions that its replicas. That is, it is more up to date than the promoted replica. As such, it will likely break on replication.

If the master and replica happen to be in complete sync when you shut down the master, then use GTID or Pseudo-GTID to position the old master (now replica) under the new master.

**Comment by shlomi-noach** [comment]
If this answers your question, please consider closing the issue. Thanks!

**Comment by shahbour** [comment]
Sorry i did not get back , yes tested it using GTID and worked perfectly .
