### ISSUE TITLE
Cannot set Raft Advertise parameter

### ISSUE THREAD

**Issue by samiahlroos** [openark/orchestrator#312]
We have Orchestrator nodes which need to go through NAT gateways when talking to each other using Raft.

To make this work I need to set Raft's `advertise` address correctly (when calling `raft.NewTCPTransport`), to the NATed address. Unfortunately, Orchestrator currently doesn't let me set that.

I have added RaftAdvertise as a configurable parameter, which does indeed solve my problem.

How likely would it be to get support for this in Orchestrator?

**Comment by shlomi-noach** [comment]
@samiahlroos thank you, if I understand correctly, you wish to add a `RaftAdvertise` configuration variable to `orchestrator`, that will be used to configure raft itself -- without modifying the `hashicorp/raft` code under `vendor/` ?

If so, I'm happy for a PR and it is very likely to be merged.

**Comment by samiahlroos** [comment]
Exactly; Raft already knows about advertise addresses, I only need to be able to set it in orchestrator and pass it on to Raft.

**Comment by samiahlroos** [comment]
Thanks a lot for merging that!
