### ISSUE TITLE
Master and slave are running on different ports

### ISSUE THREAD

**Issue by AshokJivani** [openark/orchestrator#317]
Hello,

I am getting following error on orchestrator logs.
```
ERROR ReadTopologyInstance(host:XXXX) show variables like 'maxscale%': dial tcp host:XXXX: getsockopt: connection refused
```

Digging into more, I have noticed that Orchestrator only throws above error for the slaves which are running on different ports then their respective masters. `DiscoverByShowSlaveHosts` is disabled in Orchestrator configs that means Orchestrator would use `SHOW PROCESSLIST` to find out slave(s) for given master.

Per below code, it looks like slave is picking master's port. 

https://github.com/github/orchestrator/blob/master/go/inst/instance_dao.go#L575

Any help would be appreciated.

**Comment by shlomi-noach** [comment]
There is no way for `orchestrator` to infer the replica's port via `show processlist`. Therefore, you would need to:

- configure `"DiscoverByShowSlaveHosts": true,"`
- make sure `report_host` and `report_port` are correctly set in all of your servers.
- unfortunately those variables are not dynamic and require a server restart.

**Comment by AshokJivani** [comment]
Thanks for the prompt response. I was thinking that with `SHOW PROCESSLIST` you wouldn't be able to find slave's port but just wanted to get your thoughts on that. 

I guess this is something to be aware of while using different ports for master and slave(s)

Thanks,
Ashok
