### ISSUE TITLE
missing replication username/password error when changing from master-slave to master-comaster

### ISSUE THREAD

**Issue by igroene** [openark/orchestrator#323]
I have a simple topology master -> slave configured, and when I drag and drop the master on top of the slave, orchestrator asks if I want to make master-master replication as expected. Problem is the master is not properly configured afterwards:
```     
Last_IO_Error: Fatal error: Invalid (empty) username when attempting to connect to the master server. Connection attempt terminated.
```
is there any way to feed the user/pass to orchestrator?

**Comment by shlomi-noach** [comment]
@igroene there is one way: configure your MySQL with:

```
master_info_repository = 'TABLE'
```

And grant `orchestrator` read access on `mysql.slave_master_info`. See https://github.com/github/orchestrator/blob/master/docs/install.md#grant-access-to-orchestrator-on-all-your-mysql-servers

**Comment by igroene** [comment]
Thanks Shlomi, I had missed that. What are your thoughts on adding new configuration variables for a “default” replication user / pass? That would enanle support for < 5.6 and installations that still don’t use the master info table.

**Comment by shlomi-noach** [comment]
This has come up a few times before. I'm not sure I like `orchestrator` having replication passwords; this is largely a security debate. I'm open to hear more opinions.

**Comment by igroene** [comment]
One could argue that granting access to slave_master_info is a similar issue from a security point of view. Another possibility could be orchestrator prompting for the user/password when it is needed. I think the only scenario for that would be setting up master-master right?

**Comment by cezmunsta** [comment]
@shlomi-noach perhaps allowing it to be read from another table in the DB so that it is not stored in `orchestrator` and can still be read (and more importantly is usable without a restart to change to `TABLE`). @igroene you grant SELECT access to the, or not :smile:

**Comment by shlomi-noach** [comment]
@cezmunsta what is your reasoning to _not_ using `master_info_repository = 'TABLE'`?

**Comment by cezmunsta** [comment]
@shlomi-noach so, until 8.0 the default is `FILE`, plus for anyone still running 5.5 there is only `FILE`. In addition, for those running on a version that supports `TABLE`, but aren't using it then you must restart MySQL.. if `orchestrator` supported the read of credentials from a specified table (avoiding writing to MySQL system tables), perhaps via a query to allow for encryption of the credentials, then it would mean that `orchestrator` would support a transition from `FILE` to `TABLE` too. Also, some people prefer to avoid error [1760](https://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html#error_er_insecure_change_master).

I guess that the ideal solution would be to additionally support Vault, as you could use the libraries

**Comment by shlomi-noach** [comment]
Gotcha on defaults and on 5.5.

> for those running on a version that supports TABLE, but aren't using it then you must restart MySQL.

This is actually dynamic and I've always transitioned dynamically.

> I guess that the ideal solution would be to additionally support Vault, as you could use the libraries

Agreed. In the future.

configuration vs. table: configuration-based credentials imply single credentials for all clusters. Table-based credentials allow per-cluster credentials, but then also you'd need to populate tables on all clusters. That is also painful.

**Comment by cezmunsta** [comment]
> this is actually dynamic and I've always transitioned dynamically.

@shlomi-noach you are of course correct :+1: .. my ageing memory failed recalling that as one of the RO ones. Maybe because I've tended to have been applying `relay_log_recovery` at the same. 

> Table-based credentials allow per-cluster credentials, but then also you'd need to populate tables on all clusters. That is also painful.

I think that the benefit of per-cluster configuration would be worth it; this would be no different to the cluster helper queries, etc - automation can always do it for you :wink:

**Comment by shlomi-noach** [comment]
> this would be no different to the cluster helper queries

True. OK, let me consider the options. I'm not strongly objecting anymore, and implementation is quick enough.

**Comment by shlomi-noach** [comment]
@igroene @cezmunsta please consider https://github.com/github/orchestrator/pull/582

**Comment by shlomi-noach** [comment]
@igroene @cezmunsta please consider https://github.com/github/orchestrator/pull/603
