### ISSUE TITLE
Killing Existing Queries (Persisted Connections) During Manual Failover

### ISSUE THREAD

**Issue by emusickid** [openark/orchestrator#328]
> Hey there,
I have a need to kill off persisted connections after a failover (manual not an auto-recovery) and I see the API has a Kill Endpoint `kill-query/:host/:port/:process`, but I am not finding an endpoint to fetch a list from the `information_schema.processlist`. Am I just missing this, or is this feature just available yet?

Thanks!!

**Comment by shlomi-noach** [comment]
The `kill-query` endpoint is not something I'm pursuing. What I'd suggest for you to do is to put those `kill`s in your custom hooks (`PostMasterFailoverProcesses`).

**Comment by emusickid** [comment]
Gotcha - thanks for the info @shlomi-noach!!
