### ISSUE TITLE
Aggregate overview mouseover could also show delays

### ISSUE THREAD

**Issue by sjmudd** [openark/orchestrator#33]
A URL such as: https://orchestrator.mydomain.com/web/cluster/somecluster:3306?compact=true provides a good summary. If I'm in compact mode I don't see all the hosts but a bubble with the number of hosts replicating underneath a master or intermediate master.

If you mouse over that bubble then you get a list of hostnames, and mysql versions.

I'd like to also see the replication delay seen by orchestrator as that would allow me to have a quick overview of all the delays and saves me opening up a compact list.

This is convenient if you have several slaves replicating from a master.

**Comment by shlomi-noach** [comment]
Thank you for this suggestion -- will work on this

**Comment by shlomi-noach** [comment]
Fixed by https://github.com/github/orchestrator/pull/52
