### ISSUE TITLE
Trying to understand the delay between relocating replicas and graceful master takeover

### ISSUE THREAD

**Issue by zmoazeni** [openark/orchestrator#333]
Hi there! We're evaluating orchestrator and whether it would be a good fit for our team.

Right now there's some confusion on how to trigger a controlled failover event. For example if we need to restart the writer/master server. So this wouldn't be an unexpected failure event.

Right now we trigger that via:

```
orchestrator -c relocate-replicas -i $(orchestrator -c which-cluster-master) -d $(orchestrator -c get-best-master-replacement)
orchestrator -c graceful-master-takeover
```

My main question is that we can't run the second command `graceful-master-takeover` immediately. We have to wait for over a minute otherwise orchestrator fails with:

> FATAL GracefulMasterTakeover: master 10.0.0.31:3306 should only have one replica (making the takeover safe and simple), but has 3. Aborting

What is the reason for this delay? If it's connected to a poll, is there a specific config we can configure to reduce the time or better yet, a command that we could run to trigger an update so that we don't have to wait for the next cycle in the poll?

**Comment by shlomi-noach** [comment]
@zmoazeni perfect timing. This was [just merged](https://github.com/github/orchestrator/pull/330) a couple days ago. Details inside.

**Comment by zmoazeni** [comment]
Ahhh that makes a lot of sense now. Thanks!!

**Comment by shlomi-noach** [comment]
I hope to make a release next week.

**Comment by shlomi-noach** [comment]
fixed and released in https://github.com/github/orchestrator/releases/tag/v3.0.3
