### ISSUE TITLE
Can't find the Extra item in menu

### ISSUE THREAD

**Issue by ahdong2007** [openark/orchestrator#334]
> I can't find the Extra item in the menu after I have the orchestrator run. Did I miss any steps to configure the orchestrator? Thanks in advance!

**Comment by shlomi-noach** [comment]
Stuff that used to be under "Extra" are now under "Audit".
"Discover" is now under "Cluster".

**Comment by shlomi-noach** [comment]
If everything is fine, please consider closing this issue.
