### ISSUE TITLE
golang version requirement

### ISSUE THREAD

**Issue by ofbeaton** [openark/orchestrator#336]
centos 6 had golang 1.5 from epel, centos 7 has core golang 1.8 and now golang 1.9 is out.

We run orchestrator and I tried to find a place in the docs where it mentions what version orchestrator works with, minimum and maximum. Could this please be added to the docs, possibly in https://github.com/github/orchestrator/blob/master/docs/requirements.md

**Comment by shlomi-noach** [comment]
Thank you -- will update the docs. It's just that by nature of things the docs always tend to be behind. FYI right now we're building via either `go1.7` or `go1.8`. Not yet `go1.9`.

**Comment by shlomi-noach** [comment]
Wait. Did you mean [this documentation page which indicates the required golang version](https://github.com/github/orchestrator/blob/11ff2b07ebfff3aa43cb7c87b8f943bbb24c14c4/docs/developers.md#requirements)? 😆

**Comment by shlomi-noach** [comment]
@ofbeaton https://github.com/github/orchestrator/blob/master/docs/requirements.md is not the right place to put it since normal users don't need to have `go` in the first place. 

Only developers who are interested in contributing code to the project or otherwise hacking it for their own benefit do.

**Comment by ofbeaton** [comment]
Rather embarrassingly, and not being familiar with go at all, I had assumed that since the requirements page mentioned it, it was required on the box. `standalone` really should have clued me in. My deployments are now much easier, thank you!

Many apologies for wasting your time.

**Comment by sjmudd** [comment]
Shlomi, fwiw I'm building with golang 1.9 and that works fine. Not surprising as Go's backwards compatibility promises are pretty strict.

**Comment by shlomi-noach** [comment]
@sjmudd thanks for the info!
I'm wondering why https://storage.googleapis.com/golang/ doesn't list `go1.9` yet.

**Comment by sjmudd** [comment]
Quoting you from earlier "It's just that by nature of things the docs always tend to be behind" ??? :-)
It could be there's been no change in apis. ?
