### ISSUE TITLE
Support for adding dynamic recovery filters

### ISSUE THREAD

**Issue by hmcgonig** [openark/orchestrator#348]
I have a need to ignore certain instances (mysql/vitess in a kubernetes pod) when doing automated recovery with orchestrator. I could only find hostname filters (RecoveryIgnoreHostnameFilters) and while my hostnames do include a pattern I could filter on, setting `MySQLHostnameResolveMethod: @@hostname` conflicts with my IP only setup.

It would be awesome if I could setup something to run a filter query on the failover target to validate its eligibility. For example, if I could `select @@hostname` and filter hosts that match a certain regex, would be perfect.

Alternatively allow setting a "display name" field via various methods (like @@hostname etc), and then have a matching `RecoveryIgnoreDisplayNameFilters` list.

It's also entirely possible I missed a config prop and this can easily be done in another way. Any ideas? Thanks!

**Comment by shlomi-noach** [comment]
@hmcgonig I believe you wish to look at something else: promotion-rules.

If I understand correctly, it's not that you wish to ignore those servers in general, you just never want them to be promoted. Is that correct?

Please see https://github.com/github/orchestrator/blob/master/docs/deployment.md#adding-promotion-rules

For each server, you will declare that its promotion rule is `must_not`. This happens dynamically. E.g. we have backup servers or testing servers in production we never want to promote, so we set up this cron entry in those hosts:

```
orchestrator-client -c register-candidate -i $(hostname) --promotion-rule must_not
```

**Comment by shlomi-noach** [comment]
I should add a promotion rule expires after an hour. You will want to continuously execute that in cron, as in:

```
*/5 * * * * /usr/bin/orchestrator-client -c register-candidate -i $(hostname) --promotion-rule must_not
```

**Comment by hmcgonig** [comment]
This is perfect, exactly what I was looking for. Thank you so much.

**Comment by hmcgonig** [comment]
So, I just tried this and noticed that using `DetectPromotionRuleQuery` overrides any promotion rules set via the API. I ended up solving my problem by modifying the query.

I run with vitess, so the default set of vitess config had `DetectPromotionRuleQuery` set to:
`SELECT value FROM _vt.local_metadata WHERE name='PromotionRule'`
which I changed to
`SELECT CASE WHEN @@hostname REGEXP '.*(-backup)$' THEN 'must_not' ELSE value END FROM _vt.local_metadata WHERE name='PromotionRule'`

this way anything with a `.*-backup` hostname is automatically set to `PromotionRule: must_not`

**Comment by shlomi-noach** [comment]
You are correct, and `DetectPromotionRuleQuery` overrides `api`. I should have connected the dots when you said you were using vitess. 

Your solution is :+1:
