### ISSUE TITLE
Crash seen in orchestrator when relocating GTID slaves

### ISSUE THREAD

**Issue by sjmudd** [openark/orchestrator#353]
I had a crash on 3.0.1.1 (this is a minor variation of your code but there are no changes related to GTID in my own code) at this point:
```                // Parallelize repoints
                go func() {
                        defer func() { barrier <- &replica.Key }()         <<====== line 611
```
Logging shows:
```panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x89b5a5]

goroutine 71904174 [running]:
github.com/github/orchestrator/go/inst.moveReplicasViaGTID.func1.1(0xc436362960, 0xc4201b7760)
        /builddir/build/BUILD/orchestrator-3.0.1.1/GO/src/github.com/github/orchestrator/go/inst/instance_topology.go:611 +0x25
github.com/github/orchestrator/go/inst.moveReplicasViaGTID.func1(0xc436362960, 0xc4201b7760, 0xc4271c6840, 0xc43709ad20, 0xc4488a3180, 0xc4488a31a0, 0xc4488a31c0)
        /builddir/build/BUILD/orchestrator-3.0.1.1/GO/src/github.com/github/orchestrator/go/inst/instance_topology.go:631 +0xe0
created by github.com/github/orchestrator/go/inst.moveReplicasViaGTID
        /builddir/build/BUILD/orchestrator-3.0.1.1/GO/src/github.com/github/orchestrator/go/inst/instance_topology.go:631 +0x327
```
Which seems to imply that `replica` is nil. I can imagine that’s not expected to happen and wonder how it could have happened.

Other orchestrator apps in the cluster have been running since 5/10/2017 and are still happy. This uses traditional orchestrator with several apps talking to a backend MySQL service.

I need to check but there may have been a network related issue at this time but even so I would not expect orchestrator to crash.

My suggestion would be to add a check for this condition or ensure the caller can not provide a nil value which would trigger this.

This is not urgent but it may be current code could be affected similarly.

**Comment by shlomi-noach** [comment]
Deja-Vu: https://github.com/github/orchestrator/issues/263
@sjmudd can you confirm [this change](https://github.com/github/orchestrator/pull/265/files) made it to your version?

**Comment by sjmudd** [comment]
No, it's missing. Thanks for pointing out the fault. I'll patch my code for now and and then look to catch up with your most recent changes.
