### ISSUE TITLE
One orchestrator down => No leader 

### ISSUE THREAD

**Issue by tapuhi** [openark/orchestrator#358]
Hi @shlomi-noach , 
     One of my orchestrator nodes got down(not the one that was a leader)  and now orchestrator/raft is unable to elect one of its nodes as a leader.

  Isn't it possible to have weights/ preferred node so that even if we have an even number of nodes up we can still have a leader?

BR

**Comment by shlomi-noach** [comment]
How many nodes of `orchestrator` do you have in the first place? You need to have a minimum of `3` to form a consensus.

> Isn't it possible to have weights/ preferred node so that even if we have an even number of nodes up we can still have a leader?

There's no weights or preferred node setups, but that is irrelevant to "even if we have an even number of nodes up we can still have a leader?".

If you have 3 nodes, and one goes down, the other two should form a consensus and elect a leader. The fact the remaining number of nodes is even is not important. What's important is the _majority_ of it.

**Comment by tapuhi** [comment]
We have 3 nodes. But again, one down makes orchestrator unable to elect a leader

**Comment by shlomi-noach** [comment]
This isn't my experience, so let's try and figure out what happens at your place. Any single node that goes down does that?

What do you see when you `tail -f /var/log/orchestrator.log | grep -i raft` (on the two remaining nodes)?
Are you certain the config file in all three nodes is identical in terms of `RaftNodes`? And are you certain all three `orchestrator` nodes are indeed the ones listed in `RaftNodes`? If one of them isn't, then it isn't really part of the cluster.

**Comment by shlomi-noach** [comment]
Can this issue be closed?

**Comment by tapuhi** [comment]
Yes, I was not reproduced since then and we've lost several nodes since then,
