### ISSUE TITLE
Receiving Error Uptime Error After Rebooting MySQL Node.

### ISSUE THREAD

**Issue by emusickid** [openark/orchestrator#359]
Hey guys,

We are in the process of rolling out Orchestrator in our production environment. I just found a potential bug after rebooting a node with a cluster being monitored by Orchestrator.

Error: 
```
ERROR Error 1264: Out of range value for column 'uptime' at row 1
```
It appears that the Uptime column in the database_instance table is not able to be updated and causing the thread that captures stats for that node to fail. The server that was rebooted is showing as lagging  (replication) in the Orchestrator UI.

Has anyone else ran into this yet?

Thanks for all the great work- this is the first major issue I've been faced with so far.

Version we are using:
```
apt-cache policy orchestrator
orchestrator:
  Installed: 1:3.0.1
  Candidate: 1:3.0.1
  Version table:
 *** 1:3.0.1 0
```

**Comment by shlomi-noach** [comment]
`uptime` is a `int unsigned` type in the `database_instance` underlying table, whose value is set by invoking `show global status like 'uptime'`. Could you invoke said query on your server and report the response?

**Comment by emusickid** [comment]
Just rebooted  my other Master and I get the error again:
```
mysql> show global status like 'uptime';
+---------------+----------------------+
| Variable_name | Value                |
+---------------+----------------------+
| Uptime        | 18446744073709548169 |
+---------------+----------------------+
1 row in set (0.00 sec)

```
Status is showing uptime blank here :/ : 
```
11:52:22][(none)] mysql> status
--------------
mysql  Ver 14.14 Distrib 5.7.14-8, for debian-linux-gnu (x86_64) using  6.3

Connection id:		1988
Current database:	
Current user:		root@localhost
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		5.7.14-8-log Percona Server (GPL), Release '8', Revision '1f84ccd'
Protocol version:	10
Connection:		Localhost via UNIX socket
Server characterset:	utf8
Db     characterset:	utf8
Client characterset:	utf8
Conn.  characterset:	utf8
UNIX socket:		/var/run/mysqld/mysqld.sock
Uptime:			--------------
```
Actual Server Uptime:
```
]:~# uptime 
 11:48:14 up 11 min,  1 user,  load average: 0.33, 0.34, 0.27
```
Log from Leader Node:
```
Dec 21 11:40:59 [8333]: Error 1264: Out of range value for column 'uptime' at row 1
Dec 21 11:41:02 [8333]: Error 1264: Out of range value for column 'uptime' at row 1
Dec 21 11:41:05 [8333]: Error 1264: Out of range value for column 'uptime' at row 1
Dec 21 11:41:08 r[8333]: Error 1264: Out of range value for column 'uptime' at row 1
```

The interesting thing is that I tried this same thing in my staging environment and had no issues 🤔 .

Also after maybe 30 minutes last night the uptime cleared from the initial issue I posted - and the Orchestrator was able to crawl the full topology ine again for this DB Cluster.

This smells like an issues with MySQL 5.7.

**Comment by emusickid** [comment]
I'm going to close this out @shlomi-noach - but in case anyone experiences this there will be some record of it.

If interested I seemed to of had some issues with pt-heartbeat and had to restart it and then that actually fixed the uptime value in MySQL - not sure how all that's related, but this is definitely not an issue with Orchestrator.

Thanks man!!

-Eric

**Comment by shlomi-noach** [comment]
I'm wondering what `orchestrator` should do in this scenario, though. What would be a behavior that makes sense?

**Comment by emusickid** [comment]
I guess you could make the `uptime` value more optional - and then gracefully issue a warning in the log. `Orchestrator` could then at least startup, and if/when this issue corrects itself things will be fine. Otherwise we would be able to see these warnings in the log and take appropriate action.

Just a quick thought - might be some better ideas out there as well.

Thanks man!!

-Eric
