### ISSUE TITLE
Dashboard empty after upgrade from 2.15 to 3.0.3

### ISSUE THREAD

**Issue by Povezi** [openark/orchestrator#368]
Hi, missing all clusters and dashboard is now empty... any missing step? 

Suggestion: it would be nice to have update guide in documentation...

**Comment by shlomi-noach** [comment]
@Povezi there's no special steps to be taken when upgrading. Can you please share your config, and can you please look at/paste the error log? Thank you.

**Comment by linuxgood1230** [comment]
@Povezi Maybe you shoude  clear chrome/firfox cache，then Refresh

**Comment by shlomi-noach** [comment]
No response. Closing as stale.
