### ISSUE TITLE
Show active node "active time" and "uptime" in https://myurl.example.com/web/status

### ISSUE THREAD

**Issue by sjmudd** [openark/orchestrator#37]
The current /web/status url shows the list of members of the orchestrator cluster and which node is active. We also show the version of orchestrator that is running.

A couple of things that are not shown for each orchestrator node:
* process uptime
* if an active node: time active

This gives you some idea of the stability of the cluster and also how long it has been running. Without that it's pretty hard to tell.

Why is this useful? Basically it allows you to see if your network is stable, if the servers have been running for the amount of time you might expect and you can do all of this at the click of a button and without dropping into the OS or using other monitoring tools to see it.

**Comment by shlomi-noach** [comment]
Fixed by #53
