### ISSUE TITLE
Support SSL replication in graceful master takeover

### ISSUE THREAD

**Issue by stankevich** [openark/orchestrator#380]
**Problem:** In an SSL-enabled replication environment (`REQUIRE SSL` in grants, `MASTER_SSL = 1` in `CHANGE MASTER TO ...` on the client), Orchestrator is unable to reattach the demoted master properly.

If master fails, all replicas already know about SSL replication — this is stored in `mysql.slave_master_info` — they don't need any additional configuration to replicate from the newly promoted master. Orchestrator doesn't need to do anything special here.

However, during a graceful master takeover Orchestrator needs to issue a `CHANGE MASTER TO MASTER_SSL = 1` in addition to other `CHANGE MASTER TO ...` statements on the former master (now a replica) in order for it to start replicating from the new master.

This also affects co-master replication when created from a master-replica pair.

Could Ochestrator detect whether `CHANGE MASTER TO MASTER_SSL = 1` is required based on `AllowTLS` value of the former replica (now master)? Are there better alternatives? Am I missing something?

I could help with the PR.

Thanks!

**Comment by shlomi-noach** [comment]
@stankevich if you have the time to look into this, I'm more than happy. 

> Could Ochestrator detect whether CHANGE MASTER TO MASTER_SSL = 1 is required based on AllowTLS value of the former replica (now master)? 

Makes perfect sense to me. Perhaps @dveeden or @sjmudd can confirm, since they have been working on, and contributing SSL support in `orchestrator`?

**Comment by dveeden** [comment]
Yes seems to make sense to me.

**Comment by stankevich** [comment]
Thanks!

**Comment by shlomi-noach** [comment]
Thank _you_
