### ISSUE TITLE
Orchestrator PromotionRule settings appear to not be used (or logic of usage is unclear)

### ISSUE THREAD

**Issue by sjmudd** [openark/orchestrator#39]
I recently had an intermediate master failure and orchestrator promoted a slave which had a promotion rule  `must not`. This was not expected.

* `instance.PromotionRule` settings seem to be correctly set and used and I was using the api calls to ensure that all servers had the expected `PromotionRule` I required. This works fine.  I double checked the promoted server's rules and they showed `must_not`.
* in my case the analysis showed an issue type of `DeadIntermediateMasterWithSingleSlaveFailingToConnect`
* I see that `RecoverDeadIntermediateMaster()` calls `GetCandidateSiblingOfIntermediateMaster()` which as far as I can see makes no reference to `PromotionRule` settings.
* There has been talk that under some circumstances Orchestrator may do the promotion in a couple of steps but it would be good if the intention is documented and if or where this is actually implemented were described so people know what to expect.
* as far as I can see the `PromotionRule` is only used on semi-sync slaves in certain circumstances.

So if `PromotionRule` is currently used for determining the best alternative intermediate master to promote can you point me in the right direction. I guess the same goes for primary master election too (though the issue I saw was on a failed intermediate master).

If this functionality is missing and you want help in implementing it then please let me know. I really want to use this functionality and given the CandidatePromotionRule type and description, and the fact there's a Instance.PromotionRule column I assumed that this was working now.

Related is the fact that following the exact details of an Intermediate master failure (it being noticed as part of the discovery process and also the fact the slaves also notice this, followed by the process of relocation and final termination of the recovery process) is really hard. If you have few servers then there is less logging but if the number of servers increases finding the relevant lines in the log file is quite tricky. I wonder if there is a way that some sort of `reference` can be generated and passed down in all related logging to allow me to do something like a grep of that reference and see the full recovery history.  This would mean that if a failure happens then you could easily provide a detailed audit of everything that happens now related to the recovery process. While there is auditing information it seems not to be sufficiently detailed at the moment to provide a full trail. I think it would be good to have something which can run and which can give all the information needed to explain in detail the timing of when the problem happened, what was done once it was detected to resolve it, and whether the process completed successfully or not.  I think that something like this would be useful and more so for people who are not aware of all the code details of orchestrator.

**Comment by sjmudd** [comment]
I also notice there is a `IsCandidate` field in `Instance` so these values seem to overlap. Or is there a requirement to set both settings to get the required behaviour?

I've just assumed that setting the `PromotionRule` would be good enough but perhaps that is not the case. This would require me to additionally do bulk changes to IsCandidate to ensure that orchestrator picks up all relevant promotion rules for the different slaves so seems to be more work.

Hence clarification of behaviour and expected configuration would be good.

**Comment by sjmudd** [comment]
Note: as a work around for my specific current usage I could do something like this:
* modify `go/inst/instance_dao.go` `RegisterCandidateInstance` to set `IsCandidate` = `true` IF PromotionRule is `must` or `prefer`. That change is easy and while it doesn't resolve the `must_not` issue it does help and should be reasonably straightforward to implement.

However, please let me know if my understanding of intended usage of the current settings is valid or not.

**Comment by sjmudd** [comment]
So partial workaround implemented. Please consider accepting this if appropriate while a better solution is determined.

**Comment by shlomi-noach** [comment]
This is where `IsCandidate` gets to consider (or, rather, _exclude_) `must_not` servers: https://github.com/github/orchestrator/blob/92b5c7c093a2803cd8a5e483d64d522a1a17aa55/go/inst/instance_dao.go#L810-L811

**Comment by shlomi-noach** [comment]
On further discussing this event in private, there is no operational issue, but with concerns about wording.

the topology was something like:

```
master
+ replica1
+ replica2
   + testingserver
```

`testingserver` was set as `must_not`.

`replica2` failed. `orchestrator` detected `DeadIntermediateMasterWithSingleSlaveFailingToConnect` and relocated `testingserver` under `master`.

There is no error here. The server `testingserver` was not turned to be master or intermediate master of other replicas. Wording wise, it was more "salvaged" than "promoted".

There is no flaw of logic in this failover and it worked as expected.

Discussed with @sjmudd we will pursue improved wording, on a new issue.
