### ISSUE TITLE
MySQL can't recover with GTID

### ISSUE THREAD

**Issue by Xinglao4** [openark/orchestrator#392]
@shlomi-noach: I'm trying to test the recovery of orchestrator and having some problems. When I stop the master of MySQL, who enable the GTID, the slave can't be promoted to master.
This content appear in the recover log:
All errors:
PseudoGTIDPattern not configured; cannot use Pseudo-GTID
I find this word in the document: "At this time recovery requires either GTID (Oracle or MariaDB), Pseudo GTID or Binlog Servers." Is it means the GTID only useful for Oracle or MariaDB, not MySQL?

By the way,  I'm the first time to use the raft, should I do some extra thing to start the raft? I have create and edit /etc/profile.d/orchestrator-client.sh according to the document. But I don't know how to start the raft. I can use the command like "orchestrator-client -c which-api", but error on "orchestrator-client -c raft-leader" of word "raft-state: not running with raft setup".
What can I do for this?

Thanks!

**Comment by shlomi-noach** [comment]
> Is it means the GTID only useful for Oracle or MariaDB, not MySQL?


Oracle owns MySQL. When I say "Oracle" I mean "MySQL".

From the little information I get here, `orchestrator` doesn't think your servers are running GTID. Can you please confirm they are? Are you using `gtid_mode=ON` on all boxes? is `AUTO_POSITION=1` on `SHOW SLAVE STATUS` on all replicas?


> By the way, I'm the first time to use the raft, should I do some extra thing to start the raft? 

Have you followed the manual, https://github.com/github/orchestrator/blob/master/docs/configuration-raft.md#configuration-raft ?

**Comment by Xinglao4** [comment]
> orchestrator doesn't think your servers are running GTID

![image](https://user-images.githubusercontent.com/17682294/35567809-4ab715ca-0601-11e8-8740-4cb4e84e43b8.png)
![image](https://user-images.githubusercontent.com/17682294/35567825-5946fbdc-0601-11e8-9dd1-5a186a559553.png)
I think orchestrator knows my servers are running GTID. Are there any possible problems?

> Have you followed the manual

I have configed like this. Are there any wrongs?

**Comment by shlomi-noach** [comment]
I'd appreciate it if you could please paste direct text, and not screenshots, at least re: your config file. The screenshot makes it difficult for me to read, quote, and point to a problem.

The `raft` configuration problem is: you need to remove the `<>`. Just put in the IP. I can see why you were confused with this, I will update the documentation (though "<>" it a standard notation for "replace this with your actual data").

**Comment by shlomi-noach** [comment]
As per the documentation, an example looks like:

```
  "RaftEnabled": true,
  "RaftDataDir": "/var/lib/orchestrator",
  "RaftBind": "10.0.0.2",
  "DefaultRaftPort": 10008,
  "RaftNodes": [
    "10.0.0.1",
    "10.0.0.2",
    "10.0.0.3"
  ],
```

**Comment by shlomi-noach** [comment]
Can you paste the output of `orchestrator -c topology -i name.of.one.of.the.boxes` please?
And, if possible, the output of `<your-orchestratir-url>/api/cluster/<name-of-your-cluster>`

Thank you

**Comment by shlomi-noach** [comment]
Please make sure to answer:

> Are you using gtid_mode=ON on all boxes? is AUTO_POSITION=1 on SHOW SLAVE STATUS on all replicas?

**Comment by shlomi-noach** [comment]
I only now notice that the screenshot is of the documentation page. Please: I cannot see what you;ve configured.

> I have configed like this. Are there any wrongs?

I have no idea what your configuration is. How can I help you?

**Comment by Xinglao4** [comment]
I have change my config of raft like this:
`# Configuration: raft

Set up a [orchestrator/raft](raft.md) cluster for high availability.

Assuming you will run `orchestrator/raft` on a `3` node setup, you will configure this on each node:

```json
  "RaftEnabled": true,
  "RaftDataDir": "/usr/local/bin/orchestrator",
  "RaftBind": "10.76.163.200",
  "DefaultRaftPort": 10008,
  "RaftNodes": [
    "10.76.163.200",
    "10.76.162.231",
    "10.76.162.232"
  ],
```

Some breakdown:

- `RaftEnabled` must be set to `true`, otherwise `orchestrator` runs in shared-backend mode.
- `RaftDataDir` must be set to a directory writable to `orchestrator.` `orchestrator` will attempt to create the directory if not exists.
- `RaftBind` must be set, use the IP address or full hostname of local host. This IP or hostname will also be listed as one of the `RaftNodes` variable.
- `DefaultRaftPort` can be set to any port, but must be consistent across all deployments.
- `RaftNodes` should list all nodes of the raft cluster. This list will consist of either IP addresses or host names, and will include the value of this host itself as presented in `RaftBind`.

As example, the following might be a working setup:

```json
  "RaftEnabled": true,
  "RaftDataDir": "/usr/local/bin/orchestrator",
  "RaftBind": "10.76.162.231",
  "DefaultRaftPort": 10008,
  "RaftNodes": [
    "10.76.163.200",
    "10.76.162.231",
    "10.76.162.232"
  ],
```

as well as this:
```json
  "RaftEnabled": true,
  "RaftDataDir": "/usr/local/bin/orchestrator",
  "RaftBind": "10.76.162.232",
  "DefaultRaftPort": 10008,
  "RaftNodes": [
    "10.76.163.200",
    "10.76.162.231",
    "10.76.162.232"
  ],
```

If your orchestrator/raft nodes need to communicate via NAT gateways, you can additionally set "RaftAdvertise" to IP or hostname which other nodes should contact. Otherwise other nodes would try to talk to the "RaftBind" address and fail.

### Backend DB

A `raft` setup supports either `MySQL` or `SQLite` backend DB. See [backend](configuration-backend.md) configuration for either. Read [high-availability](high-availability.md) page for scenarios, possibilities and reasons to using either.`

There are three parts of nodes. Should I fill in like this?

**Comment by shlomi-noach** [comment]
@Xinglao4 please, I'm trying to assist here. Can you please not paste the manual in response to my question? Can you please just paste your configuration file, and only your configuration file? Otherwise I'm sorry but I cannot help you anymore.

**Comment by Xinglao4** [comment]
> Can you paste the output of orchestrator -c topology -i name.of.one.of.the.boxes please?

[root@mysql-sredb01.xh orchestrator]# orchestrator-client -c topology -i orch_test
mysql-sredb04.xh:3306   [0s,ok,5.7.18-15-log,rw,ROW,>>,GTID]
+ mysql-sredb05.xh:3306 [0s,ok,5.7.18-15-log,rw,ROW,>>,GTID]
+ mysql-sredb06.xh:3306 [0s,ok,5.7.18-15-log,rw,ROW,>>,GTID]

> And, if possible, the output of <your-orchestratir-url>/api/cluster/<name-of-your-cluster>

[root@mysql-sredb01.xh orchestrator]# curl "10.76.163.200:3306/api/cluster/orch_test"
5.7.18-15-log[_%.w^CO�����"Qu#os:smysql_native_password��Got packets out of order

**Comment by Xinglao4** [comment]
Sorry, I have update the comment and only keep the content where I config.

**Comment by shlomi-noach** [comment]
~~Seems to me like your running `https://`? Please add `https://` and try again.~~

**Comment by Xinglao4** [comment]
[root@mysql-sredb01.xh orchestrator]# curl "http://10.76.163.200:3306/api/cluster/orch_test"
B'�����{W c#4t%mysql_native_password��Got packets out of order

**Comment by shlomi-noach** [comment]
You have connected to your mysql server (`3306`) instead of `orchestrator`. Please try `<your.orchestrator.server>:3000/api/...`

I'm assuming your port is `:3000`. If you can _please paste your config file_ that would be extremely helpful.

**Comment by Xinglao4** [comment]
```
[root@mysql-sredb01.xh orchestrator]# curl "http://10.76.163.200:3000/api/cluster/orch_test"
[{"Key":{"Hostname":"mysql-sredb04.xh","Port":3306},"InstanceAlias":"","Uptime":18014,"ServerID":1793306238,"ServerUUID":"b6631ba9-00b0-11e8-8e84-002238ce01d2","Version":"5.7.18-15-log","VersionComment":"Percona Server (GPL), Release 15, Revision bff2cd9","FlavorName":"Percona","ReadOnly":false,"Binlog_format":"ROW","BinlogRowImage":"FULL","LogBinEnabled":true,"LogSlaveUpdatesEnabled":true,"SelfBinlogCoordinates":{"LogFile":"mysql-bin.000010","LogPos":194,"Type":0},"MasterKey":{"Hostname":"","Port":0},"IsDetachedMaster":false,"Slave_SQL_Running":false,"Slave_IO_Running":false,"HasReplicationFilters":false,"SupportsOracleGTID":true,"UsingOracleGTID":false,"UsingMariaDBGTID":false,"UsingPseudoGTID":false,"ReadBinlogCoordinates":{"LogFile":"","LogPos":0,"Type":0},"ExecBinlogCoordinates":{"LogFile":"","LogPos":0,"Type":0},"IsDetached":false,"RelaylogCoordinates":{"LogFile":"","LogPos":0,"Type":1},"LastSQLError":"","LastIOError":"","SecondsBehindMaster":{"Int64":0,"Valid":false},"SQLDelay":0,"ExecutedGtidSet":"","GtidPurged":"","SlaveLagSeconds":{"Int64":0,"Valid":false},"SlaveHosts":[{"Hostname":"mysql-sredb06.xh","Port":3306},{"Hostname":"mysql-sredb05.xh","Port":3306}],"ClusterName":"mysql-sredb04.xh:3306","SuggestedClusterAlias":"orch_test","DataCenter":"","PhysicalEnvironment":"","ReplicationDepth":0,"IsCoMaster":false,"HasReplicationCredentials":false,"ReplicationCredentialsAvailable":false,"SemiSyncEnforced":false,"SemiSyncMasterEnabled":false,"SemiSyncReplicaEnabled":false,"LastSeenTimestamp":"2018-01-30 21:43:34","IsLastCheckValid":true,"IsUpToDate":true,"IsRecentlyChecked":true,"SecondsSinceLastSeen":{"Int64":4,"Valid":true},"CountMySQLSnapshots":0,"IsCandidate":false,"PromotionRule":"neutral","IsDowntimed":false,"DowntimeReason":"","DowntimeOwner":"","DowntimeEndTimestamp":"","ElapsedDowntime":0,"UnresolvedHostname":"","AllowTLS":false,"LastDiscoveryLatency":2757445},{"Key":{"Hostname":"mysql-sredb05.xh","Port":3306},"InstanceAlias":"","Uptime":557853,"ServerID":1603306147,"ServerUUID":"b7463cf0-00b0-11e8-ba98-00228310e4db","Version":"5.7.18-15-log","VersionComment":"Percona Server (GPL), Release 15, Revision bff2cd9","FlavorName":"Percona","ReadOnly":false,"Binlog_format":"ROW","BinlogRowImage":"FULL","LogBinEnabled":true,"LogSlaveUpdatesEnabled":true,"SelfBinlogCoordinates":{"LogFile":"mysql-bin.000004","LogPos":346,"Type":0},"MasterKey":{"Hostname":"mysql-sredb04.xh","Port":3306},"IsDetachedMaster":false,"Slave_SQL_Running":true,"Slave_IO_Running":true,"HasReplicationFilters":false,"SupportsOracleGTID":true,"UsingOracleGTID":false,"UsingMariaDBGTID":false,"UsingPseudoGTID":false,"ReadBinlogCoordinates":{"LogFile":"mysql-bin.000010","LogPos":194,"Type":0},"ExecBinlogCoordinates":{"LogFile":"mysql-bin.000010","LogPos":194,"Type":0},"IsDetached":false,"RelaylogCoordinates":{"LogFile":"mysql-relay-bin.000011","LogPos":407,"Type":1},"LastSQLError":"\"\"","LastIOError":"\"\"","SecondsBehindMaster":{"Int64":0,"Valid":true},"SQLDelay":0,"ExecutedGtidSet":"b6631ba9-00b0-11e8-8e84-002238ce01d2:1","GtidPurged":"","SlaveLagSeconds":{"Int64":0,"Valid":true},"SlaveHosts":[],"ClusterName":"mysql-sredb04.xh:3306","SuggestedClusterAlias":"orch_test","DataCenter":"","PhysicalEnvironment":"","ReplicationDepth":1,"IsCoMaster":false,"HasReplicationCredentials":true,"ReplicationCredentialsAvailable":true,"SemiSyncEnforced":false,"SemiSyncMasterEnabled":false,"SemiSyncReplicaEnabled":false,"LastSeenTimestamp":"2018-01-30 21:43:34","IsLastCheckValid":true,"IsUpToDate":true,"IsRecentlyChecked":true,"SecondsSinceLastSeen":{"Int64":4,"Valid":true},"CountMySQLSnapshots":0,"IsCandidate":false,"PromotionRule":"neutral","IsDowntimed":false,"DowntimeReason":"","DowntimeOwner":"","DowntimeEndTimestamp":"","ElapsedDowntime":0,"UnresolvedHostname":"","AllowTLS":false,"LastDiscoveryLatency":2679811},{"Key":{"Hostname":"mysql-sredb06.xh","Port":3306},"InstanceAlias":"","Uptime":557856,"ServerID":1613306242,"ServerUUID":"b54bcf3a-00b0-11e8-bf29-002240a11bf0","Version":"5.7.18-15-log","VersionComment":"Percona Server (GPL), Release 15, Revision bff2cd9","FlavorName":"Percona","ReadOnly":false,"Binlog_format":"ROW","BinlogRowImage":"FULL","LogBinEnabled":true,"LogSlaveUpdatesEnabled":true,"SelfBinlogCoordinates":{"LogFile":"mysql-bin.000004","LogPos":346,"Type":0},"MasterKey":{"Hostname":"mysql-sredb04.xh","Port":3306},"IsDetachedMaster":false,"Slave_SQL_Running":true,"Slave_IO_Running":true,"HasReplicationFilters":false,"SupportsOracleGTID":true,"UsingOracleGTID":false,"UsingMariaDBGTID":false,"UsingPseudoGTID":false,"ReadBinlogCoordinates":{"LogFile":"mysql-bin.000010","LogPos":194,"Type":0},"ExecBinlogCoordinates":{"LogFile":"mysql-bin.000010","LogPos":194,"Type":0},"IsDetached":false,"RelaylogCoordinates":{"LogFile":"mysql-relay-bin.000017","LogPos":407,"Type":1},"LastSQLError":"\"\"","LastIOError":"\"\"","SecondsBehindMaster":{"Int64":0,"Valid":true},"SQLDelay":0,"ExecutedGtidSet":"b6631ba9-00b0-11e8-8e84-002238ce01d2:1","GtidPurged":"","SlaveLagSeconds":{"Int64":0,"Valid":true},"SlaveHosts":[],"ClusterName":"mysql-sredb04.xh:3306","SuggestedClusterAlias":"orch_test","DataCenter":"","PhysicalEnvironment":"","ReplicationDepth":1,"IsCoMaster":false,"HasReplicationCredentials":true,"ReplicationCredentialsAvailable":true,"SemiSyncEnforced":false,"SemiSyncMasterEnabled":false,"SemiSyncReplicaEnabled":false,"LastSeenTimestamp":"2018-01-30 21:43:34","IsLastCheckValid":true,"IsUpToDate":true,"IsRecentlyChecked":true,"SecondsSinceLastSeen":{"Int64":4,"Valid":true},"CountMySQLSnapshots":0,"IsCandidate":false,"PromotionRule":"neutral","IsDowntimed":false,"DowntimeReason":"","DowntimeOwner":"","DowntimeEndTimestamp":"","ElapsedDowntime":0,"UnresolvedHostname":"","AllowTLS":false,"LastDiscoveryLatency":3185397}]
```
It is my fault. So sorry for that.

**Comment by Xinglao4** [comment]
I have find:
`"UsingOracleGTID":false`
I will check it again now.

**Comment by shlomi-noach** [comment]
On the replicas I see `"UsingOracleGTID": false,`. This should be `true`. 
I'd like to help, and for that I'm asking again, can you please confirm you have   `AUTO_POSITION=1` on `SHOW SLAVE STATUS` on all replicas? I suspect you don't.

**Comment by shlomi-noach** [comment]
The `raft` setup seems good.

**Comment by shlomi-noach** [comment]
To debug `raft` , I need raft-related messages from the error log. Ideally, you will restart the `orchestrator` service, and `grep raft /var/log/orchestrator.log` and paste the output.

**Comment by Xinglao4** [comment]
I have solve the first problem. It is because I don't set AUTO_POSITION=1. Thank you a lot.

The second question about raft. I don't know should I direct config in the file named configuration-raft.md?
I have change the config file in three parts:
> 
> ```json
>   "RaftEnabled": true,
>   "RaftDataDir": "/usr/local/bin/orchestrator",
>   "RaftBind": "10.76.163.200",
>   "DefaultRaftPort": 10008,
>   "RaftNodes": [
>     "10.76.163.200",
>     "10.76.162.231",
>     "10.76.162.232"
>   ],
> ```
>
> ```json
>   "RaftEnabled": true,
>   "RaftDataDir": "/usr/local/bin/orchestrator",
>   "RaftBind": "10.76.162.231",
>   "DefaultRaftPort": 10008,
>   "RaftNodes": [
>     "10.76.163.200",
>     "10.76.162.231",
>     "10.76.162.232"
>   ],
> ```
> 
> ```json
>   "RaftEnabled": true,
>   "RaftDataDir": "/usr/local/bin/orchestrator",
>   "RaftBind": "10.76.162.232",
>   "DefaultRaftPort": 10008,
>   "RaftNodes": [
>     "10.76.163.200",
>     "10.76.162.231",
>     "10.76.162.232"
>   ],
> ```

**Comment by shlomi-noach** [comment]
`configuration-raft.md` is a documentation page. You need to edit your `orchestrator` config file, which should be `/etc/init.d/orchestrator.conf.json`

**Comment by Xinglao4** [comment]
> You need to edit your orchestrator config file, which should be /etc/init.d/orchestrator.conf.json

This is the reason...
I have run the raft successfully now. 
I have ask a lot because of learn this first time. Thanks for answer me so much.

**Comment by shlomi-noach** [comment]
It took me a while to realize your confusion was with the documentation page, which explains why you pasted it in the first place. I'm glad this works now!

**Comment by Xinglao4** [comment]
> grep raft /var/log/orchestrator.log and paste the output.

The last question: How can I specified the position of orchestrator.log, which parameter, I don't find it anywhere.

**Comment by shlomi-noach** [comment]
This is defined in `/etc/init.d/orchestrator`, https://github.com/github/orchestrator/blob/a77ee001dc95b8dc0476b929164f37b1141f54c1/etc/init.d/orchestrator.bash#L49

**Comment by Xinglao4** [comment]
> This is defined in /etc/init.d/orchestrator,

I think it is defined and don't need to do any other operation. But I have not see this file in the path.

```
[root@mysql-sredb01.xh log]# less /var/log/orchestrator.log
/var/log/orchestrator.log: 没有那个文件或目录
```

**Comment by shlomi-noach** [comment]
Im assuming you're on the box where the HTTP service is running, is that so?

**Comment by Xinglao4** [comment]
> Im assuming you're on the box where the HTTP service is running, is that so?

Yes, so I want to know should I add some parameter when I run the orchestrator?

**Comment by shlomi-noach** [comment]
No. I'd suggest getting assistance from IT/sysadmin in locating the log file. There _is_ a log file.

**Comment by Xinglao4** [comment]
Maybe this is relate to the operation of build main.go again by me.
Now I have create the log file by specified the path of output.
Thank you again.

**Comment by shlomi-noach** [comment]
I'd recommend just using one of the supplied `.deb` or `.rpm` binaries in https://github.com/github/orchestrator/releases/latest

**Comment by Xinglao4** [comment]
I will consider the suggest seriously, thanks.
