### ISSUE TITLE
Parsing grants in canInjectPseudoGTID() can fail when instance uses ANSI_QUOTES. 

### ISSUE THREAD

**Issue by mikelust** [openark/orchestrator#393]
In particular
```if strings.Contains(grant, `DROP`) && strings.Contains(grant, fmt.Sprintf(" ON `%s`.*", config.PseudoGTIDSchema)) 
 {
				foundDropOnSchema = true
}```

was failing for us because our grants show
```    GRANT DROP on "_pseudo_gtid_".* to <user>```

i.e. double quotes because of instance sql_mode that includes ANSI_QUOTES.

We are working around it by giving the broader grant on `*.*` to the Orchestrator user, but it would be nice not to.

Thanks for the AutoPseudoGTID feature, we needed it.

**Comment by shlomi-noach** [comment]
@mikelust would you care to test https://github.com/github/orchestrator/pull/395, if you can?

**Comment by mikelust** [comment]
Tested.   Downloaded branch, reinstated logging line 2723 in instance_dao.go to help debugging.
Revoked all drop grants from orchestrator user.  Verified the log:
2018-02-03 19:54:28 INFO ................isInjectedPseudoGTID returning from cache xxxmysql-02:3306:false
Granted schema specific grants to orchestrator user.  
'show grants' output, note the quotes:
```| GRANT DROP ON "_pseudo_gtid_".* TO 'orchestrator'@'host'                        |```
Afterward, log shows:
2018-02-03 19:54:28 INFO ................isInjectedPseudoGTID returning from cache xxxmysql-02:3306:true

Looks great.  Thanks for the quick help.
