### ISSUE TITLE
orchestrator-client support Basic Auth

### ISSUE THREAD

**Issue by linuxgood1230** [openark/orchestrator#397]
orchstrator-client use curl to send req to Api

use curl -s 'http/mysqlserver.com:3000/api' -u username:password

**Comment by shlomi-noach** [comment]
Hi! Please clarify: is this a feature request? A documentation update?

**Comment by linuxgood1230** [comment]
curl command is documentation update
orchstrator-client  is a feature request

**Comment by shlomi-noach** [comment]
Please see https://github.com/github/orchestrator/pull/466

**Comment by shlomi-noach** [comment]
@linuxgood1230 I wonder if you can test and confirm #466 works to your satisfaction?

**Comment by shlomi-noach** [comment]
@linuxgood1230 any thoughts?

**Comment by shlomi-noach** [comment]
fixed by #466
