### ISSUE TITLE
Enhancement: Allow custom rendering or other hooks for the web interface

### ISSUE THREAD

**Issue by berlincount** [openark/orchestrator#403]
In some constellations, you might want to be able to customise the look and feel of the web interface.

It would be helpful to have some dedicated injection points for custom CSS and JavaScript.

**Comment by shlomi-noach** [comment]
While I'm not opposed to the general idea of customizing JS & CSS, the following must be made clear:

- How will I support users who have set up custom CSS and JS? (I don't wish to)
- What will be my indication that they are indeed running custom CSS and JS? (To be able to tell them "unsupported")
- Documentation must be updated to reflect these changes.

Thank you!

**Comment by berlincount** [comment]
Thanks for your consideration :)

- I'd make clear that customisations are optional and unsupported, but that endpoints / hooks can be added as needed, but that the API and data structures are subject to change at your leisure, and also largely undocumented. Anyone capable of using the Web Developer features of any current browser should have no trouble inspecting and adjusting as needed
- I'd make the corresponding files "config files" in the Debian package (so `dpkg` handles them correctly on updates) and use some XHR-style fetching in the JavaScript to verify original checksums (gathered during the build process) against the version currently running? If the checksum of the current `css/custom.css`/`js/custom.js` mismatched with the shipped one, add `-customized` to the version string .. and ask to reproduce any issues on a non-customised version when supported.
- I'd leave the documentation sparse and mention that there are some hooks and that (unstable) data structures can be used .. if needed.

Hope that helps?

**Comment by shlomi-noach** [comment]
Thank you! a few more clarifications:

> I'd make the corresponding files "config files" in the Debian package (so dpkg handles them correctly on updates) and use some XHR-style fetching in the JavaScript to verify original checksums (gathered during the build process) against the version currently running?

  Do you know how to do this? Are you able to add this to the PR?

> I'd leave the documentation sparse and mention that there are some hooks and that (unstable) data structures can be used .. if needed.

  Heh, it was a polite way of asking you to add said documentation 😆

**Comment by berlincount** [comment]
Heh, I was trying to sidestep it ;) I guess I might be able to do so, yes. Need to find some time under somewhere under the sofa or so ...

**Comment by berlincount** [comment]
I'm considering rewriting it slightly to use https://learn.jquery.com/events/introduction-to-custom-events/ with event names like `orchestrator:preRenderCluster` and `orchestrator:postRenderCluster`, so we got a more standardised approach here (and don't need empty hook functions, plus a grep for available hooks becomes easy).

**Comment by berlincount** [comment]
PR was updated per comments :)

**Comment by berlincount** [comment]
After the PR was merged (thanks!!), this only waits for the next release :)

**Comment by shlomi-noach** [comment]
Expect a release early next week.
