### ISSUE TITLE
cluster for mysql group replication

### ISSUE THREAD

**Issue by sych74** [openark/orchestrator#409]
Hi!
I'm using a mysql group replication and I know that orchestrator does not support MGR. I would like to use orchestrator only for display all instances in the same cluster. How can I do it?

Thank you!

**Comment by shlomi-noach** [comment]
orchestrator will not identify the cluster instances as belonging to the same cluster. So they can show up as three different sincle-host clusters... Not what you'd want to get, I'm sure.

**Comment by sych74** [comment]
Thanks for your reply!

**Comment by ernstae** [comment]
Just curious -- Is this considered a "closed - will not fix" sort of issue?  Does it have any fuel for the future?

I'm also running multiple group replication clusters, and wanted to incorporate orchestrator to make this easier to manage.

**Comment by shlomi-noach** [comment]
@ernstae while I would love to have `orchestrator` support group replication, I don't have it on my table any time soon. Also, it would be quite the change and a major PR as I believe, unless we can come up with a nice hack to somehow isolate the group-replication logic from normal replication detection/failover logic.
