### ISSUE TITLE
inconsistent behaviour acknowledging failovers via GUI (Raft)

### ISSUE THREAD

**Issue by igroene** [openark/orchestrator#410]
Hi, I am testing auto-failover in a simple lab. I have 3 test servers in a master-slave topology with Orchestrator also installed on each one of those, and configured to use raft protocol:
```
mysql2 ----> mysql1
    |
    ---------> mysql3
```
So mysql2 is the master, and I've also validated mysql3 is the current Orchestrator leader

I'm seeing the following sequence of events:
1. I kill mysql on the current master
2. I observe orchestrator correctly fails over to a new node
3. I bring the old master back as a slave, orchestrator recognizes this properly
4. I kill the new master
5. Orchestrator does not promote a new master (as expected due to flap protection)

Contents of the log on Orchestrator leader:
```
Feb 13 17:38:50 mysql3 orchestrator[15286]: 2018-02-13 17:38:50 ERROR AttemptRecoveryRegistration: cluster mysql2:3306 has recently experienced a failover (of mysql2:3306) and is in active period. It will not be failed over again. You may acknowledge the failure on this cluster (-c ack-cluster-recoveries) or on mysql2:3306 (-c ack-instance-recoveries) to remove this blockage
Feb 13 17:38:50 mysql3 orchestrator[15286]: 2018-02-13 17:38:50 INFO topology_recovery: found an active or recent recovery on mysql2:3306. Will not issue another RecoverDeadMaster.
Feb 13 17:38:50 mysql3 orchestrator[15286]: 2018-02-13 17:38:50 ERROR 2018-02-13 17:38:50 ERROR AttemptRecoveryRegistration: cluster mysql2:3306 has recently experienced a failover (of mysql2:3306) and is in active period. It will not be failed over again. You may acknowledge the failure on this cluster (-c ack-cluster-recoveries) or on mysql2:3306 (-c ack-instance-recoveries) to remove this blockage
```
I've validated that manually running the ack-cluster-recoveries from command line allows the new failover to succeed, however the problem I see is there is no way (that I could find) to perform that operation via the GUI.
There is the following message displayed in the GUI of Orchestrator leader:
```
A DeadMaster on mysql2:3306 is blocked due to a previous recovery
```
But if I click on the "previous recovery" hyperlink (which takes me to http://mysql2:3000/web/audit-recovery/cluster/mysql2:3306), I don't see any un'acked recoveries, which is puzzling.
After digging a bit more I did find references to my un'acked recovery by looking at the audit-recovery page of either mysql1 or mysql2, but as those nodes are not the leader, one cannot ack the failover from there either.
Please let me know if I am missing something here.

Thanks

**Comment by shlomi-noach** [comment]
> however the problem I see is there is no way (that I could find) to perform that operation via the GUI.

In the GUI: the master box is painted black, the replicas are painted red, correct? Does tha master box not have a "recover" button? And if you click it, does it not open a drop down from where you can ask to failover?
That button _should_ override any unacknowledged recoveries. A human may always kick a recovery regardless of the history ; via that GUI button, via `/api/force-master-failover/...`, via `orchestrator-client -c force-master-failover ...`
If that button exists and clicking it doesn't do what you expect it to do, can you please paste the `orchestrator.log` entries around that time? (in particular, grep for `recover`)

> But if I click on the "previous recovery" hyperlink (which takes me to http://mysql2:3000/web/audit-recovery/cluster/mysql2:3306), I don't see any un'acked recoveries, which is puzzling.
After digging a bit more I did find references to my un'acked recovery by looking at the audit-recovery page of either mysql1 or mysql2

That rings a bell, I can look into it.

**Comment by igroene** [comment]
> In the GUI: the master box is painted black, the replicas are painted red, correct? 

yes that is correct. 
>Does tha master box not have a "recover" button? And if you click it, does it not open a drop down from where you can ask to failover?

Force failover using recover button did work as expected, thanks for that!

>>But if I click on the "previous recovery" hyperlink (which takes me to http://mysql2:3000/web/audit-recovery/cluster/mysql2:3306), I don't see any un'acked recoveries, which is puzzling.
After digging a bit more I did find references to my un'acked recovery by looking at the audit-recovery page of either mysql1 or mysql2

>That rings a bell, I can look into it.

Thank you, I look forward to hearing your comments on that matter. It would be nice to be able to ack the failover via the GUI.

**Comment by shlomi-noach** [comment]
> Thank you, I look forward to hearing your comments on that matter. It would be nice to be able to ack the failover via the GUI.

It strikes me (while I'm looking into the particular message), that you are unaware that you can acknowledge any recovery from: 

top-menu -> audit -> recovery -> list of recoveries -> click the red icon

<img width="180" alt="screen shot 2018-02-14 at 19 09 00" src="https://user-images.githubusercontent.com/2607934/36217571-7f37217c-11ba-11e8-87fa-fc35ff16621c.png">

I'm not surprised you didn't find this, I confess. It's _well hidden_ and I need to improve the UI.

**Comment by igroene** [comment]
Here's what I see on the leader, after doing
top-menu -> audit -> recovery -> list of recoveries
The red icon is not there for some reason:
![screen shot 2018-02-14 at 14 27 03](https://user-images.githubusercontent.com/9805809/36218476-374b68e0-1193-11e8-9c99-c4c0e8961c1a.png)

**Comment by shlomi-noach** [comment]
Aha! I understand. This is because there's a single recovery, so it's expanded, and there's no button there. Very good. Two issues to fix.

**Comment by shlomi-noach** [comment]
Wait wait, this recovery is acknowledged in your screenshot!

**Comment by igroene** [comment]
Yes you are right. What I am seeing is for some reason doing:
top-menu -> audit -> recovery -> list of recoveries

takes me to the previous recovery (that is already acked as you pointed out) rather than giving me the list of recoveries.

**Comment by igroene** [comment]
Hi Shlomi, first of all thanks for the ack button. 
I am still seeing some inconsistent behaviour while doing the acknowledge via gui. I follow these steps:
1. kill master and let failover happen
2. leave the recovery unacked
3. kill the new master
4. ack the old failover via GUI
5. verify the old failover is displayed as acked via GUI on audit -> recovery page
6. new failover doesn't take place, and log still shows
```
Feb 15 13:20:04 mysql1 orchestrator[15352]: 2018-02-15 13:20:04 ERROR 2018-02-15 13:20:04 ERROR AttemptRecoveryRegistration: instance mysql2:3306 has recently been promoted (by failover of mysql3:3306) and is in active period. It will not be failed over. You may acknowledge the failure on mysql3:3306 (-c ack-instance-recoveries) to remove this blockage
```
I am able to trigger the new failover by doing this via CLI:
```
orchestrator-client -c ack-cluster-recoveries -a testcluster -reason acknowledge
```
Please let me know if I am doing something wrong here

**Comment by shlomi-noach** [comment]
Hmm that is strange. First, I'd like to verify you're not running anything on the non-leader raft-node, since acking on a non-leader is meaningless.

Next, can you please reproduce, and between steps 5 & 6 issue and report back:
```
select * from topology_recovery where acknowledged=0 \G
select * from topology_recovery where in_active_period=1 \G
select hostname, port, cluster_name, alias from database_instance left join cluster_alias using (cluster_name);
```
And please indicate which servers you killed.

**Comment by shlomi-noach** [comment]
(and, if this is an issue, please open a new one)
