### ISSUE TITLE
Discover behavious from a non-leader node (raft)

### ISSUE THREAD

**Issue by igroene** [openark/orchestrator#412]
When clicking Clusters -> discover from a non-leader node GUI, Feeding any data into the hostname:port box and hitting submit button will cause the "processing" wheel icon to appear and basically hang in there forever.
Maybe show a message saying discovery has to run from leader node instead? 
Also would be nice to have some indication on the GUI saying if we are executing from a leader or not.

**Comment by shlomi-noach** [comment]
One answer and one good news for you:

#### answer

On a non-leader raft node you're supposed to see an icon of an _eye_, as in:

<img width="422" alt="screen shot 2018-02-14 at 19 05 28" src="https://user-images.githubusercontent.com/2607934/36217627-9e0c7b74-11ba-11e8-957c-6c154229fad3.png">

This indicates you're in read-only mode. And most operations are not permitted. Seems like I missed on disabling the discovery.

#### Good news

You're two days late for the party. This - https://github.com/github/orchestrator/pull/408 - will make non-leader nodes proxy your request to the leader node.

#### last question

How did you come to access the non-leader node, anyway? The recommendation is to use a proxy in front of all nodes to only direct traffic to the leader: https://github.com/github/orchestrator/blob/master/docs/raft.md#proxy

**Comment by igroene** [comment]
>On a non-leader raft node you're supposed to see an icon of an eye, as in:
This indicates you're in read-only mode. And most operations are not permitted. Seems like I missed on disabling the discovery.

Thank you for the heads up, I hadn't noticed this. Yes, the discovery is still allowed.

>You're two days late for the party. This - #408 - will make non-leader nodes proxy your request to the leader node.

That's great news!

>How did you come to access the non-leader node, anyway? 

This is a test setup I am running to try different things, so I don't have a proxy in front. I was testing the raft failover and the leader role switched over, and I didn't notice and tried to add a cluster through a node that wasn't leader anymore :)

**Comment by shlomi-noach** [comment]
> This is a test setup I am running to try different things, so I don't have a proxy in front. I was testing the raft failover and the leader role switched over, and I didn't notice and tried to add a cluster through a node that wasn't leader anymore :)

OK, so technically you were not following documentation and I should just tell you to please adhere to the docs:

> You should only send requests to the leader node.

**Comment by igroene** [comment]
Agreed! thanks

**Comment by shlomi-noach** [comment]
https://github.com/github/orchestrator/pull/408 is merged, so I'm closing this issue.

Expect a release early next week.
