### ISSUE TITLE
More issues with acknowledging recovery via GUI

### ISSUE THREAD

**Issue by igroene** [openark/orchestrator#417]
Hi Shlomi, I am testing the latest release and still seeing some issues with the GUI:
1. The hyperlink at https://github.com/github/orchestrator/blob/3608ae2702bfed6fd065960e0b2991c9cd290ffd/resources/public/js/clusters-analysis.js#L17
does not lead me to the unacked recovery. I got inconsistent results, as it some times it leads me to a past already acked recovery e.g.
![image](https://user-images.githubusercontent.com/9805809/36390534-26d39e86-1582-11e8-9b1f-f9cc76ac2ec7.png)

and sometimes just the list of past recoveries that are already acked:
![image](https://user-images.githubusercontent.com/9805809/36390541-2e0af19a-1582-11e8-9722-2966cc71b4fa.png)

Please note that if I manually go to  audit -> recovery -> DeadMaster (where we have the ? icon next to it) I can ack the recovery just fine using the new button, which leads me to:
2. The new acknowledge button has a typo. It is displayed as "Acknowlede"
Finally,
3. If I ack a recovery via GUI and don't provide a reason (leaving the comment box blank) then it doesn't do anything. IMO it would be better to raise an error or just complete with some pre-defined reason.

Thank you for your time

**Comment by shlomi-noach** [comment]
> 2. The new acknowledge button has a typo. It is displayed as "Acknowlede"

Ugh!!

> 3. If I ack a recovery via GUI and don't provide a reason (leaving the comment box blank) then it doesn't do anything. IMO it would be better to raise an error or just complete with some pre-defined reason.

Doh!!

> 1. ...
> does not lead me to the unacked recovery. I got inconsistent results, as it some times it leads me to a past already acked recovery e.g.

That... shouldn't happen, especially in light of recent changes. Can you please verify/answer the following:

a. Are you always querying the same server? Or maybe sometimes the leader and sometimes followers?
b. Is there any server restart in between your requests?
c. Is the new version deployed on all your raft nodes?
d. Perhaps your browser cache is preventing loading of updated code? Can you please force-refresh the page in your browser?

Last, and assuming everything makes sense in all of the above, there's the issue of the clusterName. See, the clusterName changes upon master failover! The new cluster is named after the new master. And this is why clusterAlias was invented for, to be a consistent logical name for a cluster that can change names. Let me look in that, too.

**Comment by igroene** [comment]
Answering your questions below:

>a. Are you always querying the same server? Or maybe sometimes the leader and sometimes followers?

I am always querying the same server (leader)
>b. Is there any server restart in between your requests?

I tried with and without restarting the former master and result is the same
>c. Is the new version deployed on all your raft nodes?

yes, test cluster was rebuilt with latest version from scratch
>d. Perhaps your browser cache is preventing loading of updated code? Can you please force-refresh the page in your browser?

Tried using a different browser and clearing cache but still see the same

**Comment by shlomi-noach** [comment]
Noting that the alert is not created in 

https://github.com/github/orchestrator/blob/3608ae2702bfed6fd065960e0b2991c9cd290ffd/resources/public/js/clusters-analysis.js#L17 

but in 

https://github.com/github/orchestrator/blob/b092c26961a6d623ea75b8a923e38eb7361172ab/resources/public/js/cluster.js#L1774

**Comment by shlomi-noach** [comment]
Fixed by https://github.com/github/orchestrator/pull/418

**Comment by shlomi-noach** [comment]
@igroene any chance you've managed to test https://github.com/github/orchestrator/pull/418?

**Comment by igroene** [comment]
Not yet, sorry. I will give it a try today and report back here

**Comment by shlomi-noach** [comment]
No worries. Please take your time. Thank you!

**Comment by igroene** [comment]
Hi Shlomi sorry about the delay. All fixes worked flawlessly! thank you very much

**Comment by shlomi-noach** [comment]
Released in [3.0.8](https://github.com/github/orchestrator/releases/latest)
