### ISSUE TITLE
Occasional fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by hmcgonig** [openark/orchestrator#434]
Hey 👋 I'm using orchestrator to monitor a large amount of mysql nodes, somewhere in the 1000 ballpark, and maybe between 1-2 times per day I see orchestrator crash with a `fatal error: concurrent map iteration and map write`.

The full goroutine dump is relatively gigantic, but I've thrown it in a gist (https://gist.github.com/hmcgonig/b5184cc495420dff3d811d3a85af5a95).

For version, I'm running a self-built version of v3.0.8 using 
```
  "BackendDB": "sqlite",
  "SQLite3DataFile": ":memory:",
  "RaftEnabled": true,
```

If there's anything else I should provide, let me know! Thanks!

edit: it might also be worth mentioning that all mysql nodes have an accompanying Vitess vttablet process which should be hitting the discovery API periodically.

**Comment by shlomi-noach** [comment]
Interesting. The bug has been there for _years_ and this is the first I see it. Seems to be unrelated to Vitess and more about the use of `go-cache`. Looking into.

**Comment by shlomi-noach** [comment]
Need to update to this: https://github.com/patrickmn/go-cache/commit/a2d8b56f0c21c5562c23717b6137ed6254ddc6d4#diff-56ffa6659747ba7a23d2b5597a4cda5d

**Comment by shlomi-noach** [comment]
#435 addresses this issue.

**Comment by hmcgonig** [comment]
Hah, excellent! Thanks for the speedy fix!

**Comment by hmcgonig** [comment]
I can confirm, this fixed everything. Thanks again 👍
