### ISSUE TITLE
Expose commands as hook arguments

### ISSUE THREAD

**Issue by choadrocker** [openark/orchestrator#441]
It would be great to be able to see if a promotion was the result of a graceful-master-takeover as opposed to an unplanned promotion, taking different actions in the hooks depending, like paging or no

Something like {{command}}?

**Comment by shlomi-noach** [comment]
Makes sense! Can do.

**Comment by choadrocker** [comment]
Thanks!

**Comment by shlomi-noach** [comment]
See https://github.com/github/orchestrator/pull/442
