### ISSUE TITLE
Are there any method to sync and apply diff relay log for replicas?

### ISSUE THREAD

**Issue by Xinglao4** [openark/orchestrator#448]
Hi, @shlomi-noach ;
     Now, I want to use the orchestrator in the product environment. But before this, I need to implement the process of syncing and applying diff relay log for replicas because of the requirement of complete data when the switch occured.
     I read http://code.openark.org/blog/mysql/whats-so-complicated-about-a-master-failover and know you had an attempt at doing the same for orchestrator but was unsatisfied with the results.
     So, I want to know what happened?
     And, If there are some information or code of this function that you can provide, I am so preciate!
     Thank you.

**Comment by shlomi-noach** [comment]
### what happened?

History: https://github.com/github/orchestrator/pull/42, https://github.com/github/orchestrator/pull/48

I set up the code to sync relay logs via remote SSH. Initial local tests were fine, but then running failover tests in production showed inconsistencies between the replicas. I couldn't figure out the reason to that even after a couple weeks of investigation and finally decided to back off. I also wasn't sure how to handle uncommitted transactions in the relay logs and felt this would take much longer than I anticipated.

### > requirement of complete data when the switch occured.

Relay log syncing _does not_ guarantee "complete data". It only guarantees line up of all the replicas. You may still have data loss. That is unless you use semi-sync ; in which case be prepared to have anti-dataloss, in the form of uncommitted transactions appearing in the relay logs. Should these be there? Unsure. But anti-dataloss is as good as dataloss.

**Comment by Xinglao4** [comment]
Thank you so much! I will learn the excellent code you write detailed.

> Relay log syncing does not guarantee "complete data". It only guarantees line up of all the replicas. You may still have data loss. That is unless you use semi-sync ; in which case be prepared to have anti-dataloss, in the form of uncommitted transactions appearing in the relay logs. Should these be there? Unsure. But anti-dataloss is as good as dataloss.

Yes, I know. But the semi-sync increases the time of commit and will change to asyn when time out.
I just want to try my best to avoid dataloss instead of completely unavailable in delay scenario or 
discarding the data directly.

**Comment by shlomi-noach** [comment]
While too early to describe in depth, we're looking at good results with using semi-sync + log-slave-updates to achieve minimal loss (of data + of servers) during failover

**Comment by Xinglao4** [comment]
I have find two problems and need to seek advice from you. @shlomi-noach 

1. I created a situation like this, by add "sleep 10m" in PostMasterFailoverProcesses of config, the leader of raft changes during recovery process.
In my understanding, the log in raft will be synced from leader to followers, so the process should be continue in new leader. But the result is not like expected.
I guess, these processes don't be sync to follower, and only the ultimately change(such as the value of KV and the changed cluster_alias) will be sync,  so the intermediate process can not be continued. Is that true?

2. When the process of RESET SLAVE of new master MySQL and CHANGE MASTER of new slave MySQL will be done? From my observation, this step executes after PreFailoverProcesses and before PostMasterFailoverProcesses, Is that true?

**Comment by shlomi-noach** [comment]
@Xinglao4 seeing that this doesn't have anything to do with relay logs sync, would you mind opening a new issue? Otherwise it's difficult to track and even more difficult to close issues.

**Comment by Xinglao4** [comment]
👌

**Comment by Xinglao4** [comment]
I have test the function of sync and apply diff relay log for replicas which I added. And find some problems: The process of recover-dead-master is done twice.
The detail of log is below:

> 2018-03-31 23:27:09 INFO auditType:begin-downtime instance:mysql-sredb03.yp:3306 cluster:mysql-sredb03.yp:3306 message:owner: mysql-sredb11.xh, reason: lost-in-recovery
> 2018-03-31 23:27:09 INFO topology_recovery: RecoverDeadMaster: 0 postponed functions
> 2018-03-31 23:27:09 ERROR ReadTopologyInstance(mysql-sredb07.yp:3306) show slave hosts: ReadTopologyInstance(mysql-sredb07.yp:3306) 'show slave hosts' returned row with <host,port>: <,3306>
> 2018-03-31 23:27:09 INFO topology_recovery: checking if should replace promoted replica with a better candidate
> 2018-03-31 23:27:09 INFO topology_recovery: + checking if promoted replica is the ideal candidate
> 2018-03-31 23:27:09 INFO topology_recovery: + searching for an ideal candidate
> 2018-03-31 23:27:09 INFO topology_recovery: + checking if promoted replica is an OK candidate
> 2018-03-31 23:27:09 INFO topology_recovery: + searching for a candidate
> 2018-03-31 23:27:09 INFO topology_recovery: + searching for a candidate
> 2018-03-31 23:27:09 INFO topology_recovery: + found no server to promote on top promoted replica
> 2018-03-31 23:27:09 INFO topology_recovery: promoted instance mysql-sredb07.yp:3306 requires no further action
> 2018-03-31 23:27:09 INFO topology_recovery: promoted replica: mysql-sredb07.yp:3306
> 2018-03-31 23:27:09 INFO auditType:recover-dead-master instance:mysql-sredb03.yp:3306 cluster:mysql-sredb03.yp:3306 message:promoted replica: mysql-sredb07.yp:3306
> 2018-03-31 23:27:09 WARNING executeCheckAndRecoverFunction: ignoring analysisEntry that has no action plan: FirstTierSlaveFailingToConnectToMaster; key: mysql-sredb07.yp:3306
> 2018-03-31 23:27:09 ERROR dial tcp 10.72.130.183:3306: getsockopt: connection refused

> 2018-03-31 23:27:19 INFO auditType:begin-downtime instance:mysql-sredb03.yp:3306 cluster:mysql-sredb03.yp:3306 message:owner: mysql-sredb11.xh, reason: lost-in-recovery
> 2018-03-31 23:27:19 INFO topology_recovery: RecoverDeadMaster: 0 postponed functions
> 2018-03-31 23:27:19 INFO topology_recovery: checking if should replace promoted replica with a better candidate
> 2018-03-31 23:27:19 INFO topology_recovery: + checking if promoted replica is the ideal candidate
> 2018-03-31 23:27:19 INFO topology_recovery: + searching for an ideal candidate
> 2018-03-31 23:27:19 INFO topology_recovery: + checking if promoted replica is an OK candidate
> 2018-03-31 23:27:19 INFO topology_recovery: + searching for a candidate
> 2018-03-31 23:27:19 INFO topology_recovery: + searching for a candidate
> 2018-03-31 23:27:19 INFO topology_recovery: + found no server to promote on top promoted replica
> 2018-03-31 23:27:19 INFO topology_recovery: promoted instance mysql-sredb07.yp:3306 requires no further action
> 2018-03-31 23:27:19 INFO topology_recovery: promoted replica: mysql-sredb07.yp:3306
> 2018-03-31 23:27:19 INFO auditType:recover-dead-master instance:mysql-sredb03.yp:3306 cluster:mysql-sredb03.yp:3306 message:promoted replica: mysql-sredb07.yp:3306

We can see the process of recover-dead-master is done twice in 10 seconds. I don't know why?

**Comment by Xinglao4** [comment]
I find the same cluster has two topologyRecovery, I think is unreasonable.
I see the condition of refusing RecoveryRegistration is that there are an active or recent recovery. But it's successful when there are an active recovery. Are there anything wrong?

**Comment by Xinglao4** [comment]
@shlomi-noach Can you please help me to solve this problem?

**Comment by shlomi-noach** [comment]
@Xinglao4 sorry for the delay, I was out of office.

I'm missing context here. What was the setup? Was that a planned failover? Unplanned? Manual? Automated?

Also I believe the above log is missing some important tasks. Surely there was some recovery related info preceeding the log you've pasted? I'd need that.

> I see the condition of refusing RecoveryRegistration is that there are an active or recent recovery. But it's successful when there are an active recovery. Are there anything wrong?

That's the way it should be.

What is your configuration for `RecoveryPeriodBlockSeconds` (or `RecoveryPeriodBlockMinutes`)?

**Comment by shlomi-noach** [comment]
Last, and once again, please make this its own issue. Please note this issue is closed, and should remain closed. It would be difficult for me to track down any further comments on this issue.

**Comment by Xinglao4** [comment]
> What is your configuration for RecoveryPeriodBlockSeconds (or RecoveryPeriodBlockMinutes)?

I think it's because of this, too. I change the value of RecoveryPeriodBlockSeconds from 10 to 3600, and the problem is solved.

> Please note this issue is closed, and should remain closed.

okok. I will close this issue. I ask in this issue again is because the problem occured in the process of trying to realize apply diff relay log for replicas :)

**Comment by shlomi-noach** [comment]
> I think it's because of this, too. I change the value of RecoveryPeriodBlockSeconds from 10 to 3600, and the problem is solved.

Hmmmm this gives me a way to reproduce the problem, but definitely it should not happen.
