### ISSUE TITLE
Force rediscovery of slave

### ISSUE THREAD

**Issue by s4mur4i** [openark/orchestrator#449]
Hello team,

I would have a question regarding orchestrator. I am using it in an environment and during provision of some slaves, orchestrator failed to connect since the required user was not present. After the failure, I am not seeing logs of orchestrator retrying to connect.
If I go to discover and point to slave orchestrator can connect to slave and adds it as a new cluster which is incorrect.

1. Is there a way to force rediscovery within a cluster?
2. How many times does orchestrator retry a connection to a host? When does it give up?
3. With a sqlite backend, where does orchestrator keep connection username and password? Looking at the tables, could not find it.

Thank you

**Comment by shlomi-noach** [comment]
Hi,

0. If orchestrator is unable to connect to some server `S0` the first time, it never creates a record in its backend database. It will not try again connecting to the host if unsuccessful the first time.

  - Unless the host is replicating from a known server `S1`, in which case `show processlist` or `show slave hosts` on `S1` will repeatedly make `orchestrator` attempt to re-discover `S0`. This is the basic premise of `orchestrator`: discover anything that is connected.

  - But if `S0` is connected nowhere, `orchestrator` will not try reconnecting.

1. Rediscovery within a cluster happens automatically, as explained above.

2. Depends:

  - If the server is connected to the topology graph, infinitely.
  - If the server is not connected to any other known hosts (no replication), and it was seen at least _once_, then `UnseenInstanceForgetHours` (see config)

3. Username & password are not written in the backend DB. They should be provided in configuration. See https://github.com/github/orchestrator/blob/master/docs/configuration-discovery-basic.md

**Comment by s4mur4i** [comment]
Hy,

Thank you for the information, it helped to solve the issue.
