### ISSUE TITLE
Some detail about recovery.

### ISSUE THREAD

**Issue by Xinglao4** [openark/orchestrator#451]
I have find two problems and need to seek advice from you. @shlomi-noach

I created a situation like this, by add "sleep 10m" in PostMasterFailoverProcesses of config, the leader of raft changes during recovery process.
In my understanding, the log in raft will be synced from leader to followers, so the process should be continue in new leader. But the result is not like expected.
I guess, these processes don't be sync to follower, and only the ultimately change(such as the value of KV and the changed cluster_alias) will be sync, so the intermediate process can not be continued. Is that true?

When the process of RESET SLAVE of new master MySQL and CHANGE MASTER of new slave MySQL will be done? From my observation, this step executes after PreFailoverProcesses and before PostMasterFailoverProcesses, Is that true?

**Comment by shlomi-noach** [comment]
> I guess, these processes don't be sync to follower, and only the ultimately change(such as the value of KV and the changed cluster_alias) will be sync, so the intermediate process can not be continued. Is that true?

You are correct that invocation of external hooks are not transferred to the followers. If the leader fails _before_ completing the recovery, or, to clarify, before the topology is healed, then the follower will pick up where things were left and will run its own recovery. But once the topology is healed you are correct and there's a gray zone. I'll try and think more about this.

> When the process of RESET SLAVE of new master MySQL and CHANGE MASTER of new slave MySQL will be done? From my observation, this step executes after PreFailoverProcesses and before PostMasterFailoverProcesses, Is that true?

Correct. If you don't like it, you can `"ApplyMySQLPromotionAfterMasterFailover": false,` and do it on your own in your post failover scripts.

**Comment by Xinglao4** [comment]
If I set "ApplyMySQLPromotionAfterMasterFailover": false, it only detects the DeadMaster, and the following steps, such as select the new master, reset slave, change master, update information, etc, are all needed to do by me. Is it?

**Comment by shlomi-noach** [comment]
> it only detects the DeadMaster, and the following steps, such as select the new master, reset slave, change master, update information, etc, are all needed to do by me. Is it?

No. Please see https://github.com/github/orchestrator/blob/master/docs/configuration-recovery.md#promotion-actions

**Comment by shlomi-noach** [comment]
I should clarify. You asked about `RESET SLAVE` of new master and `CHANGE MASTER`. These are two very different operations.

The `CHANGE MASTER` is part of the very basic recovery mechanism. If you don't want that, you don't want  recovery at all. The `RESET MASTER` part is optional.

**Comment by Xinglao4** [comment]
ok, I understand.
The ApplyMySQLPromotionAfterMasterFailover is only affects the step of RESET SLAVE and SET READ ONLY = 0.

**Comment by Xinglao4** [comment]
The step of RESET SLAVE and CHANGE MASTER which will be done earlier if "ApplyMySQLPromotionAfterMasterFailover": true?

**Comment by shlomi-noach** [comment]
Can this issue be closed?

**Comment by Xinglao4** [comment]
👌of course!
