### ISSUE TITLE
provide a way to start slave on former master after graceful master switch

### ISSUE THREAD

**Issue by igroene** [openark/orchestrator#453]
`PostMasterFailoverProcesses` hook fires too early for putting start slave there. Orchestrator still hasn't done change master as part of topology recover.
Maybe add a new hook that fires at the end of topology recovery? or give a parameter that says something like StartSlaveAfterGracefulMasterSwitch: true/false

**Comment by shlomi-noach** [comment]
> PostMasterFailoverProcesses hook fires too early for putting start slave there. Orchestrator still hasn't done change master as part of topology recover.

Oh dear, the consequence of optimization... Let me look into it.

**Comment by shlomi-noach** [comment]
I see four different approaches:

- Add a `PostGracefulTakeoverProcesses` that will only fire after everything's done
- Add global config variable in the form of `StartReplicationOnDemotedMasterAfterGracefulTakeover`
- Send a flag to the specific invocation. e.g. `orchestrator-client -c graceful-master-takeover -start-replication-afterwards ...`
- Add a new command, e.g. `orchestrator-client -c graceful-master-takeover-and-start-replication-afterwards`

I'm mostly unhappy with:
- A global variable seems to me to be in too wide scope.
- A hint to the operation can be done from command line, but what about a web operation?
- Same for a new command.

I'm reasonably happy with `PostGracefulTakeoverProcesses`, which is the symmetrical counterpart for  `PreGracefulTakeoverProcesses`.

**Comment by shlomi-noach** [comment]
Sorry, fifth approach: make sure `PostMasterFailoverProcesses` runs _after_ the failover really completes. I would like to pursue this first.

All thoughts are welcome.

**Comment by shlomi-noach** [comment]
Strike that. `PostGracefulTakeoverProcesses` is the way forward.
