### ISSUE TITLE
Orchestrator forgets cluster_name if master instance is down

### ISSUE THREAD

**Issue by eminugurkenar** [openark/orchestrator#459]
Hi, 

I am testing failover feature of orchestrator , but i experienced a problem. 
If master is down for a while (4-5 minutes) , orchestrator forgets cluster_name so it sends hostname of the instance to post-failover script, instead of sending cluster_name.

`DetectClusterAliasQuery: "select ifnull(max(cluster_name), '') as cluster_alias from meta.cluster where anchor=1",`

Is there any way to say do not forget cluster_name or if the master is down ask cluster_name to slaves?

**Comment by eminugurkenar** [comment]
I read this issue https://github.com/github/orchestrator/issues/391 and your comment says,  

> Once it's set, and until told otherwise, that's the alias. MySQL can go down and still orchestrator will associate it with that alias.

If it is the case , somehow it sends ClusterName as failureClusterAlias.

**Comment by shlomi-noach** [comment]
Somewhat, but not strictly, related: https://github.com/github/orchestrator/issues/424
