### ISSUE TITLE
Orchestrator update the KV Store with the lastest mysql master discovered

### ISSUE THREAD

**Issue by jsecchiero** [openark/orchestrator#483]
Hi there!

orchestrator KV updates seems are not respecting the web interface cluster representation.
These are the step for reproduce:
1) i add a cluster with three nodes (1 master mysql-0 and 2 slaves mysql-1, mysql-2) just adding the master from the discovery (orchestrator automatically detect all the tree)
2) i create a new node (mysql-3) separated from the cluster before and add it with the discovery.
The problem here is that now in consul KV store i have the standalone node as a master and this is not what i expect to have because in the web interface i still see the cluster with three nodes.

```
curl http://1.1.1.1:8500/v1/kv/mysql/master/mysql/hostname
[{"LockIndex":0,"Key":"mysql/master/mysql/hostname","Flags":0,"Value":"bXlzcWwtMy5ub2RlLmRhdGFjZW50ZXIuY29uc3VsCg==","CreateIndex":130998,"ModifyIndex":150282}]
```

Imho these are the parameters that can trigger this (if you want the complete conf is below):
```
"ClusterNameToAlias": {".*": "mysql"},
"KVClusterMasterPrefix": "mysql/master",
"ConsulAddress": "1.1.1.1:8500"
```

If i do the api call `api/submit-masters-to-kv-stores` i see all the master detected, but only the last is on consul (mysql-3).
```
curl http://1.1.1.2:3000/api/submit-masters-to-kv-stores
{"Code":"OK","Message":"Submitted 10 masters","Details":[{"Key":"mysql/master/mysql","Value":"mysql-0.node.datacenter.consul:3306"},{"Key":"mysql/master/mysql/hostname","Value":"mysql-0.node.datacenter.consul"},{"Key":"mysql/master/mysql/port","Value":"3306"},{"Key":"mysql/master/mysql/ipv4","Value":"192.168.0.210"},{"Key":"mysql/master/mysql/ipv6","Value":""},{"Key":"mysql/master/mysql","Value":"mysql-3.node.datacenter.consul:3306"},{"Key":"mysql/master/mysql/hostname","Value":"mysql-3.node.datacenter.consul"},{"Key":"mysql/master/mysql/port","Value":"3306"},{"Key":"mysql/master/mysql/ipv4","Value":"192.168.0.211"},{"Key":"mysql/master/mysql/ipv6","Value":""}]}
```

Please let me know if I'm misinterpreting the orchestrator behavior.
Any advice is appreciated.
Thanks
Jacopo

p.s. the complete conf:
```
{
  "#": "-----",
  "#": "Orchestrator General Options",
  "#": "-----",
  "Debug": false,
  "ListenAddress": ":3000",
  "ListenSocket": "",
  "MySQLConnectTimeoutSeconds": 2,
  "ReasonableMaintenanceReplicationLagSeconds": 20,
  "SkipMaxScaleCheck": true,
  "StatusEndpoint": "/api/status",
  "StatusSimpleHealth": true,
  "URLPrefix": "",
  "#": "-----",
  "#": "Orchestrator Database Options",
  "#": "-----",
  "MySQLOrchestratorDatabase": "orchestrator",
  "MySQLOrchestratorHost": "127.0.0.1",
  "MySQLOrchestratorPort": 3306,
  "MySQLReadTimeoutSeconds": 30,
  "PanicIfDifferentDatabaseDeploy": false,
  "SkipOrchestratorDatabaseUpdate": false,
  "#": "-----",
  "#": "Orchestrator Service Discovery Options",
  "#": "-----",
  "ClusterNameToAlias": {".*": "mysql"},
  "ConsulAddress": "192.168.0.73:8500",
  "DatacenterPattern": "",
  "DefaultInstancePort": 3306,
  "DetectClusterAliasQuery": "",
  "DetectClusterDomainQuery": "",
  "DetectDatacenterQuery": "",
  "DetectPhysicalEnvironmentQuery": "",
  "DiscoverByShowSlaveHosts": false,
  "HostnameResolveMethod": "none",
  "InstancePollSeconds": 5,
  "KVClusterMasterPrefix": "mysql/master",
  "MySQLDiscoveryReadTimeoutSeconds": 10,
  "MySQLHostnameResolveMethod": "none",
  "PhysicalEnvironmentPattern": "",
  "RejectHostnameResolvePattern": "",
  "UnseenInstanceForgetHours": 240,
  "#": "-----",
  "#": "Orchestrator MySQL Topology Options",
  "#": "-----",
  "DetectSemiSyncEnforcedQuery": "",
  "MySQLTopologyReadTimeoutSeconds": 600,
  "ReasonableReplicationLagSeconds": 10,
  "ReplicationLagQuery": "",
  "#": "-----",
  "#": "Orchestrator Pseudo GTID Options",
  "#": "-----",
  "DetectPseudoGTIDQuery": "",
  "PseudoGTIDMonotonicHint": "asc:",
  "PseudoGTIDPattern": "",
  "PseudoGTIDPatternIsFixedSubstring": false,
  "#": "-----",
  "#": "Orchestrator Recovery Options",
  "#": "-----",
  "ApplyMySQLPromotionAfterMasterFailover": true,
  "DetachLostReplicasAfterMasterFailover": true,
  "FailMasterPromotionIfSQLThreadNotUpToDate": true,
  "FailureDetectionPeriodBlockMinutes": 1,
  "MasterFailoverLostInstancesDowntimeMinutes": 1,
  "RecoverIntermediateMasterClusterFilters": ["*"],
  "RecoverMasterClusterFilters": ["*"],
  "RecoveryIgnoreHostnameFilters": [],
  "RecoveryPeriodBlockSeconds": 30,
  "RecoveryPollSeconds": 2,
  "#": "-----",
  "#": "Orchestrator Recovery Hooks",
  "#": "-----",
  "IntermediateMasterFailoverProcesses": [],
  "OnFailureDetectionProcesses": [],
  "PostFailoverProcesses": [],
  "PostMasterFailoverProcesses": [],
  "PostUnsuccessfulFailoverProcesses": [],
  "PreFailoverProcesses": [],
  "#": "-----",
  "#": "Orchestrator Security Options",
  "#": "-----",
  "AuthUserHeader": "",
  "AuthenticationMethod": "",
  "HTTPAuthPassword": "",
  "HTTPAuthUser": "",
  "PowerAuthUsers": ["*"],
  "ReadOnly": false,
  "UseSuperReadOnly": true,
  "#": "-----",
  "#": "Orchestrator Server -> Client Security Options",
  "#": "-----",
  "MySQLTopologyCredentialsConfigFile": "/etc/mysql/orchestrator-topology.cnf",
  "MySQLTopologySSLCAFile": "",
  "MySQLTopologySSLCertFile": "",
  "MySQLTopologySSLPrivateKeyFile": "",
  "MySQLTopologySSLSkipVerify": false,
  "MySQLTopologyUseMutualTLS": false,
  "#": "-----",
  "#": "Orchestrator Server -> Orchestrator DB Security Options",
  "#": "-----",
  "MySQLOrchestratorCredentialsConfigFile": "/etc/mysql/orchestrator-backend.cnf",
  "MySQLOrchestratorSSLCAFile": "",
  "MySQLOrchestratorSSLCertFile": "",
  "MySQLOrchestratorSSLPrivateKeyFile": "",
  "MySQLOrchestratorSSLSkipVerify": false,
  "MySQLOrchestratorUseMutualTLS": false,
  "#": "-----",
  "#": "Orchestrator Logging Options",
  "#": "-----",
  "AuditLogFile": "","AuditToSyslog": false,"EnableSyslog": false
}
```

**Comment by shlomi-noach** [comment]
I'm unsure if I understand the question correctly, so I'll give two answers based on the two variations that I perceive:

### If you're asking why only the master and not the replicas:

KV store should only store masters. It is used for master service discovery, not for general service discovery. If you have a master and two replicas, then only the master should show up.

### If you're asking why only one master and not 10 masters

You've made a hard coded mapping:
```
"ClusterNameToAlias": {".*": "mysql"},
```
which maps _all clusters to the same name_, namely `mysql`.

I wish to discourage you from using `ClusterNameToAlias` in the first place. I urge you to read the docs: https://github.com/github/orchestrator/blob/master/docs/configuration-discovery-classifying.md#cluster-alias

What you want is a different alias for different clusters. This is something you must do. Otherwise `orchestrator` doesn't know how you call your clusters.

**Comment by jsecchiero** [comment]
Hi there,

thanks for the reply.

What i'm asking is essentially why is not used ClusterByAlias, like what the web gui is doing apparently,  but instead is used the latest (discovered?) cluster to register the master to the KV. Seems ClusterByAlias have some logic behind and give priority to the cluster with more nodes.
What i'm noticing from your reply is that i should not use ClusterNameToAlias (.*) and setup the alias myself and it's ok for me so my question for me is answered but not sure if it's enough for my objective.

I'm trying to automatically startup a new mysql cluster and orchestrator toghether. My first try was successful with the use of a _mysql boostrap node_ that register himself to the orchestrator and setup a cluster name. Other nodes wait a master from KV store before sync from it and start a replica.

The second try, is where i'm failing, i'm trying to simplify more the process and not using a _mysql boostrap node_, so every node is equal and they all register to orchestrator using the same cluster alias. Because is possible to have multiple clusters with the same alias is not possible to me to create a consistent way to do that. There is anyway to accomplish something similar?

Thanks
Jacopo

**Comment by shlomi-noach** [comment]
I confess I'm confused and I'm not sure what the purpose of your question is.

> The second try, is where i'm failing, i'm trying to simplify more the process and not using a mysql boostrap node, 

What's a "mysql bootstrap node"?

> Because is possible to have multiple clusters with the same alias 

You should have different aliases for different clusters. Do not use the same alias for all clusters.

**Comment by jsecchiero** [comment]
> I confess I'm confused and I'm not sure what the purpose of your question is.

I'm trying to automatically startup a new mysql cluster and orchestrator toghether.

> What's a "mysql bootstrap node"?

it's just a role in the automation process, i'll try to better explain the first attempt (where I am currently succeeding). There are two roles here, the bootstrap node and the slave nodes (it's not the perfect role name but it's just for differentiate).
The main role of the bootstrap node here is to _bootstrap_ the cluster, so:

1. is the first to start 
2. create a mysql meta table and write here a cluster name
3. say to orchestrator to discover the bootstrap node
4. say to orchestrator to update the kv with the new master

Because orchestrator in this scenario is configured with DetectClusterAliasQuery, it use just this for the cluster alias name.

Instead the slaves nodes:

1. wait until a master is discovered (using consul kv)
2. start a full sync procedure from master

At this point orchestrator automatically put the slave node/s into the cluster.
When all is completed the bootstrap node can be deleted and should never be used in future (becouse can create duplicated cluster name), instead is possible to increase/decrease the number of nodes just reusing the slave node role.

Because this workflow require more manual work and the the fact that two different role exist can lead in confusion/error to the user, i'd like to provide a more simple workflow using just a role. So in the second attempt (where I am currently failing), there is no a bootstrap-node/slave node difference.
This is an example of the workflow:

1. create a mysql meta table and write here a cluster name
2. say to orchestrator to discover the node
3. say to orchestrator to update the kv with the new master
4. try to figure out if the node itself is master, if not start a sync procedure from it

as obvious above, in step 2, if use multiple node is possible to find more cluster with the same alias so the process is inconsistent and can't be used.

> You should have different aliases for different clusters. Do not use the same alias for all clusters.

This is just an use case, but imagine if a user wrongly add a master node with out-of-date data but with the same cluster alias name defined. KV are updated with the new out-of-date master and this can be dangerous in production.
Is correct that orchestrator can accept multiple alias with the same name?

Thanks
Jacopo

**Comment by shlomi-noach** [comment]
I'm really sorry, but I still can't follow the logic. I may be jetlagged, but:

> The main role of the bootstrap node here is to bootstrap the cluster, so:
> say to orchestrator to update the kv with the new master

Is the bootstrap node the master?

Because if so, then:

> At this point orchestrator automatically put the slave node/s into the cluster.
> When all is completed the bootstrap node can be deleted and should never be used in future 

So you asked `orchestrator` to list it as `master`, and then you delete it?

I'm getting the feeling something is broken with the logic. I just don't understand what this process stands for. If you need to start up a cluster + orchestrator, there is no need for a bootstrap node.

Perhaps if you can describe what's wrong with just setting up your normal cluster and letting `orchestrator` detect it?

**Comment by jsecchiero** [comment]
> Is the bootstrap node the master?
in the first phase, yes! but it's transitory, it's just for cluster initialization so later can be deleted.

> So you asked orchestrator to list it as master, and then you delete it?
> 
> I'm getting the feeling something is broken with the logic. I just don't understand what this process stands for. If you need to start up a cluster + orchestrator, there is no need for a bootstrap node.
> 

i'm using terraform modules (with cloud-init scripts behind) and this one is an example:
```
module "mysql-orchestrator" {
  source = "mysql-orchestrator"
  name = "mm"
  bootstrap = "true"
  quantity = "3"
}
```
creates this:
![image](https://user-images.githubusercontent.com/17151394/39468794-2713118e-4d35-11e8-9248-baafc4e9f015.png)

at this point i can set `bootstrap = "false"` because the node is just one more then desired (quantity is 3 but nodes are 4) and now i have this:
![image](https://user-images.githubusercontent.com/17151394/39468898-a8a04398-4d35-11e8-9d14-f3998c268282.png)

Later i can increase/decrease the nodes just using `quantity` and this is working perfectly to me.

> Perhaps if you can describe what's wrong with just setting up your normal cluster and letting orchestrator detect it?

maybe the confusion is related on what tool i'm using for doing this, because all instances starts together and cloud-init script go in parallel on each instance.

If are needed more examples let me know.

Thanks
Jacopo

**Comment by jsecchiero** [comment]
sorry i realized that the first ss is after some modification (bootstrap node is not master), i'll re-upload this

**Comment by shlomi-noach** [comment]
Thank you for all the details, and I'm sorry I still do not understand what the bootstrap node is needed for. I do not know what `bootstrap = "false"` stands for. I do not understand what is wrong with my original suggestions. I do not know what the cloud-init scripts are and what relevance there is to them running parallel.

I think you're trying to ask me to solve a system which I am unfamiliar with. 

I'm trying to explain what a solution is, and it shouldn't matter that you're bootstrapping an entire new cluster plus orchestrator together.

I'm sorry that I can't help you further.

**Comment by jsecchiero** [comment]
of course the use case is not _very_ related to the tool and go deeper to this is not very useful. I'm not asking to you to solve my scripts, i'm just interested in what is behind some decision that i'm not fully understand actually.

> imagine if a user wrongly add a master node with out-of-date data but with the same cluster alias name defined. KV are updated with the new out-of-date master and this can be dangerous in production.
> Is correct that orchestrator can accept multiple alias with the same name?

Thanks
Jacopo

**Comment by shlomi-noach** [comment]
> imagine if a user wrongly add a master node with out-of-date data but with the same cluster alias name defined. KV are updated with the new out-of-date master and this can be dangerous in production.

I see what you're saying, but I'm unsure what would be a solution. See, in the even of master failure, the cluster could split. One would be the "survived" cluster and the other would be the "disconnected" cluster. But both belong with the same logical cluster (i.e. would still have same cluster alias).

So it is wrong for `orchestrator` to completely disallow having two clusters with the same alias.

With proper automation I think the risk that your setup will set same alias to completely different clusters is low.


> Is correct that orchestrator can accept multiple alias with the same name?

No, a cluster can only have one single alias.

**Comment by jsecchiero** [comment]
seems a good reason to do that.
sorry for the long tedious thread i was just curios :)
Thanks
Jacopo

**Comment by shlomi-noach** [comment]
Thank you
