### ISSUE TITLE
Set Old Master as Read Only in Replication Topology

### ISSUE THREAD

**Issue by umeshvuggina** [openark/orchestrator#494]
Hi,

We are using Mysql Master - Slave and Master-Master Setups for different Applications. Does Orchestrator support both? We started testing on Master - Slave pair and Failover is working fine as expected with Orchestrator i.e. its resetting slave and turning off read only to promote it as Master.

The challenge we are facing is when Old Master service comes back and its taking requests as well (We are using VIP). Even though we are disabling Old Master under VIP, as an extra caution, we would like to enforce Old Master as read-only once it starts. We are keeping only two nodes in one Replication Topology.

Thanks,
-Umesh

**Comment by shlomi-noach** [comment]
> Old Master service comes back and its taking requests

Please see http://code.openark.org/blog/mysql/mysql-master-discovery-methods-part-2-vip-dns

It depends on how the old master "went away". Did it crash? Best suggestion is to hard code `read_only=1` in `my.cnf`.
Did it get network isolated? Then `orchestrator` can't reach it and ask it to turn `read_only=1`.

`orchestrator` does _try_ to `set global read_only=1` on old master:

https://github.com/github/orchestrator/blob/2f0f2a71c4b7684088507608b949ef1eef7c7051/go/logic/topology_recovery.go#L780

**Comment by umeshvuggina** [comment]
Thanks Shlomi. Yes we are testing with Crashing Old Master. Its working as expected after setting read_only=1 in my.cnf. 

When the Crashed Old Master is up after an hour or so, how can we Automate replication back with Current Master.  We have replication setup script (which takes dump and restores with Master Position), but trying to hook it in Orchestrator to avoid Manual Intervention. i.e. Automating the Addition of Node back to topology once Node is up and set-up replication

Thanks in Advance !!

**Comment by shlomi-noach** [comment]
> but trying to hook it in Orchestrator to avoid Manual Intervention. i.e. Automating the Addition of Node back to topology once Node is up and set-up replication

At this time there's nothing in `orchestrator` to do that for you, and no particular hook...
