### ISSUE TITLE
KV Stores don't seem to be initialized before it's used

### ISSUE THREAD

**Issue by TylerLubeck** [openark/orchestrator#497]
I've been assisting in setting up our orchestrator <-> consul integration and nothing we do can get orchestrator to set values in consul, either automatically or via the manual `./orc-cli -config ./orchestrator.conf.json -c submit-masters-to-kv-stores`. 

We have `ConsulAddress` in our config file, pointed at the proper place:
```
$ cat orchestrator.conf.json | grep ConsulAddress
  "ConsulAddress": "127.0.0.1:8500",
```

It's _very_ possible we're just doing something wrong, but I've been poking around in the code a bit and it looks like the KV Stores object isn't necessarily initialized by the time we go to use it:

Taking a look at `registerCliCommand("submit-masters-to-kv-stores" ...)`:
https://github.com/github/orchestrator/blob/master/go/app/cli.go#L1194-L1211

I added the following on line 1203, just before the pairs are put in the KV store:

```go
fmt.Errorf("Number of stores: %d", len(kv.GetKVStores())
for store := range kv.GetKVStores() { /* public version of kv.getKVStores, added for this test */
   fmt.Errorf("Store: %v", store)
}
```

And there are 0 stores registered at this point.

I modified kv.go some more to ensure that InitKVStores is always called before getKVStores, and that seems to have resolved our problem. I'm not sure that's really the solution though - have y'all seen anything like this before, or have any suggestions on where to look next? I've opened a PR with the code change as well, just in case.

/cc @choadrocker

**Comment by shlomi-noach** [comment]
Thank you. Indeed KV stored were neglected to initialize in CLI mode. See https://github.com/github/orchestrator/pull/499

**Comment by TylerLubeck** [comment]
Thanks @shlomi-noach !
