### ISSUE TITLE
orchestrator-client fails silently when pushing Consul keys

### ISSUE THREAD

**Issue by ghost** [openark/orchestrator#503]
Howdy,

LTNS - hope things are well! Love what's going on with the project -- I'm evaluating using it for small-cluster scenarios at my current shop (orchestrator/raft + SQLite). Seems ideal when combined with semisynchronous replication.

After installing a fresh 3-node setup and then realizing that you support Consul (awesome), I tried configuring Orchestrator to talk to Consul and then I ran the expected:

 orchestrator-client -c submit-masters-to-kv-stores

This resulted in the expected list of keys and data (I had used Discover on a slave, nice!) -- but it actually failed silently (i.e. didn't populate config in Consul).

Turned out I had the wrong IPs (127.0.0.1 instead of the local machine IP -- duh, typical.), so changing that solved it.

Thanks again and keep up the great work, cheers!

**Comment by shlomi-noach** [comment]
Hi @rbastic , thank you for this report. Confirmed, the error does not propagate back. I'll explain why this happens (not justifying):

KV writes are commands that go through the raft protocol, assuming `raft` is enabled, as is the case with your setup.
With the `raft` protocol, you submit a command to `raft`, and then it gets invokes asynchronously. This is why the response gets lost.
There is actually a way to sync until the leader has executed the command, and capture the return code (or `error`). I agree this is desired. I'll look into it, it implies more than this KV change, and has more impact on the overall `raft` handling design.

**Comment by shlomi-noach** [comment]
Actually it was a relatively small change without much impact. See #507

**Comment by ghost** [comment]
Awesome! Thanks. I'll give this another shot soon.

**Comment by shlomi-noach** [comment]
released in https://github.com/github/orchestrator/releases/tag/v3.0.11
