### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by ghost** [openark/orchestrator#504]
"Acknodledged recovery"

cd ~/go-src/src/github.com/github.com/orchestrator
$ grep -R Acknodledged
go/http/api.go:	Respond(r, &APIResponse{Code: OK, Message: fmt.Sprintf("Acknodledged cluster recoveries"), Details: clusterName})
go/http/api.go:	Respond(r, &APIResponse{Code: OK, Message: fmt.Sprintf("Acknodledged instance recoveries"), Details: instanceKey})
go/http/api.go:	Respond(r, &APIResponse{Code: OK, Message: fmt.Sprintf("Acknodledged recovery"), Details: idParam})
go/http/api.go:	Respond(r, &APIResponse{Code: OK, Message: fmt.Sprintf("Acknodledged all recoveries"), Details: comment})

Wanted to be helpful so here's two commands to fix it:
  grep -lR Acknodledged | xargs -n 1 perl -pi.bak -e 's/Acknodledged/Acknowledged/g'
  # can git status/git diff to confirm
  git clean -dfx

Or I can submit a PR if you prefer :) 

Cheers,

**Comment by shlomi-noach** [comment]
Thank you!

**Comment by ghost** [comment]
No, thank you :-) I will likely have a ton of (hopefully-not-too-annoying) questions soon :)

Great job, keep up the good work!
