### ISSUE TITLE
FlushNontrivialResolveCacheToDatabase error messages

### ISSUE THREAD

**Issue by cezmunsta** [openark/orchestrator#515]
Currently the code for [`FlushNontrivialResolveCacheToDatabase`](https://github.com/github/orchestrator/blob/master/go/inst/resolve.go#L213) always emits an error message when passing through the following code path when `HostnameResolveMethod` is anything other than `none`:
```
go/inst/resolve.go
212:func FlushNontrivialResolveCacheToDatabase() error {
214:            return log.Errorf("FlushNontrivialResolveCacheToDatabase() called, but HostnameResolveMethod is %+v", config.Config.HostnameResolveMethod)

go/logic/orchestrator.go
499:                                    go inst.FlushNontrivialResolveCacheToDatabase()
```
e.g.
`ERROR FlushNontrivialResolveCacheToDatabase() called, but HostnameResolveMethod is cname`

This appears once per minute in the log.

The function is always called and so regardless of which condition would be best to apply to this check, the message itself seems like it should be restricted to a specific log level, such as running in verbose or debug states, rather than being an error.

**Comment by shlomi-noach** [comment]
Agreed the error message should not be there. Let me dig into this, it's one of the older parts of the code and there was some reason for putting the logic there, I'm sure. I think.

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/github/orchestrator/pull/547
