### ISSUE TITLE
Provide ubuntu bionic packages

### ISSUE THREAD

**Issue by stefnats** [openark/orchestrator#530]
Hi,

i recently upgraded to ubuntu bionic and it would be neat if you could provide bionic packages, especially over packagecloud.io

**Comment by shlomi-noach** [comment]
Thank you, will do (starting next release)

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/github/orchestrator/pull/546

**Comment by stefnats** [comment]
As i see, with the new release, the packages are now provided for bionic :) Thanks!
