### ISSUE TITLE
FailMasterPromotionIfSQLThreadNotUpToDate not working in coMaster setup

### ISSUE THREAD

**Issue by samiahlroos** [openark/orchestrator#534]
I've been trying to use `"FailMasterPromotionIfSQLThreadNotUpToDate": true` and wondering why it is not working like I expected.

It looks like that config option is only checked in the `checkAndRecoverDeadMaster` function, and not in `checkAndRecoverDeadCoMaster`. We use coMaster replication, so mystery solved, I think. 

I'd be happy to open a PR adding check for `FailMasterPromotionIfSQLThreadNotUpToDate` to `checkAndRecoverDeadCoMaster` function, but before doing so: is there a reason for this behavior and I'm just not seeing it?

**Comment by shlomi-noach** [comment]
There is no intended reason. I'm happy for a PR.
