### ISSUE TITLE
Question about orchestrator package for debian/stretch

### ISSUE THREAD

**Issue by yotles** [openark/orchestrator#536]
Hello.

I have tried to use https://packagecloud.io/github/orchestrator for installing orhestrator on Debian 9.3 but there no candidates. It's only for debian/jessie and debian/wheezy. Do you plan to prepare a package for debian/stretch?

Thanks.

**Comment by shlomi-noach** [comment]
Thank you: addressed by https://github.com/github/orchestrator/pull/546
