### ISSUE TITLE
GracefulMasterTakeover should fail right away if designated master is in PromotionIgnoreHostnameFilters list

### ISSUE THREAD

**Issue by dougfales** [openark/orchestrator#569]
We are using the new `GracefulMasterTakeover` stuff since upgrdaing to 3.0.11. We have been very happy with this feature overall, but there is one small suggestion we came up with while testing in our staging environment: when a designated master is being explicitly ignored in `PromotionIgnoreHostnameFilters`, orchestrator should fail immediately. 

In the current flow of [`GracefulMasterTakeover`](https://github.com/github/orchestrator/blob/master/go/logic/topology_recovery.go#L1645), if you try to promote a server that matches the `PromotionIgnoreHostnameFilters`, the end result is a change to your topology and a non-writable master.  Orchestrator doesn't check the `IsBannedFromBeingCandidateReplica` until after it has regrouped replicas under the designated master and started the recovery.

Here's [a small change](https://github.com/dougfales/orchestrator/commit/b27bff18f18ac5d6f921a945ab2ae963af5b9e9b) which would have worked for us. If you think this is a good idea, I'd be happy to open a PR. And if you want more comprehensive checks, such as the binlog format checking in `chooseCandidateReplica`, I'm happy to help with that as well.

**Comment by dougfales** [comment]
cc @zmoazeni in case you have anything to add here?

**Comment by zmoazeni** [comment]
I worked with @dougfales on this. And I agree it burned us much longer than it should have until we realized that we had set the `PromotionIgnoreHostnameFilters` long before.

I do want to mention/expand on a couple things.

## The biggest issue is that the writer/master is left readonly with no indication why

This is what caught us by surprise. Luckily we weren't in a production environment, but it certainly instilled the fear of Science in us if we had been. Doug and I traced the code and it looks like the code marks the existing writer/master readonly prior to doing any replication `CHANGE MASTER TO..` switches, but in the scenario where we're trying to replace it with a prohibited server, we were just left in a real funky state.

I understand why the code is written the way it is. I'm not sure if it makes sense to flip the writer/master back to writable in the event it can't promote another server. However, that's where Doug's suggestion above comes in. If the server we're trying to promote is banned in some form, it would be wonderful to fail fast and verbosely to avoid kicking off all the steps.

## UI suggestion

I'll make one more suggestion as part of this discussion. It would be amazing to see which hosts are not available as candidates in the web UI visually (and perhaps even mention what setting barred it in the inspect view). Right now all replicas of a writer are considered a valid candidate. Either adding another icon or a border would be fantastic.

We couldn't figure out why when we could chose one replica (either with the `-d` option or in the UI drag/drop) and takeover without problems but with another our entire setup broke.

**Comment by shlomi-noach** [comment]
@dougfales thank you! The change you suggest makes perfect sense. I'm happy for a PR.

@zmoazeni 
> The biggest issue is that the writer/master is left readonly with no indication why

I've actually been bitten by this, too. I think there should be a rollback such that the old master is turned writable again in case of promotion failure. If any of you is interesting in submitting a PR for this, I'm grateful. Otherwise I'm a bit slow to code this in the next few weeks.

**Comment by msolters** [comment]
Hmm, so is this issue closed?

**Comment by dougfales** [comment]
@msolters I think it should be since the original issue is fixed in https://github.com/github/orchestrator/pull/570. I'll close it now. Thanks!
