### ISSUE TITLE
Does orchestrator support mysql master slave  online failover ?

### ISSUE THREAD

**Issue by cloudufull** [openark/orchestrator#574]
Does orchestrator support mysql master-slave  online failover ?
    
Just like MHA's online failover function

It's very Useful when maintaining hardware and the operating system on the master node

**Comment by shlomi-noach** [comment]
I'm not sure I understand what you mean. Did you mean a "planned fail over"? Yes: https://github.com/github/orchestrator/blob/master/docs/topology-recovery.md#graceful-master-promotion

**Comment by cloudufull** [comment]
yes  ，but when i test graceful-master-takeover in orchestrator  version 3.0.11, it seems  slave can't change master without username&password(my mysql server is 5.5.33)  after graceful-master-takeover ,  and the  new master didn't execute reset slave all even I set "ApplyMySQLPromotionAfterMasterFailover": true  , just execute reset slave and set global read_only=0.

**Comment by shlomi-noach** [comment]
`RESET SLAVE ALL` is only supported as of `5.5.16` and as of `5.6.3`, and apparently I only check the latter. Let me see what can be done.

> but when i test graceful-master-takeover in orchestrator version 3.0.11, it seems slave can't change master without username&password

`orchestrator` does not know your replication credentials. related: https://github.com/github/orchestrator/issues/323#issuecomment-338668549
Right now what you can do is use a `PostGracefulTakeoverProcesses` hook to assign replication credentials to the old master.

**Comment by cloudufull** [comment]
ok ~ thank you  very much sir, and  i understanded ! ^-^ 
 And    when  i   test orchestrator-client use option -b ,  found  at  script orchestrator-client the 190th line  `api_response=$(curl -b "${basic_auth}" -s "$uri" | jq '.')`, may be it should by ` curl -u   "${basic_auth}" -s "$uri" | jq '.')`

**Comment by shlomi-noach** [comment]
> And when i test orchestrator-client use option -b 

@cloudufull thank you, addressed by https://github.com/github/orchestrator/pull/581
