### ISSUE TITLE
Does orchestrator  failover after  slave instance Completion log，when master instance dead

### ISSUE THREAD

**Issue by cloudufull** [openark/orchestrator#578]
When an master instance dead, but the server is still connected, orchestrator can proactively go to the master' server to dump the unreplicat binaries from the master binlog,  then apply them to the smallest lag slave ， and then switch ？ 
just like the function of mha.

**Comment by shlomi-noach** [comment]
Sorry, it cannot. There was a failed attempt at https://github.com/github/orchestrator/pull/42 and around.
