### ISSUE TITLE
Differentiating GracefulTakeover from MasterFailure in Hook

### ISSUE THREAD

**Issue by cclose** [openark/orchestrator#579]
I noticed that the Recovery Hooks do not seem to differentiate between planned failovers (Graceful-Master-Takeover) and actual failures. 

I had been having an issue where I has triggering a STONITH process in my PreFailoverProcesses and noticed that this was making my GracefulTakeovers fail. What was happening was I did not expect the Graceful Takeover to trigger the PreFailoverProcesses as there were seperate hooks for these so I assumed wrong. Thus, my STONITH process was triggering mid-takeover and shutting down the master.

This is fine, though I think the documentation could better illuminate what each hook is for, except that I'm not actually sure how to differentiate the difference between planned takeovers and true failures. In a graceful takeover, I don't really want to STONITH my master as I trust the takeover process to handle the rotation (or maybe this is a bad assumption on my part?).

I thought maybe ORC_FAILURE_TYPE ({failureType}) would work, but it indicates "DeadMaster". I checked the source to find the list of possible values and noticed there is a "NoProblem" state that doesn't appear to be used. Why does Orchestrator label a Takeover as "DeadMaster". I would expect something like "PlannedSwitch" or "Takeover" as my Master isn't really dead.

Anyways, I tried looking in the source that generates the magic replacement variables and the environment variables and noticed one that is not documented in the md files: ORC_COMMAND. I added this to my hooks and viola: "ORC_COMMAND: graceful-master-takeover". Excellent! I could pass this value to my STONITH process and have it either run a system check or do nothing. However, since it's undocumented, i'm not sure if it's wise to use it. Is this just a missing documentation item, or should I not be using this variable in this manner?

Thanks

**Comment by shlomi-noach** [comment]
It's a missing documentation issue. Thank you for pointing this out!

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/github/orchestrator/pull/583
