### ISSUE TITLE
Incorrect curl flag for user authentication

### ISSUE THREAD

**Issue by timhughes** [openark/orchestrator#580]
I believe the correct flag to use here is `--user` in place of  `-b` 

from the man page the `-b` is the same as `--cookie`.

I think the intention here was to use `--basic` but in that case you still need the `--user` flag so the code should be:
```
curl --basic --user "${basic_auth}" 
```
### Locations in code
https://github.com/github/orchestrator/blob/f2fedd871fc2811d7696234f3f332c7c791416c6/resources/bin/orchestrator-client#L167

https://github.com/github/orchestrator/blob/f2fedd871fc2811d7696234f3f332c7c791416c6/resources/bin/orchestrator-client#L190

### examples showing it broken and working
```
[root@orchestrator ~]# curl --basic admin:password -s http://orchestrator.local:3000/api/clusters-info
Not Authorized
```

```
[root@orchestrator ~]# curl --user admin:password -s http://orchestrator.local:3000/api/clusters-info
[{"ClusterName":"db4.local:3306","ClusterAlias":"db4.local:3306","ClusterDomain":"","CountInstances":5,"HeuristicLag":0,"HasAutomatedMasterRecovery":false,"HasAutomatedIntermediateMasterRecovery":false}]
```

**Comment by shlomi-noach** [comment]
Thank you for spotting this. Addresses by https://github.com/github/orchestrator/pull/581
