### ISSUE TITLE
flapping between old master and new master

### ISSUE THREAD

**Issue by iraj-norouzi** [openark/orchestrator#602]
hi dear

i run 
orchestration 3 server
mysql 5.7 3 server
proxysql 1 server

when i downed master server switched to slave and worke it no problem
but i uped master server flapping between old master and new master and does not worked!
Please Help me

**Comment by shlomi-noach** [comment]
Hi,

I'd like to believe you fell victim to a bad Google Translate scenario. "dear" isn't the word you are looking for.

I'm having trouble understanding your case. I'd need you to explain more about everything please.

**Comment by iraj-norouzi** [comment]
Sorry
i'm  can not write english very well.
Anyway 
What information do you need?
Thank you for helping me

**Comment by iraj-norouzi** [comment]
i have a 6 server
server1:mysql1
server2:mysql2
server3:mysql3
server4:proxysql and orchestrator1
orch2:orchestrator2
orch3:orchestrator3

mysql config is:
```
#!/bin/bash
. constants
mysql -hserver1 -P3306 -uroot -p$MYSQL_PWD -e"stop slave;"
mysql -hserver1 -P3306 -uroot -p$MYSQL_PWD -e"reset slave;"
mysql -hserver1 -P3306 -uroot -p$MYSQL_PWD -e"reset master;"
mysql -hserver1 -P3306 -uroot -p$MYSQL_PWD -e"SET GLOBAL READ_ONLY=0;" > /dev/null 2>&1
mysql -hserver2 -P3306 -uroot -p$MYSQL_PWD -e"stop slave;"
mysql -hserver2 -P3306 -uroot -p$MYSQL_PWD -e"reset slave;"
mysql -hserver2 -P3306 -uroot -p$MYSQL_PWD -e"reset master;"
mysql -hserver2 -P3306 -uroot -p$MYSQL_PWD -e"CHANGE MASTER TO MASTER_HOST='server1',MASTER_USER='root',MASTER_PASSWORD='$MYSQL_PWD',MASTER_AUTO_POSITION = 1;" > /dev/null 2>&1
mysql -hserver2 -P3306 -uroot -p$MYSQL_PWD -e"START SLAVE; SET GLOBAL READ_ONLY=1;" > /dev/null 2>&1

mysql -hserver3 -P3306 -uroot -p$MYSQL_PWD -e"stop slave;"
mysql -hserver3 -P3306 -uroot -p$MYSQL_PWD -e"reset slave;"
mysql -hserver3 -P3306 -uroot -p$MYSQL_PWD -e"reset master;"

mysql -hserver3 -P3306 -uroot -p$MYSQL_PWD -e"CHANGE MASTER TO MASTER_HOST='server1',MASTER_USER='root',MASTER_PASSWORD='$MYSQL_PWD',MASTER_AUTO_POSITION = 1;" > /dev/null 2>&1
mysql -hserver3 -P3306 -uroot -p$MYSQL_PWD -e"START SLAVE; SET GLOBAL READ_ONLY=1;" > /dev/null 2>&1

mysql -hserver1 -P3306 -uroot -p$MYSQL_PWD -e"GRANT usage,replication client on *.* to monitor@'%' identified by 'monitor';" > /dev/null 2>&1
mysql -hserver1 -P3306 -uroot -p$MYSQL_PWD -e"CREATE DATABASE sysbench" > /dev/null 2>&1
```

proxy sql config:
```
DELETE FROM mysql_servers;
INSERT INTO mysql_servers (hostgroup_id,hostname,port,max_replication_lag) VALUES (0,'server1',3306,1);
INSERT INTO mysql_servers (hostgroup_id,hostname,port,max_replication_lag) VALUES (1,'server1',3306,1);
INSERT INTO mysql_servers (hostgroup_id,hostname,port,max_replication_lag) VALUES (1,'server2',3306,1);
INSERT INTO mysql_servers (hostgroup_id,hostname,port,max_replication_lag) VALUES (1,'server3',3306,1);
DELETE FROM mysql_replication_hostgroups;
INSERT INTO mysql_replication_hostgroups VALUES (0,1,'');
LOAD MYSQL SERVERS TO RUNTIME;
SAVE MYSQL SERVERS TO DISK;

DELETE FROM mysql_users;
INSERT INTO mysql_users (username,password,active) values ('root','root',1);
LOAD MYSQL USERS TO RUNTIME;
SAVE MYSQL USERS TO DISK;

DELETE FROM mysql_query_rules;
INSERT INTO mysql_query_rules (rule_id,active,match_digest,destination_hostgroup,apply) VALUES (1,1,'^SELECT.*FOR UPDATE',0,1),(2,1,'^SELECT',1,1);
LOAD MYSQL QUERY RULES TO RUNTIME;
SAVE MYSQL QUERY RULES TO DISK;
```

orchestrator config:
```
#!/bin/bash
. constants
export ORCHESTRATOR_API="http://server4:3000/api http://orc2:3000/api http://orc3:3000/api"
ssh server4 'pkill screen'
ssh orc2 'pkill screen'
ssh orc3 'pkill screen'
ssh server4 'rm -rf /var/lib/orchestrator/*'
ssh orc2 'rm -rf /var/lib/orchestrator/*'
ssh orc3 'rm -rf /var/lib/orchestrator/*'
ssh server4 'screen -dm /usr/local/orchestrator/orchestrator --debug --stack http'
ssh orc2 'screen -dm /usr/local/orchestrator/orchestrator --debug --stack http'
ssh orc3 'screen -dm /usr/local/orchestrator/orchestrator --debug --stack http'


orchestrator-client -c discover -i server1

orchestrator-client -c discover -i server2

orchestrator-client -c discover -i server3

orchestrator-client -c topology -a $(orchestrator-client -c clusters)
```

```shell
cat /etc/orchestrator.conf.json

```

```json
{
  "Debug": true,
  "ListenAddress": ":3000",
  "MySQLTopologyUser": "root",
  "MySQLTopologyPassword": "root",
  "BackendDB": "sqlite",
  "SQLite3DataFile": "/var/lib/orchestrator/orchestrator.db",
  "RaftEnabled": true,
  "RaftDataDir": "/var/lib/orchestrator/",
  "RaftBind": "server4",
  "DefaultRaftPort": 10008,
  "RaftNodes": [
    "server4",
    "orc2",
    "orc3"
  ],
  "HostnameResolveMethod": "default",
  "MySQLHostnameResolveMethod": "@@report_host",
  "ApplyMySQLPromotionAfterMasterFailover": true,
  "RecoverMasterClusterFilters": [
    "*"
  ],
  "RecoverIntermediateMasterClusterFilters": [
    "*"
  ],
  "PreFailoverProcesses": [
  "echo 'Will recover from {failureType} on {failureCluster}' >> /tmp/recovery.log",
  "bash /etc/orch/docker-mysql-proxysql/bin/docker-mysql-post.bash",
  "bash /etc/orch/docker-mysql-proxysql/bin/docker-orchestrator-post.bash"

  ],
  "PostFailoverProcesses": [
    "echo '(for all types) Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Successor: {successorHost}:{successorPort}' >> /tmp/recovery.log"
  ],
  "PostUnsuccessfulFailoverProcesses": [],
  "PostMasterFailoverProcesses": [
    "echo 'Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Promoted: {successorHost}:{successorPort}' >> /tmp/recovery.log"
  ],
  "PostIntermediateMasterFailoverProcesses": []
}
```

**Comment by iraj-norouzi** [comment]
when mysql server1  downed server2 is master and worked without problem but server1 mysql is up flapping between server1 and server2 !

**Comment by shlomi-noach** [comment]
If I understand correctly, you have:

```
server1 (master)
+- server2 (replica)
+- server3 (replica)
```
it would be great if you could show me the output of `orchestrator-client -c topology -a server1`.

Now, if I understand correctly, you're taking `server1` down and you are expecting failover, correct?
Which happens.

Now, when you bring `server1` up, what I'm not sure about is exactly _what is flapping_. Is `server3` replication flapping between `server1` and `server2`?

Or do you mean your client's traffic is flapping between `server1` and `server2`, in which case this is a Proxy problem?

I'm going to guess this is the proxy problem. I am also going to guess (I cannot see it in your above input), that your ProxySQL servers sends write traffic to servers with `read_only=0`.

This is an anti-pattern, something you should not be using. Please see http://code.openark.org/blog/mysql/mysql-master-discovery-methods-part-4-proxy-heuristics

A little helpful is to use:

> Configuration tip
> With an automated failover solution, use read_only=1 in my.cnf at all times. Only the failover solution will set a server to read_only=0.
> With this configuration, when M restarts, MySQL starts up as read_only=1.

But it only helps a bit, it does not solve the problem. Letting proxy identify the master via `read_only=0` is a mistake.

**Comment by iraj-norouzi** [comment]
exactly
```
server1 (master)
+- server2 (replica)
+- server3 (replica)
```

```
orchestrator-client -c topology -a server1
server1:3306   [0s,ok,5.7.23-log,rw,ROW,>>,GTID]
+ server2:3306 [0s,ok,5.7.23-log,ro,ROW,>>,GTID]
+ server3:3306 [0s,ok,5.7.23-log,ro,ROW,>>,GTID]
```

client's traffic do not flapping proxysql is worked Properly.
i tested with below command:
```
watch -d "mysql -u root -proot -h 127.0.0.1 -P6033 -e 'SELECT @@hostname FOR UPDATE' "
```
and see Every 2 to 3 seconds changed server !

**Comment by iraj-norouzi** [comment]
cat /etc/my.cnf
[mysqld]
innodb_log_file_size=512M
innodb_buffer_pool_size=256M
innodb_flush_log_at_trx_commit=2
sync_binlog=1
server-id=111
gtid_mode=ON
enforce_gtid_consistency=true
log-bin
log-slave-updates
relay_log_info_repository=TABLE
relay_log_recovery=ON
master_info_repository=TABLE
read_only=0
report_host=server1

**Comment by shlomi-noach** [comment]
> client's traffic do not flapping proxysql is worked Properly.

Please explain what is flapping.

**Comment by shlomi-noach** [comment]
> watch -d "mysql -u root -proot -h 127.0.0.1 -P6033 -e 'SELECT @@hostname FOR UPDATE' "

`6033` is ProxySQL port, correct?

Which means any time you wish to connect to MySQL you go through ProxySQL, correct?

And every few second you get different host.

This means client traffic to MySQL is flapping. ProxySQL is flapping the backend server. I strongly believe I am correct on this, please read https://github.com/github/orchestrator/issues/602#issuecomment-417919884 again as well as the link to my blog.

**Comment by shlomi-noach** [comment]
closing as no response
