### ISSUE TITLE
Web UI Display Issue - All Instances in a Cluster Overlap

### ISSUE THREAD

**Issue by hamzahsa94** [openark/orchestrator#604]
The web ui is working well for one of my clusters but for the other one all the instances are overlapped.

I can't see the topology or select individual instances, it isn't possible to move anything around. Everything works well when I use the command line, so the underlying application is working well.

When I opened up the developer console I can see some errors. The same thing is happening on Chrome, Edge and Firefox.

Attached image showing the issue.

![orchestrator-3 0 12-errors](https://user-images.githubusercontent.com/37233366/45115492-d79a4f80-b104-11e8-9d57-f151287075f0.png)

Please let me know if there's a fix for this. I had the issue since Orchestrator 3.0.11 and am using 3.0.12 now.

**Comment by shlomi-noach** [comment]
Can you please paste your`orchestrator-client -c topology -cluster ...`?
Feel free to redact actual hostnames.

**Comment by shlomi-noach** [comment]
Do you happen to have circular replication?

**Comment by hamzahsa94** [comment]
The output is as below:
```
hahmed@IRVPMM01:/usr/local/orchestrator$  ./orchestrator -c topology -i ADB01:3306 cli
- DC1DB01:3306     [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
  + DC1DB02:3306   [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
  + DC1DB03:3306   [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
  + DC1DB04:3306   [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
  - DC1DB05:3306   [unknown,invalid,5.7.12-log,rw,MIXED,>>,GTID]
  + DC2DB01:3306   [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
    + DC2DB02:3306 [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
    + DC2DB03:3306 [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
    + DC2DB04:3306 [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
    + DC2DB05:3306 [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
```
DC1DB05 is down right now, but the issue in orchestrator has existed since earlier.

Circular replication is not set up on this cluster, but it is enabled on another cluster where I do not have this issue.

**Comment by hamzahsa94** [comment]
The output is as below:
```
hamzahsa94@DC1ORC01:/usr/local/orchestrator$  ./orchestrator -c topology -i DC1DB01:3306 cli
- DC1DB01:3306     [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
  + DC1DB02:3306   [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
  + DC1DB03:3306   [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
  + DC1DB04:3306   [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
  - DC1DB05:3306   [unknown,invalid,5.7.12-log,rw,MIXED,>>,GTID]
  + DC2DB01:3306   [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
    + DC2DB02:3306 [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
    + DC2DB03:3306 [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
    + DC2DB04:3306 [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
    + DC2DB05:3306 [0s,ok,5.7.12-log,rw,MIXED,>>,GTID]
```
DC1DB05 is down right now, but the issue in orchestrator has existed since earlier.

Circular replication is not set up on this cluster, but it is enabled on another cluster where I do not have this issue.

**Comment by shlomi-noach** [comment]
Is there anything else peculiar about your replication setup? Multi-source replication?
What is your config's `HostnameResolveMethod` and `MySQLHostnameResolveMethod` ?

**Comment by hamzahsa94** [comment]
Not really, I have the same setup for another cluster and it is showing up without any issues. 


  "HostnameResolveMethod": "default",
  "MySQLHostnameResolveMethod": "@@hostname"

**Comment by hamzahsa94** [comment]
I am not sure how, but the issue seems to have resolved itself.

The entire topology is being shown clearly.

**Comment by shlomi-noach** [comment]
🤷‍♂️

**Comment by hamzahsa94** [comment]
Closing the issue as there are no updates and the issue hasn't repeated.
