### ISSUE TITLE
status is  unknown,unchecked 

### ISSUE THREAD

**Issue by wsh-sun** [openark/orchestrator#605]
```
[root@gz-60-36 ~]# orchestrator -c discover -i 172.21.60.73:3306 --debug --stack cli
2018-09-06 14:16:25 INFO starting orchestrator
2018-09-06 14:16:25 INFO Read config: /etc/orchestrator.conf.json
2018-09-06 14:16:25 DEBUG Hostname unresolved yet: 172.21.60.73
2018-09-06 14:16:25 DEBUG Cache hostname resolve 172.21.60.73 as 172.21.60.73
2018-09-06 14:16:25 DEBUG Initializing orchestrator
2018-09-06 14:16:25 DEBUG Connected to orchestrator backend: orchestrator:?@tcp(127.0.0.1:3306)/orchestrator?timeout=2s
2018-09-06 14:16:25 DEBUG Orchestrator pool SetMaxOpenConns: 128
2018-09-06 14:16:25 DEBUG Hostname unresolved yet: 172.21.60.74
2018-09-06 14:16:25 DEBUG Cache hostname resolve 172.21.60.74 as 172.21.60.74
172.21.60.73:3306
[root@gz-60-36 ~]# orchestrator -c discover -i 172.21.60.74:3306 --debug --stack cli
2018-09-06 14:16:29 INFO starting orchestrator
2018-09-06 14:16:29 INFO Read config: /etc/orchestrator.conf.json
2018-09-06 14:16:29 DEBUG Hostname unresolved yet: 172.21.60.74
2018-09-06 14:16:29 DEBUG Cache hostname resolve 172.21.60.74 as 172.21.60.74
2018-09-06 14:16:29 DEBUG Initializing orchestrator
2018-09-06 14:16:29 DEBUG Connected to orchestrator backend: orchestrator:?@tcp(127.0.0.1:3306)/orchestrator?timeout=2s
2018-09-06 14:16:29 DEBUG Orchestrator pool SetMaxOpenConns: 128
2018-09-06 14:16:29 DEBUG Hostname unresolved yet: 172.21.60.73
2018-09-06 14:16:29 DEBUG Cache hostname resolve 172.21.60.73 as 172.21.60.73
172.21.60.74:3306
[root@gz-60-36 ~]# orchestrator -c topology -i 172.21.60.73:3306
172.21.60.73:3306 [0s,ok,5.7.15-log,rw,ROW]
172.21.60.74:3306 [0s,ok,5.7.15-log,rw,ROW,GTID]
```
after 20 seconds：
```
[root@gz-60-36 ~]# orchestrator -c topology -i 172.21.60.73:3306
172.21.60.73:3306 [unknown,unchecked,5.7.15-log,rw,ROW]
172.21.60.74:3306 [unknown,unchecked,5.7.15-log,rw,ROW,GTID]
```

when i  execute discover again，the status is ok。how to make orchestrator continuous discovery？？？it has a parameter  in /etc/orchestrator.conf.json  ？i konw the orchestrator -c continuous --debug cli 。
thanks

**Comment by shlomi-noach** [comment]
Hi,
You want to run `orchestrator` as a service. If you install the `.rpm` or `.deb` packages, you would `/etc/init.d/orchestrator start`.

Or you could also just `orchestrator http`, assuming all config files are in the right place.

This will run `orchestrator` not just to handle a single command, but provide HTTP API, continuous discovery, failure detection and recovery.

**Comment by shlomi-noach** [comment]
see https://github.com/github/orchestrator/blob/master/docs/execution.md

**Comment by wsh-sun** [comment]
thank you very much ！
But i dont't  want to execute  as web/API service,just command line。
If you install the .rpm or .deb packages----i just download https://github.com/github/orchestrator。 
are they the same？？

**Comment by shlomi-noach** [comment]
OK then, try `orchestrator -c continuous`

**Comment by wsh-sun** [comment]
thanks~

**Comment by wsh-sun** [comment]
orchestrator -c continuous --debug cli >> /tools/usr/local/orchestrator/orchestrator.log  2>&1 & 

i find some message in orchestrator.log：
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:45:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:45:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:45:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:46:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:46:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:47:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:47:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:47:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:49:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:49:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:49:00 statement.go:27: Invalid Connection

but i see the topology：
orchestrator -c topology -i 172.21.60.73:3306
172.21.60.73:3306      [0s,ok,5.7.15-log,rw,ROW]
+ 172.21.60.74:3306    [0s,ok,5.7.15-log,rw,ROW,GTID]
  + 172.21.60.123:3306 [0s,ok,5.7.15-log,rw,ROW,GTID]

so the message if can be ignored？

**Comment by wsh-sun** [comment]
`orchestrator -c continuous --debug cli >> /tools/usr/local/orchestrator/orchestrator.log 2>&1 &

i find some message in orchestrator.log：
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:45:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:45:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:45:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:46:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:46:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:47:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:47:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:47:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:49:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:49:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:49:00 statement.go:27: Invalid Connection
`
but i see the topology：
`
orchestrator -c topology -i 172.21.60.73:3306
172.21.60.73:3306 [0s,ok,5.7.15-log,rw,ROW]

172.21.60.74:3306 [0s,ok,5.7.15-log,rw,ROW,GTID]
172.21.60.123:3306 [0s,ok,5.7.15-log,rw,ROW,GTID]`
so the message if can be ignored？

**Comment by wsh-sun** [comment]
orchestrator -c continuous --debug cli >> /tools/usr/local/orchestrator/orchestrator.log  2>&1 & 
i see some message in orchestrator.log
`[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:45:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:45:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:45:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:46:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:46:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:47:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:47:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:47:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:49:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:49:00 statement.go:27: Invalid Connection
[MySQL] 2018/09/06 15:49:00 statement.go:27: Invalid Connection
`
when i see the topology  is ok ,the message if can be ignored? 
`orchestrator -c topology -i 172.21.60.73:3306
172.21.60.73:3306      [0s,ok,5.7.15-log,rw,ROW]
+ 172.21.60.74:3306    [0s,ok,5.7.15-log,rw,ROW,GTID]
  + 172.21.60.123:3306 [0s,ok,5.7.15-log,rw,ROW,GTID]
`

**Comment by wsh-sun** [comment]
orchestrator -c continuous --debug cli >> /tools/usr/local/orchestrator/orchestrator.log 2>&1 &
i see some message in orchestrator.log

[MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:44:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:45:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:45:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:45:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:46:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:46:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:47:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:47:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:47:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:48:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:49:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:49:00 statement.go:27: Invalid Connection [MySQL] 2018/09/06 15:49:00 statement.go:27: Invalid Connection
when i see the topology is ok ,the message if can be ignored?
orchestrator -c topology -i 172.21.60.73:3306
172.21.60.73:3306 [0s,ok,5.7.15-log,rw,ROW]
172.21.60.74:3306 [0s,ok,5.7.15-log,rw,ROW,GTID]
172.21.60.123:3306 [0s,ok,5.7.15-log,rw,ROW,GTID]

**Comment by shlomi-noach** [comment]
you shouldn't be getting that many `Invalid Connection` messages. It _looks OK_ but also looks like you may get into trouble.

**Comment by wsh-sun** [comment]
thanks ,
