### ISSUE TITLE
orchestrator with --noop flag still allows to manage slave status

### ISSUE THREAD

**Issue by pznamensky** [openark/orchestrator#606]
Looks like a bug: orchestrator (3.0.12) with --noop flag still allows to start/stop/restart slave from the web UI.

**Comment by shlomi-noach** [comment]
That is correct. Unfortunately without `noop` there is no way to evaluate many operations. It would be impossible to say whether one operation or another would even be possible. It unfortunately has to stay.

**Comment by pznamensky** [comment]
@shlomi-noach, we'd like to give ability for all our staff to view a topology of our mysql cluster.
Is it looks ok to setup nginx in front of orchestrator and deny all non-GET requests to the UI?

**Comment by shlomi-noach** [comment]
@pznamensky you could integrate with LDAP, or if you're looking for a simpler approach, try `"AuthenticationMethod": "multi"`. See the docs: https://github.com/github/orchestrator/blob/master/docs/security.md

**Comment by pznamensky** [comment]
Oh, I missed it. Thanks!
