### ISSUE TITLE
What does  '>>'  mean???

### ISSUE THREAD

**Issue by wsh-sun** [openark/orchestrator#615]
[root@qq-60-36 orchestrator]# orchestrator -c topology -i 172.21.60.74:3306
172.21.60.73:3306    [0s,ok,5.7.15-log,rw,ROW,>>]
+ 172.21.60.123:3306 [0s,ok,5.7.15-log,rw,ROW,GTID]
+ 172.21.60.74:3306  [0s,ok,5.7.15-log,ro,ROW,>>,GTID]

What does  '>>'  mean ???

**Comment by shlomi-noach** [comment]
It means the server is running with `log-slave-updates`.
