### ISSUE TITLE
submit-masters-to-kv-stores fails update in zookeeper 

### ISSUE THREAD

**Issue by timhughes** [openark/orchestrator#619]
`submit-masters-to-kv-stores` fails on zookeeper if the data already there so that basically it only works the first time. 

```
[root@orchestrator ~]# /usr/local/orchestrator/orchestrator -c submit-masters-to-kv-stores
mysql/master/thprof-live:thprof-live-mdbs1.local:3306
mysql/master/thprof-live/hostname:thprof-live-mdbs1.local
mysql/master/thprof-live/port:3306
mysql/master/thprof-live/ipv4:192.168.121.146
mysql/master/thprof-live/ipv6:
[root@orchestrator ~]# /usr/local/orchestrator/orchestrator -c submit-masters-to-kv-stores
2018-09-13 09:30:37 FATAL zk: node already exists
```
I have `"KVClusterMasterPrefix": "mysql/master",` in my config 

It looks like it is failing when it tries to create the cluster path `/mysql/master/thprof-live`

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/github/orchestrator/pull/620. If you're able to test it on your side I'm grateful.

**Comment by timhughes** [comment]
Thanks you beat me to it and your code is cleaner. Tested as working
