### ISSUE TITLE
Don't necessarily require manual acknowledgement for audit-recovery

### ISSUE THREAD

**Issue by sjmudd** [openark/orchestrator#636]
In an environment with a large number of servers orchestrator may recovery quite frequently. If this works well then it may not be necessary to verify/validate each recovery that takes place.

I would like to optionally limit the acknowledgement state on failed recoveries as that probably requires someone to verify what happened, and auto-close other successful recoveries for primary master or intermediate masters.

I would guess the current behaviour is fine by default so an option to only require acknowledgement on failed recoveries would be good.

I can provide more context privately if that would be useful.

**Comment by sjmudd** [comment]
An alternative option would be to provide an `acknowledge all` type button which would be applied to all un-acknowledged failures. To some extent I think that both features should exist.

**Comment by shlomi-noach** [comment]
@sjmudd what would be the logic for `orchestrator` to determine which recoveries should be auto-acknowledged?

Also, please be advised that there is a `-c ack-all-recoveries` command, see #447

**Comment by shlomi-noach** [comment]
@sjmudd shall I close this?
