### ISSUE TITLE
Make canMoveViaGTID smarter - do not move a delayed slave if doing so will throw away relay logs it needs.

### ISSUE THREAD

**Issue by sjmudd** [openark/orchestrator#643]
First mentioned in https://github.com/github/orchestrator/issues/640 but made into a separate issue to keep things clean.

The function `canMoveViaGTID` may need to be smarter as it currently does not take into account some issues which can arise and which may break replication when used from `moveReplicasViaGTID`. They are:

Moving a delayed slave which has a considerable amount of delay (and thus relay logs) may also cause issues:
* if the equivalent binlogs are on the new master they need to be fetched again which is wasteful but may be unavoidable
* if the equivalent binlogs are not on the new master then replication will break as the `CHANGE MASTER TO` command will remove any relay logs prior to reconnecting to the new master.
* it seems wise to check `gtid_executed` and `gtid_purged` on the new master with `Retrieved_Gtid_Set` and `Executed_Gtid_Set` (or `gtid_executed`) from the slave to identify if this might happen and not attempt the relocation in this case, providing a helpful error message why this isn't possible.

**Comment by shlomi-noach** [comment]
Interestingly this does not happen with `PseudoGTID` where we first check for possible correlation, and only then issue the (destructive) `change master to` command.

**Comment by shlomi-noach** [comment]
@sjmudd if I'm not mistaken `Retrieved_Gtid_Set` is irrelevant in this case, since it depicts the GTID entries in the relay logs; but what we want to see is whether the server is capable of replicating assuming we _purge_ the relay logs. Correct?

**Comment by shlomi-noach** [comment]
**EDIT** this comment depicted an algorithm to predict whether it would be correct to move replica below another GTID-wise. It was wrong and I chose to hide it (it's still visible in history)

**Comment by shlomi-noach** [comment]
Addressed by #661

**Comment by sjmudd** [comment]
@shlomi-noach  not quite.
The retrieved set shows what's been collected. If you run change master you may throw these events  away so if the events are not on the new master and are in the relay logs (visible via the retrieved set) then the only safe thing to do is _wait_ until the relay logs are processed after which it may be safe to do a change master (you probably need to check again afterwards). Checking the executed set on the slave vs the purge and executed set on the master will tell you if the master has the data or not but this doesn't tell you if the relay logs provide the wanted data or not.

I guess that if the data is on the master it's ok to drop the relay logs and pull them again from the new master even if this is not efficient. At least it should work.

**Comment by sjmudd** [comment]
The error I'm trying to prevent is this one on the slave:

```
                Last_IO_Errno: 1236
                Last_IO_Error: Got fatal error 1236 from master when reading data from binary log: 'The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires.'
```

**Comment by shlomi-noach** [comment]
@sjmudd we are saying the same thing here. #661 addresses that.

> then the only safe thing to do is wait until the relay logs are processed

And so `orchestrator` will refuse a `change master to` if the replica's relay logs are the only thing that's containing long since purged entries on the master.
