### ISSUE TITLE
when orchestrator the mysql master down,how can it choose the new mysql master

### ISSUE THREAD

**Issue by zeusYi** [openark/orchestrator#655]
Hi , 
  I have a question to ask. 
  the Mysql Cluster topology is one master have two slaves. And I have add this cluster into the orchestrator.  When I shutdown the master instance, how orchestrator can choose the new master db from two slaves, and change another slave db's master to the new master.(like MHA)

**Comment by shlomi-noach** [comment]
Like this: https://github.com/github/orchestrator/blob/master/docs/failure-detection.md, https://github.com/github/orchestrator/blob/master/docs/topology-recovery.md

**Comment by zeusYi** [comment]
@shlomi-noach  
Thank you very much to reply my question , I have read the docs,and add the 
 "RecoverMasterClusterFilters": ["*"],
  "RecoverIntermediateMasterClusterFilters": ["*"],
into orchestrator configuration files.

But When I shutdown the master mysql ，orchestrator automatic split two cluster,the slave2 become  new master role mysql ,but the slave1 still point the master db to old shutdown master, why slave1  can not point the master to  new role master-slave2 ?  what configure I should modify  in the 
configuration files ?

**Comment by shlomi-noach** [comment]
@yiwenshuo are you using GTID? Pseudo GTID? You must be using one of these.

Do both replicas have `log_slave_updates`? If not, one cannot take over the other.

**Comment by zeusYi** [comment]
The MySQL server version is percona 5.7.21-21, and enable gtid。The orchestrator info is : 
master:

Last seen | 2018-10-12 14:29:45 (3s ago)
-- | --
Self coordinates | mysql-bin.000015:194
Num replicas | 2Regroup replicas
Server ID | 3
Server UUID | 64de3fa4-8c02-11e8-b5d4-00505630f05a
Version | 5.7.21-21-log
Read only | false Set read-only
Has binary logs | true
Binlog format | ROW/FULL
Logs slave updates | trueTake siblings
GTID supported | true
GTID based replication | false Enable
GTID mode | ON
Semi-sync enforced | false
Uptime | 7513
Allow TLS | false
Cluster | master:3306
Audit | master:3306
Agent | master



slave1:

Last seen | 2018-10-12 14:29:46 (2s ago)
-- | --
Master | master:3306Reset slave
Replication running | true Restart slaveStop slaveToggle Dropdown
Seconds behind master | 0
Replication lag | 0
SQL delay | 0
Master coordinates | mysql-bin.000015:194 Detach replica
Self coordinates | mysql-bin.000004:234
Num replicas | 0
Server ID | 4
Server UUID | 575c344c-cb92-11e8-bc49-00505635c427
Version | 5.7.21-21-log
Read only | false Set read-only
Has binary logs | true
Binlog format | ROW/FULL
Logs slave updates | trueTake siblings
GTID supported | true
GTID based replication | false Enable
GTID mode | ON
Semi-sync enforced | false
Uptime | 68955
Allow TLS | false
Cluster | master:3306
Audit | slave1:3306
Agent | slave1


slave2:

Last seen | 2018-10-12 14:29:46 (2s ago)
-- | --
Master | master:3306Reset slave
Replication running | true Restart slaveStop slaveToggle Dropdown
Seconds behind master | 0
Replication lag | 0
SQL delay | 0
Master coordinates | mysql-bin.000015:194 Detach replica
Self coordinates | mysql-bin.000005:234
Num replicas | 0
Server ID | 5
Server UUID | dd497295-cbb3-11e8-bb78-00505635c427
Version | 5.7.21-21-log
Read only | false Set read-only
Has binary logs | true
Binlog format | ROW/FULL
Logs slave updates | trueTake siblings
GTID supported | true
GTID based replication | false Enable
GTID mode | ON
Semi-sync enforced | false
Uptime | 13235
Allow TLS | false
Cluster | master:3306
Audit | slave2:3306
Agent | slave2

**Comment by shlomi-noach** [comment]
Did you close the issue by mistake?

**Comment by shlomi-noach** [comment]
It looks to me like you're not really using `MASTER_AUTO_POSITION=1` in your replication. You have GTID enabled, but not using it.

**Comment by zeusYi** [comment]
@shlomi-noach ,yes thank you very much, after I change the MASTER_AUTO_POSITION from 0 to 1, all things are normal,thanks .
