### ISSUE TITLE
Smaller Docker Image

### ISSUE THREAD

**Issue by tcaxias** [openark/orchestrator#66]
Hi all,

I've just created a [PR](https://github.com/github/orchestrator/pull/65) to update the Dockerfile to produce a smaller base image.
Sorry for not creating an issue beforehand, I've just read that's how it should be done.
Anyway, hope it's useful to you.

Thanks for the amazing tool that Orchestrator is!

**Comment by shlomi-noach** [comment]
closed by #65 

not released yet
