### ISSUE TITLE
This is Just a question regarding consul kv store updates 

### ISSUE THREAD

**Issue by AkshathPatkar** [openark/orchestrator#668]
Wanted to understand how orchestrator updates consul KV store. any doc i can find online to read about it.

What happened was in our environment, we named our cluster `abc` 
in orchestrator config we are looking at config `"KVClusterMasterPrefix": "mysql/master",`

How does orchestrator updates the KV store in consul does it updates like mysql/master/abc/****

Now if i change orchestrator config to `"KVClusterMasterPrefix": "mysql/master/xyz",` will it work?

I have a second question is how are doe server-id gets updated in cluster table in meta db? Do we need to write a hook for it?

**Comment by shlomi-noach** [comment]
Please see https://github.com/github/orchestrator/blob/master/docs/configuration-kv.md#breakdown-entries

If `"KVClusterMasterPrefix": "mysql/master",` then you will have

- `mysql/master/abc`
- `mysql/master/abc/hostname`
- `mysql/master/abc/port`
- `mysql/master/abc/ipv4`
- `mysql/master/abc/ipv6`

> Now if i change orchestrator config to "KVClusterMasterPrefix": "mysql/master/xyz", will it work?

You will have

- `mysql/master/xyz/abc`
- `mysql/master/xyz/abc/hostname`
- `mysql/master/xyz/abc/port`
- `mysql/master/xyz/abc/ipv4`
- `mysql/master/xyz/abc/ipv6`

**Comment by shlomi-noach** [comment]
> I have a second question is how are doe server-id gets updated in cluster table in meta db? Do we need to write a hook for it?

I don't understand the question. `server-id`s are not updated in a meta db's cluster table. Can you please clarify what it is you're trying to achieve?

**Comment by AkshathPatkar** [comment]
Thanks @shlomi-noach .

We have multiple mySQL clusters. How does orchestrator works if we just have `"KVClusterMasterPrefix": "mysql/master",`

eg : 
cluster 1: has server1, server2, server3 (master is server1) 
cluster 2: has server4, server5, server6(master is server4)


Can we  use same orchestrator for 2 diff mySQL clusters? how does KV store works in that case

**Comment by shlomi-noach** [comment]
> we named our cluster abc

leads to:

> mysql/master/abc

If you name your cluster `cluster1` then you will have

> mysql/master/cluster1

**Comment by AkshathPatkar** [comment]
Thanks @shlomi-noach  appreciate it. i am closing this
