### ISSUE TITLE
GTID on multi-master replication: wrong report of errant transaction and population of ancestry_uuid

### ISSUE THREAD

**Issue by cohenjo** [openark/orchestrator#672]
Hi,
We use multi-master in our deployment.
we've upgraded our Orchestrator to v3.0.13 and hit a couple of issue.

1. it seems that the ancestry_uuid field is filling up in a loop over the 2 masters - eventually the column is filled and the discovery process fails to re-sample nodes.

2. we also noticed lot's of reports on errant transactions - when inspecting the code and data in the orchestrator DB it seems the the errant transactions are simply transaction that the co-master (which is our replica) did not execute yet.

It seems that when Orchestrator reducts the master UUID it should also reduct itself from the comparison

If I understand correctly it's related to this code:
[https://github.com/github/orchestrator/blob/4d9e3153238b7beb9f81b5f82e1a95d4515b86ee/go/inst/instance_dao.go#L787](https://github.com/github/orchestrator/blob/4d9e3153238b7beb9f81b5f82e1a95d4515b86ee/go/inst/instance_dao.go#L787)

for a sample data adding info from `database_instance` table:
1st master:
```
      server_uuid: 4e50da23-5405-11e6-b6be-12e8a266ca5b
      master_uuid: c78e2298-803f-11e7-92bd-0686a463e0e6
executed_gtid_set: 4e50da23-5405-11e6-b6be-12e8a266ca5b:1-29333315,
c78e2298-803f-11e7-92bd-0686a463e0e6:1-1536905
    ancestry_uuid: 4e50da23-5405-11e6-b6be-12e8a266ca5b,c78e2298-803f-11e7-92bd-0686a463e0e6,4e50da23-5405-11e6-b6be-12e8a266ca5b,c78e2298-803f-11e7-92bd-0686a463e0e6,4e50da23-5405-11e6-b6be-12e8a266ca5b,c78e2298-803f-11e7-92bd-0686a463e0e6,4e50da23-5405-11e6-b6be-12e8a266ca5b,c78e2298-803f-11e7-92bd-0686a463e0e6...
```
2nd master:
```
      server_uuid: c78e2298-803f-11e7-92bd-0686a463e0e6
      master_uuid: 4e50da23-5405-11e6-b6be-12e8a266ca5b
executed_gtid_set: 4e50da23-5405-11e6-b6be-12e8a266ca5b:1-29333155,
c78e2298-803f-11e7-92bd-0686a463e0e6:1-1536905
    ancestry_uuid: 4e50da23-5405-11e6-b6be-12e8a266ca5b,c78e2298-803f-11e7-92bd-0686a463e0e6,4e50da23-5405-11e6-b6be-12e8a266ca5b,c78e2298-803f-11e7-92bd-0686a463e0e6,4e50da23-5405-11e6-b6be-12e8a266ca5b,c78e2298-803f-11e7-92bd-0686a463e0e6,4e50da23-5405-11e6-b6be-12e8a266ca5b,c78e2298-803f-11e7-92bd-0686a463e0e6...
```

Thank you for your help,
Regards,
 - Jony

**Comment by shlomi-noach** [comment]
Thank you, I haven't taken the effects of circular replication into account. Can you please clarify whether you're on active-active or active-passive setup?

**Comment by cohenjo** [comment]
We actually have both options :)
we have clusters in which one is set as read_only (so almost nothing can come from there )
and we also have clusters with writes on both ends - although most traffic would reach 1 - so it's about 9:1 in terms of load.

I see the above for both options.

**Comment by shlomi-noach** [comment]
@cohenjo are you able to test https://github.com/github/orchestrator/pull/673?

At this time this should fix the infinitely growing `ancestry_uuid`.
I'm looking into errant transactions.

**Comment by cohenjo** [comment]
Sure, I'll create a binary from it to test - thanks

**Comment by cohenjo** [comment]
@shlomi-noach  - finished testing, it resolved the infinite loop.
Thanks for the quick response - much appreciated 👍

**Comment by shlomi-noach** [comment]
> It seems that when Orchestrator reducts the master UUID it should also reduct itself from the comparison

Generally speaking this is exactly what it's _not_ supposed to do. Errant transactions are _likely_ to generate on the server itself. But, this needs to be solved in a different manner when circular replication is involved.

**Comment by shlomi-noach** [comment]
This is now feature complete.

`ancestry_uuid`: both co-masters include each other in ancestry
`gtid_errant`: a co-master's _own transactions_ are ignored when evaluating errant transactions.

**Comment by cohenjo** [comment]
Thanks - I can confirm this closes and fixes both issues.
For circular replication errant transactions on the co-masters are effectively just lag of transactions not implemented.
for replicas lower in the tree the treatment is the same as regular replication.
all transactions on a co-master not yet executed on the 2nd co-master fulfil the definition of errant transaction but they will get executed when the lag closes and they will be executed as the other master and replicas under it are all downstream from the executing master.

I think this new fix implements this well - thank you 👍

**Comment by shlomi-noach** [comment]
Let's keep this open until #673 is merged, at which time it will auto-close this issue.
