### ISSUE TITLE
Semi Sync enabled but Dashboard shows not enabled

### ISSUE THREAD

**Issue by SQLadmin** [openark/orchestrator#690]
Im using the latest version of Orchestrator. 
I have enabled the semi sync on both master and slave. But in the dashboard its showing not enabled.

## MASTER:
```
mysql>  show variables like 'rpl_semi_syn%';
+-------------------------------------------+------------+
| Variable_name                             | Value      |
+-------------------------------------------+------------+
| rpl_semi_sync_master_enabled              | ON         |
| rpl_semi_sync_master_timeout              | 10000      |
| rpl_semi_sync_master_trace_level          | 32         |
| rpl_semi_sync_master_wait_for_slave_count | 1          |
| rpl_semi_sync_master_wait_no_slave        | ON         |
| rpl_semi_sync_master_wait_point           | AFTER_SYNC |
| rpl_semi_sync_slave_enabled               | OFF        |
| rpl_semi_sync_slave_trace_level           | 32         |
+-------------------------------------------+------------+
```

## SLAVE:
```
mysql>  show variables like 'rpl_semi_syn%';
+---------------------------------+-------+
| Variable_name                   | Value |
+---------------------------------+-------+
| rpl_semi_sync_slave_enabled     | ON    |
| rpl_semi_sync_slave_trace_level | 32    |
+---------------------------------+-------+
```

## Dashboard:
![image](https://user-images.githubusercontent.com/16044251/47948142-1146d580-df51-11e8-8ced-bdcd38654ed9.png)

**Comment by shlomi-noach** [comment]
`Semi-sync enforced` means a different thing than what you expect, and I understand the confusion. Enforcing means `orchestrator` can be asked to enfore re-applying semi- sync on replicas after failover. See https://github.com/outbrain/orchestrator/pull/187/files

I see there's no attribute in the dialog to indicate is semi-sync is enabled. Will add one.
On the topology graph, you should see a checkbox icon per box, which indicates it's using semi sync.

**Comment by SQLadmin** [comment]
Thanks for the clarification. I'm closing this issue.
