### ISSUE TITLE
ERROR FlushNontrivialResolveCacheToDatabase() called, but HostnameResolveMethod is none

### ISSUE THREAD

**Issue by mia0x75** [openark/orchestrator#695]
Orchestrator prints the error message once a minute, is that normal?

config:
```
  "HostnameResolveMethod": "none",
  "MySQLHostnameResolveMethod": "",
```
Thanks.

**Comment by shlomi-noach** [comment]
Seems duplicate of https://github.com/github/orchestrator/issues/515, fixed by https://github.com/github/orchestrator/pull/547.

Which version are you using?

**Comment by shlomi-noach** [comment]
solved by https://github.com/github/orchestrator/pull/712

**Comment by shlomi-noach** [comment]
#712 is not merged yet. Reopening.
