### ISSUE TITLE
Strange martini logs

### ISSUE THREAD

**Issue by mia0x75** [openark/orchestrator#696]
Built up an orchestrator raft cluster with 134(leader)/135/136, then add mysql servers, open web page (135), it takes too long to finish the request, after check the log, I found these error logs

```
2018/11/07 16:37:39 [DEBUG] raft: Node 10.100.97.135:10008 updated peer set (2): [10.100.97.134:10008 10.100.97.135:10008 10.100.97.136:10008]
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124:56522
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135, 10.100.97.135
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135, 10.100.97.135, 10.100.97.135
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135
[martini] Started GET /web/cluster/alias/cs11 for 10.100.97.124, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135, 10.100.97.135
.
.
.
.
.
.
.

2018-11-07 16:38:29 ERROR Heath test is failing for over 5 seconds. raft yielding
2018/11/07 16:38:30 [DEBUG] raft-net: 10.100.97.135:10008 accepted connection from: 10.100.97.134:10662
2018-11-07 16:38:30 ERROR Heath test is failing for over 5 seconds. raft yielding
2018-11-07 16:38:31 ERROR Heath test is failing for over 5 seconds. raft yielding
2018-11-07 16:38:32 ERROR Heath test is failing for over 5 seconds. raft yielding
2018/11/07 16:38:34 [ERR] raft-net: Failed to flush response: write tcp 10.100.97.135:10008->10.100.97.134:10642: write: broken pipe
2018-11-07 16:38:34 ERROR Heath test is failing for over 5 seconds. raft yielding
2018-11-07 16:38:40 ERROR Heath test is failing for over 5 seconds. raft yielding
2018-11-07 16:38:40 ERROR Heath test is failing for over 5 seconds. raft yielding
2018-11-07 16:38:42 ERROR Heath test is failing for over 5 seconds. raft yielding
2018-11-07 16:38:42 ERROR Heath test is failing for over 5 seconds. raft yielding
2018-11-07 16:38:43 ERROR Heath test is failing for over 5 seconds. raft yielding
2018-11-07 16:38:44 ERROR Heath test is failing for over 5 seconds. raft yielding
2018-11-07 16:38:52 ERROR Heath test is failing for over 5 seconds. raft yielding
2018/11/07 16:38:56 [WARN] raft: Heartbeat timeout from "" reached, but leadership suspended. Will not enter Candidate mode
2018/11/07 16:41:19 [ERR] raft: Failed to make RequestVote RPC to 10.100.97.134:10008: dial tcp 10.100.97.134:10008: i/o timeout
2018/11/07 16:41:19 [ERR] raft: Failed to make RequestVote RPC to 10.100.97.136:10008: dial tcp 10.100.97.136:10008: i/o timeout
2018-11-07 16:41:19 ERROR Heath test is failing for over 5 seconds. raft yielding
2018-11-07 16:41:19 ERROR Heath test is failing for over 5 seconds. raft yielding
2018/11/07 16:41:21 [DEBUG] raft-net: 10.100.97.135:10008 accepted connection from: 10.100.97.134:10716
2018-11-07 16:41:22 ERROR Heath test is failing for over 5 seconds. raft yielding
2018/11/07 16:41:23 http: proxy error: context canceled
2018/11/07 16:41:24 [DEBUG] raft: Votes needed: 2
2018/11/07 16:41:24 [DEBUG] raft: Vote granted from 10.100.97.135:10008. Tally: 1
2018-11-07 16:41:24 ERROR Heath test is failing for over 5 seconds. raft yielding
2018-11-07 16:41:25 FATAL Node is unable to register health. Please check database connnectivity.
```

Notice: machine cs11 is not 124, the error log is very strange.

**Comment by shlomi-noach** [comment]
what happens when you hit:

- `/api/raft-status`
- `/api/raft-leader`
- `/api/raft-health`

on each of the hosts?
Sounds to me like raft could not set up.

**Comment by mia0x75** [comment]
orchestrator crashes on 135

```
$ curl http://10.100.97.135:3000/api/leader-check
curl: (7) Failed to connect to 10.100.97.135 port 3000: Connection refused
```

136 is the new leader
```
$ curl http://10.100.97.136:3000/api/leader-check
"OK"
```

orchestrator cluster setup:
```
.
.
.
  "HostnameResolveMethod": "none",
  "MySQLHostnameResolveMethod": "",
.
.
.
  "RaftEnabled": true,
  "RaftBind": "10.100.97.134",
  "DefaultRaftPort": 10008,
  "RaftDataDir": "/var/lib/orchestrator",
  "RaftNodes": [
    "10.100.97.134",
    "10.100.97.135",
    "10.100.97.136"
  ],
.
.
.
```

repeat steps:
1, setup orchestrator cluster
2, add master slave mysql replication cluster (1 master, 2 slaves), see the screenshot below
![screenshot from 2018-11-08 09 59 07](https://user-images.githubusercontent.com/5111356/48173054-2f3f7c00-e33d-11e8-95b4-101be7e19010.png)
3, shutdown master
4, refresh web page

**Comment by shlomi-noach** [comment]
Thank you. Just to clarify, to reproduce you shutdown master of MySQL cluster and that leads to a crash of the `orchestrator` leader?

**Comment by mia0x75** [comment]
Yes, keep web page auto refresh.

**Comment by shlomi-noach** [comment]
@mia0x75 sorry, I don't understand. Keeping the web page auto-refresh is what causing the `orchestrator` leader to crash? Withgout auto-refresh it does not crash?

Can you please clarify what are the steps to reproduce the problem?

**Comment by mia0x75** [comment]
No idea, but it is martini log, somehow I guess.

**Comment by shlomi-noach** [comment]
I'm unable to reproduce this at this time. I could really use the answers to https://github.com/github/orchestrator/issues/696#issuecomment-436625378. Writing again below:

what happens when you hit:

- `/api/raft-status`
- `/api/raft-leader`
- `/api/raft-health`

on each of the hosts?

**Comment by mia0x75** [comment]
I can setup a cluster on cloud servers, and send the login info to you, could you leave your email?

**Comment by shlomi-noach** [comment]
I'd prefer not to go down that way.

**Comment by makmanalp** [comment]
Hi @shlomi-noach, turns out we've hit this exact same issue and managed to narrow it down a bit.

For us, orchestrator runs out of memory if we kill the master in kubernetes (this is a problem when we’re doing rolling restarts - it’ll get stuck in a crash loop)? It has something to do with orchestrator’s new proxy-to-master mechanism: after it boots up it thinks it’s proxying to the master but the address it’s proxying to is itself. So any request is infinitely proxied to itself, which grows the `X-Forwarded-For` header in an infinite loop until the container runs out of memory and gets killed. My current (weak) theory is a race condition inside around `raftReverseProxy`: https://gist.github.com/makmanalp/8bc764beda887079aff8d4bb1fec3780

**Comment by makmanalp** [comment]
(Happy to make a new bug report if that helps!)

**Comment by shlomi-noach** [comment]
@makmanalp thank you for the fantastic detail in https://gist.github.com/makmanalp/8bc764beda887079aff8d4bb1fec3780 ; I'm looking into this.

**Comment by shlomi-noach** [comment]
Without reproducing as yet, what I believe the situation to be is:

- As you describe, the node was previously the leader, now demoted.
- It correctly identifies that it is not the leader, therefore  continues:

https://github.com/github/orchestrator/blob/151029a103429fe16123b9842d1a5b4b175bd5d5/go/http/raft_reverse_proxy.go#L21-L24

- It finds the leader, therefore continues:

https://github.com/github/orchestrator/blob/151029a103429fe16123b9842d1a5b4b175bd5d5/go/http/raft_reverse_proxy.go#L21-L24

- But, finds its own URI as the `LeaderUri` in: 

https://github.com/github/orchestrator/blob/151029a103429fe16123b9842d1a5b4b175bd5d5/go/http/raft_reverse_proxy.go#L29

- Which must imply that it has not received a notification for the change of leader URI. This change takes place here:

https://github.com/github/orchestrator/blob/151029a103429fe16123b9842d1a5b4b175bd5d5/go/logic/command_applier.go#L297-L304

Possibly the speed of redirects is so fast that we get OOM before the node finally gets told about the identity of the leader. Drafting a PR to avoid infinite loops.

**Comment by shlomi-noach** [comment]
@makmanalp please see https://github.com/github/orchestrator/pull/792
