### ISSUE TITLE
Meta database and tables referenced in configuration documentation are not created

### ISSUE THREAD

**Issue by EagleEyeJohn** [openark/orchestrator#701]
Hi

After following the installation and configuration instructions in order, you end up on [onfiguration-discovery-classifying](https://github.com/github/orchestrator/blob/master/docs/configuration-discovery-classifying.md) which mentions
```
ReplicationLagQuery": "select absolute_lag from meta.heartbeat_view",
```
But even though orchestrator has run, it has not created the meta database, either through not attempting to do so, else it failed because the initial setup creates a MySQL user with the privileges that allow it to only access the _orchestrator_ database.
```
mysql> show databases like 'orchestrator';
+-------------------------+
| Database (orchestrator) |
+-------------------------+
| orchestrator            |
+-------------------------+
1 row in set (0.00 sec)

mysql> show databases like 'meta';
Empty set (0.00 sec)
```

It would seem prudent to document the create of the database and tables?

There are historical references to meta database here:
- [Getting Started Orchestrator](https://blog.pythian.com/getting-started-orchestrator/)
- [Practical Orchestrator Tutorial](https://www.percona.com/live/e17/sites/default/files/slides/Practical%20Orchestrator%20Tutorial%20-%20FileId%20-%20115449.pdf)

**Comment by shlomi-noach** [comment]
As per https://github.com/github/orchestrator/blob/master/docs/configuration-discovery-classifying.md#replication-lag you are the one responsible to create the table, you choose your own table structure, you are responsible to tell `orchestrator` what query to use to read cluster-alias/instance-alias/replicaiton-lag.

To the best of my non-native English understanding, this is stated clearly. Please let me know if the language should change and how so.

**Comment by shlomi-noach** [comment]
Extra comment in documentation: https://github.com/github/orchestrator/pull/708/files#diff-00e64a8af4dd5116b95476a6691792dc
