### ISSUE TITLE
Bad characters in CHANGE MASTER

### ISSUE THREAD

**Issue by utdrmac** [openark/orchestrator#703]
I have no idea what happened. I'm testing out Orchestrator so all default config using sqlite backend.
mysql3 is master. mysql1 and mysql2 are slaves. I set up Orc and discovered the cluster. I went to shutdown mysql3 to see what would happen. No slave promotion happened (I think this is expected).
When I started mysql3 back up, neither of the slaves would reconnect. Checking slave status, I see this:

```
mysql1> show slave status\G
...
              Master_Log_File: //mysql-bin.000003:891
          Read_Master_Log_Pos: 891
               Relay_Log_File: mysql1-relay-bin.000001
                Relay_Log_Pos: 4
        Relay_Master_Log_File: //mysql-bin.000003:891
             Slave_IO_Running: No
            Slave_SQL_Running: Yes
```

```
[root@manager orchestrator]# ./orchestrator --version
3.0.13
603ef0df49be700607c371f9fc6fa4d12615cd21
```

**Comment by tomkrouper** [comment]
The title mentions bad characters in `change master`. Do you have logs showing this? Can you share, please?

**Comment by utdrmac** [comment]
Here is all of the logging during my test. Replication was working fine before I started Orc. I then did a simple `stop` on the master, mysql3. After I waited to see what Orc would do (about 3 minutes) and observing that Orc was not going to do any failover/slave promotion, I started mysql3 back up. Replication was not healed by Orc so I stopped Orc (ctrl-c) and tried to fix it myself. I simply did 'start slave' on mysql1 and then noticed errors in slave status and noticed the odd lines noted above. Since no other scripts are running, and since I made no changes to the slave config, I can only assume that Orc made these changes.

I will attempt to repeat this exercise to see if reproducible.

[orchestrator-log.txt](https://github.com/github/orchestrator/files/2567149/orchestrator-log.txt)

**Comment by utdrmac** [comment]
Repeating earlier scenario. Orc default config in place (except for MySQLTopologyUser and password updated). mysql3 is master. mysql2 and mysql1 are slaves.

<img width="749" alt="screen shot 2018-11-09 at 1 28 27 pm" src="https://user-images.githubusercontent.com/4413670/48283928-a0f1f580-e423-11e8-8799-2641edbc2f7e.png">

```
mysql1> show slave status\G
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: 192.168.70.30
                  Master_User: repl
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: mysql-bin.000004
          Read_Master_Log_Pos: 1306376
               Relay_Log_File: mysql1-relay-bin.000003
                Relay_Log_Pos: 1306589
        Relay_Master_Log_File: mysql-bin.000004
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
```

`[root@mysql3 ~]# systemctl stop mysql`

I annotated in the log when I stopped. Orc then showed me this:

<img width="754" alt="screen shot 2018-11-09 at 1 31 56 pm" src="https://user-images.githubusercontent.com/4413670/48284117-1c53a700-e424-11e8-8370-8c14329c6ddd.png">

I then clicked on Recover->Force recover (the only option) expecting Orc to promote one of the surviving slaves to be new master. This did not happen. Instead, I got the following:

<img width="657" alt="screen shot 2018-11-09 at 1 32 33 pm" src="https://user-images.githubusercontent.com/4413670/48284171-460cce00-e424-11e8-9328-0aec188febe0.png">

Clicking on the left cluster gives error:

<img width="704" alt="screen shot 2018-11-09 at 1 32 43 pm" src="https://user-images.githubusercontent.com/4413670/48284185-4efd9f80-e424-11e8-9ee2-ff3355ddbda4.png">

The "right" cluster shows this:

<img width="487" alt="screen shot 2018-11-09 at 1 32 52 pm" src="https://user-images.githubusercontent.com/4413670/48284198-545aea00-e424-11e8-93b7-544e4c88baf7.png">

And slave status on mysql1 shows those errant characters again.

```
mysql1> show slave status\G
*************************** 1. row ***************************
               Slave_IO_State: Connecting to master
                  Master_Host: 192.168.70.30
                  Master_User: repl
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: //mysql-bin.000004:1306376
          Read_Master_Log_Pos: 1306376
               Relay_Log_File: mysql1-relay-bin.000001
                Relay_Log_Pos: 4
        Relay_Master_Log_File: //mysql-bin.000004:1306376
             Slave_IO_Running: Connecting
            Slave_SQL_Running: Yes
```

And on mysql2 (a previous slave):

```
mysql2> show slave status\G
Empty set (0.00 sec)
```

Full log of the above reproduction: [orch-attempt2.txt](https://github.com/github/orchestrator/files/2567281/orch-attempt2.txt)

**Comment by utdrmac** [comment]
I repeated the issue again, this time I enabled the general log on mysql1 and saw this:

```
2018-11-09T11:53:09.806381Z	  138 Query	change master to master_log_file='//mysql-bin.000005:154', master_log_pos=154
```

So Orc is clearly changing the master to something incorrect/badly formatted

**Comment by shlomi-noach** [comment]
The leading `//` for the binary log file is the result of a `detach-replica` operation: this is a way to forcibly break replication, prevent it from running, but in a reversible way.
I'm guessing you did not invoke `detahc-replica` yourself, hence I assume you have `DetachLostReplicasAfterMasterFailover` or `MasterFailoverDetachReplicaMasterHost` configured as `true`. See https://github.com/github/orchestrator/blob/8d5e68425120e25494e5cca0903665255a155101/go/config/config.go#L236-L241

**Comment by utdrmac** [comment]
I have neither of those parameters in my config. I'm using the default config. Correct, I did not invoke detach-replica.
Ah, those are aliases. I do have `MasterFailoverDetachSlaveMasterHost: true`, and `DetachLostSlavesAfterMasterFailover: true`
Ok, now that I understand these characters are intended and for the reason, I'm good here.
