### ISSUE TITLE
SQL permission error for AutoPseudoGTID not visible in logs

### ISSUE THREAD

**Issue by utdrmac** [openark/orchestrator#704]
I tried searching through all the documentation for enabling AutoPseudoGTID and all I found was that I just need to set this:

```
[
...
  "AutoPseudoGTID": true,
...
]
```

mysql1 (S), mysql2 (S), mysql3 (M). Start Orc. Discover cluster in GUI. Check binary log of mysql3, no visible pseudogtids in binary logs. Nothing in GUI indicating pseudoGTID either. Nothing in orc log indicating error.

<img width="660" alt="screen shot 2018-11-09 at 4 55 30 pm" src="https://user-images.githubusercontent.com/4413670/48292658-d0fbc180-e440-11e8-9225-ec312059c83c.png">

 Not sure what else I need to set/configure to get this aspect working.

**Comment by utdrmac** [comment]
Sadly, re-reading the documentation more closely says I need to grant privileges to drop the PGTID fake tables. I missed this.

What bothers me about this most, is that Orchestrator gives NO ERROR messages about bad permissions or "permission denied to DROP VIEW". It's just completely silent.

I have debugging turned on in Orc, so I would have expected _any_ issues such as invalid permissions to show up in the log for diagnosis.

I'm going to leave this open to get a comment on why SQL permission errors are not visible in logs.

**Comment by shlomi-noach** [comment]
@utdrmac I see your point, but the design is different. From the [documentation](https://github.com/github/orchestrator/blob/master/docs/configuration-discovery-pseudo-gtid.md#automated-pseudo-gtid-injection):

> orchestrator will only attempt injecting Pseudo-GTID where it is allowed to do so. If you want to limit Pseudo-GTID injection to specific clusters, you may do so by only granting the privilege on those clusters you want orchestrator to inject Pseudo-GTID. You may disable Pseudo-GTID injection on a specific cluster via:
> REVOKE DROP ON _pseudo_gtid_.* FROM 'orchestrator'@'orch_host';

So this is less about "I can't inject pseudo-GTID therefore I should err" and more about "I'm permitted to inject Pseudo-GTID therefore I should do that".

**Comment by utdrmac** [comment]
@shlomi-noach I understand the design and can accept that. However, if someone has AutoPseudoGTID=true in their config, that means they want it (since the default is false). Since the user wants it, Orc should complain about not being able to do what the user wants. "i know you want me to do this, but i cannot because of X"

**Comment by shlomi-noach** [comment]
I see your point. I need to figure out how to do this without bloating the logs.

**Comment by shlomi-noach** [comment]
Addressed by #709
