### ISSUE TITLE
Add 'GTID' to button name

### ISSUE THREAD

**Issue by utdrmac** [openark/orchestrator#713]
https://github.com/github/orchestrator/blob/113d3ba9238063a8c16a9e78a927b51cc6d68cbe/resources/templates/layout.tmpl#L216

When viewed in the GUI, this button just says "Enable" with no tooltip or other indication of what its purpose is. Not until you click the button are you presented with a box that asks if you want to enable GTID. If the button was labeled "Enable GTID", it would clear what it is for.

Same for when this button says 'Disable' and the other button that just says "Fix" (maybe "Fix Errant GTID"?)

**Comment by shlomi-noach** [comment]
But, the button is in the context of a `GTID based replication` line. I would think it would be superfluous to name the button "Enable GTID based replication".

![screen shot 2018-11-14 at 07 18 31](https://user-images.githubusercontent.com/2607934/48461689-86ca6580-e7dd-11e8-9191-c40c15e24d15.png)

Likewise, the "Fix" button comes in a "GTID errant" context, renaming it to "Fix errant GTID" would be superfluous.

![screen shot 2018-11-14 at 07 49 31](https://user-images.githubusercontent.com/2607934/48462718-f3dffa00-e7e1-11e8-9e5e-2bf37e0ff21b.png)


What do you think?

**Comment by utdrmac** [comment]
I think we are looking in different locations. I'm referring to the very bottom of a server config box. It just says "Enable". Even if you mouse-hover, it doesn't say anything about GTID. Not until you actually click it, does it prompt you to enable GTID.

<img width="408" alt="screen shot 2018-11-14 at 2 23 15 pm" src="https://user-images.githubusercontent.com/4413670/48510277-00337980-e819-11e8-87d3-7f5e8d471446.png">

**Comment by shlomi-noach** [comment]
Then this is a bug.

**Comment by shlomi-noach** [comment]
I'm unable to reproduce this, and for me the button appears in the correct context. Could you screenshot the entire pop up dialog please?

![screen shot 2018-11-15 at 07 56 04](https://user-images.githubusercontent.com/2607934/48533156-00c92000-e8ac-11e8-8774-f1ee142c472c.png)

**Comment by utdrmac** [comment]
<img width="771" alt="screen shot 2018-11-15 at 12 29 36 am" src="https://user-images.githubusercontent.com/4413670/48534390-98f3e480-e86d-11e8-93ee-241aa8463a25.png">
<img width="1241" alt="screen shot 2018-11-15 at 12 29 46 am" src="https://user-images.githubusercontent.com/4413670/48534391-998c7b00-e86d-11e8-8ded-aa4c9af90906.png">

**Comment by shlomi-noach** [comment]
addressed by https://github.com/github/orchestrator/pull/717

**Comment by shlomi-noach** [comment]
As per https://github.com/github/orchestrator/pull/717#issuecomment-439149247 button appears on bottom instead of on relevant row, when enabled.

**Comment by shlomi-noach** [comment]
> This fixes the button not showing when GTID is not possible, but when possible to enable, the button still shows at the bottom and still only says the word "Enable". There is not any indication this "Enable" button refers to GTID.

@utdrmac this does not reproduce for me. Could you please `Shift`-Refresh to make sure the latest `js` files are loaded into browser's cache?

**Comment by shlomi-noach** [comment]
woot! Just reproduced, on a dead/unseen server.

**Comment by utdrmac** [comment]
Sweet. Sorry I couldn’t reply; been traveling for holiday.
