### ISSUE TITLE
FR: Failed/Missing/Invalid slaves are not visible in audit; no hooks

### ISSUE THREAD

**Issue by utdrmac** [openark/orchestrator#714]
4 VMs: mysql1(M), mysql2(S), mysql3(S), orc/app server

`[root@mysql3 ~]# iptables -A INPUT -s app -j DROP; iptables -A OUTPUT -s app -j DROP`

Orchestrator detects this slave has "failed" since it cannot contact it due to "network failure". But I don't see anything in the Audit->Failure Detection. I also do not see any hooks that I can leverage here.

I just read in docs/failure-detection.md that orchestrator doesn't care about these types of failures. Is this due to additional complexity required in Orc? I can see situations where environments would like to leverage Orc's monitoring of all mysql hosts for simple failures like this and at least fire off a hook/KV-update to integrate with their monitoring.

More complexity would be validating that the slave is "ok" by looking at show slave hosts or processlist on the slave's immediate master to determine if there is a real issue or if the issue is orc/slave network. I can see how that would be beyond the scope of orc, but still seems like a hook script for any mysql failure that orc manages would be nice to have.

**Comment by shlomi-noach** [comment]
> I just read in docs/failure-detection.md that orchestrator doesn't care about these types of failures.

correct.

> Is this due to additional complexity required in Orc?

It has to do with the job `orchestrator` was designed for: managing topologies and running failovers. I do not perceive `orchestrator` as a general purpose MySQL monitoring tool.

If we were to take this one step further, you'd want `orchestrator` to fire a hook any time a replica is unseen, or when `io thread` has error, or replication just stops, or replica starts lagging, or stops lagging, or changes GTID mode, or changes semi-sync mode, etc. etc.

`orchestrator` does make all these possible. Through its API you can observe all those properties and act accordingly.

**Comment by utdrmac** [comment]
Understood. Thanks!
