### ISSUE TITLE
Help Request: Failover for Intermediate Master(slave of a master)

### ISSUE THREAD

**Issue by SQLadmin** [openark/orchestrator#716]
I have pasted my topology below. Here `bhuvi-dr1` is a slave but its the master for `bhuvi-dr2`

![image](https://user-images.githubusercontent.com/16044251/48475248-653f9d00-e822-11e8-9f89-97b2c2d33693.png)
Orchestrator will perform a failover when bhuvi-dr1 went down and bhuvi-dr2 become a new master? actually Im looking a solution like this.

**Comment by shlomi-noach** [comment]
> and bhuvi-dr2 become a new master

Can you please explain again what it is you're trying to achieve?

Related/unrelated: do all replicas have same or different replication filters?

**Comment by shlomi-noach** [comment]
See some interesting discussion about intermediate-master promotion rules and limitations (in case of filters) here: https://github.com/github/orchestrator/issues/46

**Comment by SQLadmin** [comment]
The initial  implementation was
```
bhuvi-1 --> bhuvi-2
  |---------> bhuvi-3
```
We need one more database server which needs 90% of the production tables with real time data and having 10+ additional table for some financial calculations and reporting.  So we decided to replicate entire data from `bhuvi-1` to `bhuvi-dr` 

But the this finance reporting somethings sync with some payment gateways. So it must be a highly available one. The payment getways tables are only available on `bhuvi-dr1` not available on `bhuvi-1,2,3`

This is the requirement and we will use this `bhuvi-dr1` as an archive server. We'll maintain many years of records here. And in terms of replication all are using same filters.

**Comment by shlomi-noach** [comment]
I'm not sure if I got it straight: my understanding is that your intermediate master (`bhuvi-dr`) is taking writes that are not seen on the cluster's master.

This puts you in a very delicate position on all things replication and recoveries. e.g. you don't want to promote `bhuvi-dr` as master (I think this was discussed in an earlier issue).

I'm still missing the answer, though: what it is you're trying to achieve?

**Comment by SQLadmin** [comment]
Yes, your understanding is correct. 
I want to implement 2 different failover cases on one single cluster.

1. if `bhuvi-1` goes down then `bhuvi-2` or `bhuvi-3` can be a new master. Here it should not touch `bhuvi-dr1` and `bhuvi-dr2`.
2. If `bhuvi-dr1` goes down, at this time bhuvi1,2,3 and dr2 are available. So I want to promote `dr2` as a new master.

In more simple words, 

`bhuvi 1,2,3` are main servers. They can do failover between them.
`dr1` and `dr2 ` for 3rd patty, So the failover should perform only between `dr1` and `dr2`

 I mean hard limit here like DR1 down == DR2 will be master.  Bhuvi1 down == 2 or 3 will be the master. So DR server will replicate from 2 or 3

**Comment by shlomi-noach** [comment]
>  So I want to promote dr2 as a new master.

This is confusing. You want to promote it as new Intermediate Master, right? Not as master, because the master never went down in scenario 2.

> I mean hard limit here like DR1 down == DR2 will be master

So that's up to you, really. `orchestrator` will make sure when `DR1` dies that `DR2` will connect to the replication tree. There's nothing else `orchestrator` should do. For your convenience, you will define [hooks](https://github.com/github/orchestrator/blob/master/docs/configuration-recovery.md#hooks) and in particular `PostIntermediateMasterFailoverProcesses`, and your own code will do what needs to be done. Like set it writable and advertise the identity of the promoted server.

**Comment by SQLadmin** [comment]
> You want to promote it as new Intermediate Master, right? Not as master, because the master never went down in scenario 2.

Exactly this is what Im looking for. If dr1 goes down, then dr2 will be the new intermediate master.

Just for the clarification,
I'll make config like this `PromotionIgnoreHostnameFilters` =`bhuvidr1`. 

So if bhuvi1 goes down It can promote whether bhuvi2 or 3 or 4 but it'll not promote dr1 and dr2

**Comment by shlomi-noach** [comment]
>  If dr1 goes down, then dr2 will be the new intermediate master.

But, intermediate master to who? Will it have a replica? It doesn't seem so looking at your existing topology. So it will just connect back to the topology, without becoming anything special.

> I'll make config like this PromotionIgnoreHostnameFilters =bhuvidr1.

You can do that, although I suggested earlier that you can use `promotion-rule`s.

**Comment by SQLadmin** [comment]
But, intermediate master to who? Will it have a replica? It doesn't seem so looking at your existing topology. So it will just connect back to the topology, without becoming anything special.

Current setup:
`bhuvi1 --> dr1 --> dr2`

DR1 is down then
`bhuvi --> dr2 (read only should be off) `

**Comment by shlomi-noach** [comment]
`dr2` will be placed somewhere in the topology (not necessarily under master). You will need to take care of `read_only`.

**Comment by SQLadmin** [comment]
Ok, thanks

**Comment by SQLadmin** [comment]
One last question :)

1. If dr1 down then dr2 will replicate from any other existing slave? or directly from bhuvi1
2. If i want to use some hooks during the downtime of DR1 can I use `PostIntermediateMasterFailoverProcesses`

**Comment by shlomi-noach** [comment]
1. test
2. That's what I suggested.

**Comment by SQLadmin** [comment]
Great thanks 👍
