### ISSUE TITLE
open 3000  html/template: "templates/layout" is undefined

### ISSUE THREAD

**Issue by dbaspace** [openark/orchestrator#725]
start log:
 DEBUG Waiting for 15 seconds to pass before running failure detection/recovery

WEB DISPLAY:
http://172.16.0.75:3000/web/clusters
html/template: "templates/layout" is undefined
how to do

**Comment by shlomi-noach** [comment]
It seems to me like you're running the `orchestrator` binary but without extracting the full `resources/` associated path and subpaths.

How did you install `orchestrator`? https://github.com/github/orchestrator/blob/master/docs/install.md

**Comment by dbaspace** [comment]
ths,download again ok
