### ISSUE TITLE
Orchestrator fails to promote "preferred" slave in case of master-master.

### ISSUE THREAD

**Issue by ghost** [openark/orchestrator#728]
We have the following replication topology (master-master (one RW and one RO) with slave on each, GTID,  "CoMasterRecoveryMustPromoteOtherCoMaster": false):
```
M1(rw) -> S1
↕
M2(ro) -> S2 
```
I would like to promote S1 in case of M1 crashes. So I set "prefer" promotion rule to S1.
If after crash of M1, M2 is the most up-to date replica, then I can not promote S1 even, if it has "prefer" rule. Orchestrator always promotes M2:

> 2018-11-20 11:12:29 INFO topology_recovery: promoted instance M2 is not the suggested candidate S1. Will see what can be done
> 2018-11-20 11:12:29 INFO topology_recovery: suggested candidate S1 is replica of promoted instance M2. Will try and take its master
> 2018-11-20 11:12:29 ERROR M2 is co-master. Cannot take it.

Looks like it fails on TakeMaster func
 https://github.com/github/orchestrator/blob/b4cc5895929fa8fb3f104af80aa5b6129245295b/go/inst/instance_topology.go#L1660

If I understood correctly the source code, the following is happening in my case:
1. M1 crashes and Orchestrator promotes M2 as the most up-to-date replica.
2. Then Orchestrator searches for better candidate and finds S1.
3. It tries to make S1 master, but fails on TakeMaster func, when checks, whether M2 is co-master or not.

I hope the explanation is clear and helpful. 
Thank you for looking into this.

**Comment by shlomi-noach** [comment]
reference: https://github.com/github/orchestrator/issues/724

What is your configuration for `CoMasterRecoveryMustPromoteOtherCoMaster`?

**Comment by shlomi-noach** [comment]
Are you able to test https://github.com/github/orchestrator/pull/734 ?

**Comment by ghost** [comment]
@shlomi-noach, thank you for fix. I've tested it.
Promotion of S1 happened this time.
But there is still problem that I noticed and my bad that I did not describe the issue correctly.
M1 actually has several slaves:
```
M1 -> S1
   -> S3
   -> S4
```
After promotion of S1, S3 and S4 remained under M2. So I've got this:
```
S1 -> M2 -> S2
         -> S3
         -> S4
```
While expected result is:
```
S1 -> M2 -> S2
   -> S3
   -> S4

```

PS: you've asked about CoMasterRecoveryMustPromoteOtherCoMaster. It is "false" in our config.

**Comment by shlomi-noach** [comment]
> While expected result is

The topology after failover can be one of various scenarios. I'll share that I've seen many issues about what people perceive as "expected" after failover, and people perceive different things. Some want to contain everything within the same DC. Others want to forcibly move everything to the other DC.

Since the resulting topology is _valid_ I'm not sure I want to go down the path of making it make sense to everyone. There is one step to be added that "makes sense" to me in general, which is, when two steps are involved as in this case, and S1 takes over M1, that S1 should also own M1's replicas.

This is yet another step in a long and complex failover logic, that will also consume recovery time -- something I'm not keen on, either.

**Comment by ghost** [comment]
@shlomi-noach , right, I understand that. I speak from one company standpoint.
As you have wider view, you may decide better about adding or not the last step.

My thoughts about it:
As the slaves were moved once already, the second move should be relatively fast and reliable.
PS: TakeMaster was the slowest part in my test. With lag on slaves around 30s during crash, it took exactly 30s. I suppose it was waiting for all missing events to be applied on S1. It is good and by default should be like this. If someone wants faster recovery with data loss, it should be set explicitly (although I am not sure it is possible now :) ).

**Comment by shlomi-noach** [comment]
OK, what I'll do is merge #734 and consider the rest of the operation in a different PR, since it's tangential to the `TakeMaster` problem.

**Comment by shlomi-noach** [comment]
See https://github.com/github/orchestrator/pull/738

**Comment by ghost** [comment]
@shlomi-noach, #738 is conflicting with #734 in `go/logic/topology_recovery.go`:
```
<<<<<<< HEAD
                AuditTopologyRecovery(topologyRecovery, fmt.Sprintf("replace-promoted-replica-with-candidate: suggested candidate %+v is replica of promoted instance %+v. Will try and take its master", candidateInstance.Key, promotedReplica.Key))
                candidateInstance, err = inst.TakeMaster(&candidateInstance.Key)
=======
                AuditTopologyRecovery(topologyRecovery, fmt.Sprintf("suggested candidate %+v is replica of promoted instance %+v. Will try and take its master", candidateInstance.Key, promotedReplica.Key))
                candidateInstance, err = inst.TakeMaster(&candidateInstance.Key, topologyRecovery.Type == CoMasterRecovery)
>>>>>>> remotes/origin/recover-dead-co-master-take-master
```
Looks like `topologyRecovery.Type == CoMasterRecovery` is set for all cases in #734, not just for CoMaster recovery. Or I misunderstand it?

**Comment by shlomi-noach** [comment]
> Looks like topologyRecovery.Type == CoMasterRecovery is set for all cases in #734, not just for CoMaster recovery. Or I misunderstand it?

Not sure I understand the question, and I want to be careful in my answer. What does "for all cases" mean?

**Comment by ghost** [comment]
By "all cases" I meant `recoverDeadMaster` and `RecoverDeadCoMaster` functions :).
But I as I said, I could just misunderstood something. 
I want to test both #734 and #738, but they are conflicting.

**Comment by shlomi-noach** [comment]
The would-be merge is:

```
                AuditTopologyRecovery(topologyRecovery, fmt.Sprintf("replace-promoted-replica-with-candidate: suggested candidate %+v is replica of promoted instance %+v. Will try and take its master", candidateInstance.Key, promotedReplica.Key))
                candidateInstance, err = inst.TakeMaster(&candidateInstance.Key, topologyRecovery.Type == CoMasterRecovery)
```

**Comment by shlomi-noach** [comment]
#734 is merged. Try out #738
