### ISSUE TITLE
Using orchestrator  with servers using `replicate-` variables 

### ISSUE THREAD

**Issue by kowalskey** [openark/orchestrator#729]
Hello!

I have MariaDB replication setups using additional variables to control which databases and tables are actually getting replicated (in multi-master scenario when one slave replicates two databases from different hosts).

e.g:
```
            (replicate db1)
master1 ----\
             >---------- slave
master2 ----/
             (replicate db2)

```

replication is controlled by per-connection variables like `replicate-wild-do-table` or `replicate-wild-do-db`

Is there a way to use orchestrator with such configuration?

**Comment by shlomi-noach** [comment]
regardless of `replicate-*` setup, `orchestrator` does not support multisource replication.

- https://github.com/github/orchestrator/blob/master/docs/supported-topologies-and-versions.md
- https://github.com/github/orchestrator/issues/433
- https://github.com/github/orchestrator/issues/38

**Comment by kowalskey** [comment]
@shlomi-noach thank you. I missed it while browsing docs. 
I am closing this issue because my question is now answered.
