### ISSUE TITLE
accoding to web api add new instance 

### ISSUE THREAD

**Issue by dbaspace** [openark/orchestrator#732]
[martini] Completed 500 Internal Server Error in 18.22924ms
web show running 
![image](https://user-images.githubusercontent.com/23513271/48878215-86ffdc00-ee41-11e8-83bd-3eeffe923e6a.png)
check ping 👍
[root@xhhost75 orchestrator]# ping test9.hualala.com
PING test9.hualala.com (172.16.0.29) 56(84) bytes of data.
64 bytes from test9.hualala.com (172.16.0.29): icmp_seq=1 ttl=64 time=20.0 ms
64 bytes from test9.hualala.com (172.16.0.29): icmp_seq=2 ttl=64 time=18.8 ms

**Comment by dbaspace** [comment]
this name "test9.hualala.com" is master ,just now ,enter slave ip is ok but 
![image](https://user-images.githubusercontent.com/23513271/48878443-5ff5da00-ee42-11e8-8552-4f04dac35c71.png)

**Comment by shlomi-noach** [comment]
Please be more clear. I do not understand what is the question/bug/problem.

**Comment by dbaspace** [comment]
db add repost_host is ok
