### ISSUE TITLE
Question: Recovery in Mixed Replication Asynch/Semisync Environment

### ISSUE THREAD

**Issue by hamzahsa94** [openark/orchestrator#742]
Is it possible for orchestrator to perform an instance recovery in a mixed asynchronous and semisynchronous environment?

The environment is split across two data centers:
1. Each data center has a semisync master
2. Each data center has two semisync replicas
3. The semisync masters are asynchronous comasters
4. The two masters (one in each DC) are writeable
5. The slaves are read-only

The topology is as below:
![image](https://user-images.githubusercontent.com/37233366/49190156-0734ae80-f326-11e8-8e69-87253be7387e.png)

```
+ dc1DB01:3306   [0s,ok,5.7.23-log,rw,MIXED,>>,GTID]
  + dc1DB02:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
  + dc1DB03:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
+ dc2DB01:3306   [0s,ok,5.7.23-log,rw,MIXED,>>,GTID]
  + dc2DB02:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
  + dc2DB03:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
```
I tried setting the below options:
"CoMasterRecoveryMustPromoteOtherCoMaster": false
"ApplyMySQLPromotionAfterMasterFailover": true

On shutting down dc1DB01, Orchestrator changed the topology to below:
```
+ dc2DB01:3306   [0s,ok,5.7.23-log,rw,MIXED,>>,GTID]
  + dc1DB02:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
    + dc1DB03:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
  + dc2DB02:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
  + dc2DB03:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
```
But no semisync settings were changed. Thus dc1DB02 still had semisyncmaster:OFF and semisyncreplica:ON

I would prefer the topology to change to something like below, where dc1 promotes the most advanced slave to a comaster of dc2DB01 (R/W), while dc1DB03 becomes the local slave:
```
+ dc1DB02:3306 [0s,ok,5.7.23-log,rw,MIXED,>>,GTID]
  + dc1DB03:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
+ dc2DB01:3306   [0s,ok,5.7.23-log,rw,MIXED,>>,GTID]
  + dc2DB02:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
  + dc2DB03:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
```
And if dc1DB01 should come back, it would be configured as a slave of dc1DB02 (R only):
```
+ dc1DB02:3306   [0s,ok,5.7.23-log,rw,MIXED,>>,GTID]
  + dc1DB03:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
  + dc1DB01:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
+ dc2DB01:3306   [0s,ok,5.7.23-log,rw,MIXED,>>,GTID]
  + dc2DB02:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
  + dc2DB03:3306 [0s,ok,5.7.23-log,ro,MIXED,>>,GTID]
```

I believe if automated recovery is disabled, I could run a script that checks the status of instances in the topology and then run scripts that connect with the orchestrator API and perform the relocation. But is it possible to have orchestrator do it automatically?

**Comment by shlomi-noach** [comment]
Thank you. If I'm reading this right, these are two different requests. First, that semi sync is applied according to some rule, after failover. Second, that `orchestrator` failovers a master-master setup into a master-master setup.
With regard the second, please see some discussion in https://github.com/github/orchestrator/issues/740. At this time `orchestrator` does not re-create a master-master setup on a master-master failure. The reasoning is:
- By virtue of master-master, you are always left with at least one good master to run off
- The rules for choosing the alternate co-masters vary between different users
- There's multiple risks in trying to rewire a master master setup. 

All things semi-sync, `vitess` have contributed semi-sync enforcement: https://github.com/outbrain/orchestrator/pull/187
I haven't used this myself.

But what I'm thinking is that you have your particular setup, and want it to turn into another particular setup. Based on the years supporting this project I've seen different users asking for different, contradicting things, and I hesitate to choose a particular course of action such as the one you suggest.

I'd suggest using the post-failover hooks to enable semi-sync master/replica side (use `orchestrator-client -c enable-semi-sync-master|enable-semi-sync-replica` as needed). 

> I believe if automated recovery is disabled, I could run a script that checks the status of instances in the topology and then run scripts that connect with the orchestrator API and perform the relocation. 

You can do the same when automated recovery is enabled. `orchestrator` will resolve the topology into something valid, and you can folllow up with post-failover hooks to set it up the particular way you like it.

**Comment by hamzahsa94** [comment]
Thank you Shlomi!

I followed the process and used the post-failover hooks to change the topology into master-master, with the semi-sync config changes.
