### ISSUE TITLE
want to expose "force-master-takeover" by http api & orchestrator-client

### ISSUE THREAD

**Issue by MOON-CLJ** [openark/orchestrator#743]
want to expose "force-master-takeover" by http api & orchestrator-client。only available in cli currently。

**Comment by shlomi-noach** [comment]
`force-master-failover` exists in API and in `orchestrator-client`.

API:
- `force-master-failover/:host/:port`
- `force-master-failover/:clusterHint`

`orchestrator-client`:
- `orchestrator-client -c force-master-failover`

```shell
$ orchestrator-client -c help | grep force
    force-master-failover                    Forcibly discard master and initiate a failover, even if orchestrator doesn't see a problem. This command lets orchestrator choose the replacement master
```

**Comment by MOON-CLJ** [comment]
@shlomi-noach i mean "force-master-takeover" not "force-master-failover"

**Comment by shlomi-noach** [comment]
Ah, sorry, I wasn't reading this right.
Yes, it's possible to add to `api` and to `orchestrator-client`, though I've been having thoughts on the usefulness of this command. I never use it, and have instead opted to use either `graceful-master-takeover` or `force-master-failover`.

`force-master-takeover` is for when a recovery should be taking place, but is not, and you want to force it, and you also indicate where to failover too.
In my current thinking, is something like this happens I'd rather `orchestrator` just failed over where it needs to, and the burden of picking a specific destination is a harsh constraint during an outage situation.

Does that makes sense?

**Comment by MOON-CLJ** [comment]
@shlomi-noach such as a situation，the old master is very busy，we cant execute GracefulMasterTakeover，but we also want to issue a destination to promote，so we can only use ForceMasterTakeover。

**Comment by shlomi-noach** [comment]
Very good. I'll add the API

**Comment by MOON-CLJ** [comment]
@shlomi-noach thx! if you don't have much time, we can do this。we already have a commit to do this，should we give a pull request？

**Comment by shlomi-noach** [comment]
Yes, please.

**Comment by MOON-CLJ** [comment]
thx
