### ISSUE TITLE
should RelocateReplicas execute after PreGracefulTakeoverProcesses in GracefulMasterTakeover?

### ISSUE THREAD

**Issue by MOON-CLJ** [openark/orchestrator#744]
PreGracefulTakeoverProcesses execute after RelocateReplicas in GracefulMasterTakeover currently，but if PreGracefulTakeoverProcesses failed，the cluster topology stop at intermediate state，that is not what we want。

**Comment by shlomi-noach** [comment]
This is the exact opposite from an earlier request. I'm always reminded of how different users have completely different opinion on how things should work.

The counter-opinion is: if we are not successful in moving replicas, then we shouldn't failover, and we shouldn't invoke `PreGracefulTakeoverProcesses`.

**Comment by MOON-CLJ** [comment]
@shlomi-noach okay, i see。should we add one more "promotion actions" ，ApplyMySQLPromotionAfterMasterFailover alike。

**Comment by shlomi-noach** [comment]
I'd rather not. How about: after relocating replicas, and assuming pre-hooks fail, `orchestrator` moves (or attempts to move) back replicas to their original location?

**Comment by MOON-CLJ** [comment]
@shlomi-noach it works，but it make things  more complicate and also some bad impact。for example , "stop slave" will wait for a long binlog event，it is so heavy for our situation when PreGracefulTakeoverProcesses failed，because we just want to do nothing。

if not accepted，maybe we can patch ourself，just move some lines of code。

**Comment by MOON-CLJ** [comment]
thx! "PreGracefulTakeoverProcesses execute after RelocateReplicas in GracefulMasterTakeover" seems also work for us after think twice。

**Comment by MOON-CLJ** [comment]
because we can just do necessary stuffs before call graceful takeover api，instead of asking to put PreGracefulTakeoverProcesses before RelocateReplicas。
