### ISSUE TITLE
how to change  masterRecoveryType=MasterRecoveryPseudoGTID  recovery type

### ISSUE THREAD

**Issue by Voltron-Patcher** [openark/orchestrator#750]
Hi，
   I test several times，the default masterRecoveryType is  MasterRecoveryPseudoGTID, and the sample config file  lost AutoPseudoGTID , so  orchestrator can not auto failover.

  So，i want to test  other  masterRecoverType， such as MasterRecoveryBinlogServer， but i can't find configureation of  MasterRecoveryType。

**Comment by shlomi-noach** [comment]
Did you find what you were looking for?
