### ISSUE TITLE
New Orchestrator node stuck on Candidate state trying to elect

### ISSUE THREAD

**Issue by cohenjo** [openark/orchestrator#755]
Hi,
I'm adding a new Orchestrator node (4th one), when I spin it up it get's stuck trying to get elected with the other nodes shrugging him off.
I think I miss something in the bootstrapping process for a new node.

## Details
The other nodes have him in the peer list when they start:
```
2018-12-12 07:33:07 DEBUG raft: peers=[10.196.27.3:10008 10.42.183.98:10008 10.84.169.52:10008 10.96.18.8:10008]
...
2018/12/12 07:33:11 [DEBUG] raft-net: 10.84.169.52:10008 accepted connection from: 10.196.27.3:54349
...
2018/12/12 07:33:12 [WARN] raft: Rejecting vote request from 10.196.27.3:10008 since we have a leader: 10.96.18.8:10008. 
```

while it is stuck looping:
``` 2018/12/12 07:33:24 [WARN] raft: Election timeout reached, restarting election
2018/12/12 07:33:24 [INFO] raft: Node at 10.196.27.3:10008 [Candidate] entering Candidate state
2018/12/12 07:33:24 [DEBUG] raft: Votes needed: 3
2018/12/12 07:33:24 [DEBUG] raft: Vote granted from 10.196.27.3:10008. Tally: 1
2018/12/12 07:33:24 [WARN] raft: Remote peer 10.96.18.8:10008 does not have local node 10.196.27.3:10008 as a peer
2018/12/12 07:33:24 [WARN] raft: Remote peer 10.42.183.98:10008 does not have local node 10.196.27.3:10008 as a peer
2018/12/12 07:33:24 [WARN] raft: Remote peer 10.84.169.52:10008 does not have local node 10.196.27.3:10008 as a peer 
```

configuration (same on all nodes):
```
  "RaftDataDir": "/var/lib/orchestrator",
  "RaftEnabled": true,
  "RaftBind": "10.196.27.3", <-- this obviously different per node
  "DefaultRaftPort": 10008,
  "RaftNodes": [
    "10.196.27.3",
    "10.42.183.98",
    "10.84.169.52",
    "10.96.18.8"
  ], 
```

Appreciate any help :)
Thanks,
 - Jony

**Comment by shlomi-noach** [comment]
That is weird indeed. May I assume you've tried restarting the 4th node after having restarted the original three?

**Comment by cohenjo** [comment]
yes, yes  - it's even listed in the peers list when they started up.
(I run with debug so it's in the log)

is there a way to forcefully align its leader info?

**Comment by shlomi-noach** [comment]
> yes, yes - it's even listed in the peers list when they started up.

My question was whether you've restarted the 4th after having restarted the original three?

not sure what "align its leader info" means?

**Comment by cohenjo** [comment]
yes, restarted them all.
I meant it looks like it tries to be elected because it doesn't know of the current leader.
but they ignore it simply because there is already a leader...

**Comment by shlomi-noach** [comment]
I have no immediate advice. Per:
```
2018/12/12 07:33:24 [WARN] raft: Remote peer 10.96.18.8:10008 does not have local node 10.196.27.3:10008 as a peer
2018/12/12 07:33:24 [WARN] raft: Remote peer 10.42.183.98:10008 does not have local node 10.196.27.3:10008 as a peer
2018/12/12 07:33:24 [WARN] raft: Remote peer 10.84.169.52:10008 does not have local node 10.196.27.3:10008 as a peer 
```
the other three don't have `10.196.27.3` listed, but per 
```
2018-12-12 07:33:07 DEBUG raft: peers=[10.196.27.3:10008 10.42.183.98:10008 10.84.169.52:10008 10.96.18.8:10008]
```
they do. I have never seen this happen.

**Comment by cohenjo** [comment]
I try to innovate with my bugs :D

**Comment by cohenjo** [comment]
I think I made some progress - just not sure on which direction.
I tried to reboot my other servers again and noticed this little line:
```
DEBUG] raft: Node 10.96.18.8:10008 updated peer set (2): [10.96.18.8:10008 10.84.169.52:10008 10.42.183.98:10008 10.196.27.2:10008]
```
this IP `10.196.27.2` - is an IP of a dead node 
- how long does orchestrator keep info on dead nodes internally?

I'll keep looking...

**Comment by shlomi-noach** [comment]
> how long does orchestrator keep info on dead nodes internally?

I'm not sure I understand the question. `orchestrator` does not keep info about raft member nodes. Perhaps this is a DNS cache?

**Comment by cohenjo** [comment]
I Don't use DNS for this - ipv4 only in the peer lists, that's why I was wondering where it returned from.
I wonder if this is why the new node doesn't join..

It seems similar to:
https://github.com/github/orchestrator/issues/593

**Comment by cohenjo** [comment]
Ok,
Just writing here what I've noticed in case someone hits the same issue.
I had a 4 node setup - 1 was taken down and another was spin up to take its place.

It seems that as long as even 1 member of the original raft remains it kept trying to reach the dead node. (I tried to do rolling restarts to keep the service online - as many other utilities depend on it)
while it was doing so it did not accept the new member into the raft.
to solve this I had to take **ALL** nodes down.
when I started them the new raft contained the new nodes and all is well.

**Comment by shlomi-noach** [comment]
> It seems that as long as even 1 member of the original raft remains it kept trying to reach the dead node. ... to solve this I had to take ALL nodes down.

That is correct, unfortunately.

related: https://github.com/github/orchestrator/issues/593#issuecomment-416469601
