### ISSUE TITLE
GUI does not allow graceful-master-takeover when in PGTID

### ISSUE THREAD

**Issue by utdrmac** [openark/orchestrator#759]
Servers are in PGTID mode, as indicated by the icon. 

![orchestrator-gui-enterprise](https://user-images.githubusercontent.com/4413670/49977477-19a90d80-ff0c-11e8-99b5-730efb7b503f.png)

When placing GUI into 'Pseudo-Gtid Mode', attempt to drag mysql2 over to mysql1 says 'cannot drop here'.

![screen shot 2018-12-13 at 7 21 22 pm 2](https://user-images.githubusercontent.com/4413670/49977531-51b05080-ff0c-11e8-84d6-b9ce259e050f.png)

Changing to Classic Mode, GTID Mode, both say same cannot drop here. But placing GUI into 'Smart Mode', PROMOTE AS MASTER:
![screen shot 2018-12-13 at 7 23 06 pm 2](https://user-images.githubusercontent.com/4413670/49977584-8ae8c080-ff0c-11e8-8f1e-b2dabf25c8f9.png)

Using API `graceful-master-takeover` also works.

**Comment by laurent-indermuehle** [comment]
I'm also interested about why it works like that.
I've GTID activated an all MySQL Instances but I can do a graceful-master-takeover only in smart mode. All others modes displays the "Cannot drop here" sign.

**Comment by shlomi-noach** [comment]
Thank you. I think this restriction can be fixed. I don't recall there was an intent to have this restriction and don't see why we wouldn't lift it.

**Comment by shlomi-noach** [comment]
addressed by https://github.com/github/orchestrator/pull/895
