### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by kevinbin** [openark/orchestrator#769]
Mac OS 10.14.2
git branch: master

docker build -t orchestrator .
...
Building via go version go1.8.4 linux/amd64
# github.com/github/orchestrator/go/inst
go/inst/instance_topology_dao.go:780: db.Conn undefined (type *sql.DB has no field or method Conn, but does have sql.conn)
The command '/bin/sh -c bash build.sh -b' returned a non-zero code: 2

**Comment by shlomi-noach** [comment]
You will need `go1.9` or above to build.

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/github/orchestrator/pull/774

**Comment by shlomi-noach** [comment]
Fixed by #774
