### ISSUE TITLE
different ouput result of getPriorityMajorVersionForCandidate() 

### ISSUE THREAD

**Issue by yangeagle** [openark/orchestrator#770]
In the function `getPriorityMajorVersionForCandidate()`, the `map` structure: `majorVersionsCount` is used.

The traversal order of the `map` is random in golang.

So, the output result of the function may be different in two calls with the same input.

For example, 4 slaves in a cluster, 

version number as follows: 5.6，5.6，5.7，5.7.

When `getPriorityMajorVersionForCandidate() `called,  the output result may be 5.6 or 5.7.

Is this correct?

Thank you for your precious time.

cc @MOON-CLJ

**Comment by shlomi-noach** [comment]
map iteration order is undefined, correct. Which is why we iterate the entire map to get the max value:

https://github.com/github/orchestrator/blob/a2315bb61d5e96eb7c57d2ede2fa9130df10689c/go/inst/instance_topology.go#L2098-L2104

So there is not problem with this function.

**Comment by yangeagle** [comment]
Still this example，4 slaves in a cluster,

version number as follows: 5.6，5.6，5.7，5.7.


In the same failure scenario,


the first time, getPriorityMajorVersionForCandidate() called, the output result is 5.6.

the second time, getPriorityMajorVersionForCandidate() called, the output result is 5.7.


My question is: 
the same input, twice called, but different output result.

**Comment by MOON-CLJ** [comment]
PS, if master version is 5.6，4 health slaves version as follows: 5.6，5.6，5.7，5.7.

the point is, the two 5.6 slaves are prefer in this situation，because no replica append to cannotReplicateReplicas in https://github.com/github/orchestrator/blob/a2315bb61d5e96eb7c57d2ede2fa9130df10689c/go/inst/instance_topology.go#L2171-L2173

**Comment by shlomi-noach** [comment]
OK, got it, there's equal number of `5.6` and `5.7` replicas and different results in identical scenarios. Let me look into this.

**Comment by shlomi-noach** [comment]
Fixed in https://github.com/github/orchestrator/pull/773

**Comment by yangeagle** [comment]
Thank you so much.

For another function
`getPriorityBinlogFormatForCandidate`,

Whether is the same problem?

**Comment by shlomi-noach** [comment]
> Whether is the same problem?

True. Now also fixed in https://github.com/github/orchestrator/pull/773
