### ISSUE TITLE
master graceful-master-takeover but get replication user and password 

### ISSUE THREAD

**Issue by jackiesre721** [openark/orchestrator#778]
[root@PMM-TEST ~]# orchestrator-client -c topology -a PMM-TEST:3307
PMM-TEST:3307  [0s,ok,5.6.36-log,rw,STATEMENT]
+ 192.168.60.80:3306 [0s,ok,5.6.36-log,ro,STATEMENT]
+ 192.168.60.78:3306 [0s,ok,5.6.36-log,ro,STATEMENT]

orchestrator-client -c graceful-master-takeover -a PMM-TEST -d 192.168.60.78:3306

PMM-TEST change to slave，but Unable to get replication user and password 

Fatal error: Invalid (empty) username when attempting to connect to the master server. Connection attempt terminated.

**Comment by daniel-2647** [comment]
@liuqian1990 you have 2 options for this:

1. If using MySQL CE or Percona you would be able to configure Orchestrator to read replication credentials stored in mysql.slave_master_info table, which implies you need to set up your servers with master_info_repository = ‘TABLE’ option if you want Orchestrator to be able to make topology changes on your behalf. (Documented here https://github.com/github/orchestrator/blob/13142cbadc6f319f0649ba7355fd4e3a925f9bdc/docs/install.md)

2. If using mariadb (Mariadb does not support master_info_repository), you'll have to create 2 columns on some schema which orchestrator has access to, and store the repl info there. Here's what I did for one of my clients:

```bash
CREATE DATABASE IF NOT EXISTS meta;

CREATE TABLE IF NOT EXISTS meta.cluster (
  anchor TINYINT NOT NULL,
  cluster_name VARCHAR(128) CHARSET ascii NOT NULL DEFAULT '',
  cluster_domain VARCHAR(128) CHARSET ascii NOT NULL DEFAULT '',
  repl_user VARCHAR(128) CHARSET ascii NOT NULL DEFAULT '',
  repl_pass VARCHAR(128) CHARSET ascii NOT NULL DEFAULT '',
  PRIMARY KEY (anchor)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO meta.cluster (anchor, cluster_name, cluster_domain, repl_user, repl_pass) VALUES (1, '{{ ClusterName }}', '{{ ClusterDomain }}', '{{ mysql_repl_user }}', '{{ mysql_repl_password }}') ON DUPLICATE KEY UPDATE cluster_name=VALUES(cluster_name), cluster_domain=VALUES(cluster_domain);
```

You'll then need to configure orchestrator config file with the following:

```
"ReplicationCredentialsQuery": "SELECT repl_user, repl_pass from meta.cluster where anchor=1",
```

I believe this is documented here:

https://github.com/github/orchestrator/pull/603

**Comment by jackiesre721** [comment]
Thank you for @daniel-2647  your answer, I passed the password through the hooks script.

#!/bin/bash
username=
password=123456
host={failedHost}
port={failedPort}
/usr/local/mysql/bin/mysql -u$username -p$password-h$host -P$port<<EOF
stop slave;
CHANGE MASTER TO MASTER_USER='rep',MASTER_PASSWORD='123456';
start slave;
EOF

**Comment by shlomi-noach** [comment]
`123456` is the best.
