### ISSUE TITLE
about DetachReplicaOperation()

### ISSUE THREAD

**Issue by yangeagle** [openark/orchestrator#779]
In the function `DetachReplicaOperation`, it run  the command `change master to` to detach a lost replica,
like   `change master to master_log_file='//mysql-bin.000001:4788', master_log_pos=4788`

On the command line, I simulated this scene,  and an error occurred：

```
mysql > stop slave
mysql >change master to master_log_file='//mysql-bin.000001:4788', master_log_pos=4788;
ERROR 1776 (HY000): Parameters MASTER_LOG_FILE, MASTER_LOG_POS, RELAY_LOG_FILE and RELAY_LOG_POS cannot be set when MASTER_AUTO_POSITION is active.
```

**context:**

MySQL 5.7.21   with gtid

Please check it.

@MOON-CLJ

**Comment by shlomi-noach** [comment]
Correct, this won't work with GTID.

You may use `detach-replica-master-host` as a more powerful method.

**Comment by yangeagle** [comment]
The function 
`recoverDeadMaster` call the function `DetachReplicaOperation`, then the error mentioned above will occurr.

The corresponding code for this function `recoverDeadMaster`  is as follows:

```
if promotedReplica != nil && len(lostReplicas) > 0 && config.Config.DetachLostReplicasAfterMasterFailover {
		postponedFunction := func() error {
			//...
			for _, replica := range lostReplicas {
				replica := replica
				inst.DetachReplicaOperation(&replica.Key)
			}
			return nil
		}
		//...
}
```
`detach-replica-master-host` you refer to  is implemented by `DetachReplicaMasterHost`.

Should  `DetachReplicaOperation`  be  replaced by `DetachReplicaMasterHost` ?

**Comment by shlomi-noach** [comment]
Good point. Yes, it should.

**Comment by shlomi-noach** [comment]
I'd like to possibly use a different approach and do `DetachReplica` after all, but in a way that would work with GTID + `auto_position`.

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/github/orchestrator/pull/801
