### ISSUE TITLE
bash missing from Dockerfile

### ISSUE THREAD

**Issue by chrisleavoy** [openark/orchestrator#783]
Dockerfile is missing /bin/bash and results in errors during recovery steps

Looks like this broke previously in #222 but then broke again when the Dockerfile was updated to use multiple stages.

I'm still trying to wrap my head around it, will try and provide more details as I start digging.

**Comment by shlomi-noach** [comment]
That is strange, because the Docker build is now tested as part of the CI, and it passes.
