### ISSUE TITLE
Orchestrator software in HA 

### ISSUE THREAD

**Issue by SQLadmin** [openark/orchestrator#786]
There is brief documentation already available for HA for Orchestrator. But in my case, Im going to use Orchestrator in multiple nodes but all are using the same database.  The architecture looks like below,

![image](https://user-images.githubusercontent.com/16044251/51791758-b29a9c00-21cd-11e9-9270-d822bc459d38.png)
3 servers where I installed orchestrator, and all there nodes are using the same mysql server.
And use a load balancer on top of all 3 nodes and assign a CNAME url for it.

In this case, Orchestrator will work fine or any issues will come?

**Comment by shlomi-noach** [comment]
@SqlAdmin this will work fine. This is the original design before `orchestrator/raft` came to be.
