### ISSUE TITLE
MakeCoMaster fails, when master does not have any replication settings

### ISSUE THREAD

**Issue by ghost** [openark/orchestrator#788]
If master does not have replication settings, i.e. `slave slave status` is "Empty set", the attempt to make it as co-master with the slave fails with the error:

> ChangeMasterTo: Cannot change master on: master1:3306 because replication is running

As far as I understand it fails in `ChangeMasterCredentials` function, checking whether replication is stopped or not:
```
	if !instance.ReplicationThreadsStopped() {
		return instance, fmt.Errorf("ChangeMasterTo: Cannot change master on: %+v because replication is running", *instanceKey)
	}
```
But replication is neither stopped nor running. I suppose, it is "ReplicationThreadStateNoThread".
PS: this is latest version 3.0.14 issue.

**Comment by shlomi-noach** [comment]
addressed by https://github.com/github/orchestrator/pull/789
