### ISSUE TITLE
Prefailover Sanity Checks

### ISSUE THREAD

**Issue by serhatcetinkaya** [openark/orchestrator#802]
Hello,

Currently we are using Orchestrator to track the Mysql topology and do the failovers. One of the challenges we have while doing the failover is that we set `binlog_group_commit_sync_delay` to 100 on master and 0 on all the slaves. So while performing a master switch we want to make sure this variable is set and in order to do that we run a mysql command on Orchestrator node in the `PostMasterFailoverProcesses`. Before the failover we also want to make sure that Orchestrator node can connect to `{successorHost}` with provided credentials and we do that in the `PreFailoverProcesses`. Last time we had an issue, the mysql user that Orchestrator uses was deleted from mysql and it couldn't connect to mysql host in the `PreFailoverProcesses` and failover process failed, master node didn't change, however Orchestrator was set read-only on the current master. After reading documentations we thought maybe doing this checks in the `PreGracefulTakeoverProcesses` makes more sense because in the docs it says:
```
PreGracefulTakeoverProcesses: executed on planned, graceful master takeover, immediately before the master goes read-only.
```
So if this check fails, the failover process will be aborted and current master will not be read-only. Is there anything else we should consider, or does this makes sense ?

Related part from our configuration:
```
[...]
  "PreFailoverProcesses": [
    "echo 'Will recover from {failureType} on {failureCluster}' >> {{ logdir }}/recovery.log",
    "{{ pre-failover-script }} {failureClusterAlias} {failedHost}"
  ],
  "PostFailoverProcesses": [
    "echo '(for all types) Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Successor: {successorHost}:{successorPort}' >> {{ logdir }}/recovery.log"
  ],
  "PostUnsuccessfulFailoverProcesses": [],
  "PostMasterFailoverProcesses": [
    "echo 'Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Promoted: {successorHost}:{successorPort}' >> {{ logdir }}/recovery.log",
    "{{ post-master-failover-script }} {failureClusterAlias} {successorHost}"
  ],
[...]
```

**Comment by shlomi-noach** [comment]
related: https://github.com/github/orchestrator/issues/744

**Comment by shlomi-noach** [comment]
@serhatcetinkaya can you please clarify whether you're talking about planned (aka graceful) or unplanned failover?

- For planned (graceful) failovers, the current logic first runs `PreGracefulTakeoverProcesses`, and only sets the demoted master as `read_only` afterwards, and assuming the processes are successful.

https://github.com/github/orchestrator/blob/88076ab8e8951d68399c0c792ba45d5f4d96c163/go/logic/topology_recovery.go#L1839-L1849

If this is not the behavior you're seeing, then it's strange. Are you certain the process you invoked returns an error code?

- If you're talking about unplanned failovers, then can you please again what you expect to happen?

**Comment by SQLadmin** [comment]
I think  serhatcetinkaya's problem is the  binlog_group_commit_sync_delay  value in master my.cnf  is 100, but 0 on slaves.

During a planned(graceful)  failover he want to set binlog_group_commit_sync_delay to 100 on the new master.

**Comment by shlomi-noach** [comment]
@SQLadmin I'm not sure I understand how the above comment re: `binlog_group_commit_sync_delay` relates to the original comment. The issue is the master being `read-only` when it shouldn't. Is that not the case?

**Comment by serhatcetinkaya** [comment]
We run a pre-failover script in the `PreFailoverProcesses` for both planned and unplanned failovers and within that script we want to make sure that orchestrator will be able to connect to promoted master in the `PostMasterFailoverProcesses` to set `binlog_group_commit_sync_delay` to 100 (because we keep it 100 on masters and 0 on slaves). Orchestrator is using the same mysql credentials in both pre-failover and post-failover, only difference is in pre-failover it checks grants for the user, in post-failover it sets the variable using that user. 

My problem is that when I tried a planned failover the mysql credentials were wrong and orchestrator couldn't connect to mysql to check grants in the pre-failover phase. It failed the process as expected and the master didn't change, but it left the current master as read-only. So I didn't check the code but I am guessing Orchestrator sets the read-only on the demoted master during a planned failover and then starts running procedures in the `PreFailoverProcesses`. If that is the case if we move those procedures to `PreGracefulTakeoverProcesses` can we prevent demoted master being left read-only if the same scenario happens ?

**Comment by shlomi-noach** [comment]
Sorry for the late response.

> I am guessing Orchestrator sets the read-only on the demoted master during a planned failover and then starts running procedures in the PreFailoverProcesses

That is incorrect. `PreFailoverProcesses` take place before (hence `Pre`) `orchestrator` takes any steps.
If a `PreFailoverProcesses` process exits with non-zero return code, the failover is aborted.
