### ISSUE TITLE
Can't relocate a slave using GTIDs

### ISSUE THREAD

**Issue by fuyar** [openark/orchestrator#803]
Hello,

I've just migrated to latest orchestrator version (3.0.14).

My DB topology is fairly simple 1 active master / 1 passive master and multiples readonly slaves with no binlogs. Percona (Oracle) GTIDs are enabled and in use (auto master position).

When trying to relocate slaves from one master to the other one by using this : 
`orchestrator-client -c can-replicate-from-gtid -i slave1 -d master2`
I got this error : 
`Instance master2 has purged GTID entries not found on slave1`

I checked on both servers and GTID were correct and no subset was missing.

After digging a while, I found that executed_gtid_set information is missing from orchestrator internal DB for MySQL instances w/o binlogs.

The check is done here : https://github.com/github/orchestrator/blob/7bef26f042aafbd956daeaede0cd4aab2ba46e65/go/inst/instance_topology.go#L558

Executed_Gtid_Set is fetched here : 
https://github.com/github/orchestrator/blob/7bef26f042aafbd956daeaede0cd4aab2ba46e65/go/inst/instance_dao.go#L398

I made a fix and moved this into the select that gets other global informations (gtid_purged etc ..) : 
https://github.com/fuyar/orchestrator/commit/02153a47a6c08f317dbbc7242bca8ce4ef58b0e9

I dont know if this is OK and I should push a PR ?

WDYT ?

Thanks !

**Comment by shlomi-noach** [comment]
Thank you! Good catch. I'm happy for a PR.
