### ISSUE TITLE
I can't see cluster in web UI.

### ISSUE THREAD

**Issue by umnya** [openark/orchestrator#809]
Hi, I am a new in orchestrator.
I installed orchestrator 3.0.14 version.

And I tried to discover mysql server in web UI.
But I couldn't add mysql server.
So I tried to discover in cli, and I could add it.

```
$./orchestrator -c discover -i 10.179.5.247:3306 cli
$ ./orchestrator -c topology -i 10.xxx.xxx.xxx:3306 cli
10.xxx.xxx.xxx:3306 [0s,ok,5.7.24-27-log,rw,ROW,>>,GTID]
* 10.xxx.xxx.xxx.hostname:3306 [0s,ok,5.7.24-27-log,ro,ROW,>>,GTID]
* 10.xxx.xxx.xxx.hostname:3306 [0s,ok,5.7.24-27-log,ro,ROW,>>,GTID]
```

But I couldn't see any cluster in web UI.
![image](https://user-images.githubusercontent.com/8628614/52983248-85888480-342d-11e9-98bc-92e3e87dc97a.png)

So I don't know what I should do for fixing it.

**Comment by shlomi-noach** [comment]
1. What do you see under `Clusters -> Dashboard` menu?
2. are you sure the orchestrator http service and the one you run from command line use the same backend MySQL server?

**Comment by umnya** [comment]
I set up all environment again.
And I can see and it works well.
Thank you.

**Comment by shlomi-noach** [comment]
Cool. Can you please close this issue? 🙇
