### ISSUE TITLE
Orchestrator doesn't recognize jq version 1.6 (Ubuntu 14.04.5)

### ISSUE THREAD

**Issue by bliu88** [openark/orchestrator#813]
My apologies if this has been brought up before - I wasn't able to find anything online.
I'm trying to install the orchestrator_1.0_amd64.deb package, but Orchestrator complains the jq version isn't recent enough (>= v1.3):

```
which jq
/usr/bin/jq

jq --version
jq-1.6
```

```
dpkg -i orchestrator_3.0.14_amd64.deb
Selecting previously unselected package orchestrator.
(Reading database ... 100831 files and directories currently installed.)
Preparing to unpack orchestrator_3.0.14_amd64.deb ...
Unpacking orchestrator (1:3.0.14) ...
dpkg: dependency problems prevent configuration of orchestrator:
 orchestrator depends on jq (>= 1.5); however:
  Package jq is not installed.

dpkg: error processing package orchestrator (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 orchestrator
```

Orchestrator isn't recognizing that jq is on version 1.6.
Is this a known issue or am I just doing something dumb? Are there any workarounds?

If I apt-get install jq, it'll install version 1.3

**Comment by shlomi-noach** [comment]
@bliu88 havent's seen this happen. What happens if you `apt-get install -f`? (If you don't mind testing)

**Comment by bliu88** [comment]
```
sudo apt-get install -f
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  orchestrator
0 upgraded, 0 newly installed, 1 to remove and 205 not upgraded.
1 not fully installed or removed.
After this operation, 22.0 MB disk space will be freed.
Do you want to continue? [Y/n]
(Reading database ... 100925 files and directories currently installed.)
Removing orchestrator (1:3.0.14) ...

ubuntu@some-ip:/tmp$ dpkg -l | grep orch
rc  orchestrator                        1:3.0.14                                   amd64        MySQL replication topology management and HA
```

To be fair I think this is an issue with Ubuntu, _not_ Orchestrator. I'll keep digging and see what I can find. Thanks either way for looking @shlomi-noach !

**Comment by reciprocal-space** [comment]
Just ran into this issue, and believe others may struggle with it as well since apt installs jq version 1.3 on Ubuntu (and Orchestrator=3.0.14 requires jq>=1.5). 

The way I got around this was to install jq>=1.5 [from source](https://stedolan.github.io/jq/download/) and then to add this installation of jq to the package manager using `checkinstall`. The [following page](https://help.ubuntu.com/community/CompilingEasyHowTo) may be helpful in explaining all the steps.
