### ISSUE TITLE
The DiscoveryIgnoreReplicaHostnameFilters option is not documented.

### ISSUE THREAD

**Issue by jfg956** [openark/orchestrator#814]
The DiscoveryIgnoreReplicaHostnameFilters option is not documented.

Self-documentation in sample configuration file would be useful.

PR on the way.

**Comment by jfg956** [comment]
https://github.com/github/orchestrator/pull/815

**Comment by utdrmac** [comment]
Merged? Can close?

**Comment by shlomi-noach** [comment]
yes, thank you.
