### ISSUE TITLE
Delays in failover

### ISSUE THREAD

**Issue by msj12** [openark/orchestrator#818]
> HI,shlomi-noach
In the time of failover,if all of the replica have a delay, how does the orchestrator cope with? and,If IO delay exists, whether the orchestrator will transmit the delayed event to the new master
Looking forward to your reply.
> Thank you!

**Comment by shlomi-noach** [comment]
see `FailMasterPromotionIfSQLThreadNotUpToDate` in https://github.com/github/orchestrator/blob/master/docs/configuration-recovery.md#promotion-actions, and also consider the not-merged-yet https://github.com/github/orchestrator/pull/771

**Comment by msj12** [comment]
Thank you very much for your reply.

I understand the impact of FailMasterPromotionIfSQLThreadNotUpToDate on orchestrator. But I think orchestrator is too sensitive to delays, and DelayMasterPromotionIfSQLThreadNotUpToDate is a good idea to solve.

However, in the case where DelayMasterPromotionIfSQLThreadNotUpToDate is configurable, further consideration is given. At the failover time, if the master event has not yet been written to the replica's relay log, and the SQL thread catches up with the current relay log in a short period of time.(In the case of asynchronous replication, this situation may occur.) For this situation, I think it should be judged whether the master's network is reachable. If it is reachable, the master's binary log (the event slave's relay log missing) should be sent to the slave for application. This application time can be included in DelayMasterPromotionIfSQLThreadNotUpToDate.If the master network is unreachable, the configuration of FailMasterPromotionIfSQLThreadNotUpToDate determines whether to promote.

**Comment by shlomi-noach** [comment]
> For this situation, I think it should be judged whether the master's network is reachable. If it is reachable, the master's binary log (the event slave's relay log missing) should be sent to the slave for application. This application time can be included in DelayMasterPromotionIfSQLThreadNotUpToDate.If the master network is unreachable, the configuration of FailMasterPromotionIfSQLThreadNotUpToDate determines whether to promote.

Thank you for the suggestion. It has been suggested in the past, and some work has been attempted at this, but eventually dropped.
Shipping the binary logs from other servers requires an agent to be installed, or remote SSH access. 

- `orchestrator` prefers the agentless approach.
- In attempts to sync relay logs I've encountered errors which I was not comfortable working with. Like halfway-through-transaction. I know MHA solved this, I'm unlikely to. See discussion in https://github.com/github/orchestrator/issues/448
- Turning on semi-sync avoids the need for this kind of solution. In our experience semi-sync works well.
