### ISSUE TITLE
GracefulMasterTakeover ERROR

### ISSUE THREAD

**Issue by wp741** [openark/orchestrator#834]
hi,there is a [bug]
![image](https://user-images.githubusercontent.com/26134256/53943893-17b0ae00-40f9-11e9-9f95-4a285c8d6803.png)
i closed 176:13306
and then,the topological graph like this：
![image](https://user-images.githubusercontent.com/26134256/53944028-737b3700-40f9-11e9-8219-294b8b71c325.png)
i closed 177:13306
and then,the topological graph like this：
![image](https://user-images.githubusercontent.com/26134256/53944170-c3f29480-40f9-11e9-9ac4-4dc6f927d3fa.png)
i closed 175:13306
![image](https://user-images.githubusercontent.com/26134256/53944248-f00e1580-40f9-11e9-9d3e-87119d1304a5.png)
now,i started 175:13306
176:13306
177:13306
recovery master and slave
and then,the topological graph like this：
![image](https://user-images.githubusercontent.com/26134256/53944429-5004bc00-40fa-11e9-97f1-00b6128086e9.png)
now,curl -s http://192.168.11.161:3000/api/graceful-master-takeover/ms02/192.168.11.177/13306
![image](https://user-images.githubusercontent.com/26134256/53944594-affb6280-40fa-11e9-9e5f-ea242589ef57.png)
{"Code":"ERROR","Message":"invalid connection","Details":null}

**Comment by wp741** [comment]
Is this a bug in the program?
Have you tested this scenario?

**Comment by jackiesre721** [comment]
@wp741 View down http://192.168.11.161:3000/web/cluster/alias/ms02

**Comment by jackiesre721** [comment]
@wp741 master_info_repository = ‘TABLE’ #778

**Comment by wp741** [comment]
> @liuqian1990 

all of mysql servers 
![image](https://user-images.githubusercontent.com/26134256/54001309-d0243380-4185-11e9-959b-dc76aa374f99.png)

**Comment by jackiesre721** [comment]
@wp741 error log

**Comment by jackiesre721** [comment]
@wp741 mysql -e -h192.168.11.175 -p13306 -e "show slave status\G"

**Comment by wp741** [comment]
@liuqian1990 175:13306 is the master
![image](https://user-images.githubusercontent.com/26134256/54006480-75e09e00-4198-11e9-9b50-e7650939bf80.png)

i checked all the servers,not found any error.

**Comment by wp741** [comment]
when i restarted orchestrator,i can do it success.
so i think this is a bug.

**Comment by wp741** [comment]
the logs like this：

[martini] Started GET /api/graceful-master-takeover/ms03/192.168.11.175/33306 for 192.168.11.161:41746
2019-03-08 14:53:32 INFO GracefulMasterTakeover: designated master instructed to be 192.168.11.175:33306
2019-03-08 14:53:32 INFO GracefulMasterTakeover: Will let 192.168.11.175:33306 take over its siblings
2019-03-08 14:53:32 INFO moveReplicasViaGTID: Will move 1 replicas below 192.168.11.175:33306 via GTID
[mysql] 2019/03/08 14:53:32 packets.go:36: unexpected EOF
2019-03-08 14:53:32 ERROR Relocating 1 replicas of 192.168.11.177:33306 below 192.168.11.175:33306 turns to be too complex; please do it manually
[martini] Completed 500 Internal Server Error in 17.188608ms

**Comment by wp741** [comment]
"MySQLConnectionLifetimeSeconds" : 10,

**Comment by liuqian1990** [comment]
@wp741 Can you give a wechat to discuss together?
