### ISSUE TITLE
orchestrator-client -c relocate-replicas allows unexpected behavior.

### ISSUE THREAD

**Issue by tomkrouper** [openark/orchestrator#838]
When starting work for a graceful takeover, I was careless when picking the new master database. I chose a host that was behind an intermediate master. So I had replication like so:
```
M
  > R1
    > R2
  > R3
...
```
I ran `orchestrator-client -c relocate-replicas -i M -d R2`. After I did this we ended up with
```
M

R1 <> R2
        > R3
        ...
```

This is obviously not what I was wanting.

Can we please put in a safeguard to save me from myself. If the `-d` host is not a direct descendant of the `-i` host, this command should fail without taking any action.

**Comment by shlomi-noach** [comment]
The operation should definitely fail in this situation.

> If the -d host is not a direct descendant of the -i host, this command should fail without taking any action.

we should allow moving replicas between unrelated boxes. For example:

```
m
- r1
- r2
  - bunch of replicas here
```
we should be able to `relocate-replicas -i r2 -d r1`, even though `r1` is not a descendant of `r2`.

What we should explicitly prohibit is `relocate-replicas` where `-d <host>` is a descendant of and of the immediate replicas of `-i`.
