### ISSUE TITLE
Rotate orchestrator.log

### ISSUE THREAD

**Issue by cclose** [openark/orchestrator#846]
I am wondering what the proper procedure for rotating the `/var/log/orchestrator.log` file is?

I tried setting up a logrotate rule, but orchestrator doesn't write to the new log once it's rotated. The only way I can find to force this is to issue `service orchestrator restart`, which seems a little extreme.

I see that you can set it up to write to syslog, but I prefer having the separate log file.

**Comment by shlomi-noach** [comment]
This is our `logrotate` config which works well:

```
# cat /etc/logrotate.d/orchestrator
/var/log/orchestrator.log {
  daily
  rotate 7
  missingok
  ifempty
  compress
  nodelaycompress
  copytruncate
}
```

**Comment by cclose** [comment]
Ah, copytruncate is the key here. Should have looked for more options in log rotate's settings.

I can confirm this is working for me as well now. Thanks!
