### ISSUE TITLE
Change SuggestedClusterAlias and InstanceAlias to be []string instead of string 

### ISSUE THREAD

**Issue by deepthi** [openark/orchestrator#851]
We are trying to change Vitess to allow multiple databases on one MySQL. In this configuration, we will be running multiple vttablets (1 per DB) against the same MySQL.
We currently use a query to provide `InstanceAlias` to orchestrator, and upon failover, we run a reparenting command on the new master using `{successorAlias}`.
With this new use case, we need to run reparenting on `n` different vttablets.

Proposal:
1. Change `Instance.SuggestedClusterAlias`, `Instance.InstanceAlias` and `TopologyRecovery.SuccessorAlias` to `[]string`.
2. To avoid an orchestrator schema change, we have to convert the `[]string` to a `string` (concatenated using some delimiter?) before writing, and reverse the process on reading
3. Placeholder replacement can use comma-delimited list
4. This will be backwards compatible and no current users will be impacted

**Comment by shlomi-noach** [comment]
Hi @deepthi ,

This is more than a schema change, since the `orchestrator` API exports the `Instance` object, which is then used by `orchestrator-client` or however user scripts use it. The types should therefore be unchanged.

Could you please explain again the flow? How and when is the instance queried, how `vttablet` uses that information?
I recently added [instance tags](https://github.com/github/orchestrator/blob/master/docs/tags.md). I suspect we may be able to use them somehow.

**Comment by deepthi** [comment]
Here's what a sample vitess orchestrator config contains for the relevant hooks:
```
  "DetectClusterAliasQuery": "SELECT value FROM _vt.local_metadata WHERE name='ClusterAlias'",
  "DetectInstanceAliasQuery": "SELECT value FROM _vt.local_metadata WHERE name='Alias'",
  "PostMasterFailoverProcesses": [
    "echo 'Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Promoted: {successorHost}:{successorPort}' >> /tmp/recovery.log",
    "vtctlclient -server vtctld:15999 TabletExternallyReparented {successorAlias}"
]
```
The value that orchestrator is given via the `DetectInstanceAliasQuery` is a vttablet uid. In the `PostMasterFailover` hook the `InstanceAlias` of the new master is passed to the `TabletExternallyReparented` command.
When we change vitess to allow multiple vttablets running against a single MySQL, what that means is that on failover, we need to be able to run the `TabletExternallyReparented` command on all the relevant  vttablets which are running against the MySQL instance that was just promoted to master.

**Comment by deepthi** [comment]
@shlomi-noach @sougou 
I think we can accomplish this on the vitess side by doing something like this:
```  
  "DetectClusterAliasQuery": "SELECT GROUP_CONCAT(value) FROM _vt.local_metadata WHERE name='ClusterAlias'",
  "DetectInstanceAliasQuery": "SELECT GROUP_CONCAT(value) FROM _vt.local_metadata WHERE name='Alias'",
  "PostMasterFailoverProcesses": [
    "echo 'Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Promoted: {successorHost}:{successorPort}' >> /tmp/recovery.log",
    "IFS=','  for tablet in {successorAlias}; do vtctlclient -server vtctld:15999 TabletExternallyReparented $tablet; done"]
```
