### ISSUE TITLE
question about relocateReplicasInternal

### ISSUE THREAD

**Issue by yangeagle** [openark/orchestrator#864]
file: go/inst/instance_topology.go
code:
```
func relocateReplicasInternal(replicas [](*Instance), instance, other *Instance) ([](*Instance), error, []error) {
	errs := []error{}
	var err error
	// simplest:
	if instance.Key.Equals(&other.Key) {
		// already the desired setup.
		return RepointTo(replicas, &other.Key)
        }
... ...
}
```

If  `instance` is equal to  `other`, 

is it necessary to do `RepointTo()` ?

@MOON-CLJ

**Comment by shlomi-noach** [comment]
It's the same as asking whether `RepointTo` is necessary in the first place. It is an intentional way of dropping the relay logs and refreshing/restarting replication. It was originally designed to be used with binlog servers, but I did actually use it with normal servers on occasion.

**Comment by yangeagle** [comment]
OK. Thank you so much.
