### ISSUE TITLE
Graceful-master-takeover: Error: MultiMatchBelowIndependently

### ISSUE THREAD

**Issue by oleg-glushak** [openark/orchestrator#866]
I try to make a graceful-master-takeover for this topology (promote db78-31 as a master):

```
db46-19:3306   [0s,ok,5.7.23-log,rw,ROW,P-GTID]
+ db-target-data:3306     [0s,ok,8.0.13,ro,ROW,>>,P-GTID]
+ db23-101:3306           [0s,ok,8.0.15,ro,ROW,>>,P-GTID]
+ db38-100:3306           [0s,ok,5.7.23-log,ro,ROW,P-GTID]
+ db46-69:3306 [0s,ok,5.7.23-log,ro,ROW,P-GTID]
+ db46-93:3306 [0s,ok,8.0.3-rc-log,ro,ROW,>>,P-GTID]
+ db78-31:3306            [0s,ok,5.7.25-log,rw,ROW,P-GTID]
```

and get this error in UI:

> Desginated instance db78-31:3306 cannot take over all of its siblings. Error: MultiMatchBelowIndependently: Error on all 5 operations

I'm using orchestrator v3.0.14.

Logs:

> [martini] Started GET /api/graceful-master-takeover/db46-19/db78-31/3306 for [::1]:56188
2019-04-18 00:37:19 INFO GracefulMasterTakeover: designated master instructed to be db78-31:3306
2019-04-18 00:37:19 INFO GracefulMasterTakeover: Will let db78-31:3306 take over its siblings
2019-04-18 00:37:19 INFO moveReplicasViaGTID: Will move 5 replicas below db78-31:3306 via GTID
2019-04-18 00:37:19 INFO Will match 5 replicas below db78-31:3306 via Pseudo-GTID, independently
[martini] Completed 500 Internal Server Error in 171.668846ms

What could be the reason of it?

**Comment by shlomi-noach** [comment]
the reason is that `db78-31:3306` doesn't have `log_slave_updates`.

**Comment by oleg-glushak** [comment]
@shlomi-noach So easy. Great! Thanks! Would be nice to add this information directly to the logs so it would be easier to debug.
