### ISSUE TITLE
Can't use ConsulAddress with https

### ISSUE THREAD

**Issue by git001** [openark/orchestrator#874]
## What I want to todo.

I have a running consul cluster which is reachable via tls. Now when I configure **"ConsulAddress":"https://127.0.0.1:8601"** it's not possible to use consul as kv store.

## error message

```
orchestrator-client -c submit-masters-to-kv-stores
parse http://https:%2F%2F127.0.0.1:8601/v1/kv/mysql/master/mysql-001.livesystem.at:3306/ipv6: invalid URL escape %2F
```

## Infos

looks like there is a `Scheme` field in the `DefaultConfig` https://github.com/armon/consul-api/blob/master/api.go#L112 .  
Maybe you should use the hashicorp client library as mentioned in the following comment https://github.com/github/orchestrator/issues/479#issuecomment-490084026

**Comment by shlomi-noach** [comment]
This: https://github.com/github/orchestrator/pull/320 illustrates the reason why I chose not to use the official API. I realize it may sound strange from the outside, but frankly just attempting to make that work was a nightmare, and the amount of potential cross dependencies was IMO unreasonable.

**Comment by shlomi-noach** [comment]
@git001 how do you feel about submitting a PR? I'm not going to be able to work on this soon.

**Comment by git001** [comment]
Well I have created one. Is this tool still in usage in github or do you use other replication solution now?

I try to setup a cluster based on https://github.com/github/orchestrator/blob/master/docs/deployment-raft.md but I think there are some missing parts in the doc. Is there any other communication possibility to discuss with users of orchestrator?

**Comment by shlomi-noach** [comment]
> Is this tool still in usage in github

It is. However, I'm personally working on multiple other things at this time and this issue will not be my top priority one.

> Is there any other communication possibility to discuss with users of orchestrator?

There's the https://groups.google.com/forum/#!forum/orchestrator-mysql group. There's the `MySQL` slack team.
I'm happy try and answer more questions, but please understand if I'm not immediately responsive.

**Comment by git001** [comment]
Thanks for your answers. I just wanted to be sure that this project is still alive ;-)

I have already subscribed to the google group ;-)

**Comment by shlomi-noach** [comment]
Best way to see if a project is alive is to track its commit history: https://github.com/github/orchestrator/commits/master

**Comment by jhriggs** [comment]
I just submitted PR #1047 for this.

#875 adds support with `"ConsulAddress": "https://..."` This PR does it with a new option, `ConsulScheme` (only because `consulapi` splits it up into `Address` and `Scheme`). I'm curious if the desired behavior would be to allow `ConsulAddress` to accept a URL (or at least `scheme://address`) as in #875 or to use separate config variables.

#1047 also blindly skips TLS verification. Should we add another SkipVerify, `ConsulSSLSkipVerify` and/or add a configuration option to provide a trusted CA file?

**Comment by shlomi-noach** [comment]
> #1047 also blindly skips TLS verification. Should we add another SkipVerify, ConsulSSLSkipVerify and/or add a configuration option to provide a trusted CA file?

Let's iterate on that. Keep #1047 with implicit skip-verify.
