### ISSUE TITLE
Rejoin the cluster after the fault

### ISSUE THREAD

**Issue by jackiesre721** [openark/orchestrator#881]
when Master dead rejoin cluster,How to operate

**Comment by hellracer** [comment]
Though this is not a support channel, this is what I normally do in my environment our millage my vary the assumption of this is you have GTID enabled replication.

On the master i want to re-join the cluster, 

```CHANGE MASTER TO MASTER_HOST='your_current_master_db_ip',MASTER_USER='your_replication_user',MASTER_PASSWORD='your_replication_password',MASTER_AUTO_POSITION=1; START SLAVE;```

then it's up to you to decide to perform a master graceful failover if you need to

**Comment by jackiesre721** [comment]
@hellracer Thanks

**Comment by shlomi-noach** [comment]
Please use https://groups.google.com/forum/#!forum/orchestrator-mysql for questions/discussions. If your question has been answered, please close this issue.
