### ISSUE TITLE
How is orchestrator working with more than one MySQL Clusters ?

### ISSUE THREAD

**Issue by junli0411** [openark/orchestrator#889]
Hi ,
if there're more than one MySQL clusters , the orchestrator checking these MySQL clusters in parallel or in sequential? 
And if there're more than one MySQL Master failed , the orchestrator do the recovery in parallel or in sequential ?

Thanks.

**Comment by shlomi-noach** [comment]
everything runs concurrently, including failovers.

**Comment by shlomi-noach** [comment]
My advice is to ask questions on https://groups.google.com/forum/#!topic/orchestrator-mysql/
