### ISSUE TITLE
graceful switch gui set notice Invalid connection

### ISSUE THREAD

**Issue by jackiesre721** [openark/orchestrator#890]
![image](https://user-images.githubusercontent.com/8868514/57760521-4e74f700-772e-11e9-888e-10eae1b07af0.png)
![02_27_14__05_15_2019](https://user-images.githubusercontent.com/8868514/57760573-71071000-772e-11e9-822a-bda0f55639a1.jpg)

**Comment by shlomi-noach** [comment]
@liuqian1990 to be able to help you I need you to provide more details in your issue submission.

1. what did you do? 
2. What did the cluster look like before? 
3. what happened and when?
4. What did the cluster look like afterwards? 
5. please run with `--dbug --stack` and paste the relevant logs
6. anything else.

I appreciate the graphics but need more to work with.

**Comment by shlomi-noach** [comment]
@liuqian1990 following up to understand whether the problem was solved? If so, how? Thanks.
