### ISSUE TITLE
Orchestrator doesn't do recovery after detecting a failover

### ISSUE THREAD

**Issue by sxy630707** [openark/orchestrator#893]
I used the latest operator image v0.3.0-rc.1. 
I launched a MySQL cluster with 3 members, one master and two secondaries. The Orchestrator web UI show their status correctly at very beginning. But I got some error message in Orchestrator log
 `ReadTopologyInstance(my-cluster-mysql-0.mysql.default:3306) ReplicationLagQuery: Error 1142: SELECT command denied to user 'orchestrator'@'10.244.79.203' for table 'heartbeat'`
 `ReadTopologyInstance(my-cluster-mysql-1.mysql.default:3306) ReplicationLagQuery: Error 1142: SELECT command denied to user 'orchestrator'@'10.244.79.203' for table 'heartbeat'`
 `ReadTopologyInstance(my-cluster-mysql-2.mysql.default:3306) ReplicationLagQuery: Error 1142: SELECT command denied to user 'orchestrator'@'10.244.79.203' for table 'heartbeat'`
I found out that mysql user `orchestrator` did not have privileges on table `heartbeat` so I GRANT privileges manually for each mysqld.
I used `kubectl delete pod my-cluster-mysql-0 --grace-period=0 --force` to delete master. 
The Orchestrator detected the master is unreachable 
`Detected: 2019-05-15T23:29:43Z`
`2 replicating hosts :`
`my-cluster-mysql-2.mysql.default:3306`
`my-cluster-mysql-1.mysql.default:3306`
`Changelog :`
`2019-05-15T23:29:43Z UnreachableMaster,`
It, however, did not take any step to automatically recover the failure. There is no secondary to be promoted to the new master.
Can anyone help me with this issue?

**Comment by shlomi-noach** [comment]
I am not familiar with the operator image. Please consider opening an issue where you got the operator image.

Having said that, `UnreachableMaster` does not make a failover scenario. See https://github.com/github/orchestrator/blob/master/docs/failure-detection.md#unreachablemaster

**Comment by sxy630707** [comment]
Sorry to post the question in the wrong place. I am gonna close this issue.
