### ISSUE TITLE
if PreFailoverProcesses hooks supply two can't used placeholders ?

### ISSUE THREAD

**Issue by IT-xiaoge** [openark/orchestrator#896]
In my test environment，i used successorHost and successorPort parameters to fail over for PreFailoverProcesses hook,but  PreFailoverProcesses hook can not get the successorHost and successorPort values。Where is the problem?

as follows in test conf:
......
......
"PreFailoverProcesses": [
    "/home/mysql/orchestrator/bin/orchestrator_hooks -action PreFailoverProcesses -failureClusterAlias '{failureClusterAlias}' -failureType '{failureType}' -failureCluster '{failureCluster}' -successorHost '{successorHost}' -successorPort '{successorPort}'"
  ],
......
......

Recovery steps logs:
......
......
Running PreFailoverProcesses hook 1 of 1: /home/mysql/orchestrator/bin/orchestrator_hooks -action PreFailoverProcesses -failureClusterAlias 'test3308-5.6.35' -failureType 'DeadMaster' -failureCluster '10.188.36.16:3308' -successorHost '{successorHost}' -successorPort '{successorPort}'
......
......

**Comment by shlomi-noach** [comment]
`successorHost` and `successorPort` do not exist in `PreFailoverProcesses`. 

`PreFailoverProcesses` means _before_ the failover. Perhaps you're looking for `PostFailoverProcesses`?

**Comment by IT-xiaoge** [comment]
i found this in https://github.com/github/orchestrator/blob/master/go/config/config.go at line 231。
Do you want to remove the successorHost and successorPort parameters inside?


PreFailoverProcesses                       []string          // Processes to execute before doing a failover (aborting operation should any once of them exits with non-zero code; order of execution undefined). May and should use some of these placeholders: {failureType}, {failureDescription}, {command}, {failedHost}, {failureCluster}, {failureClusterAlias}, {failureClusterDomain}, {failedPort}, {successorHost}, {successorPort}, {successorAlias}, {countReplicas}, {replicaHosts}, {isDowntimed}

**Comment by shlomi-noach** [comment]
done (in pending branch), thanks.
