### ISSUE TITLE
RemoteSSHCommand

### ISSUE THREAD

**Issue by fuyuntaot115** [openark/orchestrator#899]
Hi
"RemoteSSHForMasterFailover": true,
  "RemoteSSHCommand": "ssh {hostname}",
  "RemoteSSHCommandUseSudo": true,
These three parameters are in the case of delay from the library, will copy the delayed binlog to the new main library for import, can you elaborate?

Like mha, it can give the new owner an unsynchronized relaylog to prevent losing some data.

**Comment by shlomi-noach** [comment]
Hi,

Sorry, these are leftovers from an unsuccessful attempt at MHA-like synching of relay logs. [This](https://github.com/github/orchestrator/pull/48#event-934064080) was one of the PRs involved; but later most of the code was purged. I should delete these variables, too.

**Comment by shlomi-noach** [comment]
Removed in https://github.com/github/orchestrator/pull/894/commits/1c37be35a9b20cd23249632a5badb8e3b845b09e

**Comment by shlomi-noach** [comment]
Closed as no further action is needed.
