### ISSUE TITLE
Graceful-switchover to support automatically picking the replica to promote

### ISSUE THREAD

**Issue by dpitera** [openark/orchestrator#908]
Currently, graceful switchover requires the user to select a replica to promote to the new master, however it would be nice if orchestrator could automatically pick a (if not "best") replica to promote.

"Best" replica for promotion could take into account promotion rules and replication status, i.e. a replica with a lot of lag might not be the best to promote.

**Comment by shlomi-noach** [comment]
Addressed by #1165

**Comment by shlomi-noach** [comment]
fixed by #1165
