### ISSUE TITLE
why the running log throws  Unknown column exception?

### ISSUE THREAD

**Issue by mckobe23** [openark/orchestrator#91]
hi,

   I just download the new version tarball: orchestrator-2.0.2-linux-amd64.tar.gz

   my question are:
   1. when i used command `./orchestrator http` at /usr/local/orchestrator directory, then running log throws `ERROR Error 1054: Unknown column 'first_seen_active' in 'field list'`

  2. when i used command `./orchestrator --discovery=false http` , access the web site, the running log throws `ERROR Error 1054: Unknown column 'candidate_database_instance.promotion_rule' in 'field list' `

    I looked my orchestrator database, it has 36 tables, and I tryed `select promotion_rule from candidate_database_instance;` , the mysql alert `ERROR 1054 (42S22): Unknown column 'promotion_rule' in 'field list'` message

   I think about, the version's sql is old or didn't update?

**Comment by mckobe23** [comment]
sorry, i used another user ,this user has SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, SUPER  privileges,so the table is not whole(the fileds are not incomplete)

pls closed.

**Comment by shlomi-noach** [comment]
enjoy `orchestrator`
