### ISSUE TITLE
Slave with error should be excluded from failover

### ISSUE THREAD

**Issue by jsecchiero** [openark/orchestrator#917]
### Topology (lab):

orche (orchestrator)
orch-1 (mysql master)
orch-2 (mysql slave)

### How to reproduce:

1) stop the replica generating an error on slave
create database on mysql-2
create same database on mysql-1
the following error is generated:
`Can't create database ... Error_code: 1007`

![image](https://user-images.githubusercontent.com/17151394/60252215-269ab680-98ca-11e9-86aa-339f4baa79f6.png)

2) make master unreachable from orchestrator
killall -9 mysqld on master

At this point the slave with the error become the new master

![image](https://user-images.githubusercontent.com/17151394/60252675-ef78d500-98ca-11e9-8072-b61f9a4a7445.png)

![image](https://user-images.githubusercontent.com/17151394/60252572-c0626380-98ca-11e9-80f7-c6314704f75e.png)

### Orchestrator conf:

```
{
  "Debug": false,
  "EnableSyslog": false,
  "ListenAddress": ":3000",
  "MySQLTopologyUser": "orchestrator",
  "MySQLTopologyCredentialsConfigFile": "/etc/mysql/orchestrator-frontend.cnf",
  "MySQLTopologySSLPrivateKeyFile": "",
  "MySQLTopologySSLCertFile": "",
  "MySQLTopologySSLCAFile": "",
  "MySQLTopologySSLSkipVerify": true,
  "MySQLTopologyUseMutualTLS": false,
  "MySQLOrchestratorHost": "127.0.0.1",
  "MySQLOrchestratorPort": 3306,
  "MySQLOrchestratorDatabase": "orchestrator",
  "MySQLOrchestratorCredentialsConfigFile": "/etc/mysql/orchestrator-backend.cnf",
  "MySQLOrchestratorSSLPrivateKeyFile": "",
  "MySQLOrchestratorSSLCertFile": "",
  "MySQLOrchestratorSSLCAFile": "",
  "MySQLOrchestratorSSLSkipVerify": true,
  "MySQLOrchestratorUseMutualTLS": false,
  "MySQLConnectTimeoutSeconds": 1,
  "DefaultInstancePort": 3306,
  "DiscoverByShowSlaveHosts": true,
  "InstancePollSeconds": 5,
  "UnseenInstanceForgetHours": 240,
  "SnapshotTopologiesIntervalHours": 0,
  "InstanceBulkOperationsWaitTimeoutSeconds": 10,
  "HostnameResolveMethod": "none",
  "MySQLHostnameResolveMethod": "@@report_host",
  "SkipBinlogServerUnresolveCheck": true,
  "RejectHostnameResolvePattern": "",
  "ReasonableReplicationLagSeconds": 10,
  "ProblemIgnoreHostnameFilters": [],
  "VerifyReplicationFilters": false,
  "ReasonableMaintenanceReplicationLagSeconds": 20,
  "CandidateInstanceExpireMinutes": 60,
  "AuditLogFile": "",
  "AuditToSyslog": false,
  "ReadOnly": false,
  "AuthenticationMethod": "basic",
  "HTTPAuthUser": "admin",
  "HTTPAuthPassword": "prot",
  "AuthUserHeader": "",
  "PowerAuthUsers": [
    "*"
  ],
  "ClusterNameToAlias": {
    "cluster": "cluster"
  },
  "SlaveLagQuery": "",
  "DetectClusterAliasQuery": "",
  "DetectClusterDomainQuery": "",
  "DetectInstanceAliasQuery": "",
  "DetectPromotionRuleQuery": "",
  "DataCenterPattern": "[.]([^.]+)[.][^.]+[.]mydomain[.]com",
  "PhysicalEnvironmentPattern": "[.]([^.]+[.][^.]+)[.]mydomain[.]com",
  "PromotionIgnoreHostnameFilters": [],
  "DetectSemiSyncEnforcedQuery": "",
  "ServeAgentsHttp": false,
  "AgentsServerPort": ":3001",
  "AgentsUseSSL": false,
  "AgentsUseMutualTLS": false,
  "AgentSSLSkipVerify": false,
  "AgentSSLPrivateKeyFile": "",
  "AgentSSLCertFile": "",
  "AgentSSLCAFile": "",
  "AgentSSLValidOUs": [],
  "UseSSL": false,
  "UseMutualTLS": false,
  "SSLSkipVerify": false,
  "SSLPrivateKeyFile": "",
  "SSLCertFile": "",
  "SSLCAFile": "",
  "SSLValidOUs": [],
  "URLPrefix": "",
  "StatusEndpoint": "/api/status",
  "StatusSimpleHealth": false,
  "StatusOUVerify": false,
  "AgentPollMinutes": 60,
  "UnseenAgentForgetHours": 6,
  "StaleSeedFailMinutes": 60,
  "SeedAcceptableBytesDiff": 8192,
  "PseudoGTIDPattern": "",
  "PseudoGTIDPatternIsFixedSubstring": false,
  "PseudoGTIDMonotonicHint": "asc:",
  "DetectPseudoGTIDQuery": "",
  "BinlogEventsChunkSize": 10000,
  "SkipBinlogEventsContaining": [],
  "ReduceReplicationAnalysisCount": true,
  "FailureDetectionPeriodBlockMinutes": 1,
  "RecoveryPeriodBlockSeconds": 30,
  "UseSuperReadOnly": true,
  "RecoveryIgnoreHostnameFilters": [],
  "RecoverMasterClusterFilters": [
    "*"
  ],
  "RecoverIntermediateMasterClusterFilters": [
    "*"
  ],
  "OnFailureDetectionProcesses": [
    "echo 'Detected {failureType} on {failureCluster}. Affected replicas: {countSlaves}' >> /tmp/recovery.log"
  ],
  "PreFailoverProcesses": [
    "echo 'Will recover from {failureType} on {failureCluster}' >> /tmp/recovery.log"
  ],
  "PostFailoverProcesses": [
    "echo '(for all types) Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Successor: {successorHost}:{successorPort}' >> /tmp/recovery.log"
  ],
  "PostUnsuccessfulFailoverProcesses": [],
  "PostMasterFailoverProcesses": [
    "echo 'Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Promoted: {successorHost}:{successorPort}' >> /tmp/recovery.log"
  ],
  "PostIntermediateMasterFailoverProcesses": [
    "echo 'Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Successor: {successorHost}:{successorPort}' >> /tmp/recovery.log"
  ],
  "CoMasterRecoveryMustPromoteOtherCoMaster": true,
  "DetachLostSlavesAfterMasterFailover": true,
  "ApplyMySQLPromotionAfterMasterFailover": true,
  "MasterFailoverDetachSlaveMasterHost": false,
  "MasterFailoverLostInstancesDowntimeMinutes": 0,
  "PostponeSlaveRecoveryOnLagMinutes": 0,
  "OSCIgnoreHostnameFilters": [],
  "GraphiteAddr": "",
  "GraphitePath": "",
  "GraphiteConvertHostnameDotsToUnderscores": true
}
```

### Why should not happening

The slave server can be in Error state for some good reason and can be dangerous to promote this as Master, moreover the slave may be weeks late.

There is any way to avoid this?

**Comment by shlomi-noach** [comment]
Hi, can you please clarify what kind of error that would be? Not sure in what error state the replica was beforehand.

> moreover the slave may be weeks late.

`orchestrator` explicitly checks that and prefers to promote a replica which has as less lag as possible, assuming other constraints are satisfied. You also have the configuration variables `FailMasterPromotionIfSQLThreadNotUpToDate` and `DelayMasterPromotionIfSQLThreadNotUpToDate` to further control behavior when none of the replicas ar eup to date, see https://github.com/github/orchestrator/blob/master/docs/configuration-recovery.md#promotion-actions

**Comment by shlomi-noach** [comment]
Sorry, I wasn't reading this right, need coffee. I can see the nature of the error in your original comment.

**Comment by shlomi-noach** [comment]
The situation you describe is a bit debatable. You have one master, one replica, the replica was broken at some stage, you kill the master. Should there or should there not be a promotion?

I believe `FailMasterPromotionIfSQLThreadNotUpToDate` is what you are looking for.

**Comment by jsecchiero** [comment]
Thanks for the fast reply,
i have tested `DelayMasterPromotionIfSQLThreadNotUpToDate` and seems to work well,  can i use this instead of `FailMasterPromotionIfSQLThreadNotUpToDate` ?

**Comment by shlomi-noach** [comment]
@jsecchiero if the replica is known to be broken, then `DelayMasterPromotionIfSQLThreadNotUpToDate` will just wait forever -- I'm not sure you'd want that?

**Comment by jsecchiero** [comment]
Please tell me if i'm wrong:
`DelayMasterPromotionIfSQLThreadNotUpToDate` wait ALL the slaves to have read all the relay logs
`FailMasterPromotionIfSQLThreadNotUpToDate` fail if at least ONE of the slaves have not read all relay logs

in both cases it's not optimal for me because, if i have more healthy slaves and one broken, in the first case i have to wait forever (as you said) and in the second case i don't have an automatic fail-over. It's correct?

**Comment by shlomi-noach** [comment]
sorry, that is exactly the opposite :)

- `DelayMasterPromotionIfSQLThreadNotUpToDate` will wait until at least one replica is caught up that can also be promoted (meaning that's a server that can actually be a master, has good configuration etc.). When one replica is up-to-date and is good to be promoted -- it gets promoted and the failvoer is complete.

- `FailMasterPromotionIfSQLThreadNotUpToDate` will fail if it can't find a single up-to-date replica. Thus, it fails when ALL replicas are very-much-lagging-or-broken.

**Comment by jsecchiero** [comment]
Seems `DelayMasterPromotionIfSQLThreadNotUpToDate`
Is what I want. Thanks for the explanation
