### ISSUE TITLE
AllMasterSlavesNotReplicating resulting in new slave not replcate to new master

### ISSUE THREAD

**Issue by IT-xiaoge** [openark/orchestrator#927]
when i was doing a failover test, first，i stop the one slave io thread, after Minutes，i stop another slave io thread, then i kill the master process,i found one slave become master ,but the orther one slave still replicate to dead master.

Why the slave still replicate to dead master,Shouldn't connect to new master?

**Comment by zmoazeni** [comment]
Hi @IT-xiaoge, I'm not following the scenario. I'm sure there's some substance to it, but I'd like understand the situation first.

Could you perhaps put together a list of reproducible steps that I could follow on my side? Maybe even a screenshot or two (annotated would be great!) with what you expected and didn't happen?

**Comment by IT-xiaoge** [comment]
Ok,I will introduce my deployment environment first, ip is not real.mysql version=5.7.21，based gtid
master：10.0.0.1:3306
slave：10.0.0.2:3306
slave：10.0.0.3:3306


Here are my steps：
1、Simulate online request, write a script to continuously write data to the table
2、after minutes，stop the 10.0.0.2:3306 io thread，
3、after minutes，stop the 10.0.0.3:3306 io thread（I do this for  trying to simulate online all master-slave delay ）
4、i found out there to display AllMasterSlavesNotReplicating on Page Audit Failure detection dashboard,like this 
![image](https://user-images.githubusercontent.com/25096644/60857243-5fc51600-a23c-11e9-96e2-9eddd895752c.png)
5、exec comand kill -9 {mysql_3306_pid} on master(kill -9 {10.0.0.1:3306_pid})
6、Page cluster dashboard display,
master：10.0.0.1:3306 is down 
slave：10.0.0.2:3306 is new master
slave：10.0.0.3:3306 is still repliccate from dead master 10.0.0.1:3306
7、slave：10.0.0.3:3306 exec :show slave status\G, Master_Host: //10.0.0.1

I expected slave：10.0.0.3:3306 will repliccate from 10.0.0.2:3306(new master) after failover,but it didn't happen

**Comment by zmoazeni** [comment]
Thank you! I'll try and reproduce.

I will say I am surprised orchestrator would promote 10.0.0.2 if the replication thread is stopped. I would think it would have rules out all candidates.

To double check, when you say

> after minutes，stop the 10.0.0.2:3306 io thread，

Did you run "STOP SLAVE" within MySQL on those instances?

**Comment by IT-xiaoge** [comment]
No,I didn't run "STOP SLAVE" within MySQL on those instances.

Probably because I implemented the start slave function in my hooks.
> I will say I am surprised orchestrator would promote 10.0.0.2 if the replication thread is stopped. I would think it would have rules out all 

Below is my orchestrator failover log：
[orchestrator.log](https://github.com/github/orchestrator/files/3374026/orchestrator.log)

My orchestrator version is v3.0.pre-release

**Comment by zmoazeni** [comment]
> No,I didn't run "STOP SLAVE" within MySQL on those instances.

> Probably because I implemented the start slave function in my hooks.


Hrm, what did you run to stop replication thread on those instances? And what all hooks are you running?

I'm beginning to think that we're getting to the crux of the issue where you have a hook restarting replication and 10.0.0.3 is perhaps left replicating from 10.0.0.1 (old master) because replication was down during the failover event? I don't think orchestrator would restart replication that's down to reorganize the topology.

Kind of feeling like it's an issue with your hooks here, but I'm not sure.

**Comment by IT-xiaoge** [comment]
The hooks function is to execute the `start slave;`  on PreFailoverProcesses and i did 'stop slave io_thread' on 10.0.0.3 and 10.0.0.2 instances.

In MySQL version5.6.35 ，replication based position, i do same failover test, 10.0.0.3 will replicate from 10.0.0.2, so ,should not my hooks issue.


I should logout  ‘start slave’ function with a test?

**Comment by zmoazeni** [comment]
Interesting! I'm not sure. I'll have to tinker to see if I can reproduce. Not sure why 5.6 v 5.7 would behave differently off-hand either

**Comment by IT-xiaoge** [comment]
I did the test with logout `start slave` function,but what my expected didn't happen.

This is the record I saw in the orchestrator.log, I don't know why the failover will cause lose replica? 
And why changed master on 10.0.0.3:3306 to: //10.0.0.1:3306, mysql-bin.000019:14063147 ?
i did `show slave status` on 10.0.0.3:3306, master is `Master_Host: //10.188.36.16`,why?

> INFO topology_recovery: found an active or recent recovery on 10.0.0.1:3306. Will not issue another RecoverDeadMaster.
> DEBUG GetCandidateReplica: candidate: 10.0.0.3:3306, ahead: 0, equal: 0, late: 0, break: 1
> INFO topology_recovery: RecoverDeadMaster: - lost replica: 10.0.0.3:3306
> INFO topology_recovery: RecoverDeadMaster: lost 1 replicas during recovery process; detaching them
> DEBUG ChangeMasterTo: will attempt changing master on 10.0.0.3:3306 to //10.0.0.1:3306, mysql-bin.000019:14063147
> INFO ChangeMasterTo: Changed master on 10.0.0.3:3306 to: //10.0.0.1:3306, mysql-bin.000019:14063147. GTID: true

**Comment by IT-xiaoge** [comment]
The problem is solved，found the slaves have same server_id,so the 10.0.0.3:3306 can't replicate from  10.0.0.2:3306.

Very thanks!

**Comment by zmoazeni** [comment]
Ahh interesting! Thanks for posting what it was. Have a good one.

**Comment by shlomi-noach** [comment]
Thanks both!
