### ISSUE TITLE
[question] during recovery set read_only=1 and there is a long-transaction , what happened?

### ISSUE THREAD

**Issue by jianhaiqing** [openark/orchestrator#932]

**Comment by shlomi-noach** [comment]
Honest question, did you try?
IMO `orchestrator` will abort on timeout.

BTW I'm assuming you mean a graceful-takeover, but I'm just guessing. I'd appreciate a more elaborate description of the problem.

**Comment by jianhaiqing** [comment]
Yes, i mean gracefull-takeover.  I just try, sorry for that.

https://github.com/github/orchestrator/blob/c72a6c89bb4cd18d43d3c6e5529502e0a2472290/go/logic/topology_recovery.go#L1876

```
if designatedInstance, err = inst.StopSlave(&designatedInstance.Key); err != nil {
	return nil, nil, err
}
log.Infof("GracefulMasterTakeover: Will set %+v as read_only", clusterMaster.Key)
if clusterMaster, err = inst.SetReadOnly(&clusterMaster.Key, true); err != nil {
	return nil, nil, err
}
```
during graceful-takeover, how about set global read_only=1 before stop designatedInstance slave-status ?
I a little confused how to make the designatedInstance is catching up with the master before you stop-slave of designatedInstance ?
Thanks for your explanation.

**Comment by shlomi-noach** [comment]
catching up is done here:

https://github.com/github/orchestrator/blob/c72a6c89bb4cd18d43d3c6e5529502e0a2472290/go/logic/topology_recovery.go#L1880-L1884

**Comment by jianhaiqing** [comment]
Awesome.  Thank you so much.
