### ISSUE TITLE
Packagecloud version not updated to the last GA

### ISSUE THREAD

**Issue by itsnotvalid** [openark/orchestrator#939]
Hello, I installed 3.0.14 via packagecloud's deb repo and wanted to upgrade to 3.1.1. However there seems to be no updates to that site. Is it now not recommended to install using that repo, or just forgot to push?

Thanks.

**Comment by shlomi-noach** [comment]
Thank you, that was an oversight. https://packagecloud.io/github/orchestrator is now updated with `3.1.1` builds.

However, due to naming collision, I'm unable up upload `sysv`-based packages, only `systemd`-based packages.

**Comment by itsnotvalid** [comment]
Thanks for updating.

**Comment by akamac** [comment]
As of now only 3.1.4 deb packages are available on PackageCloud, while the latest GA release is 3.2.3.
Is there any CI for deb packages? If not, could you please publish it manually?
Thanks!

**Comment by shlomi-noach** [comment]
please see https://github.com/openark/orchestrator/issues/1218
