### ISSUE TITLE
bug in the third package sqlutils

### ISSUE THREAD

**Issue by yangeagle** [openark/orchestrator#943]
I am not sure whether this question is suitable here.

I find a problem in the third package `github.com/openark/golib/sqlutils` used in `orchestrator`.

package: `github.com/openark/golib/sqlutils`
file: ` golib/sqlutils/sqlutils.go`
code:
```
// QueryRowsMap is a convenience function allowing querying a result set while poviding a callback
// function activated per read row.
func QueryRowsMap(db *sql.DB, query string, on_row func(RowMap) error, args ...interface{}) error {
	var err error
	defer func() {
		if derr := recover(); derr != nil {
			err = errors.New(fmt.Sprintf("QueryRowsMap unexpected error: %+v", derr))
		}
	}()

... ...
	return err
}
```
The `err` modified in `defer` will not return to the caller.

For example:
```
package main

import (
        "fmt"
)

func main(){
        i := test()
        fmt.Println("main i:", i)
}

func test() int {
        var a int
        defer func () {
                a = 2
        }()

        a = 1
        return a
}
```
output:
`main i: 1`

The correct usage like this:
```
package main

import (
        "fmt"
)

func main(){
        i := test()
        fmt.Println("main i:", i)
}

func test() (a int) {
        defer func () {
                a = 2
        }()

        a = 1
        return a
}
```
output:
`main i: 2`

I also submitted an issue [here](https://github.com/outbrain/golib/issues/5).

Please check it.
cc @MOON-CLJ

**Comment by shlomi-noach** [comment]
Thank you. Please consider https://github.com/github/orchestrator/pull/946 as a fix.
