### ISSUE TITLE
about the GracefulMasterTakeover

### ISSUE THREAD

**Issue by yyyyoooooooooo** [openark/orchestrator#958]
Hi
I have some question about the GracefulMasterTakeover function. It  set read_only=on on old master to block write .Is add the command flush table with read lock at the same time  a necessary policy?

Thank you!

**Comment by shlomi-noach** [comment]
`flush table with read lock` can be a long running operations in my experience, on a busy master. This is the reason I opted for `read_only`.

For questions, I suggest using the [orchestrator-mysql](https://groups.google.com/forum/#!forum/orchestrator-mysql) google group

**Comment by yyyyoooooooooo** [comment]
> `flush table with read lock` can be a long running operations in my experience, on a busy master. This is the reason I opted for `read_only`.
> 
> For questions, I suggest using the [orchestrator-mysql](https://groups.google.com/forum/#!forum/orchestrator-mysql) google group

OK
