### ISSUE TITLE
GTID mode relocation not working with Percona releases

### ISSUE THREAD

**Issue by fuyar** [openark/orchestrator#96]
Hey !

I've just enabled Oracle GTID on my Percona 5.7.10 farm (2 masters + slaves). Tried to relocate using the GTID mode and I got the following error : "Cannot move via GTID as not both instances use GTID".

I first checked into the orchestrator database and I get that : 

```
+--------------------------------------+---------------------+----------------------+-------------+-------------+-------------+
| hostname                             | last_checked        | supports_oracle_gtid | oracle_gtid | server_uuid | gtid_purged |
+--------------------------------------+---------------------+----------------------+-------------+-------------+-------------+
| xxxx        | 2017-03-09 17:48:12 |                    0 |           1 |             |             |
| yyyy          | 2017-03-09 17:48:12 |                    0 |           1 |             |             |
| zzzz        | 2017-03-09 17:48:12 |                    0 |           1 |             |             |
....
```
The problem is that supports_oracle_gtid is not set while having gtid_mode = ON.

I checked into the code, it seems that you're restricting the query getting those status to isOracleMySQL instances.
https://github.com/github/orchestrator/blob/5c34db981e5b91f03fb31135b1f0bb3bfc3c4ed0/go/inst/instance_dao.go#L303

isPercona() should also get these infos as the GTID implementation is the same.

Thanks !

**Comment by shlomi-noach** [comment]
Thanks you for this report & analysis; good catch about percona/oracle -- looking into.

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/github/orchestrator/pull/98
