### ISSUE TITLE
Orchestrator not detecting intermediate master failure with relay_log_space_limit.

### ISSUE THREAD

**Issue by jfg956** [openark/orchestrator#999]
Because of MySQL Bug#97345 ([1]), Orchestrator might miss that an intermediate master has failed.

[1]: https://bugs.mysql.com/bug.php?id=97345

The scenario go like this:
1) the IO Thread is in state "Waiting for the slave SQL thread to free enough relay log space"

2) the intermediate master (IM) fails

3) Orchestrator is not able to connect to the IM, but the slaves are not seeing the IM as failed because of Bug#97345, so Orchestrator does not failover.

Discussed with Sholmi, the solution would be to run "STOP SLAVE IO_THREAD; START SLAVE IO_THREAD" on the slaves, which would trigger the slave to detect the failure (it is shown in Bug#97345 that this trigger the slave to detect the failure).

**Comment by shlomi-noach** [comment]
Thank you! The solution would be similar to the already existing solution for Masters (I applied the logic to masters, but not to intermediate masters), as per:

- [UnreachableMasterWithLaggingReplicas](https://github.com/github/orchestrator/blob/master/docs/failure-detection.md#unreachablemasterwithlaggingreplicas)

https://github.com/github/orchestrator/blob/5c80b6aaba9ba83fa8c1fe8bf8fe6df99e7c4d24/go/inst/analysis_dao.go#L330-L333

https://github.com/github/orchestrator/blob/5c80b6aaba9ba83fa8c1fe8bf8fe6df99e7c4d24/go/logic/topology_recovery.go#L1524-L1525

https://github.com/github/orchestrator/blob/5c80b6aaba9ba83fa8c1fe8bf8fe6df99e7c4d24/go/logic/topology_recovery.go#L1409-L1418

**Comment by shlomi-noach** [comment]
Fix suggested in https://github.com/github/orchestrator/pull/1005
